-- Zone: West Ronfaure
return {
  ["Amanita"] = { { name = "Tenax strap", average_rate = "31.1%" } },
  ["Bomb"] = { { name = "Pinch of bomb ash", average_rate = "32.9%" }, { name = "Bomb arm", average_rate = "15.8%" } },
  ["Carrion Worm"] = { { name = "Flint stone", average_rate = "21.2%" }, { name = "Chunk of copper ore", average_rate = "12.3%" }, { name = "Chunk of silver ore", average_rate = "1.4%" }, { name = "Chunk of zinc ore", average_rate = "6.1%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Ding Bats"] = { { name = "Bat wing", average_rate = "22.2%" } },
  ["Enchanted Bones"] = { { name = "Bone chip", average_rate = "19.9%" } },
  ["Forest Funguar"] = { { name = "Sleepshroom", average_rate = "21.3%" }, { name = "Dark cluster", average_rate = "0.02%" } },
  ["Forest Hare"] = { { name = "Rabbit hide", average_rate = "38.0%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Fungus Beetle"] = { { name = "Clipeus", average_rate = "97.0%" }, { name = "Beetle jaw", average_rate = "30.8%" }, { name = "Insect wing", average_rate = "34.9%" } },
  ["Goblin Fisher"] = { { name = "Goblin mail", average_rate = "2.1%" }, { name = "Beastcoin", average_rate = "1.8%" }, { name = "Goblin helm", average_rate = "3.3%" }, { name = "Fastwater fishing rod", average_rate = "0.71%" }, { name = "Bamboo fishing rod", average_rate = "1.6%" }, { name = "Yew fishing rod", average_rate = "4.0%" }, { name = "Clothespole", average_rate = "0.44%" } },
  ["Goblin Thug"] = { { name = "Goblin armor", average_rate = "1.5%" }, { name = "Wild onion", average_rate = "12.5%" }, { name = "Beastcoin", average_rate = "1.5%" }, { name = "Goblin mask", average_rate = "3.2%" }, { name = "Fire cluster", average_rate = "0.01%" } },
  ["Goblin Weaver"] = { { name = "Square of grass cloth", average_rate = "1.6%" }, { name = "Spool of grass thread", average_rate = "2.8%" }, { name = "Square of cotton cloth", average_rate = "0.65%" }, { name = "Beastcoin", average_rate = "1.4%" }, { name = "Goblin mask", average_rate = "3.1%" }, { name = "Goblin armor", average_rate = "1.3%" }, { name = "Spool of cotton thread", average_rate = "1.2%" } },
  ["Jaggedy-Eared Jack"] = { { name = "Slice of hare meat", average_rate = "24.1%" }, { name = "Rabbit hide", average_rate = "41.1%" }, { name = "Rabbit charm", average_rate = "4.6%" } },
  ["Land Crab"] = { { name = "Chunk of rock salt", average_rate = "26.2%" } },
  ["Limicoline Crab"] = { { name = "Chunk of rock salt", average_rate = "34.6%" }, { name = "Slice of land crab meat", average_rate = "1.7%" } },
  ["Mouse Bat"] = { { name = "Bat wing", average_rate = "22.0%" }, { name = "Vial of fiend blood", average_rate = "1.4%" }, { name = "Wind cluster", average_rate = "0.03%" } },
  ["Orcish Fodder"] = { { name = "Orcish axe", average_rate = "15.7%" }, { name = "Fire cluster", average_rate = "0.02%" } },
  ["Orcish Grappler"] = { { name = "Fire cluster", average_rate = "0.02%" } },
  ["Orcish Mesmerizer"] = { { name = "Scroll of Bind", average_rate = "5.8%" }, { name = "Scroll of Blind", average_rate = "6.4%" } },
  ["Passage Crab"] = { { name = "Chunk of rock salt", average_rate = "28.3%" }, { name = "Slice of land crab meat", average_rate = "1.9%" } },
  ["Pixie"] = { { name = "Pinch of Stygian ash", average_rate = "59.9%" } },
  ["Pyracmon"] = { { name = "Federation stables scarf", average_rate = "39.4%" }, { name = "Republic stables medal", average_rate = "32.4%" }, { name = "Kingdom stables collar", average_rate = "52.1%" } },
  ["River Crab"] = { { name = "Chunk of rock salt", average_rate = "22.1%" }, { name = "Chunk of Lufet salt", average_rate = "13.2%" }, { name = "Slice of land crab meat", average_rate = "1.8%" }, { name = "Water cluster", average_rate = "0.05%" } },
  ["Scarab Beetle"] = { { name = "Insect wing", average_rate = "12.3%" }, { name = "Beetle jaw", average_rate = "1.4%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Tainted Hound"] = { { name = "Wolf hide", average_rate = "13.7%" }, { name = "Revival tree root", average_rate = "7.1%" }, { name = "Dark cluster", average_rate = "0.39%" } },
  ["Tree Crab"] = { { name = "Chunk of rock salt", average_rate = "21.0%" }, { name = "Slice of land crab meat", average_rate = "1.7%" } },
  ["Tunnel Worm"] = { { name = "Flint stone", average_rate = "22.5%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Vermivorous Crab"] = { { name = "Chunk of rock salt", average_rate = "27.0%" }, { name = "Slice of land crab meat", average_rate = "3.2%" } },
  ["Wild Rabbit"] = { { name = "Rabbit hide", average_rate = "19.2%" }, { name = "Slice of hare meat", average_rate = "40.7%" }, { name = "Earth cluster", average_rate = "0.00%" } },
  ["Wild Sheep"] = { { name = "Slice of giant sheep meat", average_rate = "23.0%" }, { name = "Sheepskin", average_rate = "12.5%" }, { name = "Sheep tooth", average_rate = "6.2%" }, { name = "Earth cluster", average_rate = "0.00%" } },
}
