-- Zone: Valkurm Dunes
return {
  ["Beach Pugil"] = { { name = "Handful of pugil scales", average_rate = "12.8%" }, { name = "Shall shell", average_rate = "6.0%" }, { name = "Water cluster", average_rate = "0.01%" } },
  ["Bogy"] = { { name = "Bloody robe", average_rate = "39.2%" }, { name = "Revival tree root", average_rate = "13.8%" }, { name = "Luminicloth", average_rate = "7.1%" } },
  ["Brutal Sheep"] = { { name = "Sheepskin", average_rate = "21.9%" }, { name = "Sheep tooth", average_rate = "11.7%" }, { name = "Slice of giant sheep meat", average_rate = "33.5%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Cutter"] = { { name = "Chunk of rock salt", average_rate = "50.0%" } },
  ["Damselfly"] = { { name = "Damselfly worm", average_rate = "9.5%" }, { name = "Insect wing", average_rate = "6.7%" }, { name = "Wind cluster", average_rate = "0.02%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "140.8%" } },
  ["Fire Elemental"] = { { name = "Fire cluster", average_rate = "149.0%" } },
  ["Ghoul"] = { { name = "Bone chip", average_rate = "11.4%" }, { name = "Magicked skull", average_rate = "22.0%" } },
  ["Giant Bat"] = { { name = "Bat wing", average_rate = "20.9%" }, { name = "Vial of fiend blood", average_rate = "1.4%" } },
  ["Goblin Ambusher"] = { { name = "Block of animal glue", average_rate = "12.5%" }, { name = "Goblin mask", average_rate = "3.2%" }, { name = "Goblin armor", average_rate = "1.7%" }, { name = "Beastcoin", average_rate = "1.3%" }, { name = "Fire cluster", average_rate = "0.01%" } },
  ["Goblin Bounty Hunter"] = { { name = "Goblin helm", average_rate = "3.2%" }, { name = "Goblin mail", average_rate = "1.7%" }, { name = "Lightning cluster", average_rate = "0.03%" } },
  ["Goblin Butcher"] = { { name = "Goblin helm", average_rate = "3.2%" }, { name = "Goblin mail", average_rate = "1.5%" } },
  ["Goblin Gambler"] = { { name = "Goblin mask", average_rate = "3.2%" }, { name = "Goblin armor", average_rate = "1.8%" }, { name = "Bag of poison flour", average_rate = "1.6%" }, { name = "Fire cluster", average_rate = "0.06%" } },
  ["Goblin Leecher"] = { { name = "Scroll of Sneak", average_rate = "3.0%" }, { name = "Scroll of Barsleep", average_rate = "2.8%" }, { name = "Silver beastcoin", average_rate = "1.4%" }, { name = "Scroll of Protectra", average_rate = "3.3%" }, { name = "Scroll of Barpoison", average_rate = "1.5%" }, { name = "Scroll of Silence", average_rate = "2.7%" }, { name = "Scroll of Paralyze", average_rate = "3.8%" }, { name = "Scroll of Deodorize", average_rate = "1.2%" }, { name = "Goblin mask", average_rate = "3.8%" }, { name = "Goblin armor", average_rate = "1.7%" }, { name = "Scroll of Invisible", average_rate = "0.49%" }, { name = "Mannequin feet", average_rate = "0.01%" }, { name = "Fire cluster", average_rate = "0.01%" } },
  ["Goblin Mugger"] = { { name = "Goblin armor", average_rate = "1.5%" }, { name = "Goblin mask", average_rate = "3.5%" }, { name = "Silver beastcoin", average_rate = "1.4%" }, { name = "Fire cluster", average_rate = "0.01%" } },
  ["Goblin Swordmaker"] = { { name = "Mannequin legs", average_rate = "25.0%" } },
  ["Goblin Tinkerer"] = { { name = "Beastcoin", average_rate = "1.4%" }, { name = "Goblin helm", average_rate = "2.9%" }, { name = "Goblin mail", average_rate = "1.4%" }, { name = "Lightning cluster", average_rate = "0.03%" } },
  ["Golden Bat"] = { { name = "Bat wing", average_rate = "100.2%" }, { name = "Night cape", average_rate = "20.7%" }, { name = "Vial of fiend blood", average_rate = "7.8%" } },
  ["Hill Lizard"] = { { name = "Lizard tail", average_rate = "23.4%" }, { name = "Lizard skin", average_rate = "12.7%" }, { name = "Fire cluster", average_rate = "0.03%" } },
  ["Hippomaritimus"] = { { name = "Channeling robe", average_rate = "31.1%" } },
  ["Marchelute"] = { { name = "Tavnazia pass", average_rate = "105.4%" }, { name = "Revival tree root", average_rate = "7.2%" } },
  ["Metal Shears"] = { { name = "Stately crab shell", average_rate = "39.9%" } },
  ["Night Bats"] = { { name = "Bat wing", average_rate = "20.2%" } },
  ["Pixie"] = { { name = "Pinch of Stygian ash", average_rate = "94.1%" } },
  ["Sand Bats"] = { { name = "Bat wing", average_rate = "22.9%" }, { name = "Sand bat fang", average_rate = "13.0%" } },
  ["Sand Hare"] = { { name = "Slice of hare meat", average_rate = "23.6%" }, { name = "Rabbit hide", average_rate = "12.7%" }, { name = "La Theine cabbage", average_rate = "6.3%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Snipper"] = { { name = "Slice of land crab meat", average_rate = "6.6%" }, { name = "Chunk of rock salt", average_rate = "25.1%" }, { name = "Crab apron", average_rate = "9.8%" }, { name = "Crab shell", average_rate = "1.6%" }, { name = "Water cluster", average_rate = "0.03%" } },
  ["Stag Crab"] = { { name = "Slice of land crab meat", average_rate = "16.0%" }, { name = "Chunk of rock salt", average_rate = "24.0%" } },
  ["Star Bat"] = { { name = "Bat wing", average_rate = "20.4%" }, { name = "Vial of fiend blood", average_rate = "1.3%" } },
  ["Thread Leech"] = { { name = "Vial of fiend blood", average_rate = "13.7%" }, { name = "Water cluster", average_rate = "0.01%" } },
  ["Valkurm Emperor"] = { { name = "Insect wing", average_rate = "104.3%" }, { name = "Empress hairpin", average_rate = "35.1%" } },
  ["Will-O'-The-Wisp"] = { { name = "Pinch of bomb ash", average_rate = "24.3%" }, { name = "Bomb arm", average_rate = "10.4%" } },
}
