-- Zone: Jugner Forest
return {
  ["Boggart"] = { { name = "Scroll of Regen", average_rate = "5.9%" } },
  ["Bogy"] = { { name = "Bloody robe", average_rate = "39.4%" }, { name = "Revival tree root", average_rate = "10.6%" }, { name = "Luminicloth", average_rate = "4.5%" } },
  ["Brutal Sheep"] = { { name = "Sheepskin", average_rate = "21.5%" }, { name = "Slice of giant sheep meat", average_rate = "33.3%" }, { name = "Sheep tooth", average_rate = "12.8%" } },
  ["Capricornus"] = { { name = "Fierce belt", average_rate = "14.3%" } },
  ["Forest Leech"] = { { name = "Vial of fiend blood", average_rate = "13.1%" } },
  ["Forest Tiger"] = { { name = "Black tiger fang", average_rate = "24.5%" }, { name = "Black tiger hide", average_rate = "14.7%" } },
  ["Fradubio"] = { { name = "Bellicose mantle", average_rate = "56.9%" }, { name = "Rosewood log", average_rate = "51.0%" }, { name = "Mahogany log", average_rate = "25.5%" }, { name = "Ebony log", average_rate = "41.2%" }, { name = "Petrified log", average_rate = "9.8%" } },
  ["Fraelissa"] = { { name = "Rosewood log", average_rate = "48.7%" }, { name = "Almogavar bow", average_rate = "39.6%" }, { name = "Mahogany log", average_rate = "28.3%" }, { name = "Ebony log", average_rate = "18.4%" }, { name = "Petrified log", average_rate = "10.9%" } },
  ["Ghoul"] = { { name = "Magicked skull", average_rate = "16.7%" } },
  ["Goblin Ambusher"] = { { name = "Goblin mask", average_rate = "2.9%" }, { name = "Block of animal glue", average_rate = "14.4%" }, { name = "Beastcoin", average_rate = "1.9%" }, { name = "Goblin armor", average_rate = "1.3%" } },
  ["Goblin Butcher"] = { { name = "Goblin helm", average_rate = "3.8%" }, { name = "Goblin mail", average_rate = "1.4%" } },
  ["Goblin Gambler"] = { { name = "Goblin mask", average_rate = "3.9%" }, { name = "Goblin armor", average_rate = "0.78%" }, { name = "Bag of poison flour", average_rate = "0.78%" } },
  ["Goblin Leecher"] = { { name = "Scroll of Sneak", average_rate = "3.3%" }, { name = "Scroll of Protectra", average_rate = "3.5%" }, { name = "Goblin mask", average_rate = "1.5%" }, { name = "Scroll of Paralyze", average_rate = "4.1%" }, { name = "Silver beastcoin", average_rate = "1.8%" }, { name = "Scroll of Barpoison", average_rate = "3.3%" }, { name = "Goblin armor", average_rate = "1.5%" }, { name = "Scroll of Silence", average_rate = "2.5%" }, { name = "Scroll of Barsleep", average_rate = "1.5%" }, { name = "Scroll of Invisible", average_rate = "0.76%" } },
  ["Goblin Mugger"] = { { name = "Silver beastcoin", average_rate = "1.5%" }, { name = "Goblin mask", average_rate = "4.0%" }, { name = "Goblin armor", average_rate = "2.0%" } },
  ["Goblin Tinkerer"] = { { name = "Beastcoin", average_rate = "1.8%" }, { name = "Goblin mail", average_rate = "2.1%" }, { name = "Goblin helm", average_rate = "4.9%" } },
  ["Huge Leech"] = { { name = "Vial of fiend blood", average_rate = "16.7%" }, { name = "Vial of beastman blood", average_rate = "12.5%" } },
  ["Jugner Funguar"] = { { name = "Sleepshroom", average_rate = "28.1%" }, { name = "Woozyshroom", average_rate = "14.5%" } },
  ["King Arthro"] = { { name = "Reraiser", average_rate = "88.5%" }, { name = "Square of damascene cloth", average_rate = "148.0%" }, { name = "Vile elixir", average_rate = "84.3%" }, { name = "Magic cuisses", average_rate = "105.1%" }, { name = "Velocious belt", average_rate = "12.9%" } },
  ["Knight Crab"] = { { name = "Chunk of rock salt", average_rate = "105.6%" }, { name = "Crab shell", average_rate = "39.7%" }, { name = "Slice of land crab meat", average_rate = "81.7%" } },
  ["Krabkatoa"] = { { name = "Krabkatoa shell", average_rate = "127.4%" }, { name = "Petrified log", average_rate = "19.4%" }, { name = "Acubens helm", average_rate = "30.3%" }, { name = "Karka ring", average_rate = "16.7%" }, { name = "Chunk of platinum ore", average_rate = "6.1%" }, { name = "Handful of wyvern scales", average_rate = "9.9%" }, { name = "Chunk of fire ore", average_rate = "2.9%" }, { name = "Igneous barnacle", average_rate = "44.6%" }, { name = "Coral fragment", average_rate = "13.3%" }, { name = "Mahogany log", average_rate = "17.2%" }, { name = "Manticore hide", average_rate = "1.5%" }, { name = "Chunk of gold ore", average_rate = "8.5%" }, { name = "Ram horn", average_rate = "9.2%" }, { name = "Chunk of ice ore", average_rate = "1.7%" }, { name = "Vile elixir", average_rate = "3.9%" }, { name = "Gold ingot", average_rate = "2.7%" }, { name = "Platinum ingot", average_rate = "4.8%" }, { name = "Ebony log", average_rate = "9.4%" }, { name = "Mythril ingot", average_rate = "11.1%" }, { name = "Demon horn", average_rate = "10.2%" }, { name = "Square of raxa", average_rate = "4.1%" }, { name = "Philosopher's stone", average_rate = "1.5%" }, { name = "Phoenix feather", average_rate = "1.9%" }, { name = "Chunk of darksteel ore", average_rate = "5.3%" }, { name = "Spool of gold thread", average_rate = "2.4%" }, { name = "Chunk of mythril ore", average_rate = "4.1%" }, { name = "Ram skin", average_rate = "2.7%" }, { name = "Darksteel ingot", average_rate = "6.5%" }, { name = "Chunk of light ore", average_rate = "2.4%" }, { name = "Chunk of wind ore", average_rate = "1.2%" }, { name = "Chunk of water ore", average_rate = "1.9%" }, { name = "Reraiser", average_rate = "3.6%" }, { name = "Chunk of lightning ore", average_rate = "2.2%" }, { name = "Slab of granite", average_rate = "1.2%" }, { name = "Square of rainbow cloth", average_rate = "2.2%" }, { name = "Vile elixir +1", average_rate = "2.2%" }, { name = "Chunk of dark ore", average_rate = "0.97%" }, { name = "Wyvern skin", average_rate = "1.5%" }, { name = "Hi-reraiser", average_rate = "1.5%" }, { name = "Chunk of earth ore", average_rate = "0.73%" } },
  ["Land Pugil"] = { { name = "Handful of pugil scales", average_rate = "12.1%" } },
  ["Meteormauler Zhagtegg"] = { { name = "Garde pick", average_rate = "45.4%" } },
  ["Orcish Cursemaker"] = { { name = "Seedspall Lux", average_rate = "12.2%" } },
  ["Orcish Fighter"] = { { name = "Seedspall Lux", average_rate = "12.1%" } },
  ["Orcish Grunt"] = { { name = "Seedspall Lux", average_rate = "12.3%" } },
  ["Orcish Neckchopper"] = { { name = "Seedspall Lux", average_rate = "14.4%" } },
  ["Orcish Serjeant"] = { { name = "Seedspall Lux", average_rate = "12.6%" } },
  ["Orcish Stonechucker"] = { { name = "Seedspall Lux", average_rate = "13.5%" } },
  ["Panzer Percival"] = { { name = "Beetle jaw", average_rate = "101.3%" }, { name = "Insect wing", average_rate = "11.0%" }, { name = "Neckchopper", average_rate = "24.5%" }, { name = "Beetle shell", average_rate = "16.3%" } },
  ["Sappy Sycamore"] = { { name = "Seeker earring", average_rate = "26.8%" } },
  ["Scavenging Hound"] = { { name = "Wolf hide", average_rate = "4.5%" }, { name = "Revival tree root", average_rate = "4.5%" } },
  ["Screamer"] = { { name = "Bird egg", average_rate = "11.5%" }, { name = "Bird feather", average_rate = "22.6%" } },
  ["Skeleton Esquire"] = { { name = "Revival tree root", average_rate = "8.0%" }, { name = "Bone chip", average_rate = "28.0%" } },
  ["Snipper"] = { { name = "Chunk of rock salt", average_rate = "22.2%" }, { name = "Crab shell", average_rate = "1.8%" }, { name = "Slice of land crab meat", average_rate = "5.8%" } },
  ["Sprite"] = { { name = "Pinch of Stygian ash", average_rate = "91.5%" } },
  ["Stag Beetle"] = { { name = "Beetle shell", average_rate = "13.5%" }, { name = "Insect wing", average_rate = "24.7%" }, { name = "Beetle jaw", average_rate = "6.7%" } },
  ["Stag Crab"] = { { name = "Chunk of rock salt", average_rate = "27.0%" }, { name = "Slice of land crab meat", average_rate = "5.9%" }, { name = "Crab shell", average_rate = "2.6%" } },
  ["Supplespine Mujwuj"] = { { name = "Blue jasper", average_rate = "50.0%" } },
  ["Thread Leech"] = { { name = "Vial of fiend blood", average_rate = "23.4%" }, { name = "Vial of beastman blood", average_rate = "10.9%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "153.5%" } },
  ["Walking Tree"] = { { name = "Dryad root", average_rate = "24.6%" }, { name = "Sprig of mistletoe", average_rate = "13.0%" }, { name = "Puffball", average_rate = "7.2%" }, { name = "Oak log", average_rate = "2.4%" } },
  ["Wandering Sapling"] = { { name = "Treant bulb", average_rate = "29.4%" }, { name = "Bag of herb seeds", average_rate = "7.8%" }, { name = "Bag of vegetable seeds", average_rate = "15.1%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "148.7%" } },
  ["Will-O'-The-Wisp"] = { { name = "Pinch of bomb ash", average_rate = "26.7%" }, { name = "Bomb arm", average_rate = "18.9%" } },
  ["Yacumama"] = { { name = "Backlash torque", average_rate = "15.3%" } },
  ["Yilbegan"] = { { name = "Mahogany log", average_rate = "14.3%" }, { name = "Mythril ingot", average_rate = "28.6%" }, { name = "Petrified log", average_rate = "23.8%" }, { name = "Lucky coin", average_rate = "4.8%" }, { name = "Chunk of mythril ore", average_rate = "9.5%" }, { name = "Agrona's leggings", average_rate = "47.6%" }, { name = "Demon horn", average_rate = "9.5%" }, { name = "Ram horn", average_rate = "9.5%" }, { name = "Platinum ingot", average_rate = "4.8%" }, { name = "Reraiser", average_rate = "9.5%" }, { name = "Square of scarlet kadife", average_rate = "28.6%" }, { name = "Ebony log", average_rate = "9.5%" }, { name = "Ram skin", average_rate = "4.8%" }, { name = "Philosopher's stone", average_rate = "4.8%" }, { name = "Darksteel ingot", average_rate = "4.8%" }, { name = "Hi-reraiser", average_rate = "4.8%" }, { name = "Chunk of darksteel ore", average_rate = "9.5%" }, { name = "Handful of wyvern scales", average_rate = "9.5%" }, { name = "Coral fragment", average_rate = "4.8%" }, { name = "Gold ingot", average_rate = "4.8%" }, { name = "Chunk of gold ore", average_rate = "14.3%" }, { name = "Spool of gold thread", average_rate = "4.8%" } },
  ["Zombie"] = { { name = "Bone chip", average_rate = "20.0%" } },
}
