-- Zone: South Gustaberg
return {
  ["Amber Quadav"] = { { name = "Scroll of Blind", average_rate = "7.5%" }, { name = "Scroll of Bind", average_rate = "5.7%" } },
  ["Amethyst Quadav"] = { { name = "Quadav backplate", average_rate = "23.1%" }, { name = "Scroll of Protectra", average_rate = "3.1%" }, { name = "Scroll of Sneak", average_rate = "2.8%" }, { name = "Scroll of Paralyze", average_rate = "3.8%" }, { name = "Scroll of Barsleep", average_rate = "2.9%" }, { name = "Water cluster", average_rate = "0.03%" } },
  ["Black Wolf"] = { { name = "Wolf hide", average_rate = "15.2%" }, { name = "Revival tree root", average_rate = "6.6%" }, { name = "Dark cluster", average_rate = "0.09%" } },
  ["Bubbly Bernie"] = { { name = "Steam clock", average_rate = "95.1%" }, { name = "Slice of land crab meat", average_rate = "3.3%" } },
  ["Carnero"] = { { name = "Katayama ichimonji", average_rate = "70.0%" } },
  ["Ding Bats"] = { { name = "Bat wing", average_rate = "21.8%" } },
  ["Enchanted Bones"] = { { name = "Bone chip", average_rate = "29.8%" } },
  ["Fledermaus"] = { { name = "Bat wing", average_rate = "23.2%" }, { name = "Vial of fiend blood", average_rate = "1.4%" } },
  ["Goblin Fisher"] = { { name = "Goblin helm", average_rate = "2.9%" }, { name = "Yew fishing rod", average_rate = "4.5%" }, { name = "Bamboo fishing rod", average_rate = "1.4%" }, { name = "Goblin mail", average_rate = "1.7%" }, { name = "Beastcoin", average_rate = "1.6%" }, { name = "Fastwater fishing rod", average_rate = "0.53%" }, { name = "Clothespole", average_rate = "0.21%" } },
  ["Goblin Thug"] = { { name = "Goblin mask", average_rate = "3.7%" }, { name = "Goblin armor", average_rate = "1.8%" }, { name = "Wild onion", average_rate = "13.4%" }, { name = "Beastcoin", average_rate = "1.6%" }, { name = "Fire cluster", average_rate = "0.01%" } },
  ["Goblin Weaver"] = { { name = "Goblin armor", average_rate = "1.8%" }, { name = "Goblin mask", average_rate = "3.6%" }, { name = "Square of grass cloth", average_rate = "1.7%" }, { name = "Beastcoin", average_rate = "1.5%" }, { name = "Spool of cotton thread", average_rate = "1.3%" }, { name = "Square of cotton cloth", average_rate = "0.64%" }, { name = "Spool of grass thread", average_rate = "2.9%" }, { name = "Fire cluster", average_rate = "0.01%" } },
  ["Huge Hornet"] = { { name = "Pot of honey", average_rate = "6.4%" }, { name = "Insect wing", average_rate = "13.0%" }, { name = "Wind cluster", average_rate = "0.01%" } },
  ["Land Crab"] = { { name = "Slice of land crab meat", average_rate = "1.3%" }, { name = "Chunk of rock salt", average_rate = "21.6%" }, { name = "Water cluster", average_rate = "0.01%" } },
  ["Leaping Lizzy"] = { { name = "Bounding boots", average_rate = "22.2%" }, { name = "Lizard tail", average_rate = "37.0%" }, { name = "Lizard skin", average_rate = "12.6%" }, { name = "Fire cluster", average_rate = "0.16%" } },
  ["Maneating Hornet"] = { { name = "Beehive chip", average_rate = "24.9%" }, { name = "Pot of honey", average_rate = "13.5%" }, { name = "Insect wing", average_rate = "6.8%" }, { name = "Giant stinger", average_rate = "1.6%" }, { name = "Wind cluster", average_rate = "0.01%" } },
  ["Ornery Sheep"] = { { name = "Slice of giant sheep meat", average_rate = "26.0%" }, { name = "Sheepskin", average_rate = "14.2%" }, { name = "Vial of fresh blood", average_rate = "2.7%" }, { name = "Sheep tooth", average_rate = "1.5%" } },
  ["Passage Crab"] = { { name = "Chunk of rock salt", average_rate = "20.0%" } },
  ["Pixie"] = { { name = "Pinch of Stygian ash", average_rate = "77.2%" } },
  ["Pyracmon"] = { { name = "Federation stables scarf", average_rate = "32.3%" }, { name = "Kingdom stables collar", average_rate = "34.4%" }, { name = "Republic stables medal", average_rate = "30.6%" } },
  ["Rock Lizard"] = { { name = "Lizard tail", average_rate = "24.2%" }, { name = "Earth cluster", average_rate = "0.02%" } },
  ["Sand Crab"] = { { name = "Chunk of rock salt", average_rate = "25.0%" } },
  ["Shrapnel"] = { { name = "Pinch of bomb ash", average_rate = "22.4%" }, { name = "Bomb arm", average_rate = "11.4%" } },
  ["Stone Crab"] = { { name = "Chunk of rock salt", average_rate = "6.7%" } },
  ["Stone Eater"] = { { name = "Flint stone", average_rate = "22.8%" }, { name = "Chunk of copper ore", average_rate = "12.9%" }, { name = "Chunk of zinc ore", average_rate = "6.4%" }, { name = "Chunk of silver ore", average_rate = "1.4%" }, { name = "Earth cluster", average_rate = "0.00%" } },
  ["Tococo"] = { { name = "Armiger's lace", average_rate = "30.1%" } },
  ["Tunnel Worm"] = { { name = "Flint stone", average_rate = "22.4%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Vulture"] = { { name = "Bird egg", average_rate = "12.8%" }, { name = "Bird feather", average_rate = "22.6%" }, { name = "Fire cluster", average_rate = "0.01%" } },
  ["Walking Sapling"] = { { name = "Treant bulb", average_rate = "23.3%" }, { name = "Bag of grain seeds", average_rate = "13.1%" }, { name = "Bag of vegetable seeds", average_rate = "6.5%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Young Quadav"] = { { name = "Shell shield", average_rate = "13.0%" }, { name = "Water cluster", average_rate = "0.00%" } },
}
