-- Zone: Oldton Movalpolos
return {
  ["Amoebic Nodule"] = { { name = "Vial of slime oil", average_rate = "51.7%" } },
  ["Ancient Bomb"] = { { name = "Pinch of hoary bomb ash", average_rate = "170.7%" }, { name = "Oldton chest key", average_rate = "7.9%" } },
  ["Blind Crab"] = { { name = "Slice of land crab meat", average_rate = "5.4%" }, { name = "Chunk of rock salt", average_rate = "12.2%" } },
  ["Bugbear Bondman"] = { { name = "Bugbear mask", average_rate = "7.5%" }, { name = "Oldton chest key", average_rate = "8.0%" }, { name = "Chunk of kopparnickel ore", average_rate = "32.0%" }, { name = "Igneous rock", average_rate = "2.1%" } },
  ["Bugbear Muscleman"] = { { name = "Spool of rugged gold thread", average_rate = "18.9%" } },
  ["Bugbear Servingman"] = { { name = "Chunk of kopparnickel ore", average_rate = "42.8%" }, { name = "Bugbear mask", average_rate = "9.8%" }, { name = "Igneous rock", average_rate = "3.2%" } },
  ["Bugbear Strongman"] = { { name = "Aikido koshita", average_rate = "32.0%" }, { name = "Bugbear mask", average_rate = "7.5%" }, { name = "Shinimusha haidate", average_rate = "16.2%" } },
  ["Cutter"] = { { name = "Chunk of rock salt", average_rate = "23.2%" }, { name = "Slice of land crab meat", average_rate = "8.9%" } },
  ["Dark Bats"] = { { name = "Bat wing", average_rate = "32.6%" }, { name = "Bat fang", average_rate = "17.9%" }, { name = "Vial of fiend blood", average_rate = "9.4%" }, { name = "Vial of beastman blood", average_rate = "3.2%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "159.9%" }, { name = "Oldton chest key", average_rate = "6.2%" } },
  ["Ghost Crab"] = { { name = "Chunk of rock salt", average_rate = "102.3%" }, { name = "Slice of land crab meat", average_rate = "62.8%" }, { name = "Crab shell", average_rate = "27.9%" } },
  ["Goblin Craftsman"] = { { name = "Goblin helm", average_rate = "11.0%" }, { name = "Goblin mail", average_rate = "4.7%" } },
  ["Goblin Doorman"] = { { name = "Goblin mail", average_rate = "5.3%" }, { name = "Goblin helm", average_rate = "9.3%" }, { name = "Oldton chest key", average_rate = "8.6%" } },
  ["Goblin Freelance"] = { { name = "Goblin helm", average_rate = "10.7%" }, { name = "Goblin mail", average_rate = "5.3%" }, { name = "Moblumin ingot", average_rate = "21.6%" } },
  ["Goblin Gutterman"] = { { name = "Goblin mask", average_rate = "9.3%" }, { name = "Goblin armor", average_rate = "4.9%" } },
  ["Goblin Hammerman"] = { { name = "Goblin helm", average_rate = "11.2%" }, { name = "Goblin mail", average_rate = "4.5%" }, { name = "Magicked steel ingot", average_rate = "16.3%" } },
  ["Goblin Leadman"] = { { name = "Goblin armor", average_rate = "5.4%" }, { name = "Magicked steel ingot", average_rate = "14.1%" }, { name = "Goblin mask", average_rate = "9.6%" } },
  ["Goblin Oilman"] = { { name = "Magicked steel ingot", average_rate = "15.0%" }, { name = "Goblin helm", average_rate = "7.5%" }, { name = "Goblin mail", average_rate = "3.4%" }, { name = "Oldton chest key", average_rate = "7.6%" } },
  ["Goblin Shovelman"] = { { name = "Oldton chest key", average_rate = "6.6%" }, { name = "Goblin mask", average_rate = "7.6%" }, { name = "Goblin armor", average_rate = "3.3%" } },
  ["Goblin Tollman"] = { { name = "Goblin mask", average_rate = "11.0%" }, { name = "Magicked steel ingot", average_rate = "11.6%" }, { name = "Goblin armor", average_rate = "5.1%" }, { name = "Oldton chest key", average_rate = "11.2%" } },
  ["Goblin Wolfman"] = { { name = "Parade gorget", average_rate = "32.1%" } },
  ["Moblin Ashman"] = { { name = "Moblin hotrok", average_rate = "29.1%" }, { name = "Moblin helm", average_rate = "4.7%" }, { name = "Moblumin ingot", average_rate = "20.5%" }, { name = "Moblin mail", average_rate = "9.3%" }, { name = "Oldton chest key", average_rate = "11.1%" } },
  ["Moblin Chapman"] = { { name = "Spool of Moblin thread", average_rate = "47.2%" }, { name = "Moblin mask", average_rate = "22.9%" }, { name = "Moblin sheepskin", average_rate = "9.7%" }, { name = "Moblin armor", average_rate = "3.8%" } },
  ["Moblin Coalman"] = { { name = "Moblin mask", average_rate = "10.6%" }, { name = "Oldton chest key", average_rate = "9.4%" }, { name = "Moblin armor", average_rate = "3.2%" } },
  ["Moblin Gasman"] = { { name = "Moblin mask", average_rate = "10.1%" }, { name = "Moblin armor", average_rate = "3.1%" }, { name = "Oldton chest key", average_rate = "10.2%" } },
  ["Moblin Gurneyman"] = { { name = "Moblin armor", average_rate = "19.7%" }, { name = "Moblin mask", average_rate = "44.3%" } },
  ["Moblin Pikeman"] = { { name = "Oldton chest key", average_rate = "10.8%" }, { name = "Moblin mask", average_rate = "9.6%" }, { name = "Moblin armor", average_rate = "3.2%" } },
  ["Moblin Ragman"] = { { name = "Moblin mask", average_rate = "10.6%" }, { name = "Moblin armor", average_rate = "2.9%" } },
  ["Moblin Repairman"] = { { name = "Moblin mask", average_rate = "8.1%" }, { name = "Oldton chest key", average_rate = "8.1%" }, { name = "Moblin armor", average_rate = "3.3%" } },
  ["Moblin Rodman"] = { { name = "Goblin helm", average_rate = "14.6%" }, { name = "Oldton chest key", average_rate = "8.9%" }, { name = "Goblin mail", average_rate = "7.2%" } },
  ["Moblin Witchman"] = { { name = "Spool of Moblin thread", average_rate = "48.8%" }, { name = "Moblin mask", average_rate = "22.5%" }, { name = "Moblin sheepskin", average_rate = "10.9%" }, { name = "Moblin armor", average_rate = "4.1%" } },
  ["Snipper"] = { { name = "Chunk of rock salt", average_rate = "25.0%" }, { name = "Slice of land crab meat", average_rate = "1.1%" } },
  ["Stirge"] = { { name = "Bat wing", average_rate = "35.8%" }, { name = "Bat fang", average_rate = "19.6%" }, { name = "Vial of fiend blood", average_rate = "5.0%" }, { name = "Vial of beastman blood", average_rate = "2.2%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "161.0%" }, { name = "Oldton chest key", average_rate = "3.7%" } },
}
