-- Zone: Cape Teriggan
return {
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "142.4%" } },
  ["Beach Bunny"] = { { name = "Slice of hare meat", average_rate = "28.2%" }, { name = "Rabbit hide", average_rate = "15.1%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Doom Mage"] = { { name = "Bone chip", average_rate = "32.5%" }, { name = "Revival tree root", average_rate = "16.0%" }, { name = "Scroll of Blizzard III", average_rate = "10.4%" } },
  ["Doom Soldier"] = { { name = "Bone chip", average_rate = "102.4%" }, { name = "Cold bone", average_rate = "8.4%" }, { name = "Revival tree root", average_rate = "8.3%" }, { name = "Dark knight's testimony", average_rate = "5.8%" } },
  ["Enna-Enna"] = { { name = "Pinch of bomb ash", average_rate = "42.3%" }, { name = "Bomb arm", average_rate = "15.5%" } },
  ["Fantasma"] = { { name = "Revival tree root", average_rate = "28.5%" }, { name = "Square of wool cloth", average_rate = "14.6%" } },
  ["Fire Elemental"] = { { name = "Fire cluster", average_rate = "149.2%" } },
  ["Frostmane"] = { { name = "Lock of manticore hair", average_rate = "139.1%" }, { name = "Manticore fang", average_rate = "53.6%" }, { name = "Manticore hide", average_rate = "103.6%" }, { name = "Lockheart", average_rate = "6.4%" } },
  ["Goblin Alchemist"] = { { name = "Scroll of Esuna", average_rate = "14.7%" }, { name = "Scroll of Reraise III", average_rate = "8.7%" }, { name = "White mage's testimony", average_rate = "15.8%" }, { name = "Scroll of Cure V", average_rate = "3.1%" }, { name = "Scroll of Regen III", average_rate = "5.1%" }, { name = "Scroll of Shellra IV", average_rate = "6.7%" }, { name = "Scroll of Curaga IV", average_rate = "1.6%" } },
  ["Goblin Bandit"] = { { name = "Goblin mask", average_rate = "6.8%" }, { name = "Goblin armor", average_rate = "2.6%" }, { name = "Gold beastcoin", average_rate = "2.2%" }, { name = "Fire cluster", average_rate = "0.01%" } },
  ["Goblin Boss"] = { { name = "Mannequin feet", average_rate = "7.7%" }, { name = "Mannequin legs", average_rate = "7.7%" } },
  ["Goblin Doctor"] = { { name = "Mannequin feet", average_rate = "7.9%" }, { name = "Mannequin legs", average_rate = "3.2%" } },
  ["Goblin Duelist"] = { { name = "Mannequin legs", average_rate = "6.5%" }, { name = "Mannequin feet", average_rate = "8.7%" } },
  ["Goblin Mercenary"] = { { name = "Warrior's testimony", average_rate = "7.4%" }, { name = "Goblin helm", average_rate = "6.1%" }, { name = "Goblin mail", average_rate = "3.0%" }, { name = "Gold beastcoin", average_rate = "2.4%" } },
  ["Goblin Pirate"] = { { name = "Mannequin feet", average_rate = "11.9%" }, { name = "Mannequin legs", average_rate = "9.5%" } },
  ["Goblin Professor"] = { { name = "Mannequin feet", average_rate = "23.1%" }, { name = "Mannequin legs", average_rate = "3.8%" } },
  ["Goblin Shepherd"] = { { name = "Ash staff", average_rate = "45.6%" }, { name = "Ram skin", average_rate = "33.5%" }, { name = "Jug of singing herbal broth", average_rate = "7.5%" }, { name = "Beastmaster's testimony", average_rate = "14.4%" }, { name = "Fire cluster", average_rate = "0.01%" } },
  ["Greater Manticore"] = { { name = "Lock of manticore hair", average_rate = "34.6%" }, { name = "Manticore hide", average_rate = "17.6%" }, { name = "Manticore fang", average_rate = "8.1%" }, { name = "Wind cluster", average_rate = "0.01%" } },
  ["Killer Jonny"] = { { name = "Fendoir", average_rate = "16.2%" } },
  ["Kreutzet"] = { { name = "Sirocco kukri", average_rate = "69.2%" }, { name = "Giant bird plume", average_rate = "15.4%" }, { name = "Giant bird feather", average_rate = "67.3%" } },
  ["Robber Crab"] = { { name = "Slice of land crab meat", average_rate = "29.1%" }, { name = "Crab shell", average_rate = "15.0%" }, { name = "Water cluster", average_rate = "0.00%" } },
  ["Rock Crab"] = { { name = "Chunk of rock salt", average_rate = "100.0%" } },
  ["Sand Cockatrice"] = { { name = "Slice of cockatrice meat", average_rate = "29.6%" }, { name = "Cockatrice skin", average_rate = "15.5%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Sand Lizard"] = { { name = "Lizard egg", average_rate = "13.8%" }, { name = "Lizard tail", average_rate = "28.0%" }, { name = "Lizard skin", average_rate = "7.0%" }, { name = "Fire cluster", average_rate = "0.01%" } },
  ["Tegmine"] = { { name = "Aptant of durus", average_rate = "15.8%" }, { name = "Aptant of bellum", average_rate = "15.0%" } },
  ["Terror Pugil"] = { { name = "Handful of pugil scales", average_rate = "15.2%" }, { name = "Water cluster", average_rate = "0.01%" } },
  ["Velociraptor"] = { { name = "Raptor skin", average_rate = "15.1%" }, { name = "Fire cluster", average_rate = "0.00%" } },
  ["Zmey Gorynych"] = { { name = "Aptant of durus", average_rate = "14.4%" }, { name = "Aptant of primus", average_rate = "20.2%" } },
}
