-- Zone: Eastern Altepa Desert
return {
  ["Antican Auxiliarius"] = { { name = "Antican pauldron", average_rate = "15.5%" }, { name = "Piece of rotten meat", average_rate = "27.4%" }, { name = "Chunk of copper ore", average_rate = "1.6%" } },
  ["Antican Centurio"] = { { name = "Piece of rotten meat", average_rate = "57.2%" }, { name = "Antican pauldron", average_rate = "28.1%" }, { name = "Chunk of mythril ore", average_rate = "4.1%" }, { name = "Dhalmel leather missive", average_rate = "1.2%" } },
  ["Antican Decurio"] = { { name = "Piece of rotten meat", average_rate = "25.6%" }, { name = "Antican pauldron", average_rate = "13.8%" }, { name = "Scroll of Flash", average_rate = "6.4%" }, { name = "Chunk of iron ore", average_rate = "1.3%" } },
  ["Antican Faber"] = { { name = "Piece of rotten meat", average_rate = "26.8%" }, { name = "Antican robe", average_rate = "13.4%" }, { name = "Chunk of copper ore", average_rate = "1.8%" } },
  ["Antican Funditor"] = { { name = "Antican robe", average_rate = "13.0%" }, { name = "Piece of rotten meat", average_rate = "26.9%" }, { name = "Iron arrow", average_rate = "6.7%" }, { name = "Chunk of copper ore", average_rate = "1.6%" } },
  ["Antican Sagittarius"] = { { name = "Antican robe", average_rate = "17.1%" }, { name = "Piece of rotten meat", average_rate = "23.0%" }, { name = "Chunk of iron ore", average_rate = "1.1%" }, { name = "Iron arrow", average_rate = "2.7%" } },
  ["Antican Speculator"] = { { name = "Piece of rotten meat", average_rate = "29.9%" }, { name = "Antican robe", average_rate = "17.9%" }, { name = "Chunk of iron ore", average_rate = "1.0%" } },
  ["Antican Veles"] = { { name = "Piece of rotten meat", average_rate = "62.9%" }, { name = "Antican pauldron", average_rate = "29.1%" }, { name = "Chunk of mythril ore", average_rate = "5.6%" }, { name = "Dhalmel leather missive", average_rate = "1.9%" } },
  ["Bigclaw"] = { { name = "Chunk of rock salt", average_rate = "100.0%" }, { name = "Slice of land crab meat", average_rate = "100.0%" } },
  ["Cactrot Rapido"] = { { name = "Bag of cactus stems", average_rate = "116.7%" }, { name = "Arete del sol", average_rate = "53.3%" }, { name = "Cactuar root", average_rate = "106.7%" }, { name = "Cactus arm", average_rate = "110.0%" }, { name = "Arco de velocidad", average_rate = "5.0%" } },
  ["Centurio Xii-I"] = { { name = "Intruder earring", average_rate = "49.0%" } },
  ["Cutter"] = { { name = "Chunk of rock salt", average_rate = "109.1%" }, { name = "Crab shell", average_rate = "18.2%" }, { name = "Slice of land crab meat", average_rate = "27.3%" } },
  ["Desert Dhalmel"] = { { name = "Sprig of papaka grass", average_rate = "10.9%" }, { name = "Slice of dhalmel meat", average_rate = "105.1%" }, { name = "Dhalmel hide", average_rate = "30.7%" }, { name = "Giant femur", average_rate = "20.6%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Diatryma"] = { { name = "Slice of diatryma meat", average_rate = "23.3%" }, { name = "Giant bird plume", average_rate = "8.6%" }, { name = "Giant bird feather", average_rate = "12.1%" } },
  ["Donnergugi"] = { { name = "Piece of thunder coral", average_rate = "24.4%" } },
  ["Doom Scorpion"] = { { name = "Scorpion shell", average_rate = "18.6%" }, { name = "Scorpion claw", average_rate = "24.3%" }, { name = "Vial of desert venom", average_rate = "7.3%" } },
  ["Dune Widow"] = { { name = "Spider web", average_rate = "298.9%" }, { name = "Spider torque", average_rate = "5.3%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "157.0%" } },
  ["Fire Elemental"] = { { name = "Fire cluster", average_rate = "149.2%" } },
  ["Flesh Eater"] = { { name = "Chunk of zinc ore", average_rate = "7.5%" }, { name = "Flint stone", average_rate = "32.7%" }, { name = "Chunk of copper ore", average_rate = "15.0%" }, { name = "Chunk of iron ore", average_rate = "1.4%" } },
  ["Giant Spider"] = { { name = "Spider web", average_rate = "1.5%" }, { name = "Earth cluster", average_rate = "0.07%" } },
  ["Goblin Poacher"] = { { name = "Goblin mask", average_rate = "4.2%" }, { name = "Goblin armor", average_rate = "1.8%" }, { name = "Mythril beastcoin", average_rate = "1.9%" }, { name = "Fire cluster", average_rate = "0.03%" } },
  ["Goblin Reaper"] = { { name = "Goblin helm", average_rate = "4.1%" }, { name = "Scroll of Absorb-INT", average_rate = "2.1%" }, { name = "Scroll of Absorb-AGI", average_rate = "1.8%" }, { name = "Scroll of Absorb-VIT", average_rate = "1.8%" }, { name = "Goblin mail", average_rate = "1.6%" } },
  ["Goblin Robber"] = { { name = "Mythril beastcoin", average_rate = "1.8%" }, { name = "Goblin mask", average_rate = "4.0%" }, { name = "Goblin armor", average_rate = "1.6%" }, { name = "Fire cluster", average_rate = "0.03%" } },
  ["Goblin Trader"] = { { name = "Goblin mask", average_rate = "3.1%" }, { name = "Goblin armor", average_rate = "3.1%" } },
  ["Ironshell"] = { { name = "Chunk of rock salt", average_rate = "112.5%" }, { name = "Crab shell", average_rate = "50.0%" }, { name = "Slice of land crab meat", average_rate = "37.5%" } },
  ["Lesser Manticore"] = { { name = "Lock of manticore hair", average_rate = "26.4%" }, { name = "Manticore hide", average_rate = "15.1%" }, { name = "Manticore fang", average_rate = "7.7%" } },
  ["Lost Soul"] = { { name = "Bone chip", average_rate = "25.0%" }, { name = "Revival tree root", average_rate = "13.2%" } },
  ["Nandi"] = { { name = "Rathe earring", average_rate = "17.6%" } },
  ["Sabotender"] = { { name = "Cactus arm", average_rate = "27.9%" }, { name = "Flask of distilled water", average_rate = "28.7%" }, { name = "Cactuar needle", average_rate = "14.0%" }, { name = "Arnica root", average_rate = "14.7%" } },
  ["Sabotender Corrido"] = { { name = "Aptant of tachus", average_rate = "15.8%" }, { name = "Aptant of ishis", average_rate = "23.7%" } },
  ["Sand Beetle"] = { { name = "Beetle shell", average_rate = "14.8%" }, { name = "Insect wing", average_rate = "29.0%" }, { name = "Beetle jaw", average_rate = "7.1%" }, { name = "Earth cluster", average_rate = "0.05%" } },
}
