-- Zone: East Sarutabaruta
return {
  ["Balloon"] = { { name = "Pinch of bomb ash", average_rate = "24.0%" }, { name = "Bomb arm", average_rate = "4.0%" } },
  ["Bumblebee"] = { { name = "Pot of honey", average_rate = "1.6%" }, { name = "Insect wing", average_rate = "3.3%" }, { name = "Rarab tail", average_rate = "5.4%" }, { name = "Wind cluster", average_rate = "0.01%" } },
  ["Carrion Crow"] = { { name = "Bird egg", average_rate = "12.5%" }, { name = "Bird feather", average_rate = "22.9%" }, { name = "Fire cluster", average_rate = "0.02%" } },
  ["Crawler"] = { { name = "Spool of silk thread", average_rate = "13.5%" }, { name = "Crawler calculus", average_rate = "13.2%" }, { name = "Smooth stone", average_rate = "8.9%" }, { name = "Earth cluster", average_rate = "0.00%" } },
  ["Duke Decapod"] = { { name = "Pelte", average_rate = "30.8%" } },
  ["Fighting Pugil"] = { { name = "Handful of pugil scales", average_rate = "32.7%" } },
  ["Giant Bee"] = { { name = "Pot of honey", average_rate = "13.7%" }, { name = "Insect wing", average_rate = "6.8%" }, { name = "Beehive chip", average_rate = "24.9%" }, { name = "Giant stinger", average_rate = "1.7%" }, { name = "Wind cluster", average_rate = "0.01%" } },
  ["Goblin Fisher"] = { { name = "Bamboo fishing rod", average_rate = "1.7%" }, { name = "Goblin helm", average_rate = "2.5%" }, { name = "Goblin mail", average_rate = "1.6%" }, { name = "Yew fishing rod", average_rate = "3.9%" }, { name = "Beastcoin", average_rate = "1.4%" }, { name = "Fastwater fishing rod", average_rate = "0.49%" }, { name = "Clothespole", average_rate = "0.26%" } },
  ["Goblin Thug"] = { { name = "Beastcoin", average_rate = "2.0%" }, { name = "Wild onion", average_rate = "15.6%" }, { name = "Goblin mask", average_rate = "5.4%" }, { name = "Goblin armor", average_rate = "2.5%" } },
  ["Goblin Weaver"] = { { name = "Square of grass cloth", average_rate = "1.7%" }, { name = "Goblin mask", average_rate = "3.1%" }, { name = "Goblin armor", average_rate = "1.7%" }, { name = "Spool of grass thread", average_rate = "2.7%" }, { name = "Spool of cotton thread", average_rate = "1.4%" }, { name = "Beastcoin", average_rate = "1.2%" }, { name = "Square of cotton cloth", average_rate = "0.24%" } },
  ["Mad Fox"] = { { name = "Wolf hide", average_rate = "13.9%" }, { name = "Revival tree root", average_rate = "4.6%" } },
  ["Magicked Bones"] = { { name = "Bone chip", average_rate = "22.0%" } },
  ["Mandragora"] = { { name = "Cornette", average_rate = "13.9%" }, { name = "Pinch of Yuhtunga sulfur", average_rate = "4.9%" }, { name = "Two-leaf mandragora bud", average_rate = "8.9%" }, { name = "Four-leaf mandragora bud", average_rate = "1.5%" }, { name = "Earth cluster", average_rate = "0.02%" } },
  ["Mud Pugil"] = { { name = "Handful of pugil scales", average_rate = "32.1%" } },
  ["Palm Crab"] = { { name = "Chunk of rock salt", average_rate = "17.7%" }, { name = "Slice of land crab meat", average_rate = "1.6%" } },
  ["Pixie"] = { { name = "Pinch of Stygian ash", average_rate = "63.6%" } },
  ["Pug Pugil"] = { { name = "Handful of pugil scales", average_rate = "12.9%" }, { name = "Water cluster", average_rate = "0.06%" } },
  ["Pyracmon"] = { { name = "Kingdom stables collar", average_rate = "39.1%" }, { name = "Republic stables medal", average_rate = "37.9%" }, { name = "Federation stables scarf", average_rate = "29.9%" } },
  ["River Crab"] = { { name = "Remi shell", average_rate = "12.2%" }, { name = "Chunk of rock salt", average_rate = "22.6%" }, { name = "Slice of land crab meat", average_rate = "1.2%" }, { name = "Water cluster", average_rate = "0.01%" } },
  ["Savanna Crab"] = { { name = "Chunk of rock salt", average_rate = "21.4%" }, { name = "Slice of land crab meat", average_rate = "4.5%" } },
  ["Savanna Rarab"] = { { name = "Rabbit hide", average_rate = "12.8%" }, { name = "Muddy bar tab", average_rate = "7.2%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Sharp-Eared Ropipi"] = { { name = "Entrancing ribbon", average_rate = "100.0%" } },
  ["Spiny Spipi"] = { { name = "Spool of silk thread", average_rate = "163.7%" }, { name = "Mist silk cape", average_rate = "36.8%" } },
  ["Tiny Mandragora"] = { { name = "Two-leaf mandragora bud", average_rate = "8.0%" }, { name = "Earth cluster", average_rate = "0.02%" } },
  ["Yagudo Acolyte"] = { { name = "Yagudo feather", average_rate = "92.6%" }, { name = "Yagudo bead necklace", average_rate = "22.3%" }, { name = "Scroll of Barsleep", average_rate = "2.9%" }, { name = "Scroll of Paralyze", average_rate = "3.6%" }, { name = "Scroll of Protectra", average_rate = "2.6%" }, { name = "Scroll of Sneak", average_rate = "2.9%" }, { name = "Wind cluster", average_rate = "0.02%" } },
  ["Yagudo Initiate"] = { { name = "Yagudo bead necklace", average_rate = "12.6%" }, { name = "Skull locust", average_rate = "1.5%" }, { name = "Yagudo feather", average_rate = "36.5%" }, { name = "Wind cluster", average_rate = "0.02%" } },
  ["Yagudo Scribe"] = { { name = "Yagudo feather", average_rate = "92.5%" }, { name = "Scroll of Blind", average_rate = "6.8%" }, { name = "Scroll of Bind", average_rate = "5.2%" }, { name = "Yagudo bead necklace", average_rate = "22.5%" } },
}
