-- Zone: Buburimu Peninsula
return {
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "166.5%" } },
  ["Backoo"] = { { name = "Mandragora scale", average_rate = "34.5%" } },
  ["Bogy"] = { { name = "Bloody robe", average_rate = "32.9%" }, { name = "Revival tree root", average_rate = "14.2%" }, { name = "Luminicloth", average_rate = "7.3%" } },
  ["Buburimboo"] = { { name = "Handful of pugil scales", average_rate = "23.0%" }, { name = "Buburimu gorget", average_rate = "16.2%" } },
  ["Bull Dhalmel"] = { { name = "Slice of dhalmel meat", average_rate = "106.5%" }, { name = "Giant femur", average_rate = "21.2%" }, { name = "Dhalmel hide", average_rate = "29.5%" }, { name = "Cup of dhalmel saliva", average_rate = "11.1%" }, { name = "Sprig of papaka grass", average_rate = "9.8%" }, { name = "Earth cluster", average_rate = "0.00%" } },
  ["Carnivorous Crawler"] = { { name = "Spool of silk thread", average_rate = "17.0%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Clipper"] = { { name = "Chunk of rock salt", average_rate = "17.0%" }, { name = "Slice of land crab meat", average_rate = "4.3%" } },
  ["Ghoul"] = { { name = "Magicked skull", average_rate = "26.8%" }, { name = "Bone chip", average_rate = "14.7%" } },
  ["Goblin Ambusher"] = { { name = "Block of animal glue", average_rate = "12.6%" }, { name = "Goblin mask", average_rate = "3.6%" }, { name = "Beastcoin", average_rate = "1.4%" }, { name = "Goblin armor", average_rate = "1.9%" }, { name = "Fire cluster", average_rate = "0.02%" } },
  ["Goblin Bounty Hunter"] = { { name = "Goblin mail", average_rate = "2.0%" }, { name = "Goblin helm", average_rate = "4.2%" } },
  ["Goblin Butcher"] = { { name = "Goblin mail", average_rate = "1.6%" }, { name = "Goblin helm", average_rate = "3.7%" }, { name = "Lightning cluster", average_rate = "0.02%" } },
  ["Goblin Gambler"] = { { name = "Goblin mask", average_rate = "4.0%" }, { name = "Goblin armor", average_rate = "1.7%" }, { name = "Bag of poison flour", average_rate = "1.7%" }, { name = "Fire cluster", average_rate = "0.02%" } },
  ["Goblin Leecher"] = { { name = "Scroll of Barpoison", average_rate = "1.5%" }, { name = "Scroll of Barsleep", average_rate = "3.2%" }, { name = "Scroll of Invisible", average_rate = "0.70%" }, { name = "Goblin armor", average_rate = "1.7%" }, { name = "Goblin mask", average_rate = "3.9%" }, { name = "Scroll of Protectra", average_rate = "3.0%" }, { name = "Scroll of Silence", average_rate = "3.0%" }, { name = "Scroll of Paralyze", average_rate = "4.0%" }, { name = "Scroll of Sneak", average_rate = "2.9%" }, { name = "Silver beastcoin", average_rate = "1.3%" }, { name = "Scroll of Deodorize", average_rate = "0.93%" } },
  ["Goblin Mugger"] = { { name = "Goblin mask", average_rate = "3.5%" }, { name = "Goblin armor", average_rate = "1.9%" }, { name = "Silver beastcoin", average_rate = "1.7%" } },
  ["Goblin Tinkerer"] = { { name = "Goblin mail", average_rate = "2.1%" }, { name = "Goblin helm", average_rate = "3.4%" }, { name = "Beastcoin", average_rate = "1.6%" } },
  ["Helldiver"] = { { name = "Bird feather", average_rate = "101.4%" }, { name = "Wingedge", average_rate = "26.0%" } },
  ["Mighty Rarab"] = { { name = "Slice of hare meat", average_rate = "34.5%" }, { name = "Wild rabbit tail", average_rate = "7.8%" }, { name = "Earth cluster", average_rate = "0.00%" } },
  ["Pixie"] = { { name = "Pinch of Stygian ash", average_rate = "91.1%" } },
  ["Poison Leech"] = { { name = "Vial of bird blood", average_rate = "95.6%" }, { name = "Carbuncle's ruby", average_rate = "1.7%" }, { name = "Water cluster", average_rate = "0.03%" } },
  ["Shoal Pugil"] = { { name = "Handful of pugil scales", average_rate = "12.8%" }, { name = "Shall shell", average_rate = "6.4%" } },
  ["Snipper"] = { { name = "Slice of land crab meat", average_rate = "6.4%" }, { name = "Chunk of rock salt", average_rate = "25.3%" }, { name = "Crab shell", average_rate = "1.5%" }, { name = "Water cluster", average_rate = "0.06%" } },
  ["Stag Crab"] = { { name = "Chunk of rock salt", average_rate = "31.5%" }, { name = "Slice of land crab meat", average_rate = "2.7%" } },
  ["Sylvestre"] = { { name = "Ball of Saruta cotton", average_rate = "13.2%" }, { name = "Two-leaf mandragora bud", average_rate = "10.2%" }, { name = "Four-leaf mandragora bud", average_rate = "1.1%" }, { name = "Pinch of Yuhtunga sulfur", average_rate = "4.2%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Wake Warder Wanda"] = { { name = "Melampus staff", average_rate = "32.0%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "135.1%" } },
  ["Will-O'-The-Wisp"] = { { name = "Bomb arm", average_rate = "14.5%" }, { name = "Pinch of bomb ash", average_rate = "32.1%" } },
  ["Zombie"] = { { name = "Bone chip", average_rate = "23.6%" } },
  ["Zu"] = { { name = "Bird feather", average_rate = "23.9%" }, { name = "Bird egg", average_rate = "13.1%" }, { name = "Fire cluster", average_rate = "0.02%" } },
}
