-- Zone: Newton Movalpolos
return {
  ["Bugbear Deathsman"] = { { name = "Chunk of kopparnickel ore", average_rate = "21.4%" }, { name = "Bugbear mask", average_rate = "9.7%" }, { name = "Sylvan stone", average_rate = "14.3%" }, { name = "Newton coffer key", average_rate = "10.0%" }, { name = "Igneous rock", average_rate = "3.2%" }, { name = "Lightning cluster", average_rate = "0.15%" } },
  ["Bugbear Matman"] = { { name = "Chunk of kopparnickel ore", average_rate = "33.3%" }, { name = "Rutter sabatons", average_rate = "33.3%" }, { name = "Bugbear mask", average_rate = "33.3%" }, { name = "Sylvan stone", average_rate = "33.3%" } },
  ["Bugbear Trashman"] = { { name = "Bugbear mask", average_rate = "8.4%" }, { name = "Chunk of kopparnickel ore", average_rate = "34.6%" }, { name = "Igneous rock", average_rate = "2.5%" }, { name = "Sylvan stone", average_rate = "12.7%" } },
  ["Bugbear Watchman"] = { { name = "Sylvan stone", average_rate = "22.5%" }, { name = "Igneous rock", average_rate = "8.1%" }, { name = "Newton coffer key", average_rate = "6.4%" }, { name = "Chunk of kopparnickel ore", average_rate = "16.6%" }, { name = "Bugbear mask", average_rate = "2.4%" } },
  ["Dire Bat"] = { { name = "Bat wing", average_rate = "28.8%" }, { name = "Bat fang", average_rate = "10.0%" }, { name = "Vial of fiend blood", average_rate = "7.5%" }, { name = "Vial of beastman blood", average_rate = "1.2%" } },
  ["Dreyruk"] = { { name = "Elixir", average_rate = "100.0%" }, { name = "Blustery dagger", average_rate = "100.0%" }, { name = "Alcedo cuisses", average_rate = "100.0%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "165.6%" } },
  ["Goblin Fireman"] = { { name = "Goblin helm", average_rate = "7.2%" }, { name = "Gold key", average_rate = "14.7%" }, { name = "Goblin mail", average_rate = "2.9%" } },
  ["Goblin Foreman"] = { { name = "Gold key", average_rate = "14.2%" }, { name = "Goblin mask", average_rate = "5.9%" }, { name = "Goblin armor", average_rate = "3.3%" } },
  ["Goblin Hangman"] = { { name = "Goblin helm", average_rate = "7.9%" }, { name = "Jar of firesand", average_rate = "16.8%" }, { name = "Goblin mail", average_rate = "3.3%" } },
  ["Goblin Headman"] = { { name = "Goblin armor", average_rate = "2.2%" }, { name = "Goblin mask", average_rate = "7.8%" }, { name = "Jar of firesand", average_rate = "15.3%" } },
  ["Goblin Junkman"] = { { name = "Jar of firesand", average_rate = "18.8%" }, { name = "Newton coffer key", average_rate = "4.2%" }, { name = "Goblin helm", average_rate = "7.2%" }, { name = "Goblin mail", average_rate = "3.0%" } },
  ["Goblin Lengthman"] = { { name = "Gold key", average_rate = "13.5%" }, { name = "Goblin armor", average_rate = "3.9%" }, { name = "Goblin mask", average_rate = "5.4%" } },
  ["Goblin Marksman"] = { { name = "Goblin mask", average_rate = "8.5%" }, { name = "Goblin armor", average_rate = "2.1%" }, { name = "Jar of firesand", average_rate = "18.3%" } },
  ["Goblin Packman"] = { { name = "Goblin helm", average_rate = "6.4%" }, { name = "Gold key", average_rate = "12.9%" }, { name = "Goblin mail", average_rate = "2.8%" } },
  ["Goblin Swordsman"] = { { name = "Sylvan stone", average_rate = "93.8%" }, { name = "Goblin helm", average_rate = "3.0%" }, { name = "Goblin mail", average_rate = "2.3%" } },
  ["Goblin's Bat"] = { { name = "Newton coffer key", average_rate = "2.5%" } },
  ["Mimic"] = { { name = "Newton coffer key", average_rate = "50.0%" } },
  ["Moblin Aidman"] = { { name = "Moblin armor", average_rate = "8.4%" }, { name = "Spool of Moblin thread", average_rate = "41.4%" }, { name = "Moblin sheepskin", average_rate = "21.0%" }, { name = "Newton coffer key", average_rate = "0.88%" } },
  ["Moblin Draftsman"] = { { name = "Moblin sheepskin", average_rate = "17.6%" }, { name = "Moblin mask", average_rate = "33.7%" }, { name = "Moblin armor", average_rate = "9.8%" }, { name = "Scroll of Stone III", average_rate = "0.85%" }, { name = "Scroll of Stonega II", average_rate = "0.47%" }, { name = "Scroll of Quake", average_rate = "0.08%" }, { name = "Scroll of Stonega III", average_rate = "0.08%" } },
  ["Moblin Engineman"] = { { name = "Jar of firesand", average_rate = "35.9%" }, { name = "Moblin sheepskin", average_rate = "16.8%" }, { name = "Moblin armor", average_rate = "10.6%" }, { name = "Scroll of Aeroga III", average_rate = "0.42%" }, { name = "Scroll of Aeroga II", average_rate = "0.70%" }, { name = "Scroll of Aero III", average_rate = "2.0%" }, { name = "Scroll of Aero IV", average_rate = "0.14%" } },
  ["Moblin Groundman"] = { { name = "Moblin hotrok", average_rate = "30.0%" }, { name = "Moblin helm", average_rate = "22.7%" }, { name = "Moblin mail", average_rate = "5.3%" } },
  ["Moblin Roadman"] = { { name = "Jar of firesand", average_rate = "35.9%" }, { name = "Moblin mask", average_rate = "17.2%" }, { name = "Glass fiber fishing rod", average_rate = "9.9%" }, { name = "Newton coffer key", average_rate = "0.10%" }, { name = "Moblin armor", average_rate = "3.7%" } },
  ["Moblin Scalpelman"] = { { name = "Moblin armor", average_rate = "19.2%" }, { name = "Moblin mask", average_rate = "33.1%" } },
  ["Moblin Tankman"] = { { name = "Moblin mask", average_rate = "32.8%" }, { name = "Gold key", average_rate = "6.0%" }, { name = "Moblin sheepskin", average_rate = "14.7%" }, { name = "Moblin armor", average_rate = "2.4%" }, { name = "Fire cluster", average_rate = "0.10%" } },
  ["Moblin Topsman"] = { { name = "Spool of Moblin thread", average_rate = "36.6%" }, { name = "Moblin mask", average_rate = "17.2%" }, { name = "Moblin armor", average_rate = "8.1%" } },
  ["Moblin Workman"] = { { name = "Moblin mask", average_rate = "16.8%" }, { name = "Gold key", average_rate = "7.5%" }, { name = "Moblin armor", average_rate = "2.4%" } },
  ["Moblin Yardman"] = { { name = "Moblin mask", average_rate = "18.1%" }, { name = "Moblin armor", average_rate = "2.3%" }, { name = "Gold key", average_rate = "5.8%" } },
  ["Nightmare Bats"] = { { name = "Bat wing", average_rate = "38.2%" }, { name = "Bat fang", average_rate = "17.8%" }, { name = "Vial of fiend blood", average_rate = "12.1%" }, { name = "Newton coffer key", average_rate = "7.6%" }, { name = "Vial of beastman blood", average_rate = "3.2%" } },
  ["Purgatory Bat"] = { { name = "Bat wing", average_rate = "46.5%" }, { name = "Bat fang", average_rate = "19.2%" }, { name = "Newton coffer key", average_rate = "8.1%" }, { name = "Vial of fiend blood", average_rate = "11.1%" }, { name = "Vial of beastman blood", average_rate = "6.1%" } },
  ["Succubus Bats"] = { { name = "Bat fang", average_rate = "17.2%" }, { name = "Bat wing", average_rate = "35.9%" }, { name = "Vial of fiend blood", average_rate = "8.6%" }, { name = "Vial of beastman blood", average_rate = "1.0%" } },
  ["Swashstox Beadblinker"] = { { name = "Darksteel codpiece", average_rate = "111.8%" }, { name = "Sylvan stone", average_rate = "23.5%" }, { name = "Pachamac's collar", average_rate = "23.5%" } },
  ["Sword Sorcerer Solisoq"] = { { name = "Aptant of arkhe", average_rate = "17.3%" }, { name = "Aptant of primus", average_rate = "23.1%" }, { name = "Aptant of fyrst", average_rate = "9.6%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "177.8%" }, { name = "Newton coffer key", average_rate = "2.2%" } },
}
