-- Zone: The Sanctuary of Zi'Tah
return {
  ["Ancient Bat"] = { { name = "Bat wing", average_rate = "30.1%" }, { name = "Bat fang", average_rate = "14.5%" }, { name = "Vial of fiend blood", average_rate = "1.7%" } },
  ["Bastet"] = { { name = "Bastet fang", average_rate = "19.9%" } },
  ["Elusive Edwin"] = { { name = "Forte earring", average_rate = "16.3%" } },
  ["Goblin Enchanter"] = { { name = "Mannequin feet", average_rate = "6.7%" }, { name = "Mannequin legs", average_rate = "13.3%" } },
  ["Goblin Furrier"] = { { name = "Square of dhalmel leather", average_rate = "1.7%" }, { name = "Square of sheep leather", average_rate = "6.2%" }, { name = "Goblin mask", average_rate = "7.1%" }, { name = "Square of black tiger leather", average_rate = "1.7%" }, { name = "Goblin armor", average_rate = "4.3%" }, { name = "Square of coeurl leather", average_rate = "0.57%" }, { name = "Mythril beastcoin", average_rate = "2.0%" } },
  ["Goblin Gambler"] = { { name = "Goblin mask", average_rate = "3.8%" }, { name = "Bag of poison flour", average_rate = "1.3%" }, { name = "Goblin armor", average_rate = "1.7%" } },
  ["Goblin Leecher"] = { { name = "Scroll of Deodorize", average_rate = "0.85%" }, { name = "Scroll of Paralyze", average_rate = "3.4%" }, { name = "Silver beastcoin", average_rate = "2.3%" }, { name = "Scroll of Silence", average_rate = "4.6%" }, { name = "Scroll of Sneak", average_rate = "2.6%" }, { name = "Goblin mask", average_rate = "7.1%" }, { name = "Scroll of Barsleep", average_rate = "2.6%" }, { name = "Scroll of Protectra", average_rate = "3.7%" }, { name = "Scroll of Barpoison", average_rate = "4.3%" }, { name = "Goblin armor", average_rate = "2.3%" }, { name = "Scroll of Invisible", average_rate = "0.57%" } },
  ["Goblin Mugger"] = { { name = "Goblin armor", average_rate = "1.9%" }, { name = "Silver beastcoin", average_rate = "1.8%" }, { name = "Goblin mask", average_rate = "2.9%" } },
  ["Goblin Poacher"] = { { name = "Mythril beastcoin", average_rate = "8.8%" }, { name = "Goblin armor", average_rate = "7.8%" }, { name = "Goblin mask", average_rate = "15.6%" }, { name = "Sack of hell hound fangs", average_rate = "5.1%" } },
  ["Goblin Reaper"] = { { name = "Scroll of Absorb-AGI", average_rate = "2.5%" }, { name = "Scroll of Absorb-VIT", average_rate = "3.4%" }, { name = "Goblin helm", average_rate = "5.0%" }, { name = "Scroll of Absorb-INT", average_rate = "4.0%" }, { name = "Goblin mail", average_rate = "1.6%" } },
  ["Goblin Robber"] = { { name = "Sack of fish bait", average_rate = "33.2%" }, { name = "Goblin mask", average_rate = "4.7%" }, { name = "Goblin armor", average_rate = "1.9%" }, { name = "Sack of hell hound fangs", average_rate = "6.1%" }, { name = "Fire cluster", average_rate = "0.04%" } },
  ["Goblin Smithy"] = { { name = "Goblin helm", average_rate = "6.3%" }, { name = "Goblin mail", average_rate = "3.8%" }, { name = "Lightning cluster", average_rate = "0.15%" } },
  ["Goblin Trader"] = { { name = "Goblin armor", average_rate = "8.4%" }, { name = "Goblin mask", average_rate = "13.0%" }, { name = "Sack of hell hound fangs", average_rate = "7.1%" }, { name = "Square of velvet cloth", average_rate = "0.17%" } },
  ["Goobbue Gardener"] = { { name = "Clump of Boyahda moss", average_rate = "33.0%" }, { name = "Bag of tree cuttings", average_rate = "16.4%" }, { name = "Clump of goobbue humus", average_rate = "0.14%" } },
  ["Goobbue Parasite"] = { { name = "Vial of fiend blood", average_rate = "15.1%" }, { name = "Vial of beastman blood", average_rate = "7.1%" }, { name = "Carbuncle's ruby", average_rate = "1.9%" } },
  ["Hell Hound"] = { { name = "Wolf hide", average_rate = "32.9%" }, { name = "Revival tree root", average_rate = "14.8%" } },
  ["Huwasi"] = { { name = "Imperial topaz", average_rate = "18.7%" } },
  ["Keeper Of Halidom"] = { { name = "Clump of Boyahda moss", average_rate = "202.5%" }, { name = "Bag of tree cuttings", average_rate = "101.3%" }, { name = "Daihannya", average_rate = "0.06%" } },
  ["Lesser Gaylas"] = { { name = "Vial of beast blood", average_rate = "93.2%" }, { name = "Vial of fiend blood", average_rate = "8.7%" }, { name = "Bat wing", average_rate = "16.4%" } },
  ["Lost Soul"] = { { name = "Bone chip", average_rate = "23.5%" }, { name = "Revival tree root", average_rate = "14.0%" } },
  ["Master Coeurl"] = { { name = "Coeurl hide", average_rate = "24.7%" }, { name = "Slice of coeurl meat", average_rate = "53.5%" }, { name = "Coeurl whisker", average_rate = "11.4%" } },
  ["Myxomycete"] = { { name = "Sleepshroom", average_rate = "31.7%" }, { name = "Woozyshroom", average_rate = "17.2%" }, { name = "Danceshroom", average_rate = "8.4%" } },
  ["Noble Mold"] = { { name = "Rain hat", average_rate = "66.7%" } },
  ["Ogrefly"] = { { name = "Insect wing", average_rate = "25.8%" }, { name = "Wind cluster", average_rate = "0.08%" } },
  ["Puroboros"] = { { name = "Bomb arm", average_rate = "17.4%" }, { name = "Pinch of bomb ash", average_rate = "25.6%" } },
  ["Revenant"] = { { name = "Square of linen cloth", average_rate = "49.5%" }, { name = "Revival tree root", average_rate = "26.9%" } },
  ["Rock Golem"] = { { name = "Chunk of mythril ore", average_rate = "8.4%" }, { name = "Golem shard", average_rate = "7.2%" } },
  ["Rot Prowler"] = { { name = "Scroll of Absorb-INT", average_rate = "7.2%" }, { name = "Scroll of Absorb-AGI", average_rate = "2.6%" }, { name = "Bone chip", average_rate = "31.7%" }, { name = "Revival tree root", average_rate = "7.9%" }, { name = "Scroll of Absorb-VIT", average_rate = "7.2%" }, { name = "Scroll of Stun", average_rate = "2.3%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "154.0%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "158.9%" } },
}
