-- Zone: Yuhtunga Jungle
return {
  ["Bigclaw"] = { { name = "Chunk of rock salt", average_rate = "100.0%" }, { name = "Slice of land crab meat", average_rate = "30.0%" }, { name = "Crab shell", average_rate = "23.3%" } },
  ["Bloodsucker"] = { { name = "Vial of fiend blood", average_rate = "10.0%" } },
  ["Carthi"] = { { name = "Lightning cluster", average_rate = "0.15%" } },
  ["Creek Sahagin"] = { { name = "Seashell", average_rate = "38.2%" }, { name = "Elshimo frog", average_rate = "17.7%" }, { name = "Shall shell", average_rate = "8.7%" }, { name = "Mermaid hands", average_rate = "2.0%" } },
  ["Death Jacket"] = { { name = "Beehive chip", average_rate = "26.9%" }, { name = "Pot of honey", average_rate = "17.8%" }, { name = "Insect wing", average_rate = "6.6%" }, { name = "Giant stinger", average_rate = "1.7%" } },
  ["Fire Elemental"] = { { name = "Fire cluster", average_rate = "171.4%" } },
  ["Goblin Furrier"] = { { name = "Square of sheep leather", average_rate = "4.6%" }, { name = "Goblin armor", average_rate = "2.7%" }, { name = "Goblin mask", average_rate = "5.7%" }, { name = "Square of dhalmel leather", average_rate = "2.2%" }, { name = "Square of coeurl leather", average_rate = "0.41%" }, { name = "Mythril beastcoin", average_rate = "1.9%" }, { name = "Square of black tiger leather", average_rate = "0.51%" } },
  ["Goblin Poacher"] = { { name = "Mythril beastcoin", average_rate = "2.4%" }, { name = "Goblin mask", average_rate = "3.0%" }, { name = "Goblin armor", average_rate = "1.8%" } },
  ["Goblin Reaper"] = { { name = "Goblin helm", average_rate = "5.1%" }, { name = "Scroll of Absorb-INT", average_rate = "2.5%" }, { name = "Scroll of Absorb-VIT", average_rate = "1.6%" }, { name = "Scroll of Absorb-AGI", average_rate = "1.1%" }, { name = "Goblin mail", average_rate = "1.6%" } },
  ["Goblin Robber"] = { { name = "Goblin mask", average_rate = "5.2%" }, { name = "Goblin armor", average_rate = "2.2%" } },
  ["Goblin Smithy"] = { { name = "Goblin helm", average_rate = "3.8%" }, { name = "Goblin mail", average_rate = "1.8%" }, { name = "Lightning cluster", average_rate = "0.04%" } },
  ["Ironshell"] = { { name = "Chunk of rock salt", average_rate = "105.0%" }, { name = "Slice of land crab meat", average_rate = "63.3%" }, { name = "Crab shell", average_rate = "23.3%" } },
  ["Ivory Lizard"] = { { name = "Lizard tail", average_rate = "39.5%" }, { name = "Lizard egg", average_rate = "23.6%" }, { name = "Slab of Elshimo marble", average_rate = "2.8%" }, { name = "Lizard skin", average_rate = "11.7%" }, { name = "Fire cluster", average_rate = "0.03%" } },
  ["Jungle Coeurl"] = { { name = "Slice of coeurl meat", average_rate = "41.7%" }, { name = "Coeurl whisker", average_rate = "13.6%" }, { name = "Coeurl hide", average_rate = "19.6%" } },
  ["Koropokkur"] = { { name = "Aega's doublet", average_rate = "12.9%" } },
  ["Lava Bomb"] = { { name = "Bomb arm", average_rate = "33.3%" } },
  ["Makara"] = { { name = "Handful of pugil scales", average_rate = "15.2%" } },
  ["Meww The Turtlerider"] = { { name = "Oliphant", average_rate = "45.9%" } },
  ["Mischievous Micholas"] = { { name = "Kazham pineapple", average_rate = "66.9%" }, { name = "Bunch of pamamas", average_rate = "100.6%" }, { name = "Thundermelon", average_rate = "44.8%" }, { name = "Kidney dagger", average_rate = "5.2%" } },
  ["Overgrown Rose"] = { { name = "Malboro vine", average_rate = "35.1%" }, { name = "Mushroom locust", average_rate = "17.7%" }, { name = "Wild pineapple", average_rate = "7.2%" }, { name = "Lacquer tree log", average_rate = "2.3%" } },
  ["Pyuu The Spatemaker"] = { { name = "Ingot of Sahagin gold", average_rate = "14.3%" } },
  ["River Sahagin"] = { { name = "Scroll of Cura", average_rate = "10.1%" }, { name = "Shall shell", average_rate = "8.0%" }, { name = "Eastern gem", average_rate = "15.8%" }, { name = "Seashell", average_rate = "18.0%" } },
  ["Rose Garden"] = { { name = "Vilma's ring", average_rate = "11.9%" }, { name = "Malboro vine", average_rate = "56.7%" }, { name = "Wild pineapple", average_rate = "5.7%" }, { name = "Lacquer tree log", average_rate = "2.6%" } },
  ["Soldier Crawler"] = { { name = "Piece of crawler cocoon", average_rate = "14.2%" }, { name = "Spool of silk thread", average_rate = "9.3%" }, { name = "Crawler egg", average_rate = "1.4%" }, { name = "Earth cluster", average_rate = "0.16%" } },
  ["Stream Sahagin"] = { { name = "Shall shell", average_rate = "8.3%" }, { name = "Seashell", average_rate = "38.1%" }, { name = "Eastern gem", average_rate = "18.7%" }, { name = "Pearl", average_rate = "2.0%" }, { name = "Water cluster", average_rate = "0.28%" } },
  ["Voluptuous Vilma"] = { { name = "Vilma's ring", average_rate = "48.1%" }, { name = "Malboro vine", average_rate = "60.4%" }, { name = "Lacquer tree log", average_rate = "3.4%" }, { name = "Wild pineapple", average_rate = "5.5%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "174.2%" } },
  ["Young Opo-Opo"] = { { name = "Pebble", average_rate = "27.4%" }, { name = "Elshimo coconut", average_rate = "7.0%" }, { name = "Bunch of pamamas", average_rate = "14.2%" }, { name = "Bunch of wild pamamas", average_rate = "1.9%" } },
  ["Yuhtunga Mandragora"] = { { name = "Two-leaf mandragora bud", average_rate = "15.2%" }, { name = "Three-leaf mandragora bud", average_rate = "1.3%" }, { name = "Earth cluster", average_rate = "0.03%" } },
}
