-- Zone: Yhoator Jungle
return {
  ["Acolnahuacatl"] = { { name = "Echo cape", average_rate = "4.9%" } },
  ["Anemone"] = { { name = "Warm egg", average_rate = "8.0%" }, { name = "Malboro vine", average_rate = "49.4%" }, { name = "Mushroom locust", average_rate = "15.6%" }, { name = "Lacquer tree log", average_rate = "2.4%" } },
  ["Big Jaw"] = { { name = "Handful of pugil scales", average_rate = "13.1%" } },
  ["Bisque-Heeled Sunberry"] = { { name = "Rancor handle", average_rate = "98.8%" } },
  ["Bright-Handed Kunberry"] = { { name = "Resentment cape", average_rate = "41.3%" } },
  ["Clipper"] = { { name = "Chunk of rock salt", average_rate = "102.2%" }, { name = "Slice of land crab meat", average_rate = "47.8%" }, { name = "Crab shell", average_rate = "22.2%" } },
  ["Fire Elemental"] = { { name = "Fire cluster", average_rate = "144.4%" } },
  ["Goblin Bouncer"] = { { name = "Goblin helm", average_rate = "2.7%" }, { name = "Goblin mail", average_rate = "1.7%" }, { name = "Gold beastcoin", average_rate = "0.33%" } },
  ["Goblin Hunter"] = { { name = "Goblin armor", average_rate = "4.7%" }, { name = "Goblin mask", average_rate = "4.7%" }, { name = "Gold beastcoin", average_rate = "1.0%" } },
  ["Goblin Pathfinder"] = { { name = "Handful of counterfeit gil", average_rate = "6.4%" }, { name = "Goblin mask", average_rate = "3.2%" }, { name = "Goblin armor", average_rate = "3.2%" }, { name = "Mythril beastcoin", average_rate = "0.35%" } },
  ["Goblin Poacher"] = { { name = "Goblin mask", average_rate = "2.6%" }, { name = "Mythril beastcoin", average_rate = "1.3%" } },
  ["Goblin Reaper"] = { { name = "Goblin mail", average_rate = "3.6%" }, { name = "Scroll of Absorb-VIT", average_rate = "2.1%" }, { name = "Scroll of Absorb-AGI", average_rate = "1.8%" }, { name = "Goblin helm", average_rate = "6.3%" }, { name = "Scroll of Absorb-INT", average_rate = "3.0%" } },
  ["Goblin Robber"] = { { name = "Goblin armor", average_rate = "1.4%" }, { name = "Goblin mask", average_rate = "2.2%" }, { name = "Mythril beastcoin", average_rate = "0.72%" } },
  ["Goblin Shaman"] = { { name = "Goblin mask", average_rate = "4.7%" }, { name = "Mythril beastcoin", average_rate = "1.5%" }, { name = "Goblin armor", average_rate = "0.76%" } },
  ["Goblin Smithy"] = { { name = "Goblin helm", average_rate = "4.7%" }, { name = "Goblin mail", average_rate = "1.6%" } },
  ["Goblin Trader"] = { { name = "Goblin armor", average_rate = "4.3%" }, { name = "Goblin mask", average_rate = "3.4%" }, { name = "Fire cluster", average_rate = "0.85%" } },
  ["Hoar-Knuckled Rimberry"] = { { name = "Sarabande earring", average_rate = "9.1%" } },
  ["Master Coeurl"] = { { name = "Slice of coeurl meat", average_rate = "28.7%" }, { name = "Coeurl hide", average_rate = "15.0%" }, { name = "Coeurl whisker", average_rate = "8.1%" } },
  ["Powderer Penny"] = { { name = "Chary earring", average_rate = "19.8%" } },
  ["Tonberry Chopper"] = { { name = "Tonberry coat", average_rate = "39.3%" }, { name = "Prelate key", average_rate = "7.7%" }, { name = "Flask of venom potion", average_rate = "18.6%" }, { name = "Ninja's testimony", average_rate = "13.5%" }, { name = "Manji shuriken", average_rate = "1.6%" }, { name = "Scroll of Hojo: Ni", average_rate = "0.18%" }, { name = "Scroll of Tonko: Ni", average_rate = "0.46%" } },
  ["Tonberry Creeper"] = { { name = "Tonberry coat", average_rate = "31.6%" }, { name = "Flask of poison potion", average_rate = "16.4%" }, { name = "Tonberry lantern", average_rate = "8.2%" } },
  ["Tonberry Harasser"] = { { name = "Tonberry coat", average_rate = "34.6%" }, { name = "Flask of poison potion", average_rate = "17.6%" }, { name = "Tonberry lantern", average_rate = "8.3%" }, { name = "Water Spirit pact", average_rate = "1.9%" } },
  ["Tonberry Hexer"] = { { name = "Tonberry coat", average_rate = "8.1%" }, { name = "Tonberry lantern", average_rate = "7.4%" }, { name = "Rancor tank", average_rate = "7.1%" }, { name = "Flask of poison potion", average_rate = "8.0%" } },
  ["Tonberry Jinxer"] = { { name = "Unlit lantern", average_rate = "25.5%" }, { name = "Tonberry coat", average_rate = "36.3%" }, { name = "Black mage's testimony", average_rate = "9.6%" }, { name = "Scroll of Thundaga II", average_rate = "6.2%" }, { name = "Scroll of Thunder III", average_rate = "2.5%" } },
  ["Tonberry Shadower"] = { { name = "Tonberry board", average_rate = "7.4%" }, { name = "Flask of venom potion", average_rate = "20.6%" }, { name = "Tonberry coat", average_rate = "40.0%" }, { name = "Gold beastcoin", average_rate = "9.3%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "146.0%" } },
  ["White Lizard"] = { { name = "Lizard tail", average_rate = "29.9%" }, { name = "Lizard egg", average_rate = "13.1%" }, { name = "Lizard skin", average_rate = "7.2%" } },
  ["Woodland Sage"] = { { name = "Petrified log", average_rate = "9.6%" }, { name = "Rosewood log", average_rate = "58.5%" }, { name = "Ebony log", average_rate = "20.6%" }, { name = "Mahogany log", average_rate = "36.3%" }, { name = "Sunlight pole", average_rate = "9.6%" } },
  ["Worker Crawler"] = { { name = "Piece of crawler cocoon", average_rate = "15.9%" }, { name = "Crawler egg", average_rate = "2.6%" }, { name = "Spool of silk thread", average_rate = "8.6%" }, { name = "Earth cluster", average_rate = "0.05%" } },
  ["Yhoator Mandragora"] = { { name = "Two-leaf mandragora bud", average_rate = "13.6%" }, { name = "Jug of humus", average_rate = "1.7%" }, { name = "Earth cluster", average_rate = "0.03%" } },
  ["Yhoator Wasp"] = { { name = "Pot of honey", average_rate = "23.5%" }, { name = "Beehive chip", average_rate = "47.7%" }, { name = "Insect wing", average_rate = "9.6%" }, { name = "Giant stinger", average_rate = "4.2%" } },
  ["Young Opo-Opo"] = { { name = "Bunch of pamamas", average_rate = "14.8%" }, { name = "Pebble", average_rate = "22.4%" }, { name = "Elshimo coconut", average_rate = "6.7%" }, { name = "Wild melon", average_rate = "1.7%" }, { name = "Lightning cluster", average_rate = "0.03%" } },
}
