-- Zone: Western Altepa Desert
return {
  ["Antican Eques"] = { { name = "Piece of rotten meat", average_rate = "30.4%" }, { name = "Scroll of Flash", average_rate = "8.4%" }, { name = "Antican pauldron", average_rate = "13.6%" }, { name = "Chunk of iron ore", average_rate = "0.70%" } },
  ["Antican Essedarius"] = { { name = "Piece of rotten meat", average_rate = "26.9%" }, { name = "Iron arrow", average_rate = "6.5%" }, { name = "Chunk of iron ore", average_rate = "1.8%" }, { name = "Antican robe", average_rate = "14.4%" } },
  ["Antican Hoplomachus"] = { { name = "Xhifhut bow", average_rate = "6.2%" }, { name = "Piece of rotten meat", average_rate = "8.5%" }, { name = "Antican pauldron", average_rate = "4.8%" }, { name = "Chunk of mythril ore", average_rate = "0.79%" } },
  ["Antican Lanista"] = { { name = "Jar of Antican acid", average_rate = "37.8%" }, { name = "Piece of rotten meat", average_rate = "12.7%" }, { name = "Antican robe", average_rate = "7.1%" }, { name = "Chunk of mythril ore", average_rate = "1.4%" } },
  ["Antican Retiarius"] = { { name = "Antican robe", average_rate = "12.2%" }, { name = "Piece of rotten meat", average_rate = "31.2%" }, { name = "Chunk of iron ore", average_rate = "2.9%" } },
  ["Antican Secutor"] = { { name = "Piece of rotten meat", average_rate = "28.0%" }, { name = "Antican pauldron", average_rate = "14.5%" }, { name = "Dhalmel leather missive", average_rate = "6.2%" }, { name = "Chunk of mythril ore", average_rate = "1.8%" }, { name = "Dark cluster", average_rate = "0.15%" } },
  ["Bigclaw"] = { { name = "Chunk of rock salt", average_rate = "114.3%" }, { name = "Crab shell", average_rate = "14.3%" }, { name = "Slice of land crab meat", average_rate = "28.6%" } },
  ["Cactuar"] = { { name = "Flask of distilled water", average_rate = "28.1%" }, { name = "Cactuar needle", average_rate = "15.1%" }, { name = "Cactus arm", average_rate = "27.0%" }, { name = "Arnica root", average_rate = "14.0%" } },
  ["Cactuar Cantautor"] = { { name = "Cactuar needle", average_rate = "210.6%" }, { name = "Bag of cactus stems", average_rate = "105.6%" }, { name = "Kung fu shoes", average_rate = "7.7%" } },
  ["Calchas"] = { { name = "Fuchingiri", average_rate = "22.2%" } },
  ["Celphie"] = { { name = "Dhalmel whistle", average_rate = "44.4%" }, { name = "Slice of dhalmel meat", average_rate = "63.9%" }, { name = "Giant femur", average_rate = "11.1%" }, { name = "Sprig of papaka grass", average_rate = "2.8%" } },
  ["Dahu"] = { { name = "Lock of dahu hair", average_rate = "16.9%" } },
  ["Desert Beetle"] = { { name = "Insect wing", average_rate = "29.7%" }, { name = "Beetle shell", average_rate = "14.8%" }, { name = "Beetle jaw", average_rate = "7.4%" }, { name = "Earth cluster", average_rate = "0.04%" } },
  ["Desert Dhalmel"] = { { name = "Slice of dhalmel meat", average_rate = "104.8%" }, { name = "Dhalmel hide", average_rate = "27.6%" }, { name = "Giant femur", average_rate = "22.3%" }, { name = "Sprig of papaka grass", average_rate = "10.3%" } },
  ["Desert Manticore"] = { { name = "Lock of manticore hair", average_rate = "42.4%" }, { name = "Manticore fang", average_rate = "9.1%" }, { name = "Manticore hide", average_rate = "19.8%" } },
  ["Desert Spider"] = { { name = "Spider web", average_rate = "7.3%" }, { name = "Earth cluster", average_rate = "0.04%" } },
  ["Desert Worm"] = { { name = "Chunk of copper ore", average_rate = "16.0%" }, { name = "Flint stone", average_rate = "30.1%" }, { name = "Chunk of zinc ore", average_rate = "8.0%" }, { name = "Chunk of iron ore", average_rate = "1.8%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "154.7%" } },
  ["Fallen Knight"] = { { name = "Bone chip", average_rate = "29.7%" }, { name = "Revival tree root", average_rate = "5.5%" }, { name = "Scroll of Absorb-VIT", average_rate = "7.7%" }, { name = "Scroll of Absorb-AGI", average_rate = "3.3%" }, { name = "Scroll of Stun", average_rate = "3.3%" }, { name = "Scroll of Absorb-INT", average_rate = "2.2%" } },
  ["Fire Elemental"] = { { name = "Fire cluster", average_rate = "162.5%" } },
  ["Goblin Bouncer"] = { { name = "Gold beastcoin", average_rate = "1.5%" }, { name = "Goblin helm", average_rate = "4.4%" }, { name = "Goblin mail", average_rate = "1.5%" } },
  ["Goblin Enchanter"] = { { name = "Goblin armor", average_rate = "3.1%" }, { name = "Goblin mask", average_rate = "3.1%" }, { name = "Gold ingot", average_rate = "1.5%" }, { name = "Silver ingot", average_rate = "1.5%" } },
  ["Goblin Hunter"] = { { name = "Goblin mask", average_rate = "2.9%" }, { name = "Gold beastcoin", average_rate = "2.9%" } },
  ["Goblin Welldigger"] = { { name = "Goblin mask", average_rate = "4.4%" }, { name = "Flask of distilled water", average_rate = "11.1%" } },
  ["Ironshell"] = { { name = "Chunk of rock salt", average_rate = "125.0%" }, { name = "Slice of land crab meat", average_rate = "75.0%" }, { name = "Crab shell", average_rate = "37.5%" } },
  ["King Vinegarroon"] = { { name = "Ace's helm", average_rate = "45.5%" }, { name = "Venomous claw", average_rate = "29.5%" }, { name = "Heavy shell", average_rate = "13.6%" } },
  ["Lich"] = { { name = "Bone chip", average_rate = "20.8%" }, { name = "Southern mummy", average_rate = "7.5%" }, { name = "Revival tree root", average_rate = "11.3%" } },
  ["Phorusrhacos"] = { { name = "Giant bird feather", average_rate = "31.6%" }, { name = "Giant bird plume", average_rate = "8.3%" } },
  ["Picolaton"] = { { name = "Thrakon breastplate", average_rate = "18.2%" } },
  ["Tulwar Scorpion"] = { { name = "Scorpion claw", average_rate = "25.9%" }, { name = "Vial of desert venom", average_rate = "5.4%" }, { name = "Scorpion shell", average_rate = "14.7%" } },
}
