-- Zone: Qufim Island
return {
  ["Acrophies"] = { { name = "Vial of fiend blood", average_rate = "13.3%" }, { name = "Carbuncle's ruby", average_rate = "1.5%" }, { name = "Water cluster", average_rate = "0.02%" } },
  ["Ancient Bat"] = { { name = "Bat wing", average_rate = "22.9%" }, { name = "Vial of fiend blood", average_rate = "1.8%" } },
  ["Atkorkamuy"] = { { name = "Aptant of durus", average_rate = "21.8%" }, { name = "Aptant of tachus", average_rate = "16.2%" } },
  ["Banshee"] = { { name = "Square of cotton cloth", average_rate = "25.1%" }, { name = "Revival tree root", average_rate = "14.0%" }, { name = "Scroll of Escape", average_rate = "7.3%" }, { name = "Luminicloth", average_rate = "1.2%" } },
  ["Clipper"] = { { name = "Chunk of rock salt", average_rate = "23.3%" }, { name = "Crab shell", average_rate = "1.4%" }, { name = "Slice of land crab meat", average_rate = "6.3%" }, { name = "Water cluster", average_rate = "0.02%" } },
  ["Dancing Weapon"] = { { name = "Kaiser sword", average_rate = "4.7%" } },
  ["Dark Bats"] = { { name = "Bat wing", average_rate = "20.7%" } },
  ["Dosetsu Tree"] = { { name = "Raikiri", average_rate = "48.5%" } },
  ["Giant Ascetic"] = { { name = "Ram leather missive", average_rate = "1.2%" }, { name = "Ice cluster", average_rate = "0.02%" } },
  ["Giant Hunter"] = { { name = "Northern fur", average_rate = "5.8%" }, { name = "Mannequin legs", average_rate = "0.04%" } },
  ["Giant Ranger"] = { { name = "Ram leather missive", average_rate = "1.4%" }, { name = "Mannequin feet", average_rate = "0.02%" } },
  ["Giant Trapper"] = { { name = "Ram leather missive", average_rate = "1.3%" } },
  ["Glow Bat"] = { { name = "Bat wing", average_rate = "21.1%" }, { name = "Vial of fiend blood", average_rate = "1.6%" }, { name = "Wind cluster", average_rate = "0.08%" } },
  ["Goblin Bounty Hunter"] = { { name = "Goblin mail", average_rate = "1.6%" }, { name = "Goblin helm", average_rate = "3.7%" } },
  ["Greater Pugil"] = { { name = "Handful of pugil scales", average_rate = "13.0%" }, { name = "Shall shell", average_rate = "6.3%" }, { name = "Water cluster", average_rate = "0.03%" } },
  ["Kraken"] = { { name = "Seashell", average_rate = "23.7%" }, { name = "Shall shell", average_rate = "7.4%" }, { name = "Egret fishing rod", average_rate = "5.9%" }, { name = "Blue rock", average_rate = "0.37%" } },
  ["Land Worm"] = { { name = "Flint stone", average_rate = "23.1%" }, { name = "Chunk of copper ore", average_rate = "12.5%" }, { name = "Chunk of zinc ore", average_rate = "6.2%" }, { name = "Chunk of silver ore", average_rate = "1.4%" }, { name = "Earth cluster", average_rate = "0.02%" } },
  ["Light Elemental"] = { { name = "Light cluster", average_rate = "148.6%" } },
  ["Qoofim"] = { { name = "Sylph earring", average_rate = "29.4%" } },
  ["Sea Bishop"] = { { name = "Seashell", average_rate = "31.4%" }, { name = "Shall shell", average_rate = "6.8%" }, { name = "Blue rock", average_rate = "0.85%" } },
  ["Seeker Bats"] = { { name = "Bat wing", average_rate = "24.5%" } },
  ["Slippery Sucker"] = { { name = "Mystique earring", average_rate = "18.5%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "143.8%" } },
  ["Trickster Kinetix"] = { { name = "Tabar", average_rate = "33.3%" } },
  ["Wight"] = { { name = "Bone chip", average_rate = "25.0%" }, { name = "Scroll of Tractor", average_rate = "3.0%" } },
}
