-- Zone: Castle Zvahl Baileys [S]
return {
  ["Ancient Quadav"] = { { name = "Heavy Quadav backplate", average_rate = "10.3%" }, { name = "Heavy Quadav chestplate", average_rate = "17.2%" } },
  ["Dark Elemental"] = { { name = "Dark cluster", average_rate = "148.4%" } },
  ["Deathwreaker Demon"] = { { name = "Demon horn", average_rate = "10.7%" }, { name = "Square of cambric", average_rate = "5.4%" }, { name = "Demon skull", average_rate = "1.8%" } },
  ["Demon Befouler"] = { { name = "Demon horn", average_rate = "12.9%" }, { name = "Square of cambric", average_rate = "2.8%" } },
  ["Demon Condemner"] = { { name = "Demon horn", average_rate = "16.2%" } },
  ["Demon Corrupter"] = { { name = "Demon horn", average_rate = "10.8%" }, { name = "Square of cambric", average_rate = "2.7%" } },
  ["Demon Entomber"] = { { name = "Demon horn", average_rate = "15.4%" }, { name = "Square of cambric", average_rate = "2.6%" } },
  ["Demon Justiciar"] = { { name = "Demon horn", average_rate = "12.1%" }, { name = "Square of cambric", average_rate = "1.9%" } },
  ["Demon Magus"] = { { name = "Demon horn", average_rate = "14.3%" }, { name = "Square of cambric", average_rate = "1.3%" } },
  ["Demon Suppressor"] = { { name = "Demon horn", average_rate = "32.4%" } },
  ["Demon Warrior"] = { { name = "Demon horn", average_rate = "14.6%" }, { name = "Square of cambric", average_rate = "1.8%" } },
  ["Dire Gargouille"] = { { name = "Gargouille eye", average_rate = "14.0%" }, { name = "Gargouille shank", average_rate = "28.4%" }, { name = "Gargouille horn", average_rate = "2.7%" }, { name = "Iridium ingot", average_rate = "8.7%" } },
  ["Doom Lens"] = { { name = "Ahriman wing", average_rate = "8.3%" }, { name = "Bottle of Ahriman tears", average_rate = "41.3%" }, { name = "Ahriman lens", average_rate = "17.4%" } },
  ["Errand Imp"] = { { name = "Imp horn", average_rate = "9.3%" }, { name = "Imp wing", average_rate = "26.2%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "7.8%" } },
  ["Foredoomer Demon"] = { { name = "Demon horn", average_rate = "5.7%" }, { name = "Demon skull", average_rate = "2.9%" }, { name = "Square of cambric", average_rate = "8.6%" } },
  ["Ice Elemental"] = { { name = "Ice cluster", average_rate = "141.5%" } },
  ["Icefall"] = { { name = "Snoll arm", average_rate = "38.7%" } },
  ["Iron Quadav"] = { { name = "Heavy Quadav chestplate", average_rate = "12.7%" }, { name = "Heavy Quadav backplate", average_rate = "9.9%" } },
  ["Magnes Quadav"] = { { name = "Bottled pixie", average_rate = "10.8%" }, { name = "Scroll of Blind", average_rate = "2.7%" }, { name = "Scroll of Bind", average_rate = "1.4%" } },
  ["Ogler"] = { { name = "Ahriman lens", average_rate = "16.1%" }, { name = "Bottle of Ahriman tears", average_rate = "31.7%" }, { name = "Ahriman wing", average_rate = "11.1%" } },
  ["Orcish Dragonbrander"] = { { name = "Bottled pixie", average_rate = "8.0%" } },
  ["Orcish Protector"] = { { name = "Orc helmet", average_rate = "12.5%" } },
  ["Orcish Veteran"] = { { name = "Orc helmet", average_rate = "11.4%" } },
  ["Orcish Warlord"] = { { name = "Bottled pixie", average_rate = "30.0%" } },
  ["Soulsearer Demon"] = { { name = "Square of cambric", average_rate = "4.0%" }, { name = "Scroll of Firaga III", average_rate = "1.3%" }, { name = "Demon horn", average_rate = "9.3%" }, { name = "Demon skull", average_rate = "5.3%" }, { name = "Scroll of Fire III", average_rate = "1.3%" } },
  ["Woebringer Demon"] = { { name = "Square of cambric", average_rate = "5.7%" }, { name = "Demon skull", average_rate = "3.8%" }, { name = "Demon horn", average_rate = "9.4%" } },
  ["Yagudo Chanter"] = { { name = "Scroll of Warding Round", average_rate = "16.3%" }, { name = "Scroll of Goddess's Hymnus", average_rate = "6.1%" } },
  ["Yagudo Eradicator"] = { { name = "Yagudo kote", average_rate = "14.3%" } },
  ["Yagudo High Priest"] = { { name = "Yagudo feather", average_rate = "36.4%" }, { name = "Bottled pixie", average_rate = "12.1%" } },
  ["Yagudo Knight Templar"] = { { name = "Yagudo kote", average_rate = "16.0%" } },
  ["Yagudo Prelate"] = { { name = "Scroll of Aero III", average_rate = "5.5%" }, { name = "Scroll of Aeroga II", average_rate = "5.5%" } },
  ["Yagudo Sentinel"] = { { name = "Bottled pixie", average_rate = "3.8%" }, { name = "Yagudo feather", average_rate = "42.3%" } },
}
