-- Zone: Qulun Dome
return {
  ["Adaman Quadav"] = { { name = "Dark knight's testimony", average_rate = "45.7%" }, { name = "Gold beastcoin", average_rate = "9.5%" } },
  ["Ancient Quadav"] = { { name = "Warrior's testimony", average_rate = "14.0%" }, { name = "Mythril sallet", average_rate = "0.52%" }, { name = "Mythril gauntlets", average_rate = "0.68%" }, { name = "Mythril cuisses", average_rate = "0.29%" }, { name = "Mythril leggings", average_rate = "0.23%" } },
  ["Darksteel Quadav"] = { { name = "Paladin's testimony", average_rate = "14.0%" }, { name = "Gold beastcoin", average_rate = "3.4%" }, { name = "Water cluster", average_rate = "0.02%" } },
  ["Diamond Quadav"] = { { name = "Diamond", average_rate = "98.2%" }, { name = "Scroll of Regen III", average_rate = "10.8%" }, { name = "White mage's testimony", average_rate = "94.2%" }, { name = "Scroll of Raise II", average_rate = "9.0%" }, { name = "Scroll of Shellra IV", average_rate = "17.0%" }, { name = "Dodge cape", average_rate = "15.9%" }, { name = "Scroll of Cure V", average_rate = "6.9%" }, { name = "Scroll of Curaga IV", average_rate = "2.2%" } },
  ["Platinum Quadav"] = { { name = "Beastcoin", average_rate = "42.2%" }, { name = "Gold beastcoin", average_rate = "8.5%" } },
  ["Ruby Quadav"] = { { name = "Ruby", average_rate = "55.2%" }, { name = "Scroll of Shell IV", average_rate = "38.9%" }, { name = "Red mage's testimony", average_rate = "41.5%" } },
  ["Sapphire Quadav"] = { { name = "Black mage's testimony", average_rate = "13.5%" }, { name = "Scroll of Water III", average_rate = "6.8%" }, { name = "Scroll of Water IV", average_rate = "2.2%" }, { name = "Scroll of Flood", average_rate = "1.5%" }, { name = "Scroll of Waterga II", average_rate = "4.7%" }, { name = "White slacks", average_rate = "0.70%" }, { name = "Black mitts", average_rate = "0.47%" }, { name = "Scroll of Waterga III", average_rate = "3.0%" }, { name = "Moccasins", average_rate = "0.52%" } },
  ["Za'dha Adamantking"] = { { name = "Platinum beastcoin", average_rate = "102.7%" }, { name = "Phoenix feather", average_rate = "27.0%" }, { name = "Ebony log", average_rate = "5.4%" }, { name = "Scroll of Raise III", average_rate = "97.3%" }, { name = "White mage's testimony", average_rate = "97.3%" }, { name = "Square of raxa", average_rate = "33.8%" }, { name = "Mahogany log", average_rate = "14.9%" }, { name = "Philosopher's stone", average_rate = "27.0%" }, { name = "Petrified log", average_rate = "17.6%" }, { name = "Handful of wyvern scales", average_rate = "6.8%" }, { name = "Mistilteinn", average_rate = "5.4%" }, { name = "Damascus ingot", average_rate = "5.4%" }, { name = "Chunk of platinum ore", average_rate = "5.4%" }, { name = "Square of rainbow cloth", average_rate = "4.1%" }, { name = "Reraiser", average_rate = "5.4%" }, { name = "Square of damascene cloth", average_rate = "4.1%" }, { name = "Ram horn", average_rate = "4.1%" }, { name = "Demon horn", average_rate = "5.4%" }, { name = "Coral fragment", average_rate = "9.5%" }, { name = "Vile elixir", average_rate = "2.7%" }, { name = "Vial of black beetle blood", average_rate = "9.5%" }, { name = "Chunk of gold ore", average_rate = "8.1%" }, { name = "Vile elixir +1", average_rate = "1.4%" }, { name = "Spool of malboro fiber", average_rate = "2.7%" }, { name = "Chunk of darksteel ore", average_rate = "4.1%" } },
}
