-- Zone: Davoi
return {
  ["Blubbery Bulge"] = { { name = "Vial of slime oil", average_rate = "76.8%" } },
  ["Davoi Hornet"] = { { name = "Giant stinger", average_rate = "1.8%" }, { name = "Beehive chip", average_rate = "25.7%" }, { name = "Pot of honey", average_rate = "13.3%" }, { name = "Insect wing", average_rate = "5.5%" } },
  ["Davoi Mush"] = { { name = "Vial of slime oil", average_rate = "41.9%" } },
  ["Davoi Pugil"] = { { name = "Handful of pugil scales", average_rate = "4.0%" } },
  ["Davoi Wasp"] = { { name = "Beehive chip", average_rate = "38.6%" }, { name = "Pot of honey", average_rate = "19.2%" }, { name = "Giant stinger", average_rate = "2.6%" }, { name = "Insect wing", average_rate = "7.3%" } },
  ["Dirtyhanded Gochakzuk"] = { { name = "Curse wand", average_rate = "204.3%" } },
  ["Geezard"] = { { name = "Lizard tail", average_rate = "98.7%" }, { name = "Lizard egg", average_rate = "75.4%" }, { name = "Lizard skin", average_rate = "34.6%" } },
  ["Gloop"] = { { name = "Vial of slime oil", average_rate = "30.8%" }, { name = "Davoi chest key", average_rate = "7.7%" } },
  ["Hawkeyed Dnatbat"] = { { name = "Archer's knife", average_rate = "94.3%" }, { name = "Assassin's bow", average_rate = "8.1%" } },
  ["Morbol"] = { { name = "Malboro vine", average_rate = "154.0%" }, { name = "Ice Brand", average_rate = "9.4%" } },
  ["Oil Spill"] = { { name = "Vial of slime oil", average_rate = "33.3%" } },
  ["One-Eyed Gwajboj"] = { { name = "Well weight", average_rate = "103.8%" } },
  ["Orcish Beastrider"] = { { name = "Scroll of Absorb-INT", average_rate = "3.2%" }, { name = "Scroll of Absorb-VIT", average_rate = "2.0%" }, { name = "Iron mask", average_rate = "0.50%" }, { name = "Scroll of Absorb-AGI", average_rate = "1.9%" }, { name = "Greaves", average_rate = "0.50%" }, { name = "Chain mittens", average_rate = "0.85%" }, { name = "Chain hose", average_rate = "0.85%" } },
  ["Orcish Bowshooter"] = { { name = "Davoi chest key", average_rate = "6.3%" }, { name = "Cuir bandana", average_rate = "1.4%" }, { name = "Cuir trousers", average_rate = "1.4%" }, { name = "Cuir gloves", average_rate = "1.1%" }, { name = "Cuir highboots", average_rate = "1.7%" } },
  ["Orcish Brawler"] = { { name = "Jade cryptex", average_rate = "5.2%" }, { name = "Soil hachimaki", average_rate = "0.15%" }, { name = "Soil tekko", average_rate = "1.1%" }, { name = "Soil sitabaki", average_rate = "0.30%" }, { name = "Soil kyahan", average_rate = "0.22%" } },
  ["Orcish Champion"] = { { name = "Monk's testimony", average_rate = "14.7%" }, { name = "Davoi coffer key", average_rate = "3.8%" }, { name = "Iron mittens", average_rate = "0.33%" }, { name = "Padded cap", average_rate = "0.28%" }, { name = "Leggings", average_rate = "0.33%" }, { name = "Iron subligar", average_rate = "0.33%" } },
  ["Orcish Cursemaker"] = { { name = "Bulb of shaman garlic", average_rate = "14.4%" }, { name = "Sandals", average_rate = "1.2%" }, { name = "Black slacks", average_rate = "1.1%" }, { name = "White mitts", average_rate = "1.1%" } },
  ["Orcish Dragoon"] = { { name = "Dragoon's testimony", average_rate = "14.8%" }, { name = "Davoi coffer key", average_rate = "2.1%" } },
  ["Orcish Dreadnought"] = { { name = "Warrior's testimony", average_rate = "14.1%" }, { name = "Davoi coffer key", average_rate = "5.6%" }, { name = "Mythril cuisses", average_rate = "0.51%" }, { name = "Mythril gauntlets", average_rate = "0.32%" }, { name = "Mythril sallet", average_rate = "0.41%" }, { name = "Mythril leggings", average_rate = "0.28%" } },
  ["Orcish Farkiller"] = { { name = "Scroll of Archer's Prelude", average_rate = "2.9%" }, { name = "Davoi coffer key", average_rate = "6.9%" }, { name = "Ranger's testimony", average_rate = "14.1%" }, { name = "Fire cluster", average_rate = "0.01%" } },
  ["Orcish Fighter"] = { { name = "Lizard ledelsens", average_rate = "1.9%" }, { name = "Lizard helm", average_rate = "1.8%" }, { name = "Lizard trousers", average_rate = "1.8%" }, { name = "Lizard gloves", average_rate = "1.8%" } },
  ["Orcish Firebelcher"] = { { name = "Long boomerang", average_rate = "19.7%" }, { name = "Serpentine gun", average_rate = "6.8%" }, { name = "Davoi chest key", average_rate = "6.2%" } },
  ["Orcish Footsoldier"] = { { name = "Silver hose", average_rate = "0.33%" }, { name = "Soiled letter", average_rate = "12.1%" }, { name = "Davoi chest key", average_rate = "4.2%" }, { name = "Silver greaves", average_rate = "0.39%" }, { name = "Silver mittens", average_rate = "0.46%" }, { name = "Silver mask", average_rate = "0.20%" } },
  ["Orcish Gladiator"] = { { name = "Davoi chest key", average_rate = "2.7%" }, { name = "Padded cap", average_rate = "0.64%" }, { name = "Leggings", average_rate = "0.45%" }, { name = "Iron subligar", average_rate = "0.32%" }, { name = "Iron mittens", average_rate = "0.26%" } },
  ["Orcish Impaler"] = { { name = "Jade cryptex", average_rate = "5.6%" }, { name = "Greaves", average_rate = "1.7%" }, { name = "Chain hose", average_rate = "0.69%" }, { name = "Iron mask", average_rate = "1.4%" }, { name = "Chain mittens", average_rate = "1.5%" } },
  ["Orcish Nightraider"] = { { name = "Studded trousers", average_rate = "1.6%" }, { name = "Jade cryptex", average_rate = "6.7%" }, { name = "Studded gloves", average_rate = "1.5%" }, { name = "Studded boots", average_rate = "1.0%" }, { name = "Studded bandana", average_rate = "0.79%" } },
  ["Orcish Predator"] = { { name = "Cuir bandana", average_rate = "0.51%" }, { name = "Cuir trousers", average_rate = "0.84%" }, { name = "Cuir highboots", average_rate = "0.51%" }, { name = "Cuir gloves", average_rate = "0.34%" } },
  ["Orcish Serjeant"] = { { name = "Lizard ledelsens", average_rate = "1.8%" }, { name = "Copy of the castle floor plans", average_rate = "11.6%" }, { name = "Lizard helm", average_rate = "1.9%" }, { name = "Lizard trousers", average_rate = "2.3%" }, { name = "Lizard gloves", average_rate = "1.8%" } },
  ["Orcish Trooper"] = { { name = "Gold Orcmask", average_rate = "15.9%" }, { name = "Davoi chest key", average_rate = "2.2%" }, { name = "Scroll of Flash", average_rate = "6.8%" }, { name = "Gauntlets", average_rate = "0.46%" }, { name = "Cuisses", average_rate = "0.23%" }, { name = "Plate leggings", average_rate = "0.12%" }, { name = "Sallet", average_rate = "0.17%" } },
  ["Orcish Warchief"] = { { name = "Scroll of Flash", average_rate = "8.0%" }, { name = "Mythril leggings", average_rate = "0.39%" }, { name = "Mythril cuisses", average_rate = "0.49%" }, { name = "Mythril gauntlets", average_rate = "0.44%" }, { name = "Mythril sallet", average_rate = "0.27%" }, { name = "Fire cluster", average_rate = "0.02%" } },
  ["Orcish Zerker"] = { { name = "Mythril leggings", average_rate = "0.62%" }, { name = "Scroll of Absorb-AGI", average_rate = "9.5%" }, { name = "Scroll of Absorb-VIT", average_rate = "8.3%" }, { name = "Scroll of Absorb-INT", average_rate = "9.8%" }, { name = "Scroll of Stun", average_rate = "6.4%" }, { name = "Mythril sallet", average_rate = "0.31%" }, { name = "Mythril cuisses", average_rate = "0.16%" }, { name = "Mythril gauntlets", average_rate = "0.16%" } },
  ["Poisonhand Gnadgad"] = { { name = "Jujitsu sitabaki", average_rate = "92.1%" }, { name = "Jujitsu gi", average_rate = "10.7%" } },
  ["Purpleflash Brukdok"] = { { name = "Davoi storage key", average_rate = "101.7%" } },
  ["Steelbiter Gudrud"] = { { name = "Lizard Piercer", average_rate = "93.4%" }, { name = "Sentinel's mantle", average_rate = "7.9%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "154.2%" } },
  ["Tigerbane Bakdak"] = { { name = "Warrior's axe", average_rate = "90.4%" }, { name = "Scroll of Absorb-INT", average_rate = "7.7%" }, { name = "Tigerhunter", average_rate = "3.8%" }, { name = "Scroll of Absorb-VIT", average_rate = "1.9%" } },
  ["War Lizard"] = { { name = "Lizard tail", average_rate = "74.4%" }, { name = "Lizard egg", average_rate = "51.9%" }, { name = "Lizard skin", average_rate = "28.9%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "133.3%" } },
  ["Wolf Bat"] = { { name = "Bat wing", average_rate = "29.7%" }, { name = "Vial of fiend blood", average_rate = "1.8%" } },
  ["Wood Bats"] = { { name = "Bat wing", average_rate = "26.2%" } },
}
