-- Zone: Castle Zvahl Keep [S]
return {
  ["Adjudicator Demon"] = { { name = "Demon horn", average_rate = "5.6%" }, { name = "Demon skull", average_rate = "6.7%" }, { name = "Ice Spirit pact", average_rate = "3.3%" }, { name = "Square of cambric", average_rate = "5.0%" } },
  ["Baetyl Quadav"] = { { name = "Bottled pixie", average_rate = "12.1%" }, { name = "Scroll of Bind", average_rate = "3.5%" }, { name = "Scroll of Blind", average_rate = "4.1%" } },
  ["Berserker Demon"] = { { name = "Demon horn", average_rate = "8.0%" }, { name = "Demon skull", average_rate = "3.8%" }, { name = "Square of cambric", average_rate = "8.0%" } },
  ["Dark Elemental"] = { { name = "Dark cluster", average_rate = "133.3%" } },
  ["Demon Befouler"] = { { name = "Demon horn", average_rate = "16.1%" }, { name = "Square of cambric", average_rate = "2.7%" } },
  ["Demon Condemner"] = { { name = "Demon horn", average_rate = "15.9%" }, { name = "Square of cambric", average_rate = "1.3%" } },
  ["Demon Corrupter"] = { { name = "Demon horn", average_rate = "12.4%" }, { name = "Square of cambric", average_rate = "1.3%" } },
  ["Demon Entomber"] = { { name = "Demon horn", average_rate = "13.8%" }, { name = "Square of cambric", average_rate = "2.0%" } },
  ["Demon Justiciar"] = { { name = "Demon horn", average_rate = "16.0%" }, { name = "Square of cambric", average_rate = "2.5%" } },
  ["Demon Magus"] = { { name = "Square of cambric", average_rate = "2.6%" }, { name = "Demon horn", average_rate = "16.4%" } },
  ["Demon Suppressor"] = { { name = "Demon horn", average_rate = "16.0%" }, { name = "Square of cambric", average_rate = "2.3%" } },
  ["Demon Warrior"] = { { name = "Demon horn", average_rate = "9.6%" }, { name = "Square of cambric", average_rate = "0.86%" } },
  ["Desmodus"] = { { name = "Bat wing", average_rate = "32.9%" } },
  ["Doom Lens"] = { { name = "Bottle of Ahriman tears", average_rate = "29.5%" }, { name = "Ahriman lens", average_rate = "13.8%" }, { name = "Ahriman wing", average_rate = "6.8%" } },
  ["Doyen Quadav"] = { { name = "Heavy Quadav chestplate", average_rate = "15.3%" }, { name = "Heavy Quadav backplate", average_rate = "8.1%" } },
  ["Eclipse Demon"] = { { name = "Demon horn", average_rate = "6.5%" }, { name = "Square of cambric", average_rate = "5.2%" }, { name = "Scroll of Absorb-DEX", average_rate = "0.86%" }, { name = "Demon skull", average_rate = "2.6%" } },
  ["Errand Imp"] = { { name = "Imp wing", average_rate = "25.5%" }, { name = "Imp horn", average_rate = "8.4%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "6.3%" } },
  ["Gnarled Gargouille"] = { { name = "Gargouille eye", average_rate = "14.9%" }, { name = "Gargouille shank", average_rate = "26.8%" }, { name = "Iridium ingot", average_rate = "7.1%" }, { name = "Gargouille horn", average_rate = "1.8%" } },
  ["Ice Elemental"] = { { name = "Ice cluster", average_rate = "100.0%" } },
  ["Inferno Demon"] = { { name = "Demon horn", average_rate = "7.6%" }, { name = "Square of cambric", average_rate = "5.8%" }, { name = "Demon skull", average_rate = "5.8%" }, { name = "Scroll of Fire III", average_rate = "1.8%" }, { name = "Scroll of Firaga III", average_rate = "0.58%" } },
  ["Keep Imp"] = { { name = "Imp horn", average_rate = "2.4%" } },
  ["Ogler"] = { { name = "Ahriman lens", average_rate = "13.5%" }, { name = "Bottle of Ahriman tears", average_rate = "25.9%" }, { name = "Ahriman wing", average_rate = "6.6%" } },
  ["Orcish Cupholder"] = { { name = "Orc pauldron", average_rate = "2.2%" } },
  ["Orcish Dreadnought"] = { { name = "Orc pauldron", average_rate = "2.1%" }, { name = "Orc helmet", average_rate = "14.7%" } },
  ["Orcish Farkiller"] = { { name = "Orc pauldron", average_rate = "1.8%" } },
  ["Orcish Imperial Guard"] = { { name = "Orc helmet", average_rate = "15.5%" }, { name = "Orc pauldron", average_rate = "1.0%" } },
  ["Orcish Strategist"] = { { name = "Bottled pixie", average_rate = "12.0%" }, { name = "Orc pauldron", average_rate = "1.7%" } },
  ["Orcish Wyrmbrander"] = { { name = "Bottled pixie", average_rate = "13.3%" } },
  ["Steel Quadav"] = { { name = "Heavy Quadav chestplate", average_rate = "14.8%" }, { name = "Heavy Quadav backplate", average_rate = "5.2%" } },
  ["Titanotaur"] = { { name = "Taurus wing", average_rate = "7.2%" }, { name = "Taurus horn", average_rate = "14.7%" } },
  ["Yagudo Abbot"] = { { name = "Yagudo feather", average_rate = "54.3%" } },
  ["Yagudo Conductor"] = { { name = "Scroll of Warding Round", average_rate = "16.7%" }, { name = "Scroll of Goddess's Hymnus", average_rate = "6.6%" } },
  ["Yagudo Flagellant"] = { { name = "Yagudo feather", average_rate = "30.8%" }, { name = "Yagudo kote", average_rate = "15.4%" } },
  ["Yagudo Hierogrammat"] = { { name = "Scroll of Aero IV", average_rate = "0.58%" }, { name = "Scroll of Aero III", average_rate = "2.0%" }, { name = "Scroll of Aeroga III", average_rate = "1.7%" }, { name = "Scroll of Tornado", average_rate = "0.29%" }, { name = "Scroll of Aeroga II", average_rate = "2.0%" } },
  ["Yagudo Nokizaru"] = { { name = "Yagudo osode", average_rate = "1.1%" }, { name = "Yagudo kote", average_rate = "13.0%" } },
  ["Yagudo Yojimbo"] = { { name = "Yagudo kote", average_rate = "13.5%" }, { name = "Yagudo osode", average_rate = "0.96%" } },
}
