-- Zone: Middle Delkfutt's Tower
return {
  ["Banshee"] = { { name = "Square of cotton cloth", average_rate = "27.8%" }, { name = "Revival tree root", average_rate = "18.5%" }, { name = "Scroll of Escape", average_rate = "3.7%" }, { name = "Luminicloth", average_rate = "3.7%" } },
  ["Big Bat"] = { { name = "Bat wing", average_rate = "29.3%" }, { name = "Bat fang", average_rate = "21.7%" }, { name = "Vial of fiend blood", average_rate = "1.9%" } },
  ["Eurytos"] = { { name = "Gigas socks", average_rate = "100.0%" }, { name = "Maple shield", average_rate = "41.2%" }, { name = "Gigas necklace", average_rate = "17.6%" }, { name = "Gigas bracelets", average_rate = "29.4%" } },
  ["Evil Spirit"] = { { name = "Square of cotton cloth", average_rate = "36.4%" }, { name = "Delkfutt chest key", average_rate = "6.8%" }, { name = "Revival tree root", average_rate = "8.5%" }, { name = "Luminicloth", average_rate = "3.4%" } },
  ["Giant Gatekeeper"] = { { name = "Ram leather missive", average_rate = "1.3%" } },
  ["Giant Guard"] = { { name = "Ram leather missive", average_rate = "2.0%" } },
  ["Giant Lobber"] = { { name = "Northern fur", average_rate = "7.7%" } },
  ["Giant Sentry"] = { { name = "Ram leather missive", average_rate = "1.5%" } },
  ["Goblin Furrier"] = { { name = "Studded bandana", average_rate = "0.96%" }, { name = "Square of sheep leather", average_rate = "9.4%" }, { name = "Studded gloves", average_rate = "1.4%" }, { name = "Square of black tiger leather", average_rate = "1.4%" }, { name = "Square of dhalmel leather", average_rate = "3.1%" }, { name = "Square of coeurl leather", average_rate = "0.80%" }, { name = "Studded trousers", average_rate = "0.53%" }, { name = "Studded boots", average_rate = "1.0%" }, { name = "Fire cluster", average_rate = "0.05%" } },
  ["Goblin Pathfinder"] = { { name = "Brass mask", average_rate = "1.3%" }, { name = "Brass greaves", average_rate = "1.3%" }, { name = "Brass cuisses", average_rate = "0.79%" }, { name = "Brass finger gauntlets", average_rate = "0.64%" }, { name = "Fire cluster", average_rate = "0.05%" } },
  ["Goblin Shaman"] = { { name = "Wool cuffs", average_rate = "0.15%" }, { name = "Chestnut sabots", average_rate = "0.10%" }, { name = "Wool slops", average_rate = "0.15%" }, { name = "Wool hat", average_rate = "0.35%" } },
  ["Goblin Smithy"] = { { name = "Chain mittens", average_rate = "0.88%" }, { name = "Greaves", average_rate = "1.3%" }, { name = "Iron mask", average_rate = "1.1%" }, { name = "Chain hose", average_rate = "0.99%" } },
  ["Jagd Doll"] = { { name = "Vial of mercury", average_rate = "18.5%" }, { name = "Doll shard", average_rate = "6.0%" } },
  ["Light Elemental"] = { { name = "Light cluster", average_rate = "167.9%" }, { name = "Delkfutt chest key", average_rate = "7.1%" } },
  ["Magic Jar"] = { { name = "Magic pot shard", average_rate = "33.2%" }, { name = "Vial of mercury", average_rate = "20.9%" } },
  ["Magic Pot"] = { { name = "Vial of mercury", average_rate = "14.6%" }, { name = "Magic pot shard", average_rate = "27.8%" } },
  ["Mold Bats"] = { { name = "Bat wing", average_rate = "28.5%" } },
  ["Ogygos"] = { { name = "Gigas socks", average_rate = "107.5%" }, { name = "Mahogany shield", average_rate = "52.2%" }, { name = "Gigas necklace", average_rate = "43.3%" }, { name = "Ogygos's bracelets", average_rate = "49.3%" } },
  ["Ophion"] = { { name = "Gigas socks", average_rate = "100.0%" }, { name = "Gigas necklace", average_rate = "28.0%" }, { name = "Maple shield", average_rate = "44.0%" }, { name = "Gigas bracelets", average_rate = "28.0%" } },
  ["Panzer Doll"] = { { name = "Doll shard", average_rate = "10.9%" }, { name = "Vial of mercury", average_rate = "15.8%" } },
  ["Polybotes"] = { { name = "Gigas socks", average_rate = "100.0%" }, { name = "Gigas necklace", average_rate = "30.6%" }, { name = "Gigas bracelets", average_rate = "25.0%" }, { name = "Maple shield", average_rate = "19.4%" } },
  ["Rhoikos"] = { { name = "Gigas socks", average_rate = "100.0%" }, { name = "Maple shield", average_rate = "33.3%" }, { name = "Maple shield", average_rate = "4.8%" }, { name = "Gigas necklace", average_rate = "28.6%" }, { name = "Gigas necklace", average_rate = "4.8%" }, { name = "Gigas bracelets", average_rate = "28.6%" }, { name = "Gigas bracelets", average_rate = "4.8%" } },
  ["Rhoitos"] = { { name = "Gigas socks", average_rate = "108.7%" }, { name = "Maple shield", average_rate = "34.8%" }, { name = "Gigas necklace", average_rate = "43.5%" }, { name = "Gigas bracelets", average_rate = "43.5%" } },
  ["Stirge"] = { { name = "Bat wing", average_rate = "25.8%" }, { name = "Vial of fiend blood", average_rate = "1.8%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "161.5%" }, { name = "Delkfutt chest key", average_rate = "8.9%" } },
  ["Tower Bats"] = { { name = "Bat wing", average_rate = "24.1%" } },
}
