-- Zone: Upper Delkfutt's Tower
return {
  ["Alkyoneus"] = { { name = "Gigas socks", average_rate = "102.6%" }, { name = "Mahogany shield", average_rate = "38.9%" }, { name = "Alkyoneus's bracelets", average_rate = "8.4%" }, { name = "Gigas necklace", average_rate = "16.9%" } },
  ["Autarch"] = { { name = "Kinship axe", average_rate = "36.9%" } },
  ["Demonic Doll"] = { { name = "Vial of mercury", average_rate = "16.6%" }, { name = "Doll shard", average_rate = "7.8%" }, { name = "Ice cluster", average_rate = "0.01%" } },
  ["Dire Bat"] = { { name = "Bat wing", average_rate = "32.9%" }, { name = "Bat fang", average_rate = "16.4%" }, { name = "Vial of fiend blood", average_rate = "7.5%" }, { name = "Vial of beastman blood", average_rate = "2.0%" } },
  ["Enkelados"] = { { name = "Gigas socks", average_rate = "102.3%" }, { name = "Mahogany shield", average_rate = "45.3%" }, { name = "Gigas necklace", average_rate = "34.6%" }, { name = "Enkelados's bracelets", average_rate = "34.6%" } },
  ["Gigas Bonecutter"] = { { name = "Delkfutt chest key", average_rate = "3.7%" }, { name = "Ice cluster", average_rate = "0.03%" } },
  ["Gigas Spirekeeper"] = { { name = "Delkfutt chest key", average_rate = "3.9%" }, { name = "Ice cluster", average_rate = "0.01%" } },
  ["Gigas Stonemason"] = { { name = "Delkfutt chest key", average_rate = "3.8%" } },
  ["Gigas Torturer"] = { { name = "Delkfutt chest key", average_rate = "3.9%" }, { name = "Ice cluster", average_rate = "0.02%" } },
  ["Gigas's Bats"] = { { name = "Delkfutt chest key", average_rate = "0.10%" } },
  ["Incubus Bats"] = { { name = "Bat wing", average_rate = "33.8%" }, { name = "Vial of fiend blood", average_rate = "7.9%" }, { name = "Bat fang", average_rate = "16.8%" }, { name = "Vial of beastman blood", average_rate = "2.2%" } },
  ["Jotunn Gatekeeper"] = { { name = "Gigas socks", average_rate = "16.6%" }, { name = "Hoary battle horn", average_rate = "3.4%" }, { name = "Warrior's testimony", average_rate = "5.7%" }, { name = "Gigas necklace", average_rate = "2.3%" }, { name = "Moldy buckler", average_rate = "1.3%" }, { name = "Ice cluster", average_rate = "0.01%" } },
  ["Jotunn Hallkeeper"] = { { name = "Gigas socks", average_rate = "17.1%" }, { name = "Monk's testimony", average_rate = "5.6%" }, { name = "Hoary battle horn", average_rate = "3.5%" }, { name = "Moldy buckler", average_rate = "1.3%" }, { name = "Gigas necklace", average_rate = "2.1%" }, { name = "Ice cluster", average_rate = "0.01%" } },
  ["Jotunn Wallkeeper"] = { { name = "Gigas socks", average_rate = "35.1%" }, { name = "Scroll of Archer's Prelude", average_rate = "2.3%" }, { name = "Ranger's testimony", average_rate = "10.6%" }, { name = "Hoary battle horn", average_rate = "3.4%" }, { name = "Moldy buckler", average_rate = "1.2%" } },
  ["Jotunn Wildkeeper"] = { { name = "Gigas socks", average_rate = "35.2%" }, { name = "Beastmaster's testimony", average_rate = "10.0%" }, { name = "Hoary battle horn", average_rate = "3.3%" }, { name = "Moldy buckler", average_rate = "1.4%" }, { name = "Gigas necklace", average_rate = "2.2%" } },
  ["Light Elemental"] = { { name = "Light cluster", average_rate = "155.6%" }, { name = "Delkfutt chest key", average_rate = "11.1%" } },
  ["Magic Pot"] = { { name = "Magic pot shard", average_rate = "33.4%" }, { name = "Vial of mercury", average_rate = "16.5%" }, { name = "Red mage's testimony", average_rate = "11.1%" }, { name = "Scroll of Thundaga III", average_rate = "1.8%" }, { name = "Scroll of Shell IV", average_rate = "1.6%" }, { name = "Scroll of Burst", average_rate = "0.65%" }, { name = "Scroll of Thunder III", average_rate = "2.6%" }, { name = "Scroll of Thunder IV", average_rate = "1.2%" } },
  ["Magic Urn"] = { { name = "Vial of mercury", average_rate = "17.0%" }, { name = "Magic pot shard", average_rate = "33.4%" }, { name = "Delkfutt chest key", average_rate = "5.0%" } },
  ["Mimas"] = { { name = "Huge moth axe", average_rate = "7.4%" } },
  ["Pallas"] = { { name = "Gigas socks", average_rate = "102.4%" }, { name = "Mahogany shield", average_rate = "41.6%" }, { name = "Gigas necklace", average_rate = "17.4%" }, { name = "Pallas's bracelets", average_rate = "7.8%" } },
  ["Phasma"] = { { name = "Revival tree root", average_rate = "40.8%" }, { name = "Square of wool cloth", average_rate = "17.9%" } },
  ["Porphyrion"] = { { name = "Delkfutt key", average_rate = "429.1%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "154.8%" }, { name = "Delkfutt chest key", average_rate = "8.2%" } },
}
