-- Zone: Promyvion - Holla
return {
  ["Cerebrator"] = { { name = "Remnant of a cerebrator", average_rate = "101.1%" }, { name = "Teal memosphere", average_rate = "112.6%" } },
  ["Idle Wanderer"] = { { name = "Remnant of a fleeting memory", average_rate = "3.6%" }, { name = "Remnant of a malevolent memory", average_rate = "3.0%" }, { name = "Remnant of a burning memory", average_rate = "4.8%" }, { name = "Remnant of a somber memory", average_rate = "4.1%" }, { name = "Remnant of a radiant memory", average_rate = "3.5%" }, { name = "Remnant of a profane memory", average_rate = "3.3%" }, { name = "Remnant of a bitter memory", average_rate = "3.3%" }, { name = "Remnant of a startling memory", average_rate = "3.6%" } },
  ["Livid Seether"] = { { name = "Remnant of a burning memory", average_rate = "6.2%" }, { name = "Remnant of a radiant memory", average_rate = "2.8%" }, { name = "Remnant of a somber memory", average_rate = "4.6%" }, { name = "Remnant of a bitter memory", average_rate = "5.2%" }, { name = "Remnant of a fleeting memory", average_rate = "6.2%" }, { name = "Remnant of a malevolent memory", average_rate = "1.2%" }, { name = "Remnant of a startling memory", average_rate = "4.3%" }, { name = "Remnant of a profane memory", average_rate = "2.8%" } },
  ["Seether"] = { { name = "Remnant of a startling memory", average_rate = "5.7%" }, { name = "Recollection of guilt", average_rate = "21.3%" }, { name = "Remnant of a radiant memory", average_rate = "17.8%" }, { name = "Remnant of a profane memory", average_rate = "5.6%" }, { name = "Remnant of a somber memory", average_rate = "4.4%" }, { name = "Remnant of a malevolent memory", average_rate = "14.9%" }, { name = "Remnant of a burning memory", average_rate = "6.2%" }, { name = "Remnant of a bitter memory", average_rate = "5.4%" }, { name = "Remnant of a fleeting memory", average_rate = "5.7%" } },
  ["Thinker"] = { { name = "Teal memosphere", average_rate = "7.4%" }, { name = "Recollection of fear", average_rate = "16.6%" }, { name = "Remnant of a radiant memory", average_rate = "1.9%" }, { name = "Recollection of pain", average_rate = "16.6%" }, { name = "Remnant of a malevolent memory", average_rate = "2.1%" }, { name = "Remnant of a startling memory", average_rate = "2.0%" }, { name = "Remnant of a fleeting memory", average_rate = "1.3%" }, { name = "Remnant of a profane memory", average_rate = "2.1%" }, { name = "Remnant of a somber memory", average_rate = "2.2%" }, { name = "Remnant of a bitter memory", average_rate = "1.8%" }, { name = "Remnant of a burning memory", average_rate = "1.9%" } },
  ["Wanderer"] = { { name = "Remnant of a bitter memory", average_rate = "5.3%" }, { name = "Remnant of a malevolent memory", average_rate = "16.2%" }, { name = "Recollection of fear", average_rate = "21.8%" }, { name = "Remnant of a burning memory", average_rate = "5.8%" }, { name = "Remnant of a radiant memory", average_rate = "16.8%" }, { name = "Remnant of a somber memory", average_rate = "5.7%" }, { name = "Remnant of a profane memory", average_rate = "5.7%" }, { name = "Remnant of a fleeting memory", average_rate = "5.7%" }, { name = "Remnant of a startling memory", average_rate = "5.5%" } },
  ["Weeper"] = { { name = "Remnant of a malevolent memory", average_rate = "16.4%" }, { name = "Remnant of a profane memory", average_rate = "5.8%" }, { name = "Recollection of pain", average_rate = "21.1%" }, { name = "Remnant of a burning memory", average_rate = "5.6%" }, { name = "Remnant of a radiant memory", average_rate = "16.1%" }, { name = "Remnant of a bitter memory", average_rate = "5.9%" }, { name = "Remnant of a somber memory", average_rate = "5.4%" }, { name = "Remnant of a startling memory", average_rate = "4.8%" }, { name = "Remnant of a fleeting memory", average_rate = "6.2%" } },
  ["Woeful Weeper"] = { { name = "Remnant of a radiant memory", average_rate = "3.0%" }, { name = "Remnant of a somber memory", average_rate = "6.4%" }, { name = "Remnant of a bitter memory", average_rate = "3.0%" }, { name = "Remnant of a fleeting memory", average_rate = "5.4%" }, { name = "Remnant of a profane memory", average_rate = "2.7%" }, { name = "Remnant of a burning memory", average_rate = "6.8%" }, { name = "Remnant of a startling memory", average_rate = "4.1%" }, { name = "Remnant of a malevolent memory", average_rate = "3.4%" } },
}
