-- Zone: Castle Zvahl Baileys
return {
  ["Abyssal Demon"] = { { name = "Orc Piercer", average_rate = "43.8%" }, { name = "Demon horn", average_rate = "20.4%" }, { name = "Ice Spirit pact", average_rate = "8.4%" }, { name = "Zvahl coffer key", average_rate = "6.2%" } },
  ["Ahriman"] = { { name = "Bottle of Ahriman tears", average_rate = "43.6%" }, { name = "Ahriman lens", average_rate = "20.6%" }, { name = "Zvahl coffer key", average_rate = "9.5%" }, { name = "Ahriman wing", average_rate = "9.5%" } },
  ["Arch Demon"] = { { name = "Shellbuster", average_rate = "42.7%" }, { name = "Zvahl coffer key", average_rate = "6.3%" }, { name = "Demon horn", average_rate = "19.4%" }, { name = "Dark cluster", average_rate = "0.05%" } },
  ["Blood Demon"] = { { name = "Yagudo freezer", average_rate = "20.7%" }, { name = "Samurai's testimony", average_rate = "16.0%" }, { name = "Zvahl coffer key", average_rate = "5.8%" }, { name = "Demon pen", average_rate = "17.1%" } },
  ["Dark Elemental"] = { { name = "Dark cluster", average_rate = "153.8%" } },
  ["Demon Chancellor"] = { { name = "Handful of the sands of silence", average_rate = "8.8%" }, { name = "Whine Cellar key", average_rate = "17.5%" } },
  ["Demon Commander"] = { { name = "Whine Cellar key", average_rate = "18.2%" } },
  ["Demon General"] = { { name = "Whine Cellar key", average_rate = "16.3%" }, { name = "Demon pen", average_rate = "13.5%" }, { name = "Scroll of Absorb-INT", average_rate = "7.2%" }, { name = "Scroll of Absorb-VIT", average_rate = "4.7%" }, { name = "Scroll of Absorb-AGI", average_rate = "3.4%" } },
  ["Demon Knight"] = { { name = "Scroll of Absorb-INT", average_rate = "7.7%" }, { name = "Zvahl chest key", average_rate = "8.7%" }, { name = "Behemoth leather missive", average_rate = "8.2%" }, { name = "Scroll of Absorb-VIT", average_rate = "4.6%" }, { name = "Scroll of Absorb-AGI", average_rate = "3.0%" } },
  ["Demon Magistrate"] = { { name = "Whine Cellar key", average_rate = "19.2%" }, { name = "Handful of the sands of silence", average_rate = "7.9%" }, { name = "Ice Spirit pact", average_rate = "2.5%" } },
  ["Demon Pawn"] = { { name = "Behemoth leather missive", average_rate = "6.6%" }, { name = "Zvahl chest key", average_rate = "5.0%" } },
  ["Demon Warlock"] = { { name = "Zvahl chest key", average_rate = "7.4%" }, { name = "Ice Spirit pact", average_rate = "2.9%" } },
  ["Demon Wizard"] = { { name = "Zvahl chest key", average_rate = "8.8%" }, { name = "Behemoth leather missive", average_rate = "4.8%" } },
  ["Demon's Elemental"] = { { name = "Zvahl chest key", average_rate = "3.4%" }, { name = "Zvahl coffer key", average_rate = "2.6%" } },
  ["Doom Demon"] = { { name = "Demon horn", average_rate = "8.7%" }, { name = "Zvahl coffer key", average_rate = "5.9%" } },
  ["Dread Demon"] = { { name = "Scroll of Firaga II", average_rate = "27.1%" }, { name = "Scroll of Firaga III", average_rate = "5.1%" }, { name = "Scroll of Fire IV", average_rate = "3.6%" }, { name = "Demon horn", average_rate = "10.1%" }, { name = "Scroll of Fire III", average_rate = "7.8%" }, { name = "Scroll of Flare", average_rate = "1.6%" } },
  ["Duke Haborym"] = { { name = "Demon horn", average_rate = "60.1%" }, { name = "Demon skull", average_rate = "44.9%" }, { name = "Scroll of Absorb-DEX", average_rate = "57.6%" }, { name = "Barbarian's scythe", average_rate = "57.6%" }, { name = "Dark cluster", average_rate = "0.15%" } },
  ["Elder Quadav"] = { { name = "Plate leggings", average_rate = "0.61%" }, { name = "Gauntlets", average_rate = "0.61%" } },
  ["Emerald Quadav"] = { { name = "Leggings", average_rate = "1.3%" }, { name = "Bottle of warding oil", average_rate = "7.2%" } },
  ["Evil Eye"] = { { name = "Bottle of Ahriman tears", average_rate = "16.9%" }, { name = "Ahriman lens", average_rate = "8.8%" }, { name = "Dark cluster", average_rate = "0.04%" } },
  ["Goblin Poacher"] = { { name = "Cuir gloves", average_rate = "0.96%" }, { name = "Cuir bandana", average_rate = "1.9%" }, { name = "Cuir trousers", average_rate = "0.96%" } },
  ["Goblin Reaper"] = { { name = "Scroll of Absorb-INT", average_rate = "11.2%" }, { name = "Scroll of Stun", average_rate = "6.5%" }, { name = "Scroll of Absorb-AGI", average_rate = "4.7%" }, { name = "Scroll of Absorb-VIT", average_rate = "5.6%" } },
  ["Goblin Robber"] = { { name = "Cuir trousers", average_rate = "2.4%" }, { name = "Cuir bandana", average_rate = "1.6%" }, { name = "Cuir gloves", average_rate = "1.6%" }, { name = "Cuir highboots", average_rate = "0.80%" } },
  ["Goblin Trader"] = { { name = "Cuir gloves", average_rate = "1.7%" }, { name = "Cuir trousers", average_rate = "2.5%" }, { name = "Cuir bandana", average_rate = "0.83%" }, { name = "Cuir highboots", average_rate = "1.7%" } },
  ["Gore Demon"] = { { name = "Samurai's testimony", average_rate = "33.4%" }, { name = "Yagudo freezer", average_rate = "20.2%" } },
  ["Grand Duke Batym"] = { { name = "Demon horn", average_rate = "60.8%" }, { name = "Demonslicer", average_rate = "57.2%" }, { name = "Demon skull", average_rate = "41.9%" } },
  ["Ice Elemental"] = { { name = "Ice cluster", average_rate = "152.8%" } },
  ["Iron Quadav"] = { { name = "Plate leggings", average_rate = "0.67%" }, { name = "Gauntlets", average_rate = "0.67%" }, { name = "Scroll of Flash", average_rate = "6.7%" }, { name = "Cuisses", average_rate = "0.67%" } },
  ["Judicator Demon"] = { { name = "Shellbuster", average_rate = "42.9%" }, { name = "Demon horn", average_rate = "19.4%" } },
  ["Likho"] = { { name = "Likho talon", average_rate = "37.8%" } },
  ["Marquis Allocen"] = { { name = "Demon horn", average_rate = "60.6%" }, { name = "Demon skull", average_rate = "48.2%" }, { name = "Corsair's knife", average_rate = "59.9%" } },
  ["Marquis Amon"] = { { name = "Demon horn", average_rate = "61.6%" }, { name = "Lion crossbow", average_rate = "59.9%" }, { name = "Scroll of Firaga III", average_rate = "14.2%" }, { name = "Demon skull", average_rate = "50.1%" }, { name = "Scroll of Fire IV", average_rate = "10.9%" }, { name = "Scroll of Fire III", average_rate = "21.1%" }, { name = "Scroll of Flare", average_rate = "3.8%" } },
  ["Marquis Naberius"] = { { name = "Yellow brass chain", average_rate = "53.9%" } },
  ["Marquis Sabnock"] = { { name = "Astrolabe", average_rate = "41.3%" } },
  ["Mimic"] = { { name = "Zvahl coffer key", average_rate = "90.5%" } },
  ["Morbid Eye"] = { { name = "Bottle of Ahriman tears", average_rate = "44.1%" }, { name = "Ahriman lens", average_rate = "20.3%" }, { name = "Zvahl chest key", average_rate = "10.5%" }, { name = "Ahriman wing", average_rate = "10.7%" } },
  ["Orcish Bowshooter"] = { { name = "Cuir trousers", average_rate = "0.62%" }, { name = "Cuir highboots", average_rate = "2.5%" }, { name = "Cuir gloves", average_rate = "0.62%" } },
  ["Orcish Footsoldier"] = { { name = "Soiled letter", average_rate = "15.3%" }, { name = "Silver mask", average_rate = "0.67%" } },
  ["Orcish Gladiator"] = { { name = "Padded cap", average_rate = "0.67%" } },
  ["Orcish Trooper"] = { { name = "Gold Orcmask", average_rate = "21.3%" }, { name = "Scroll of Flash", average_rate = "9.1%" }, { name = "Gauntlets", average_rate = "0.51%" }, { name = "Plate leggings", average_rate = "0.51%" } },
  ["Spinel Quadav"] = { { name = "Velvet hat", average_rate = "1.3%" }, { name = "Velvet cuffs", average_rate = "1.3%" } },
  ["Stygian Demon"] = { { name = "Orc Piercer", average_rate = "45.5%" }, { name = "Demon horn", average_rate = "20.0%" }, { name = "Ice Spirit pact", average_rate = "7.0%" } },
  ["Yagudo Conquistador"] = { { name = "Scroll of Huton: Ni", average_rate = "4.5%" }, { name = "Juji shuriken", average_rate = "9.1%" }, { name = "Scroll of Raiton: Ni", average_rate = "3.4%" }, { name = "Scroll of Doton: Ni", average_rate = "1.8%" }, { name = "Scroll of Katon: Ni", average_rate = "2.8%" }, { name = "Scroll of Suiton: Ni", average_rate = "2.1%" }, { name = "Scroll of Hyoton: Ni", average_rate = "1.5%" } },
  ["Yagudo Lutenist"] = { { name = "Scroll of Blade Madrigal", average_rate = "7.6%" }, { name = "Scroll of Dragonfoe Mambo", average_rate = "4.1%" } },
  ["Yagudo Prior"] = { { name = "Moccasins", average_rate = "0.79%" }, { name = "Black mitts", average_rate = "0.40%" } },
  ["Yagudo Zealot"] = { { name = "Cuir gloves", average_rate = "2.2%" }, { name = "Cuir highboots", average_rate = "2.0%" }, { name = "Cuir bandana", average_rate = "2.4%" }, { name = "Cuir trousers", average_rate = "1.6%" } },
}
