-- Zone: Castle Zvahl Keep
return {
  ["Baron Vapula"] = { { name = "Demon horn", average_rate = "48.6%" }, { name = "Scroll of Thundaga II", average_rate = "51.4%" }, { name = "Demon skull", average_rate = "30.6%" }, { name = "Scroll of Aeroga III", average_rate = "43.2%" } },
  ["Baronet Romwe"] = { { name = "Demon horn", average_rate = "61.4%" }, { name = "Demon skull", average_rate = "36.4%" }, { name = "Demon's axe", average_rate = "63.6%" } },
  ["Count Bifrons"] = { { name = "Demon horn", average_rate = "58.3%" }, { name = "Demon skull", average_rate = "38.9%" }, { name = "Scroll of Absorb-DEX", average_rate = "41.7%" }, { name = "Goshisho's scythe", average_rate = "33.3%" } },
  ["Deadly Iris"] = { { name = "Ahriman wing", average_rate = "8.1%" }, { name = "Bottle of Ahriman tears", average_rate = "37.9%" }, { name = "Ahriman lens", average_rate = "19.9%" }, { name = "Zvahl chest key", average_rate = "4.0%" } },
  ["Demon Knight"] = { { name = "Scroll of Absorb-AGI", average_rate = "4.1%" }, { name = "Scroll of Absorb-VIT", average_rate = "3.6%" }, { name = "Behemoth leather missive", average_rate = "5.3%" }, { name = "Zvahl chest key", average_rate = "5.9%" }, { name = "Scroll of Absorb-INT", average_rate = "7.1%" } },
  ["Demon Pawn"] = { { name = "Behemoth leather missive", average_rate = "1.4%" }, { name = "Zvahl chest key", average_rate = "1.6%" } },
  ["Demon Warlock"] = { { name = "Zvahl chest key", average_rate = "7.8%" }, { name = "Ice Spirit pact", average_rate = "2.5%" } },
  ["Demon Wizard"] = { { name = "Behemoth leather missive", average_rate = "2.1%" }, { name = "Zvahl chest key", average_rate = "1.9%" } },
  ["Emerald Quadav"] = { { name = "Bottle of warding oil", average_rate = "8.6%" } },
  ["Evil Eye"] = { { name = "Bottle of Ahriman tears", average_rate = "17.9%" }, { name = "Ahriman lens", average_rate = "7.1%" } },
  ["Goblin Bouncer"] = { { name = "Zvahl chest key", average_rate = "5.1%" }, { name = "Mythril gauntlets", average_rate = "0.74%" }, { name = "Mythril leggings", average_rate = "2.2%" } },
  ["Goblin Enchanter"] = { { name = "Silver ingot", average_rate = "1.6%" }, { name = "Zvahl chest key", average_rate = "9.5%" }, { name = "Brass ingot", average_rate = "5.6%" }, { name = "Black mitts", average_rate = "0.79%" } },
  ["Goblin Hunter"] = { { name = "Zvahl chest key", average_rate = "7.5%" }, { name = "Raptor ledelsens", average_rate = "1.2%" } },
  ["Goblin Poacher"] = { { name = "Cuir bandana", average_rate = "2.2%" }, { name = "Cuir gloves", average_rate = "3.6%" }, { name = "Cuir highboots", average_rate = "0.72%" }, { name = "Cuir trousers", average_rate = "0.72%" } },
  ["Goblin Reaper"] = { { name = "Scroll of Absorb-INT", average_rate = "3.6%" }, { name = "Scroll of Absorb-AGI", average_rate = "6.2%" }, { name = "Scroll of Absorb-VIT", average_rate = "2.7%" }, { name = "Scroll of Stun", average_rate = "2.7%" } },
  ["Goblin Robber"] = { { name = "Cuir gloves", average_rate = "1.4%" } },
  ["Goblin Trader"] = { { name = "Cuir trousers", average_rate = "1.6%" }, { name = "Square of velvet cloth", average_rate = "1.6%" }, { name = "Cuir highboots", average_rate = "1.6%" }, { name = "Cuir gloves", average_rate = "2.1%" }, { name = "Cuir bandana", average_rate = "0.52%" } },
  ["Gold Quadav"] = { { name = "Zvahl chest key", average_rate = "9.4%" } },
  ["Iron Quadav"] = { { name = "Scroll of Flash", average_rate = "11.5%" }, { name = "Cuisses", average_rate = "1.1%" } },
  ["Morbid Eye"] = { { name = "Bottle of Ahriman tears", average_rate = "42.9%" }, { name = "Ahriman wing", average_rate = "10.5%" }, { name = "Ahriman lens", average_rate = "21.2%" }, { name = "Zvahl chest key", average_rate = "9.8%" } },
  ["Mythril Quadav"] = { { name = "Mythril cuisses", average_rate = "1.8%" }, { name = "Mythril sallet", average_rate = "1.8%" }, { name = "Mythril breastplate", average_rate = "3.6%" }, { name = "Zvahl chest key", average_rate = "5.4%" } },
  ["Orcish Bowshooter"] = { { name = "Cuir trousers", average_rate = "3.2%" }, { name = "Cuir bandana", average_rate = "0.81%" }, { name = "Cuir highboots", average_rate = "1.6%" } },
  ["Orcish Footsoldier"] = { { name = "Soiled letter", average_rate = "21.4%" }, { name = "Silver greaves", average_rate = "1.2%" }, { name = "Silver mittens", average_rate = "1.2%" }, { name = "Silver hose", average_rate = "1.2%" } },
  ["Orcish Predator"] = { { name = "Cuir trousers", average_rate = "1.7%" }, { name = "Cuir gloves", average_rate = "1.7%" }, { name = "Cuir bandana", average_rate = "0.87%" }, { name = "Zvahl chest key", average_rate = "7.0%" }, { name = "Cuir highboots", average_rate = "2.6%" } },
  ["Orcish Trooper"] = { { name = "Gauntlets", average_rate = "0.64%" }, { name = "Gold Orcmask", average_rate = "26.1%" }, { name = "Scroll of Flash", average_rate = "8.3%" }, { name = "Plate leggings", average_rate = "0.64%" } },
  ["Orcish Veteran"] = { { name = "Zvahl chest key", average_rate = "10.8%" } },
  ["Orcish Warchief"] = { { name = "Mythril cuisses", average_rate = "2.4%" }, { name = "Scroll of Flash", average_rate = "5.9%" }, { name = "Zvahl chest key", average_rate = "7.1%" }, { name = "Mythril sallet", average_rate = "2.4%" } },
  ["Orcish Zerker"] = { { name = "Scroll of Absorb-INT", average_rate = "13.8%" }, { name = "Scroll of Absorb-AGI", average_rate = "6.4%" }, { name = "Zvahl chest key", average_rate = "4.3%" }, { name = "Scroll of Stun", average_rate = "4.3%" }, { name = "Scroll of Absorb-VIT", average_rate = "11.7%" }, { name = "Mythril cuisses", average_rate = "1.1%" } },
  ["Spinel Quadav"] = { { name = "Ebony sabots", average_rate = "1.1%" } },
  ["Steel Quadav"] = { { name = "Scroll of Flash", average_rate = "10.6%" }, { name = "Zvahl chest key", average_rate = "12.8%" }, { name = "Mythril leggings", average_rate = "2.1%" } },
  ["Topaz Quadav"] = { { name = "Scroll of Auspice", average_rate = "16.5%" }, { name = "Scroll of Reraise", average_rate = "21.2%" }, { name = "Vial of Quadav mage blood", average_rate = "10.6%" }, { name = "Zvahl chest key", average_rate = "12.9%" }, { name = "White slacks", average_rate = "1.2%" } },
  ["Viscount Morax"] = { { name = "Demon horn", average_rate = "46.5%" }, { name = "Demon skull", average_rate = "38.0%" }, { name = "Dark Spirit pact", average_rate = "38.0%" } },
  ["Yagudo Abbot"] = { { name = "Canteen of Yagudo holy water", average_rate = "28.6%" }, { name = "Zvahl chest key", average_rate = "8.8%" }, { name = "Scroll of Auspice", average_rate = "8.1%" }, { name = "White cloak", average_rate = "0.35%" }, { name = "Scroll of Reraise", average_rate = "1.1%" } },
  ["Yagudo Chanter"] = { { name = "Scroll of Gold Capriccio", average_rate = "13.5%" }, { name = "Zvahl chest key", average_rate = "16.0%" }, { name = "Scroll of Foe Requiem V", average_rate = "4.9%" }, { name = "Scroll of Carnage Elegy", average_rate = "2.8%" } },
  ["Yagudo Conquistador"] = { { name = "Scroll of Doton: Ni", average_rate = "3.5%" }, { name = "Scroll of Hyoton: Ni", average_rate = "3.2%" }, { name = "Scroll of Katon: Ni", average_rate = "3.5%" }, { name = "Scroll of Huton: Ni", average_rate = "2.2%" }, { name = "Juji shuriken", average_rate = "7.7%" }, { name = "Scroll of Suiton: Ni", average_rate = "2.2%" }, { name = "Scroll of Raiton: Ni", average_rate = "4.5%" } },
  ["Yagudo Inquisitor"] = { { name = "Zvahl chest key", average_rate = "7.0%" }, { name = "Raptor trousers", average_rate = "2.5%" }, { name = "Raptor ledelsens", average_rate = "0.50%" }, { name = "Raptor gloves", average_rate = "0.50%" }, { name = "Raptor helm", average_rate = "0.50%" } },
  ["Yagudo Lutenist"] = { { name = "Scroll of Blade Madrigal", average_rate = "4.1%" }, { name = "Scroll of Dragonfoe Mambo", average_rate = "2.0%" } },
  ["Yagudo Prior"] = { { name = "White slacks", average_rate = "0.75%" }, { name = "Moccasins", average_rate = "0.38%" }, { name = "Black mitts", average_rate = "0.38%" } },
  ["Yagudo Sentinel"] = { { name = "Cuir trousers", average_rate = "2.6%" }, { name = "Cuir bandana", average_rate = "2.1%" }, { name = "Cuir highboots", average_rate = "1.7%" }, { name = "Zvahl chest key", average_rate = "10.3%" }, { name = "Cuir gloves", average_rate = "0.85%" } },
  ["Yagudo Zealot"] = { { name = "Cuir trousers", average_rate = "2.4%" }, { name = "Cuir gloves", average_rate = "3.0%" }, { name = "Cuir highboots", average_rate = "1.7%" }, { name = "Cuir bandana", average_rate = "1.0%" } },
}
