-- Zone: Ranguemont Pass
return {
  ["Bat Eye"] = { { name = "Bottle of Ahriman tears", average_rate = "100.0%" }, { name = "Ahriman lens", average_rate = "25.9%" }, { name = "Storm axe", average_rate = "7.4%" } },
  ["Bilesucker"] = { { name = "Bat wing", average_rate = "43.5%" }, { name = "Vial of fiend blood", average_rate = "3.1%" }, { name = "Wind cluster", average_rate = "0.01%" } },
  ["Blade Bat"] = { { name = "Bat wing", average_rate = "24.8%" }, { name = "Vial of fiend blood", average_rate = "1.9%" } },
  ["Cave Scorpion"] = { { name = "Scorpion claw", average_rate = "102.8%" }, { name = "Frostreaper", average_rate = "8.5%" }, { name = "Scorpion shell", average_rate = "30.0%" } },
  ["Evil Weapon"] = { { name = "Pinch of glittersand", average_rate = "27.7%" } },
  ["Giant Scorpion"] = { { name = "Scorpion claw", average_rate = "101.3%" }, { name = "Scorpion shell", average_rate = "29.5%" }, { name = "Harvester", average_rate = "6.4%" } },
  ["Gloom Eye"] = { { name = "Wit pendant", average_rate = "33.3%" } },
  ["Goblin Artificer"] = { { name = "Iron mask", average_rate = "1.3%" }, { name = "Chain hose", average_rate = "1.5%" }, { name = "Chain mittens", average_rate = "1.3%" }, { name = "Greaves", average_rate = "0.79%" } },
  ["Goblin Chaser"] = { { name = "Brass greaves", average_rate = "1.6%" }, { name = "Brass finger gauntlets", average_rate = "1.5%" }, { name = "Brass cuisses", average_rate = "1.6%" }, { name = "Brass mask", average_rate = "1.4%" } },
  ["Goblin Gambler"] = { { name = "Bag of poison flour", average_rate = "5.6%" }, { name = "Linen cuffs", average_rate = "1.5%" }, { name = "Holly clogs", average_rate = "0.37%" }, { name = "Poet's circlet", average_rate = "0.74%" }, { name = "Linen slops", average_rate = "0.74%" } },
  ["Goblin Hoodoo"] = { { name = "Chestnut sabots", average_rate = "0.51%" }, { name = "Wool cuffs", average_rate = "0.64%" }, { name = "Wool slops", average_rate = "0.51%" }, { name = "Wool hat", average_rate = "0.26%" } },
  ["Goblin Leecher"] = { { name = "Scroll of Invisible", average_rate = "1.8%" }, { name = "Scroll of Sneak", average_rate = "8.1%" }, { name = "Scroll of Protectra", average_rate = "8.1%" }, { name = "Scroll of Paralyze", average_rate = "8.4%" }, { name = "Scroll of Barsleep", average_rate = "6.9%" }, { name = "Scroll of Silence", average_rate = "6.0%" }, { name = "Linen slops", average_rate = "0.60%" }, { name = "Poet's circlet", average_rate = "0.90%" }, { name = "Scroll of Barpoison", average_rate = "1.5%" }, { name = "Holly clogs", average_rate = "0.90%" }, { name = "Scroll of Deodorize", average_rate = "2.4%" }, { name = "Linen cuffs", average_rate = "0.30%" } },
  ["Goblin Mugger"] = { { name = "Brass mittens", average_rate = "2.3%" }, { name = "Brass subligar", average_rate = "2.8%" }, { name = "Brass leggings", average_rate = "0.85%" }, { name = "Brass cap", average_rate = "1.7%" } },
  ["Goblin Tanner"] = { { name = "Square of dhalmel leather", average_rate = "4.8%" }, { name = "Studded boots", average_rate = "0.93%" }, { name = "Square of sheep leather", average_rate = "12.6%" }, { name = "Studded trousers", average_rate = "2.0%" }, { name = "Studded bandana", average_rate = "1.9%" }, { name = "Square of coeurl leather", average_rate = "0.40%" }, { name = "Studded gloves", average_rate = "0.66%" }, { name = "Square of black tiger leather", average_rate = "1.5%" } },
  ["Goblin Thug"] = { { name = "Wild onion", average_rate = "29.4%" }, { name = "Bronze mittens", average_rate = "0.97%" }, { name = "Bronze leggings", average_rate = "1.5%" }, { name = "Bronze cap", average_rate = "2.4%" }, { name = "Bronze subligar", average_rate = "2.4%" } },
  ["Goblin Weaver"] = { { name = "Spool of cotton thread", average_rate = "2.3%" }, { name = "Ash clogs", average_rate = "1.9%" }, { name = "Square of grass cloth", average_rate = "4.6%" }, { name = "Cuffs", average_rate = "1.5%" }, { name = "Spool of grass thread", average_rate = "6.0%" }, { name = "Slops", average_rate = "2.1%" }, { name = "Circlet", average_rate = "1.5%" }, { name = "Square of cotton cloth", average_rate = "2.1%" } },
  ["Hecteyes"] = { { name = "Vial of mercury", average_rate = "27.6%" }, { name = "Hecteyes eye", average_rate = "25.0%" } },
  ["Hovering Oculus"] = { { name = "Fossilized bone", average_rate = "9.0%" }, { name = "Bottle of Ahriman tears", average_rate = "43.1%" }, { name = "Seasoning stone", average_rate = "9.5%" }, { name = "Ahriman lens", average_rate = "19.8%" }, { name = "Ahriman wing", average_rate = "9.4%" } },
  ["Hyakume"] = { { name = "Booster earring", average_rate = "24.1%" } },
  ["Mucoid Mass"] = { { name = "Spellcaster's ecu", average_rate = "41.8%" } },
  ["Ooze"] = { { name = "Vial of slime oil", average_rate = "15.1%" } },
  ["Seeker Bats"] = { { name = "Bat wing", average_rate = "31.5%" } },
  ["Stirge"] = { { name = "Bat wing", average_rate = "27.4%" }, { name = "Bat fang", average_rate = "27.5%" }, { name = "Vial of fiend blood", average_rate = "1.9%" } },
  ["Taisai"] = { { name = "Hecteyes eye", average_rate = "30.2%" }, { name = "Vial of mercury", average_rate = "31.5%" } },
  ["Taisaijin"] = { { name = "Scroll of Refresh", average_rate = "104.3%" }, { name = "Hecteyes eye", average_rate = "23.9%" }, { name = "Spelunker's hat", average_rate = "7.2%" }, { name = "Vial of mercury", average_rate = "33.3%" }, { name = "Scroll of Refresh II", average_rate = "1.4%" } },
  ["Wind Bats"] = { { name = "Bat wing", average_rate = "25.9%" } },
}
