-- Zone: Toraimarai Canal
return {
  ["Bigclaw"] = { { name = "Chunk of rock salt", average_rate = "87.4%" }, { name = "Slice of land crab meat", average_rate = "71.2%" }, { name = "Crab shell", average_rate = "33.3%" } },
  ["Blackwater Pugil"] = { { name = "Handful of pugil scales", average_rate = "16.5%" }, { name = "Fossilized bone", average_rate = "8.7%" } },
  ["Bloodsucker"] = { { name = "Carbuncle's ruby", average_rate = "10.0%" }, { name = "Vial of fiend blood", average_rate = "16.4%" } },
  ["Bouncing Ball"] = { { name = "Vial of fiend blood", average_rate = "16.9%" }, { name = "Vial of beastman blood", average_rate = "10.0%" }, { name = "Carbuncle's ruby", average_rate = "2.4%" }, { name = "Toraimarai coffer key", average_rate = "2.8%" } },
  ["Brazen Bones"] = { { name = "Laran's pendant", average_rate = "40.3%" } },
  ["Canal Bats"] = { { name = "Bat wing", average_rate = "23.5%" }, { name = "Bat fang", average_rate = "51.4%" } },
  ["Canal Moocher"] = { { name = "Aptant of pera", average_rate = "29.0%" }, { name = "Aptant of geoc", average_rate = "12.9%" } },
  ["Dark Aspic"] = { { name = "Vial of slime oil", average_rate = "127.6%" } },
  ["Deviling Bats"] = { { name = "Bat wing", average_rate = "35.3%" }, { name = "Seasoning stone", average_rate = "8.3%" }, { name = "Fossilized bone", average_rate = "8.9%" } },
  ["Dire Bat"] = { { name = "Bat wing", average_rate = "36.6%" }, { name = "Toraimarai coffer key", average_rate = "12.6%" }, { name = "Vial of fiend blood", average_rate = "8.1%" }, { name = "Bat fang", average_rate = "15.9%" }, { name = "Vial of beastman blood", average_rate = "2.3%" } },
  ["Doom Mage"] = { { name = "Bone chip", average_rate = "35.7%" }, { name = "Revival tree root", average_rate = "16.1%" }, { name = "Toraimarai coffer key", average_rate = "3.3%" }, { name = "Scroll of Blizzard III", average_rate = "7.1%" } },
  ["Doom Soldier"] = { { name = "Bone chip", average_rate = "34.5%" }, { name = "Toraimarai coffer key", average_rate = "2.7%" }, { name = "Revival tree root", average_rate = "16.3%" }, { name = "Dark knight's testimony", average_rate = "8.5%" } },
  ["Drowned Bones"] = { { name = "Bone chip", average_rate = "29.3%" }, { name = "Seasoning stone", average_rate = "14.1%" }, { name = "Earth cluster", average_rate = "0.12%" } },
  ["Fallen Knight"] = { { name = "Bone chip", average_rate = "29.4%" }, { name = "Scroll of Absorb-INT", average_rate = "6.4%" }, { name = "Scroll of Absorb-VIT", average_rate = "3.1%" }, { name = "Scroll of Absorb-AGI", average_rate = "2.6%" } },
  ["Fleshcraver"] = { { name = "Bone chip", average_rate = "32.0%" }, { name = "Revival tree root", average_rate = "20.8%" }, { name = "Toraimarai coffer key", average_rate = "9.3%" } },
  ["Flume Toad"] = { { name = "Fossilized bone", average_rate = "7.6%" }, { name = "Water cluster", average_rate = "0.11%" } },
  ["Girtab"] = { { name = "Scorpion claw", average_rate = "201.4%" }, { name = "Scorpion shell", average_rate = "100.9%" }, { name = "Toraimarai coffer key", average_rate = "4.1%" }, { name = "Viking axe", average_rate = "8.7%" } },
  ["Hell Bat"] = { { name = "Bat fang", average_rate = "51.9%" }, { name = "Bat wing", average_rate = "26.9%" }, { name = "Vial of fiend blood", average_rate = "1.0%" } },
  ["Impish Bats"] = { { name = "Vial of beastman blood", average_rate = "2.5%" }, { name = "Bat wing", average_rate = "34.9%" }, { name = "Bat fang", average_rate = "15.7%" }, { name = "Vial of fiend blood", average_rate = "8.1%" }, { name = "Toraimarai coffer key", average_rate = "3.0%" } },
  ["Konjac"] = { { name = "Aptant of aecus", average_rate = "40.0%" } },
  ["Lich"] = { { name = "Bone chip", average_rate = "26.4%" } },
  ["Makara"] = { { name = "Handful of pugil scales", average_rate = "12.5%" } },
  ["Mimic"] = { { name = "Toraimarai coffer key", average_rate = "100.0%" } },
  ["Mindcraver"] = { { name = "Toraimarai coffer key", average_rate = "9.8%" }, { name = "Bone chip", average_rate = "37.3%" }, { name = "Revival tree root", average_rate = "18.7%" }, { name = "Scroll of Blizzard III", average_rate = "9.1%" } },
  ["Mousse"] = { { name = "Vial of slime oil", average_rate = "75.4%" }, { name = "Toraimarai coffer key", average_rate = "6.3%" } },
  ["Oni Carcass"] = { { name = "Undead skin", average_rate = "200.7%" }, { name = "Onikiri", average_rate = "49.7%" } },
  ["Plunderer Crab"] = { { name = "Chunk of rock salt", average_rate = "28.4%" }, { name = "Slice of land crab meat", average_rate = "15.6%" }, { name = "Crab shell", average_rate = "2.1%" }, { name = "Fossilized bone", average_rate = "7.2%" }, { name = "Seasoning stone", average_rate = "5.8%" } },
  ["Poroggo Excavator"] = { { name = "Seasoning stone", average_rate = "19.8%" }, { name = "Fossilized bone", average_rate = "9.6%" } },
  ["Rapier Scorpion"] = { { name = "Scorpion claw", average_rate = "39.4%" }, { name = "Scorpion shell", average_rate = "9.1%" }, { name = "Seasoning stone", average_rate = "12.1%" }, { name = "High-quality scorpion shell", average_rate = "9.1%" }, { name = "Fossilized bone", average_rate = "3.0%" } },
  ["Rotten Sod"] = { { name = "Revival tree root", average_rate = "38.8%" }, { name = "Undead skin", average_rate = "14.6%" }, { name = "Toraimarai coffer key", average_rate = "4.9%" } },
  ["Scavenger Crab"] = { { name = "Toraimarai coffer key", average_rate = "8.5%" }, { name = "Slice of land crab meat", average_rate = "34.8%" }, { name = "Crab shell", average_rate = "16.8%" }, { name = "High-quality crab shell", average_rate = "2.3%" } },
  ["Sodden Bones"] = { { name = "Seasoning stone", average_rate = "14.4%" }, { name = "Bone chip", average_rate = "32.0%" }, { name = "Revival tree root", average_rate = "15.7%" } },
  ["Starborer"] = { { name = "Insect wing", average_rate = "29.5%" }, { name = "Beetle shell", average_rate = "20.0%" }, { name = "Seasoning stone", average_rate = "7.7%" }, { name = "Fossilized bone", average_rate = "6.2%" }, { name = "Beetle jaw", average_rate = "9.2%" } },
  ["Starmite"] = { { name = "Starmite shell", average_rate = "14.6%" }, { name = "Beetle jaw", average_rate = "7.5%" }, { name = "Insect wing", average_rate = "29.0%" }, { name = "Toraimarai coffer key", average_rate = "2.3%" } },
  ["Stygian Pugil"] = { { name = "Handful of pugil scales", average_rate = "17.2%" }, { name = "Toraimarai coffer key", average_rate = "8.1%" } },
}
