-- Zone: Korroloka Tunnel
return {
  ["Bogy"] = { { name = "Revival tree root", average_rate = "17.6%" }, { name = "Square of cotton cloth", average_rate = "32.3%" }, { name = "Ice cluster", average_rate = "0.05%" } },
  ["Cargo Crab Colin"] = { { name = "Slice of land crab meat", average_rate = "203.7%" }, { name = "Crab shell", average_rate = "103.7%" }, { name = "Nadrs", average_rate = "29.6%" } },
  ["Clipper"] = { { name = "Crab shell", average_rate = "16.3%" }, { name = "Slice of land crab meat", average_rate = "31.2%" } },
  ["Combat"] = { { name = "Bat wing", average_rate = "31.1%" }, { name = "Bat fang", average_rate = "15.6%" }, { name = "Vial of fiend blood", average_rate = "2.7%" } },
  ["Dame Blanche"] = { { name = "Square of sarcenet cloth", average_rate = "215.8%" } },
  ["Falcatus Aranei"] = { { name = "Spider web", average_rate = "145.5%" }, { name = "Webcutter", average_rate = "54.5%" } },
  ["Gigas Foreman"] = { { name = "Gigas socks", average_rate = "15.6%" }, { name = "Gigas necklace", average_rate = "2.2%" }, { name = "Marble slab", average_rate = "0.56%" }, { name = "Helmet mole", average_rate = "22.0%" }, { name = "Maple shield", average_rate = "6.0%" } },
  ["Gigas Stonecarrier"] = { { name = "Gigas socks", average_rate = "15.3%" }, { name = "Maple shield", average_rate = "7.8%" }, { name = "Helmet mole", average_rate = "22.7%" }, { name = "Gigas necklace", average_rate = "2.0%" }, { name = "Marble slab", average_rate = "1.2%" } },
  ["Gigas Stonegrinder"] = { { name = "Helmet mole", average_rate = "26.3%" }, { name = "Gigas socks", average_rate = "15.6%" }, { name = "Maple shield", average_rate = "6.5%" }, { name = "Gigas necklace", average_rate = "2.0%" }, { name = "Marble slab", average_rate = "1.4%" } },
  ["Gigas Stonemason"] = { { name = "Gigas socks", average_rate = "17.0%" }, { name = "Helmet mole", average_rate = "23.1%" }, { name = "Maple shield", average_rate = "7.1%" }, { name = "Gigas necklace", average_rate = "1.8%" }, { name = "Marble slab", average_rate = "1.6%" } },
  ["Goblin Bounty Hunter"] = { { name = "Goblin helm", average_rate = "4.4%" }, { name = "Goblin mail", average_rate = "1.3%" } },
  ["Greater Pugil"] = { { name = "Handful of pugil scales", average_rate = "15.7%" } },
  ["Huge Spider"] = { { name = "Spider web", average_rate = "1.7%" } },
  ["Jelly"] = { { name = "Vial of slime oil", average_rate = "82.7%" } },
  ["Lacerator"] = { { name = "Slice of land crab meat", average_rate = "35.1%" }, { name = "High-quality crab shell", average_rate = "2.0%" }, { name = "Crab shell", average_rate = "16.5%" }, { name = "Water cluster", average_rate = "0.04%" } },
  ["Land Worm"] = { { name = "Flint stone", average_rate = "35.3%" }, { name = "Chunk of iron ore", average_rate = "2.4%" }, { name = "Chunk of copper ore", average_rate = "17.5%" }, { name = "Chunk of zinc ore", average_rate = "7.9%" } },
  ["Morion Worm"] = { { name = "Chunk of copper ore", average_rate = "196.4%" }, { name = "Chunk of iron ore", average_rate = "27.4%" }, { name = "Chunk of tin ore", average_rate = "64.3%" }, { name = "Morion tathlum", average_rate = "19.0%" }, { name = "Chunk of darksteel ore", average_rate = "11.9%" } },
  ["Sea Monk"] = { { name = "Seashell", average_rate = "30.7%" }, { name = "Shall shell", average_rate = "3.2%" } },
  ["Seeker Bats"] = { { name = "Bat fang", average_rate = "14.0%" }, { name = "Bat wing", average_rate = "29.1%" }, { name = "Vial of fiend blood", average_rate = "1.6%" }, { name = "Wind cluster", average_rate = "0.04%" } },
  ["Snipper"] = { { name = "Chunk of rock salt", average_rate = "27.8%" } },
  ["Spool Leech"] = { { name = "Vial of fiend blood", average_rate = "16.8%" }, { name = "Water cluster", average_rate = "0.05%" } },
  ["Thoon"] = { { name = "Impetus earring", average_rate = "18.7%" } },
  ["Thread Leech"] = { { name = "Vial of fiend blood", average_rate = "15.1%" }, { name = "Carbuncle's ruby", average_rate = "1.3%" }, { name = "Water cluster", average_rate = "0.06%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "145.9%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "166.1%" } },
}
