-- Zone: The Eldieme Necropolis [S]
return {
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "134.3%" } },
  ["Eastern Spriggan"] = { { name = "Revival tree root", average_rate = "0.90%" } },
  ["Ethniu"] = { { name = "Wolfram steel ingot", average_rate = "222.8%" }, { name = "Chunk of cobalt ore", average_rate = "51.0%" }, { name = "Scintillant ingot", average_rate = "53.1%" }, { name = "Edgeless knife", average_rate = "51.7%" }, { name = "Bahram cuisses", average_rate = "24.1%" }, { name = "Orichalcum ingot", average_rate = "11.7%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "0.61%" } },
  ["Gazer"] = { { name = "Vial of mercury", average_rate = "32.0%" }, { name = "Hecteyes eye", average_rate = "31.4%" } },
  ["Goblin Blastmaster"] = { { name = "Goblin mask", average_rate = "7.6%" }, { name = "Goblin armor", average_rate = "3.4%" } },
  ["Goblin Corpsman"] = { { name = "Goblin mask", average_rate = "3.6%" }, { name = "Goblin armor", average_rate = "3.6%" } },
  ["Goblin Freesword"] = { { name = "Goblin mail", average_rate = "2.5%" }, { name = "Goblin helm", average_rate = "6.3%" } },
  ["Goblin Pioneer"] = { { name = "Goblin mess tin", average_rate = "9.9%" }, { name = "Goblin weel", average_rate = "7.2%" } },
  ["Hell Hound"] = { { name = "Revival tree root", average_rate = "6.3%" }, { name = "Wolf hide", average_rate = "12.3%" } },
  ["Ignis Djinn"] = { { name = "Djinn arm", average_rate = "24.5%" }, { name = "Pinch of djinn ash", average_rate = "36.6%" } },
  ["Laelaps"] = { { name = "Aptant of durus", average_rate = "5.9%" }, { name = "Aptant of haelan", average_rate = "11.8%" } },
  ["Lich"] = { { name = "Bone chip", average_rate = "20.0%" }, { name = "Revival tree root", average_rate = "12.7%" } },
  ["Lost Soul"] = { { name = "Bone chip", average_rate = "20.4%" } },
  ["Northern Spriggan"] = { { name = "Revival tree root", average_rate = "0.89%" } },
  ["Orcish Brawler"] = { { name = "Scholar's testimony", average_rate = "16.5%" }, { name = "Bottled pixie", average_rate = "10.7%" } },
  ["Orcish Chasseur"] = { { name = "Scholar's testimony", average_rate = "16.7%" } },
  ["Orcish Cursemaker"] = { { name = "Bottled pixie", average_rate = "4.3%" } },
  ["Orcish Trooper"] = { { name = "Orc helmet", average_rate = "7.3%" }, { name = "Scholar's testimony", average_rate = "17.1%" } },
  ["Revenant"] = { { name = "Square of cotton cloth", average_rate = "22.6%" }, { name = "Revival tree root", average_rate = "6.9%" }, { name = "Luminicloth", average_rate = "2.1%" } },
  ["Southern Spriggan"] = { { name = "Revival tree root", average_rate = "2.5%" } },
  ["Tethra"] = { { name = "Wolfram steel ingot", average_rate = "210.8%" }, { name = "Orichalcum ingot", average_rate = "10.8%" }, { name = "Chunk of cobalt ore", average_rate = "53.4%" }, { name = "Scintillant ingot", average_rate = "40.1%" }, { name = "Cracked staff", average_rate = "40.8%" }, { name = "Bloodbead gorget", average_rate = "19.1%" } },
  ["War Smilodon"] = { { name = "Smilodon hide", average_rate = "14.0%" }, { name = "Smilodon liver", average_rate = "6.2%" } },
  ["Western Spriggan"] = { { name = "Revival tree root", average_rate = "1.1%" } },
}
