-- Zone: The Shrine of Ru'Avitau
return {
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "179.2%" } },
  ["Aura Butler"] = { { name = "Doll shard", average_rate = "8.7%" }, { name = "Vial of mercury", average_rate = "18.5%" }, { name = "Ice cluster", average_rate = "0.01%" } },
  ["Aura Gear"] = { { name = "Doll shard", average_rate = "9.6%" }, { name = "Vial of mercury", average_rate = "19.6%" } },
  ["Aura Pot"] = { { name = "Red mage's testimony", average_rate = "10.5%" }, { name = "Flask of Ro'Maeve spring water", average_rate = "6.1%" }, { name = "Vial of mercury", average_rate = "8.3%" }, { name = "Scroll of Thunder III", average_rate = "1.4%" }, { name = "Magic pot shard", average_rate = "18.7%" }, { name = "Scroll of Thunder IV", average_rate = "0.58%" }, { name = "Scroll of Thundaga III", average_rate = "0.91%" }, { name = "Scroll of Shell IV", average_rate = "1.0%" }, { name = "Scroll of Burst", average_rate = "0.34%" }, { name = "Light cluster", average_rate = "0.01%" } },
  ["Aura Sculpture"] = { { name = "Fossilized fang", average_rate = "8.0%" }, { name = "Seasoning stone", average_rate = "15.7%" }, { name = "Chunk of mythril ore", average_rate = "33.1%" }, { name = "Golem shard", average_rate = "8.1%" }, { name = "Sacred Kindred's crest", average_rate = "3.8%" }, { name = "Light cluster", average_rate = "0.17%" } },
  ["Aura Statue"] = { { name = "Chunk of mythril ore", average_rate = "29.2%" }, { name = "Chunk of diorite", average_rate = "2.1%" }, { name = "Golem shard", average_rate = "12.3%" }, { name = "Square of raxa", average_rate = "4.7%" }, { name = "Light cluster", average_rate = "0.05%" } },
  ["Aura Weapon"] = { { name = "Wind cluster", average_rate = "0.05%" } },
  ["Baelfyr"] = { { name = "Sacred Kindred's crest", average_rate = "5.9%" } },
  ["Byrgen"] = { { name = "Sacred Kindred's crest", average_rate = "3.6%" } },
  ["Dark Elemental"] = { { name = "Dark cluster", average_rate = "160.1%" } },
  ["Decorative Weapon"] = { { name = "Wind cluster", average_rate = "0.01%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "162.0%" } },
  ["Faust"] = { { name = "Summerstone", average_rate = "146.0%" }, { name = "Tonbo-Giri", average_rate = "22.9%" }, { name = "Oblation abjuration", average_rate = "47.1%" } },
  ["Fire Elemental"] = { { name = "Fire cluster", average_rate = "159.1%" } },
  ["Gefyrst"] = { { name = "Sacred Kindred's crest", average_rate = "4.8%" } },
  ["Ice Elemental"] = { { name = "Ice cluster", average_rate = "176.3%" } },
  ["Kirin"] = { { name = "Kirin's pole", average_rate = "50.9%" }, { name = "Kirin's Osode", average_rate = "50.6%" }, { name = "Scroll of Raise III", average_rate = "16.6%" }, { name = "Wyrmal abjuration: legs", average_rate = "30.0%" }, { name = "Scroll of Quake", average_rate = "16.9%" }, { name = "Square of shining cloth", average_rate = "39.9%" }, { name = "Neptunal abjuration: body", average_rate = "32.2%" }, { name = "Dryadic abjuration: body", average_rate = "37.9%" }, { name = "Orichalcum ingot", average_rate = "31.4%" }, { name = "Damascus ingot", average_rate = "29.3%" }, { name = "Wind cluster", average_rate = "0.02%" } },
  ["Mother Globe"] = { { name = "Springstone", average_rate = "160.6%" }, { name = "Libation abjuration", average_rate = "49.2%" }, { name = "Shiranui", average_rate = "23.0%" } },
  ["Olla Grande"] = { { name = "Winterstone", average_rate = "156.0%" }, { name = "Libation abjuration", average_rate = "47.5%" }, { name = "Skofnung", average_rate = "22.2%" }, { name = "Freya's tear", average_rate = "10.3%" }, { name = "Light cluster", average_rate = "0.03%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "179.0%" } },
  ["Ullikummi"] = { { name = "Autumnstone", average_rate = "158.9%" }, { name = "Oblation abjuration", average_rate = "51.3%" }, { name = "Ulfhedinn axe", average_rate = "24.8%" }, { name = "Light cluster", average_rate = "0.04%" } },
  ["Ungeweder"] = { { name = "Sacred Kindred's crest", average_rate = "5.8%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "168.9%" } },
  --["Defender"] = {},
}
