-- Zone: Promyvion - Dem
return {
  ["Gorger"] = { { name = "Remnant of a startling memory", average_rate = "2.6%" }, { name = "Beryl memosphere", average_rate = "4.3%" }, { name = "Recollection of pain", average_rate = "19.9%" }, { name = "Recollection of guilt", average_rate = "20.0%" }, { name = "Remnant of a fleeting memory", average_rate = "2.5%" }, { name = "Remnant of a burning memory", average_rate = "2.9%" }, { name = "Remnant of a bitter memory", average_rate = "2.6%" }, { name = "Remnant of a profane memory", average_rate = "2.5%" }, { name = "Remnant of a somber memory", average_rate = "2.3%" }, { name = "Remnant of a radiant memory", average_rate = "2.6%" }, { name = "Remnant of a malevolent memory", average_rate = "2.7%" } },
  ["Idle Wanderer"] = { { name = "Remnant of a radiant memory", average_rate = "5.7%" }, { name = "Remnant of a startling memory", average_rate = "5.5%" }, { name = "Remnant of a burning memory", average_rate = "6.5%" }, { name = "Remnant of a profane memory", average_rate = "4.3%" }, { name = "Remnant of a somber memory", average_rate = "6.3%" }, { name = "Remnant of a malevolent memory", average_rate = "4.3%" }, { name = "Remnant of a bitter memory", average_rate = "3.8%" }, { name = "Remnant of a fleeting memory", average_rate = "5.1%" } },
  ["Livid Seether"] = { { name = "Remnant of a startling memory", average_rate = "4.4%" }, { name = "Remnant of a fleeting memory", average_rate = "5.5%" }, { name = "Remnant of a burning memory", average_rate = "6.7%" }, { name = "Remnant of a somber memory", average_rate = "7.1%" }, { name = "Remnant of a profane memory", average_rate = "3.9%" }, { name = "Remnant of a malevolent memory", average_rate = "4.2%" }, { name = "Remnant of a bitter memory", average_rate = "4.9%" }, { name = "Remnant of a radiant memory", average_rate = "4.2%" } },
  ["Satiator"] = { { name = "Remnant of a satiator", average_rate = "98.1%" }, { name = "Beryl memosphere", average_rate = "120.1%" } },
  ["Seether"] = { { name = "Recollection of fear", average_rate = "21.5%" }, { name = "Remnant of a startling memory", average_rate = "5.5%" }, { name = "Remnant of a fleeting memory", average_rate = "5.9%" }, { name = "Remnant of a malevolent memory", average_rate = "16.6%" }, { name = "Remnant of a profane memory", average_rate = "6.1%" }, { name = "Remnant of a bitter memory", average_rate = "6.2%" }, { name = "Remnant of a radiant memory", average_rate = "17.2%" }, { name = "Remnant of a burning memory", average_rate = "6.0%" }, { name = "Remnant of a somber memory", average_rate = "5.7%" } },
  ["Wanderer"] = { { name = "Remnant of a malevolent memory", average_rate = "17.3%" }, { name = "Recollection of pain", average_rate = "22.2%" }, { name = "Remnant of a radiant memory", average_rate = "17.3%" }, { name = "Remnant of a burning memory", average_rate = "6.0%" }, { name = "Remnant of a startling memory", average_rate = "6.2%" }, { name = "Remnant of a fleeting memory", average_rate = "6.1%" }, { name = "Remnant of a bitter memory", average_rate = "6.2%" }, { name = "Remnant of a profane memory", average_rate = "6.0%" }, { name = "Remnant of a somber memory", average_rate = "6.1%" } },
  ["Weeper"] = { { name = "Remnant of a somber memory", average_rate = "6.1%" }, { name = "Remnant of a fleeting memory", average_rate = "6.3%" }, { name = "Recollection of guilt", average_rate = "22.5%" }, { name = "Remnant of a bitter memory", average_rate = "6.4%" }, { name = "Remnant of a malevolent memory", average_rate = "17.5%" }, { name = "Remnant of a radiant memory", average_rate = "17.5%" }, { name = "Remnant of a startling memory", average_rate = "6.2%" }, { name = "Remnant of a burning memory", average_rate = "6.3%" }, { name = "Remnant of a profane memory", average_rate = "6.2%" } },
  ["Woeful Weeper"] = { { name = "Remnant of a bitter memory", average_rate = "6.2%" }, { name = "Remnant of a radiant memory", average_rate = "4.6%" }, { name = "Remnant of a startling memory", average_rate = "6.2%" }, { name = "Remnant of a malevolent memory", average_rate = "3.1%" }, { name = "Remnant of a fleeting memory", average_rate = "1.5%" }, { name = "Remnant of a somber memory", average_rate = "6.2%" }, { name = "Remnant of a burning memory", average_rate = "1.5%" }, { name = "Remnant of a profane memory", average_rate = "4.6%" } },
}
