-- Zone: Lower Delkfutt's Tower
return {
  ["Ancient Bat"] = { { name = "Bat wing", average_rate = "25.7%" }, { name = "Vial of fiend blood", average_rate = "1.6%" }, { name = "Wind cluster", average_rate = "0.01%" } },
  ["Bogy"] = { { name = "Bloody robe", average_rate = "18.3%" }, { name = "Revival tree root", average_rate = "6.6%" }, { name = "Luminicloth", average_rate = "1.2%" } },
  ["Chaos Idol"] = { { name = "Vial of mercury", average_rate = "17.0%" }, { name = "Doll shard", average_rate = "7.6%" } },
  ["Epialtes"] = { { name = "Gigas socks", average_rate = "104.7%" }, { name = "Gigas bracelets", average_rate = "30.9%" }, { name = "Gigas necklace", average_rate = "34.1%" }, { name = "Maple shield", average_rate = "38.9%" } },
  ["Eurymedon"] = { { name = "Gigas socks", average_rate = "150.0%" }, { name = "Maple shield", average_rate = "150.0%" }, { name = "Gigas necklace", average_rate = "100.0%" }, { name = "Gigas bracelets", average_rate = "100.0%" } },
  ["Giant Gatekeeper"] = { { name = "Ram leather missive", average_rate = "1.5%" }, { name = "Ice cluster", average_rate = "0.03%" } },
  ["Giant Guard"] = { { name = "Ram leather missive", average_rate = "1.7%" } },
  ["Giant Lobber"] = { { name = "Northern fur", average_rate = "6.9%" }, { name = "Ice cluster", average_rate = "0.01%" } },
  ["Giant Sentry"] = { { name = "Ram leather missive", average_rate = "1.4%" }, { name = "Ice cluster", average_rate = "0.02%" } },
  ["Gigas Butcher"] = { { name = "Delkfutt chest key", average_rate = "3.8%" } },
  ["Gigas Hallwatcher"] = { { name = "Delkfutt chest key", average_rate = "4.8%" } },
  ["Gigas Punisher"] = { { name = "Delkfutt chest key", average_rate = "5.0%" } },
  ["Gigas Sculptor"] = { { name = "Delkfutt chest key", average_rate = "4.5%" } },
  ["Goblin Gambler"] = { { name = "Linen slops", average_rate = "0.80%" }, { name = "Linen cuffs", average_rate = "1.1%" }, { name = "Holly clogs", average_rate = "0.65%" }, { name = "Bag of poison flour", average_rate = "6.8%" }, { name = "Poet's circlet", average_rate = "0.64%" } },
  ["Goblin Leecher"] = { { name = "Scroll of Barpoison", average_rate = "3.6%" }, { name = "Scroll of Sneak", average_rate = "5.2%" }, { name = "Scroll of Paralyze", average_rate = "7.6%" }, { name = "Scroll of Barsleep", average_rate = "5.7%" }, { name = "Scroll of Silence", average_rate = "5.5%" }, { name = "Holly clogs", average_rate = "0.88%" }, { name = "Scroll of Protectra", average_rate = "5.9%" }, { name = "Scroll of Invisible", average_rate = "1.3%" }, { name = "Scroll of Deodorize", average_rate = "2.7%" }, { name = "Poet's circlet", average_rate = "1.0%" }, { name = "Linen slops", average_rate = "0.79%" }, { name = "Linen cuffs", average_rate = "0.79%" }, { name = "Fire cluster", average_rate = "0.03%" } },
  ["Goblin Mugger"] = { { name = "Brass leggings", average_rate = "1.9%" }, { name = "Brass cap", average_rate = "1.7%" }, { name = "Brass mittens", average_rate = "1.6%" }, { name = "Brass subligar", average_rate = "1.7%" }, { name = "Fire cluster", average_rate = "0.01%" } },
  ["Hippolytos"] = { { name = "Gigas socks", average_rate = "104.2%" }, { name = "Gigas bracelets", average_rate = "19.4%" }, { name = "Maple shield", average_rate = "31.9%" }, { name = "Gigas necklace", average_rate = "29.2%" } },
  ["Light Elemental"] = { { name = "Light cluster", average_rate = "143.4%" }, { name = "Delkfutt chest key", average_rate = "8.8%" } },
  ["Magic Pot"] = { { name = "Vial of mercury", average_rate = "14.3%" }, { name = "Magic pot shard", average_rate = "13.4%" } },
  ["Magic Urn"] = { { name = "Delkfutt chest key", average_rate = "3.6%" }, { name = "Magic pot shard", average_rate = "25.5%" }, { name = "Vial of mercury", average_rate = "14.2%" } },
  ["Seeker Bats"] = { { name = "Bat wing", average_rate = "25.6%" }, { name = "Wind cluster", average_rate = "0.02%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "142.4%" }, { name = "Delkfutt chest key", average_rate = "7.6%" } },
  ["Tyrant"] = { { name = "Loop of aramid fiber", average_rate = "26.6%" } },
}
