-- Zone: Inner Horutoto Ruins
return {
  ["Balloon"] = { { name = "Pinch of bomb ash", average_rate = "33.9%" }, { name = "Bomb arm", average_rate = "11.8%" }, { name = "Asbestos mitts", average_rate = "0.79%" } },
  ["Battle Bat"] = { { name = "Horutoto chest key", average_rate = "9.2%" }, { name = "Vial of fiend blood", average_rate = "1.4%" }, { name = "Bat wing", average_rate = "34.5%" } },
  ["Battue Bats"] = { { name = "Bat wing", average_rate = "34.5%" } },
  ["Blade Bat"] = { { name = "Bat wing", average_rate = "35.7%" }, { name = "Vial of fiend blood", average_rate = "2.3%" } },
  ["Blob"] = { { name = "Horutoto chest key", average_rate = "3.0%" } },
  ["Boggart"] = { { name = "Scroll of Regen", average_rate = "9.1%" } },
  ["Covin Bat"] = { { name = "Bat wing", average_rate = "27.9%" }, { name = "Vial of fiend blood", average_rate = "1.5%" }, { name = "Wind cluster", average_rate = "0.17%" } },
  ["Deathwatch Beetle"] = { { name = "Insect wing", average_rate = "33.5%" }, { name = "Beetle shell", average_rate = "16.4%" }, { name = "Beetle jaw", average_rate = "8.7%" } },
  ["Goblin Flesher"] = { { name = "Scale cuisses", average_rate = "1.5%" }, { name = "Faceguard", average_rate = "1.5%" }, { name = "Scale finger gauntlets", average_rate = "0.93%" }, { name = "Scale greaves", average_rate = "1.2%" }, { name = "Lightning cluster", average_rate = "0.28%" } },
  ["Goblin Gambler"] = { { name = "Bag of poison flour", average_rate = "8.1%" }, { name = "Block of Yagudo caulk", average_rate = "8.5%" }, { name = "Holly clogs", average_rate = "1.3%" }, { name = "Linen slops", average_rate = "0.79%" }, { name = "Horutoto chest key", average_rate = "1.3%" }, { name = "Linen cuffs", average_rate = "1.1%" }, { name = "Poet's circlet", average_rate = "1.1%" } },
  ["Goblin Leecher"] = { { name = "Holly clogs", average_rate = "0.84%" }, { name = "Scroll of Deodorize", average_rate = "2.4%" }, { name = "Scroll of Barpoison", average_rate = "4.2%" }, { name = "Scroll of Protectra", average_rate = "7.1%" }, { name = "Scroll of Barsleep", average_rate = "6.2%" }, { name = "Scroll of Silence", average_rate = "6.5%" }, { name = "Scroll of Paralyze", average_rate = "8.7%" }, { name = "Linen cuffs", average_rate = "1.2%" }, { name = "Block of Yagudo caulk", average_rate = "5.9%" }, { name = "Horutoto chest key", average_rate = "1.8%" }, { name = "Scroll of Sneak", average_rate = "5.4%" }, { name = "Linen slops", average_rate = "0.93%" }, { name = "Poet's circlet", average_rate = "0.71%" }, { name = "Scroll of Invisible", average_rate = "1.1%" } },
  ["Goblin Lurcher"] = { { name = "Wild onion", average_rate = "35.1%" }, { name = "Bronze leggings", average_rate = "3.9%" }, { name = "Bronze mittens", average_rate = "3.5%" }, { name = "Bronze cap", average_rate = "2.2%" }, { name = "Bronze subligar", average_rate = "2.7%" } },
  ["Goblin Metallurgist"] = { { name = "Scale finger gauntlets", average_rate = "1.3%" }, { name = "Faceguard", average_rate = "0.43%" }, { name = "Scale greaves", average_rate = "0.71%" }, { name = "Scale cuisses", average_rate = "0.86%" } },
  ["Goblin Mugger"] = { { name = "Block of Yagudo caulk", average_rate = "8.3%" }, { name = "Horutoto chest key", average_rate = "2.9%" }, { name = "Brass mittens", average_rate = "1.3%" }, { name = "Brass leggings", average_rate = "1.8%" }, { name = "Brass subligar", average_rate = "2.1%" }, { name = "Brass cap", average_rate = "2.7%" } },
  ["Goblin Thug"] = { { name = "Bronze mittens", average_rate = "3.5%" }, { name = "Wild onion", average_rate = "43.2%" }, { name = "Bronze leggings", average_rate = "3.3%" }, { name = "Bronze subligar", average_rate = "3.5%" }, { name = "Bronze cap", average_rate = "3.5%" }, { name = "Fire cluster", average_rate = "0.00%" } },
  ["Goblin Trailblazer"] = { { name = "Leather gloves", average_rate = "2.7%" }, { name = "Block of animal glue", average_rate = "36.6%" }, { name = "Leather bandana", average_rate = "4.6%" }, { name = "Leather trousers", average_rate = "3.1%" }, { name = "Leather highboots", average_rate = "3.6%" } },
  ["Goblin Weaver"] = { { name = "Slops", average_rate = "2.8%" }, { name = "Ash clogs", average_rate = "4.6%" }, { name = "Spool of cotton thread", average_rate = "3.7%" }, { name = "Square of grass cloth", average_rate = "5.9%" }, { name = "Square of cotton cloth", average_rate = "1.5%" }, { name = "Cuffs", average_rate = "3.6%" }, { name = "Circlet", average_rate = "3.9%" }, { name = "Spool of grass thread", average_rate = "7.5%" }, { name = "Fire cluster", average_rate = "0.06%" } },
  ["Magicked Bones"] = { { name = "Bone chip", average_rate = "41.0%" }, { name = "Ceremonial dagger", average_rate = "3.6%" } },
  ["Maltha"] = { { name = "Trailer's tunica", average_rate = "51.4%" }, { name = "Vial of slime oil", average_rate = "38.4%" } },
  ["Nocuous Weapon"] = { { name = "Disciple grip", average_rate = "36.7%" } },
  ["Skinnymajinx"] = { { name = "Bone chip", average_rate = "26.3%" } },
  ["Skinnymalinks"] = { { name = "Bone chip", average_rate = "32.1%" }, { name = "Revival tree root", average_rate = "16.4%" } },
  ["Slendlix Spindlethumb"] = { { name = "Circe's hat", average_rate = "26.2%" } },
  ["Troika Bats"] = { { name = "Bat wing", average_rate = "32.4%" } },
  ["Wendigo"] = { { name = "Bone chip", average_rate = "34.3%" }, { name = "Pile of answer sheets", average_rate = "5.9%" }, { name = "Rusty dagger", average_rate = "9.5%" }, { name = "Scroll of Gravity", average_rate = "3.9%" } },
  ["Will-O'-The-Wisp"] = { { name = "Pinch of bomb ash", average_rate = "30.5%" }, { name = "Bomb arm", average_rate = "15.2%" } },
}
