-- Zone: Ordelle's Caves
return {
  ["Agar Agar"] = { { name = "Soarer earring", average_rate = "27.8%" } },
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "149.0%" }, { name = "Ordelle chest key", average_rate = "7.5%" } },
  ["Ancient Bat"] = { { name = "Bat wing", average_rate = "29.9%" }, { name = "Vial of fiend blood", average_rate = "1.6%" } },
  ["Aroma Leech"] = { { name = "Civet sachet", average_rate = "8.3%" }, { name = "Sweet sachet", average_rate = "8.3%" }, { name = "Olibanum sachet", average_rate = "8.3%" } },
  ["Bilis Leech"] = { { name = "Vial of fiend blood", average_rate = "13.2%" } },
  ["Blood Bunny"] = { { name = "Rabbit hide", average_rate = "21.4%" }, { name = "Slice of hare meat", average_rate = "46.7%" } },
  ["Bombast"] = { { name = "Ardent earring", average_rate = "28.4%" } },
  ["Buds Bunny"] = { { name = "Slice of hare meat", average_rate = "25.6%" }, { name = "Rabbit hide", average_rate = "14.1%" }, { name = "Earth cluster", average_rate = "0.04%" } },
  ["Clipper"] = { { name = "Chunk of rock salt", average_rate = "21.4%" }, { name = "Crab shell", average_rate = "7.9%" } },
  ["Donggu"] = { { name = "Fidelity earring", average_rate = "22.2%" } },
  ["Dung Beetle"] = { { name = "Insect wing", average_rate = "29.7%" }, { name = "Beetle shell", average_rate = "12.3%" }, { name = "Beetle jaw", average_rate = "7.0%" } },
  ["Fly Agaric"] = { { name = "Sleepshroom", average_rate = "22.0%" } },
  ["Gerwitz's Axe"] = { { name = "Gerwitz's axe", average_rate = "101.9%" } },
  ["Gerwitz's Sword"] = { { name = "Gerwitz's sword", average_rate = "101.9%" } },
  ["Goblin Ambusher"] = { { name = "Leather bandana", average_rate = "2.2%" }, { name = "Block of animal glue", average_rate = "25.6%" }, { name = "Leather highboots", average_rate = "1.3%" }, { name = "Leather gloves", average_rate = "1.1%" }, { name = "Leather trousers", average_rate = "0.86%" } },
  ["Goblin Butcher"] = { { name = "Scale finger gauntlets", average_rate = "0.23%" }, { name = "Scale greaves", average_rate = "1.4%" }, { name = "Scale cuisses", average_rate = "1.4%" }, { name = "Faceguard", average_rate = "0.92%" } },
  ["Goblin Furrier"] = { { name = "Square of sheep leather", average_rate = "3.4%" }, { name = "Studded gloves", average_rate = "1.6%" }, { name = "Ordelle chest key", average_rate = "7.7%" }, { name = "Square of black tiger leather", average_rate = "0.99%" }, { name = "Square of coeurl leather", average_rate = "0.40%" }, { name = "Square of dhalmel leather", average_rate = "2.8%" }, { name = "Sack of Galka fangs", average_rate = "5.1%" }, { name = "Studded bandana", average_rate = "1.8%" }, { name = "Studded trousers", average_rate = "2.4%" }, { name = "Studded boots", average_rate = "0.99%" } },
  ["Goblin Gambler"] = { { name = "Bag of poison flour", average_rate = "9.4%" }, { name = "Poet's circlet", average_rate = "1.2%" }, { name = "Linen slops", average_rate = "1.2%" } },
  ["Goblin Leecher"] = { { name = "Scroll of Barsleep", average_rate = "6.7%" }, { name = "Scroll of Silence", average_rate = "7.7%" }, { name = "Scroll of Paralyze", average_rate = "10.6%" }, { name = "Scroll of Invisible", average_rate = "0.96%" }, { name = "Scroll of Protectra", average_rate = "4.8%" }, { name = "Scroll of Barpoison", average_rate = "1.9%" }, { name = "Scroll of Sneak", average_rate = "4.8%" }, { name = "Linen slops", average_rate = "0.96%" }, { name = "Linen cuffs", average_rate = "0.96%" }, { name = "Scroll of Deodorize", average_rate = "0.96%" } },
  ["Goblin Mugger"] = { { name = "Brass subligar", average_rate = "2.3%" }, { name = "Brass mittens", average_rate = "2.8%" }, { name = "Brass cap", average_rate = "2.8%" }, { name = "Brass leggings", average_rate = "1.7%" } },
  ["Goblin Pathfinder"] = { { name = "Sack of Galka fangs", average_rate = "6.0%" }, { name = "Ordelle chest key", average_rate = "8.7%" }, { name = "Brass finger gauntlets", average_rate = "0.40%" }, { name = "Brass greaves", average_rate = "1.2%" }, { name = "Brass mask", average_rate = "0.60%" }, { name = "Brass cuisses", average_rate = "0.79%" } },
  ["Goblin Shaman"] = { { name = "Ordelle chest key", average_rate = "9.0%" }, { name = "Wool cuffs", average_rate = "0.19%" }, { name = "Wool hat", average_rate = "0.38%" }, { name = "Wool slops", average_rate = "0.19%" }, { name = "Chestnut sabots", average_rate = "0.19%" } },
  ["Goblin Smithy"] = { { name = "Iron mask", average_rate = "2.5%" }, { name = "Ordelle chest key", average_rate = "10.3%" }, { name = "Chain mittens", average_rate = "1.7%" }, { name = "Chain hose", average_rate = "0.58%" }, { name = "Greaves", average_rate = "0.97%" } },
  ["Goblin Tinkerer"] = { { name = "Scale finger gauntlets", average_rate = "1.8%" }, { name = "Faceguard", average_rate = "1.2%" }, { name = "Scale cuisses", average_rate = "0.82%" }, { name = "Scale greaves", average_rate = "0.82%" } },
  ["Goliath Beetle"] = { { name = "Insect wing", average_rate = "42.7%" }, { name = "Beetle shell", average_rate = "28.7%" }, { name = "Beetle jaw", average_rate = "14.2%" }, { name = "Ordelle chest key", average_rate = "4.9%" } },
  ["Hognosed Bat"] = { { name = "Vial of fiend blood", average_rate = "2.1%" }, { name = "Bat wing", average_rate = "26.2%" } },
  ["Jelly"] = { { name = "Vial of slime oil", average_rate = "16.5%" } },
  ["Morbolger"] = { { name = "Morbolger vine", average_rate = "102.3%" }, { name = "Malboro vine", average_rate = "123.7%" } },
  ["Napalm"] = { { name = "Pinch of bomb ash", average_rate = "33.0%" }, { name = "Bomb arm", average_rate = "15.0%" }, { name = "Flame degen", average_rate = "8.5%" }, { name = "Ordelle chest key", average_rate = "8.5%" } },
  ["Poison Leech"] = { { name = "Vial of fiend blood", average_rate = "13.1%" }, { name = "Carbuncle's ruby", average_rate = "2.1%" } },
  ["Seeker Bats"] = { { name = "Vial of magicked blood", average_rate = "15.4%" }, { name = "Bat wing", average_rate = "32.4%" } },
  ["Shrieker"] = { { name = "Sleepshroom", average_rate = "25.4%" }, { name = "Danceshroom", average_rate = "13.9%" } },
  ["Slash Pine"] = { { name = "Treant bulb", average_rate = "31.5%" }, { name = "Bag of herb seeds", average_rate = "6.5%" }, { name = "Bag of grain seeds", average_rate = "12.1%" }, { name = "Dolphin staff", average_rate = "1.6%" } },
  ["Snipper"] = { { name = "Chunk of rock salt", average_rate = "23.9%" }, { name = "Slice of land crab meat", average_rate = "6.9%" }, { name = "Crab shell", average_rate = "1.1%" } },
  ["Stalking Sapling"] = { { name = "Bag of herb seeds", average_rate = "7.3%" }, { name = "Treant bulb", average_rate = "28.0%" }, { name = "Bag of vegetable seeds", average_rate = "12.8%" }, { name = "Bag of grain seeds", average_rate = "1.6%" } },
  ["Stink Bats"] = { { name = "Bat wing", average_rate = "29.0%" }, { name = "Vial of magicked blood", average_rate = "14.9%" } },
  ["Stroper"] = { { name = "Malboro vine", average_rate = "158.3%" }, { name = "Shield pendant", average_rate = "9.6%" }, { name = "Ordelle chest key", average_rate = "8.8%" } },
  ["Stroper Chyme"] = { { name = "Vial of slime oil", average_rate = "31.8%" }, { name = "Ordelle chest key", average_rate = "7.7%" }, { name = "Shikaree ring", average_rate = "2.7%" } },
  ["Swagger Spruce"] = { { name = "Bag of vegetable seeds", average_rate = "13.3%" }, { name = "Treant bulb", average_rate = "23.5%" }, { name = "Bag of herb seeds", average_rate = "6.6%" }, { name = "Bag of grain seeds", average_rate = "1.4%" } },
  ["Targe Beetle"] = { { name = "Insect wing", average_rate = "24.5%" }, { name = "Beetle shell", average_rate = "14.7%" }, { name = "Beetle jaw", average_rate = "6.6%" }, { name = "Earth cluster", average_rate = "0.06%" } },
  ["Thread Leech"] = { { name = "Vial of fiend blood", average_rate = "13.4%" } },
  ["Vorpal Bunny"] = { { name = "Slice of hare meat", average_rate = "54.7%" }, { name = "Rabbit hide", average_rate = "24.2%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "158.6%" }, { name = "Ordelle chest key", average_rate = "4.8%" } },
  ["Will-O'-The-Wisp"] = { { name = "Pinch of bomb ash", average_rate = "24.6%" }, { name = "Bomb arm", average_rate = "13.0%" } },
}
