-- Zone: Outer Horutoto Ruins
return {
  ["Ah Puch"] = { { name = "Spiro staff", average_rate = "31.1%" } },
  ["Balloon"] = { { name = "Pinch of bomb ash", average_rate = "32.7%" }, { name = "Bomb arm", average_rate = "13.7%" }, { name = "Coarse boomerang", average_rate = "3.3%" } },
  ["Battue Bats"] = { { name = "Bat wing", average_rate = "36.1%" } },
  ["Blade Bat"] = { { name = "Bat wing", average_rate = "35.9%" }, { name = "Vial of fiend blood", average_rate = "2.2%" } },
  ["Bomb King"] = { { name = "Pinch of bomb ash", average_rate = "103.5%" }, { name = "Bomb arm", average_rate = "64.3%" }, { name = "Bomb ring", average_rate = "29.6%" } },
  ["Combat"] = { { name = "Bat wing", average_rate = "37.3%" }, { name = "Vial of fiend blood", average_rate = "2.4%" }, { name = "Horutoto chest key", average_rate = "2.7%" } },
  ["Dancing Weapon"] = { { name = "Wind cluster", average_rate = "0.03%" } },
  ["Desmodont"] = { { name = "Fidelity mantle", average_rate = "22.1%" } },
  ["Doppelganger Dio"] = { { name = "Revival tree root", average_rate = "100.0%" }, { name = "Cruel scythe", average_rate = "28.9%" } },
  ["Doppelganger Gog"] = { { name = "Revival tree root", average_rate = "104.8%" }, { name = "Cruel spear", average_rate = "42.9%" } },
  ["Eight Of Batons"] = { { name = "Eight of batons card", average_rate = "14.9%" } },
  ["Eight Of Coins"] = { { name = "Eight of coins card", average_rate = "11.9%" } },
  ["Eight Of Cups"] = { { name = "Eight of cups card", average_rate = "12.0%" } },
  ["Eight Of Swords"] = { { name = "Eight of swords card", average_rate = "11.6%" }, { name = "Fire cluster", average_rate = "0.09%" } },
  ["Fetor Bats"] = { { name = "Bat wing", average_rate = "39.6%" }, { name = "Wind cluster", average_rate = "0.00%" } },
  ["Five Of Batons"] = { { name = "Horutoto chest key", average_rate = "7.6%" }, { name = "Five of batons card", average_rate = "12.5%" }, { name = "Earth cluster", average_rate = "0.06%" } },
  ["Five Of Coins"] = { { name = "Five of coins card", average_rate = "11.9%" }, { name = "Horutoto chest key", average_rate = "7.3%" } },
  ["Five Of Cups"] = { { name = "Horutoto chest key", average_rate = "7.1%" }, { name = "Five of cups card", average_rate = "13.0%" }, { name = "Water cluster", average_rate = "0.06%" } },
  ["Five Of Swords"] = { { name = "Five of swords card", average_rate = "12.5%" }, { name = "Horutoto chest key", average_rate = "7.7%" } },
  ["Four Of Batons"] = { { name = "Four of batons card", average_rate = "12.8%" } },
  ["Four Of Coins"] = { { name = "Four of coins card", average_rate = "11.6%" } },
  ["Four Of Cups"] = { { name = "Four of cups card", average_rate = "12.8%" } },
  ["Four Of Swords"] = { { name = "Four of swords card", average_rate = "12.8%" } },
  ["Fuligo"] = { { name = "Vial of slime oil", average_rate = "18.4%" }, { name = "Water cluster", average_rate = "0.01%" } },
  ["Ghoul"] = { { name = "Bone chip", average_rate = "16.0%" }, { name = "Scroll of Gravity", average_rate = "4.5%" }, { name = "Magicked skull", average_rate = "4.5%" } },
  ["Goblin Ambusher"] = { { name = "Block of animal glue", average_rate = "37.0%" }, { name = "Leather gloves", average_rate = "2.4%" }, { name = "Leather highboots", average_rate = "2.5%" }, { name = "Leather trousers", average_rate = "2.4%" }, { name = "Leather bandana", average_rate = "2.5%" } },
  ["Goblin Butcher"] = { { name = "Scale finger gauntlets", average_rate = "1.2%" }, { name = "Faceguard", average_rate = "1.3%" }, { name = "Scale greaves", average_rate = "1.3%" }, { name = "Scale cuisses", average_rate = "1.3%" } },
  ["Goblin Thug"] = { { name = "Bronze leggings", average_rate = "2.6%" }, { name = "Wild onion", average_rate = "35.6%" }, { name = "Bronze cap", average_rate = "2.2%" }, { name = "Bronze subligar", average_rate = "3.0%" }, { name = "Bronze mittens", average_rate = "2.9%" } },
  ["Goblin Tinkerer"] = { { name = "Scale cuisses", average_rate = "1.4%" }, { name = "Faceguard", average_rate = "1.3%" }, { name = "Scale greaves", average_rate = "1.4%" }, { name = "Scale finger gauntlets", average_rate = "1.2%" } },
  ["Goblin Weaver"] = { { name = "Spool of cotton thread", average_rate = "3.6%" }, { name = "Spool of grass thread", average_rate = "7.4%" }, { name = "Square of grass cloth", average_rate = "4.8%" }, { name = "Ash clogs", average_rate = "2.4%" }, { name = "Square of cotton cloth", average_rate = "1.9%" }, { name = "Circlet", average_rate = "2.2%" }, { name = "Cuffs", average_rate = "2.7%" }, { name = "Slops", average_rate = "1.9%" } },
  ["Jack Of Batons"] = { { name = "Jack of batons card", average_rate = "12.8%" } },
  ["Jack Of Coins"] = { { name = "Jack of coins card", average_rate = "12.1%" } },
  ["Jack Of Cups"] = { { name = "Jack of cups card", average_rate = "18.2%" } },
  ["Jack Of Swords"] = { { name = "Jack of swords card", average_rate = "16.7%" } },
  ["Legalox Heftyhind"] = { { name = "Piece of hefty oak lumber", average_rate = "36.2%" } },
  ["Nine Of Batons"] = { { name = "Nine of batons card", average_rate = "13.0%" } },
  ["Nine Of Coins"] = { { name = "Nine of coins card", average_rate = "11.1%" } },
  ["Nine Of Cups"] = { { name = "Nine of cups card", average_rate = "13.3%" }, { name = "Water cluster", average_rate = "0.09%" } },
  ["Nine Of Swords"] = { { name = "Nine of swords card", average_rate = "11.2%" } },
  ["Queen Of Coins"] = { { name = "Queen of coins card", average_rate = "18.5%" } },
  ["Queen Of Swords"] = { { name = "Queen of swords card", average_rate = "17.2%" } },
  ["Rotten Jam"] = { { name = "Horutoto chest key", average_rate = "2.1%" } },
  ["Seven Of Batons"] = { { name = "Seven of batons card", average_rate = "11.9%" } },
  ["Seven Of Coins"] = { { name = "Seven of coins card", average_rate = "13.6%" }, { name = "Light cluster", average_rate = "0.08%" } },
  ["Seven Of Cups"] = { { name = "Seven of cups card", average_rate = "12.6%" } },
  ["Seven Of Swords"] = { { name = "Seven of swords card", average_rate = "12.8%" }, { name = "Fire cluster", average_rate = "0.16%" } },
  ["Six Of Batons"] = { { name = "Six of batons card", average_rate = "13.0%" }, { name = "Horutoto chest key", average_rate = "1.6%" } },
  ["Six Of Coins"] = { { name = "Six of coins card", average_rate = "13.1%" }, { name = "Horutoto chest key", average_rate = "1.7%" } },
  ["Six Of Cups"] = { { name = "Six of cups card", average_rate = "13.1%" }, { name = "Horutoto chest key", average_rate = "1.4%" } },
  ["Six Of Swords"] = { { name = "Six of swords card", average_rate = "12.2%" }, { name = "Horutoto chest key", average_rate = "2.0%" } },
  ["Stink Bats"] = { { name = "Bat wing", average_rate = "33.7%" }, { name = "Horutoto chest key", average_rate = "7.8%" } },
  ["Ten Of Batons"] = { { name = "Ten of batons card", average_rate = "14.8%" } },
  ["Ten Of Coins"] = { { name = "Ten of coins card", average_rate = "14.3%" } },
  ["Ten Of Cups"] = { { name = "Scroll of Regen II", average_rate = "9.0%" }, { name = "Ten of cups card", average_rate = "14.3%" } },
  ["Ten Of Swords"] = { { name = "Ten of swords card", average_rate = "13.8%" } },
  ["Thorn Bat"] = { { name = "Bat wing", average_rate = "39.0%" }, { name = "Vial of fiend blood", average_rate = "2.6%" }, { name = "Wind cluster", average_rate = "0.01%" } },
  ["Three Of Batons"] = { { name = "Three of batons card", average_rate = "11.9%" } },
  ["Three Of Coins"] = { { name = "Three of coins card", average_rate = "10.9%" } },
  ["Three Of Cups"] = { { name = "Three of cups card", average_rate = "12.8%" } },
  ["Three Of Swords"] = { { name = "Three of swords card", average_rate = "10.8%" } },
  ["Two Of Batons"] = { { name = "Two of batons card", average_rate = "10.0%" } },
  ["Two Of Coins"] = { { name = "Two of coins card", average_rate = "10.2%" } },
  ["Two Of Cups"] = { { name = "Two of cups card", average_rate = "10.0%" } },
  ["Two Of Swords"] = { { name = "Two of swords card", average_rate = "9.9%" } },
}
