-- Zone: The Eldieme Necropolis
return {
  ["Anemone"] = { { name = "Malboro vine", average_rate = "168.8%" }, { name = "Avenger's earring", average_rate = "3.9%" } },
  ["Azer"] = { { name = "Bomb arm", average_rate = "19.5%" }, { name = "Eldieme chest key", average_rate = "9.6%" }, { name = "Pinch of bomb ash", average_rate = "35.7%" } },
  ["Blood Soul"] = { { name = "Square of cotton cloth", average_rate = "31.8%" }, { name = "Eldieme chest key", average_rate = "6.9%" }, { name = "Luminicloth", average_rate = "1.9%" }, { name = "Revival tree root", average_rate = "7.1%" } },
  ["Cwn Cyrff"] = { { name = "Swan bilbo", average_rate = "62.3%" } },
  ["Dark Stalker"] = { { name = "Tavnazia bell", average_rate = "8.7%" }, { name = "Scroll of Absorb-INT", average_rate = "6.1%" }, { name = "Scroll of Absorb-AGI", average_rate = "4.4%" }, { name = "Scroll of Absorb-VIT", average_rate = "4.2%" }, { name = "Revival tree root", average_rate = "2.7%" }, { name = "Dark cluster", average_rate = "0.02%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "155.8%" }, { name = "Eldieme chest key", average_rate = "10.0%" } },
  ["Fallen Knight"] = { { name = "Scroll of Absorb-AGI", average_rate = "3.9%" }, { name = "Bone chip", average_rate = "35.1%" }, { name = "Eldieme chest key", average_rate = "8.7%" }, { name = "Scroll of Absorb-INT", average_rate = "5.6%" }, { name = "Scroll of Absorb-VIT", average_rate = "3.9%" }, { name = "Earth cluster", average_rate = "0.06%" } },
  ["Gazer"] = { { name = "Hecteyes eye", average_rate = "106.9%" }, { name = "Vial of mercury", average_rate = "101.1%" } },
  ["Haunt"] = { { name = "Square of cotton cloth", average_rate = "29.2%" }, { name = "Scroll of Blizzaga II", average_rate = "8.9%" }, { name = "Eldieme coffer key", average_rate = "7.4%" }, { name = "Scroll of Freeze", average_rate = "5.0%" }, { name = "Ice cluster", average_rate = "0.00%" } },
  ["Hell Hound"] = { { name = "Wolf hide", average_rate = "17.3%" }, { name = "Revival tree root", average_rate = "7.1%" } },
  ["Hellbound Warlock"] = { { name = "Bone chip", average_rate = "29.1%" } },
  ["Hellbound Warrior"] = { { name = "Bone chip", average_rate = "26.3%" }, { name = "Revival tree root", average_rate = "16.7%" }, { name = "Earth cluster", average_rate = "0.10%" } },
  ["Ice Elemental"] = { { name = "Ice cluster", average_rate = "166.7%" } },
  ["Ka"] = { { name = "Scroll of Absorb-VIT", average_rate = "3.9%" }, { name = "Scroll of Absorb-AGI", average_rate = "4.3%" }, { name = "Eldieme chest key", average_rate = "7.4%" }, { name = "Scroll of Absorb-INT", average_rate = "5.3%" }, { name = "Revival tree root", average_rate = "2.1%" } },
  ["Lich"] = { { name = "Piece of ancient papyrus", average_rate = "44.6%" }, { name = "Eldieme chest key", average_rate = "8.7%" }, { name = "Bone chip", average_rate = "36.9%" } },
  ["Lich C Magnus"] = { { name = "Bone chip", average_rate = "102.4%" }, { name = "Lilith's rod", average_rate = "30.2%" } },
  ["Lost Soul"] = { { name = "Bone chip", average_rate = "26.9%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Marchosias"] = { { name = "Wolf hide", average_rate = "14.7%" }, { name = "Revival tree root", average_rate = "6.6%" } },
  ["Mimic"] = { { name = "Eldieme coffer key", average_rate = "100.0%" } },
  ["Mummy"] = { { name = "Bone chip", average_rate = "39.1%" }, { name = "Scroll of Absorb-INT", average_rate = "6.4%" }, { name = "Scroll of Absorb-VIT", average_rate = "2.6%" }, { name = "Eldieme chest key", average_rate = "8.1%" }, { name = "Scroll of Absorb-AGI", average_rate = "1.7%" }, { name = "Scroll of Stun", average_rate = "1.7%" } },
  ["Nekros Hound"] = { { name = "Wolf hide", average_rate = "27.3%" }, { name = "Revival tree root", average_rate = "15.0%" }, { name = "Dark cluster", average_rate = "0.05%" } },
  ["Puroboros"] = { { name = "Pinch of bomb ash", average_rate = "34.3%" }, { name = "Bomb arm", average_rate = "20.0%" } },
  ["Revenant"] = { { name = "Square of cotton cloth", average_rate = "27.9%" }, { name = "Revival tree root", average_rate = "7.7%" }, { name = "Luminicloth", average_rate = "1.7%" } },
  ["Shade"] = { { name = "Scroll of Absorb-INT", average_rate = "5.7%" }, { name = "Scroll of Absorb-AGI", average_rate = "2.9%" }, { name = "Scroll of Stun", average_rate = "6.8%" }, { name = "Scroll of Absorb-VIT", average_rate = "3.6%" }, { name = "Revival tree root", average_rate = "13.6%" } },
  ["Skull Of Envy"] = { { name = "Jadeite", average_rate = "100.0%" } },
  ["Skull Of Greed"] = { { name = "Fluorite", average_rate = "100.0%" }, { name = "Greed scimitar", average_rate = "100.0%" } },
  ["Skull Of Lust"] = { { name = "Painite", average_rate = "100.0%" } },
  ["Skull Of Pride"] = { { name = "Aquamarine", average_rate = "100.0%" } },
  ["Spriggan"] = { { name = "Eldieme coffer key", average_rate = "4.7%" }, { name = "Revival tree root", average_rate = "1.9%" } },
  ["Tomb Mage"] = { { name = "Bone chip", average_rate = "29.6%" }, { name = "Scroll of Blizzard III", average_rate = "4.0%" }, { name = "Eldieme coffer key", average_rate = "7.4%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Tomb Warrior"] = { { name = "Bone chip", average_rate = "29.5%" }, { name = "Eldieme coffer key", average_rate = "7.3%" } },
  ["Tomb Wolf"] = { { name = "Revival tree root", average_rate = "20.5%" }, { name = "Wolf hide", average_rate = "37.8%" }, { name = "Eldieme chest key", average_rate = "9.1%" }, { name = "Dark cluster", average_rate = "0.07%" } },
  ["Utukku"] = { { name = "Square of cotton cloth", average_rate = "31.2%" }, { name = "Revival tree root", average_rate = "17.1%" }, { name = "Luminicloth", average_rate = "3.1%" }, { name = "Eldieme chest key", average_rate = "2.4%" } },
}
