-- Zone: Gusgen Mines
return {
  ["Accursed Soldier"] = { { name = "Bone chip", average_rate = "33.5%" }, { name = "Revival tree root", average_rate = "16.9%" }, { name = "Earth cluster", average_rate = "0.02%" } },
  ["Accursed Sorcerer"] = { { name = "Bone chip", average_rate = "34.1%" }, { name = "Earth cluster", average_rate = "0.03%" } },
  ["Amphisbaena"] = { { name = "Chunk of copper ore", average_rate = "20.1%" }, { name = "Flint stone", average_rate = "39.4%" }, { name = "Chunk of silver ore", average_rate = "3.4%" }, { name = "Chunk of zinc ore", average_rate = "10.3%" }, { name = "Gusgen chest key", average_rate = "3.1%" } },
  ["Aroma Fly"] = { { name = "Civet sachet", average_rate = "7.7%" } },
  ["Asphyxiated Amsel"] = { { name = "Square of cotton cloth", average_rate = "100.0%" }, { name = "Malgust ring", average_rate = "26.7%" }, { name = "Revival tree root", average_rate = "26.7%" } },
  ["Bandersnatch"] = { { name = "Wolf hide", average_rate = "17.1%" }, { name = "Revival tree root", average_rate = "8.2%" }, { name = "Dark cluster", average_rate = "0.02%" } },
  ["Banshee"] = { { name = "Revival tree root", average_rate = "20.8%" }, { name = "Square of cotton cloth", average_rate = "38.4%" }, { name = "Scroll of Escape", average_rate = "7.5%" }, { name = "Gusgen chest key", average_rate = "7.3%" }, { name = "Luminicloth", average_rate = "1.9%" } },
  ["Blind Moby"] = { { name = "Chunk of glocolite", average_rate = "105.8%" }, { name = "Handful of pugil scales", average_rate = "25.2%" } },
  ["Bogy"] = { { name = "Bloody robe", average_rate = "27.0%" }, { name = "Revival tree root", average_rate = "7.8%" }, { name = "Luminicloth", average_rate = "1.9%" } },
  ["Burned Bergmann"] = { { name = "Square of cotton cloth", average_rate = "100.0%" }, { name = "Malflame ring", average_rate = "38.5%" }, { name = "Revival tree root", average_rate = "38.5%" } },
  ["Crushed Krause"] = { { name = "Square of cotton cloth", average_rate = "105.0%" }, { name = "Revival tree root", average_rate = "25.0%" }, { name = "Maldust ring", average_rate = "20.0%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "146.6%" }, { name = "Gusgen chest key", average_rate = "6.1%" } },
  ["Feu Follet"] = { { name = "Bomb arm", average_rate = "13.7%" }, { name = "Pinch of bomb ash", average_rate = "27.1%" }, { name = "Gusgen chest key", average_rate = "1.6%" } },
  ["Fly Agaric"] = { { name = "Sleepshroom", average_rate = "44.1%" }, { name = "Woozyshroom", average_rate = "18.4%" } },
  ["Foul Meat"] = { { name = "Revival tree root", average_rate = "30.9%" }, { name = "Clay amulet", average_rate = "9.9%" }, { name = "Undead skin", average_rate = "16.0%" } },
  ["Gallinipper"] = { { name = "Insect wing", average_rate = "12.1%" }, { name = "Gusgen chest key", average_rate = "6.0%" } },
  ["Ghast"] = { { name = "Bone chip", average_rate = "35.2%" }, { name = "Pumice stone", average_rate = "16.8%" }, { name = "Gusgen chest key", average_rate = "6.2%" } },
  ["Ghoul"] = { { name = "Bone chip", average_rate = "39.1%" }, { name = "Pumice stone", average_rate = "19.2%" }, { name = "Magicked skull", average_rate = "8.4%" }, { name = "Scroll of Gravity", average_rate = "1.2%" }, { name = "Earth cluster", average_rate = "0.00%" } },
  ["Greater Pugil"] = { { name = "Handful of pugil scales", average_rate = "12.9%" }, { name = "Gusgen chest key", average_rate = "5.8%" } },
  ["Jelly"] = { { name = "Vial of slime oil", average_rate = "15.4%" } },
  ["Juggler Hecatomb"] = { { name = "Heavy halberd", average_rate = "35.2%" } },
  ["Madfly"] = { { name = "Insect wing", average_rate = "16.6%" }, { name = "Wind cluster", average_rate = "0.01%" } },
  ["Mauthe Doog"] = { { name = "Wolf hide", average_rate = "15.8%" }, { name = "Gusgen chest key", average_rate = "4.2%" }, { name = "Revival tree root", average_rate = "5.6%" } },
  ["Mush"] = { { name = "Vial of slime oil", average_rate = "33.3%" } },
  ["Myconid"] = { { name = "Sleepshroom", average_rate = "36.5%" }, { name = "Woozyshroom", average_rate = "16.8%" }, { name = "Gusgen chest key", average_rate = "7.4%" } },
  ["Ooze"] = { { name = "Vial of slime oil", average_rate = "50.0%" } },
  ["Ore Eater"] = { { name = "Chunk of zinc ore", average_rate = "7.3%" }, { name = "Flint stone", average_rate = "26.0%" }, { name = "Chunk of copper ore", average_rate = "14.8%" }, { name = "Chunk of silver ore", average_rate = "1.3%" } },
  ["Pulverized Pfeffer"] = { { name = "Square of cotton cloth", average_rate = "101.3%" }, { name = "Malfrost ring", average_rate = "23.5%" }, { name = "Revival tree root", average_rate = "15.3%" }, { name = "Luminicloth", average_rate = "5.8%" } },
  ["Rancid Ooze"] = { { name = "Vial of slime oil", average_rate = "35.2%" }, { name = "Gusgen chest key", average_rate = "9.0%" } },
  ["Rockmill"] = { { name = "Chunk of copper ore", average_rate = "14.7%" }, { name = "Flint stone", average_rate = "29.8%" }, { name = "Chunk of silver ore", average_rate = "1.8%" }, { name = "Chunk of zinc ore", average_rate = "6.9%" } },
  ["Sadfly"] = { { name = "Insect wing", average_rate = "18.1%" }, { name = "Gusgen chest key", average_rate = "2.1%" }, { name = "Wind cluster", average_rate = "0.04%" } },
  ["Skeleton Warrior"] = { { name = "Bone chip", average_rate = "42.8%" }, { name = "Earth cluster", average_rate = "0.00%" } },
  ["Smothered Schmidt"] = { { name = "Square of cotton cloth", average_rate = "110.9%" }, { name = "Malflood ring", average_rate = "45.5%" }, { name = "Revival tree root", average_rate = "10.9%" }, { name = "Luminicloth", average_rate = "7.3%" } },
  ["Spunkie"] = { { name = "Bomb arm", average_rate = "18.6%" }, { name = "Pinch of bomb ash", average_rate = "34.0%" }, { name = "Gusgen chest key", average_rate = "3.2%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "154.5%" }, { name = "Gusgen chest key", average_rate = "5.1%" } },
  ["Wandering Ghost"] = { { name = "Miner's pendant", average_rate = "103.7%" } },
  ["Wendigo"] = { { name = "Pumice stone", average_rate = "15.7%" }, { name = "Bone chip", average_rate = "36.3%" }, { name = "Gusgen chest key", average_rate = "1.0%" } },
  ["Wight"] = { { name = "Bone chip", average_rate = "40.2%" }, { name = "Pumice stone", average_rate = "18.7%" }, { name = "Scroll of Tractor", average_rate = "1.6%" }, { name = "Gusgen chest key", average_rate = "7.8%" }, { name = "Scroll of Absorb-AGI", average_rate = "1.3%" }, { name = "Scroll of Absorb-INT", average_rate = "1.4%" }, { name = "Scroll of Absorb-VIT", average_rate = "1.4%" } },
  ["Wounded Wurfel"] = { { name = "Square of cotton cloth", average_rate = "100.0%" }, { name = "Revival tree root", average_rate = "25.0%" }, { name = "Malflash ring", average_rate = "30.0%" }, { name = "Luminicloth", average_rate = "5.0%" } },
}
