-- Zone: Crawlers' Nest
return {
  ["Aqrabuamelu"] = { { name = "Aptant of ishis", average_rate = "24.6%" }, { name = "Aptant of pera", average_rate = "27.3%" } },
  ["Awd Goggie"] = { { name = "Serving of royal jelly", average_rate = "100.0%" }, { name = "Crawler egg", average_rate = "25.0%" }, { name = "Spool of silk thread", average_rate = "56.2%" } },
  ["Blazer Beetle"] = { { name = "Insect wing", average_rate = "99.5%" }, { name = "Beetle shell", average_rate = "127.9%" }, { name = "Beetle jaw", average_rate = "63.9%" }, { name = "Nest chest key", average_rate = "9.5%" } },
  ["Caveberry"] = { { name = "Lump of loam", average_rate = "58.3%" }, { name = "Bag of fruit seeds", average_rate = "4.8%" } },
  ["Crawler Hunter"] = { { name = "Scorpion claw", average_rate = "204.6%" }, { name = "Scorpion shell", average_rate = "102.3%" }, { name = "Nest coffer key", average_rate = "8.6%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Dancing Jewel"] = { { name = "Insect wing", average_rate = "18.6%" }, { name = "Wind cluster", average_rate = "0.04%" } },
  ["Death Jacket"] = { { name = "Beehive chip", average_rate = "42.7%" }, { name = "Insect wing", average_rate = "18.4%" }, { name = "Serving of royal jelly", average_rate = "8.5%" }, { name = "Giant stinger", average_rate = "2.6%" }, { name = "Wind cluster", average_rate = "0.01%" } },
  ["Demonic Tiphia"] = { { name = "Tiphia sting", average_rate = "46.9%" }, { name = "Serving of royal jelly", average_rate = "152.6%" } },
  ["Doom Scorpion"] = { { name = "Scorpion claw", average_rate = "97.6%" }, { name = "Chunk of Derfland humus", average_rate = "17.5%" }, { name = "Scorpion shell", average_rate = "37.0%" }, { name = "Earth cluster", average_rate = "0.03%" } },
  ["Dragonfly"] = { { name = "Insect wing", average_rate = "15.4%" }, { name = "Nest chest key", average_rate = "1.9%" }, { name = "Wind cluster", average_rate = "0.04%" } },
  ["Dreadbug"] = { { name = "Giant shell bug", average_rate = "244.8%" } },
  ["Drone Crawler"] = { { name = "Rolanberry (874 C.E.)", average_rate = "103.2%" }, { name = "Spool of silk thread", average_rate = "38.6%" }, { name = "Crawler egg", average_rate = "22.8%" } },
  ["Dynast Beetle"] = { { name = "Dasra's ring", average_rate = "33.7%" } },
  ["Exoray"] = { { name = "Sleepshroom", average_rate = "101.5%" }, { name = "Clump of exoray mold", average_rate = "25.8%" }, { name = "Woozyshroom", average_rate = "34.7%" }, { name = "Danceshroom", average_rate = "7.9%" }, { name = "Nest chest key", average_rate = "8.2%" }, { name = "Dark cluster", average_rate = "0.03%" } },
  ["Fire Elemental"] = { { name = "Bag of seeds", average_rate = "75.6%" }, { name = "Fire cluster", average_rate = "151.1%" }, { name = "Nest chest key", average_rate = "6.7%" } },
  ["Guardian Crawler"] = { { name = "Rolanberry (881 C.E.)", average_rate = "102.9%" }, { name = "Spool of silk thread", average_rate = "39.4%" }, { name = "Crawler egg", average_rate = "18.5%" } },
  ["Helm Beetle"] = { { name = "Insect wing", average_rate = "102.5%" }, { name = "Beetle shell", average_rate = "93.4%" }, { name = "Beetle jaw", average_rate = "47.3%" }, { name = "Nest coffer key", average_rate = "5.9%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Hornfly"] = { { name = "Nest chest key", average_rate = "7.7%" }, { name = "Insect wing", average_rate = "16.4%" }, { name = "Wind cluster", average_rate = "0.02%" } },
  ["Killer Mushroom"] = { { name = "Woozyshroom", average_rate = "45.3%" }, { name = "King truffle", average_rate = "10.5%" }, { name = "Danceshroom", average_rate = "22.7%" } },
  ["King Crawler"] = { { name = "Spool of silk thread", average_rate = "25.2%" }, { name = "Spool of wyrdstrand", average_rate = "11.9%" }, { name = "Earth cluster", average_rate = "0.03%" } },
  ["Knight Crawler"] = { { name = "Spool of silk thread", average_rate = "5.7%" }, { name = "Nest coffer key", average_rate = "2.6%" }, { name = "Earth cluster", average_rate = "0.02%" } },
  ["Labyrinth Lizard"] = { { name = "Lizard tail", average_rate = "97.9%" }, { name = "Lizard egg", average_rate = "256.9%" }, { name = "Lizard skin", average_rate = "119.6%" }, { name = "Nest chest key", average_rate = "6.2%" }, { name = "Fire cluster", average_rate = "0.00%" } },
  ["Matron Crawler"] = { { name = "Rolanberry (864 C.E.)", average_rate = "100.0%" }, { name = "Spool of silk thread", average_rate = "25.0%" }, { name = "Crawler egg", average_rate = "16.7%" } },
  ["Maze Lizard"] = { { name = "Lizard tail", average_rate = "94.5%" }, { name = "Lizard egg", average_rate = "155.3%" }, { name = "Lizard skin", average_rate = "73.3%" } },
  ["Mimic"] = { { name = "Nest coffer key", average_rate = "91.7%" } },
  ["Mushussu"] = { { name = "Scorpion claw", average_rate = "201.7%" }, { name = "Scorpion shell", average_rate = "100.8%" }, { name = "Nest chest key", average_rate = "9.0%" } },
  ["Nest Beetle"] = { { name = "Insect wing", average_rate = "99.0%" }, { name = "Beetle shell", average_rate = "77.6%" }, { name = "Beetle jaw", average_rate = "39.7%" } },
  ["Olid Funguar"] = { { name = "Woozyshroom", average_rate = "16.6%" }, { name = "Danceshroom", average_rate = "8.1%" }, { name = "King truffle", average_rate = "3.5%" }, { name = "Dark cluster", average_rate = "0.05%" } },
  ["Puroboros"] = { { name = "Pinch of bomb ash", average_rate = "95.9%" }, { name = "Bomb arm", average_rate = "30.3%" }, { name = "Oracle's belt", average_rate = "2.9%" } },
  ["Queen Crawler"] = { { name = "Rolanberry (864 C.E.)", average_rate = "100.0%" }, { name = "Spool of silk thread", average_rate = "46.7%" }, { name = "Crawler egg", average_rate = "33.3%" } },
  ["Rumble Crawler"] = { { name = "Nest chest key", average_rate = "7.6%" }, { name = "Spool of silk thread", average_rate = "15.3%" }, { name = "Earth cluster", average_rate = "0.06%" } },
  ["Soldier Crawler"] = { { name = "Spool of silk thread", average_rate = "16.2%" }, { name = "Earth cluster", average_rate = "0.03%" } },
  ["Soul Stinger"] = { { name = "Beehive chip", average_rate = "34.8%" }, { name = "Giant stinger", average_rate = "3.2%" }, { name = "Pot of honey", average_rate = "17.8%" }, { name = "Insect wing", average_rate = "8.2%" }, { name = "Nest chest key", average_rate = "2.7%" } },
  ["Vespo"] = { { name = "Pot of honey", average_rate = "20.7%" }, { name = "Giant stinger", average_rate = "3.4%" }, { name = "Insect wing", average_rate = "10.0%" }, { name = "Beehive chip", average_rate = "44.2%" }, { name = "Wind cluster", average_rate = "0.09%" } },
  ["Water Elemental"] = { { name = "Bag of seeds", average_rate = "83.4%" }, { name = "Water cluster", average_rate = "161.5%" }, { name = "Nest chest key", average_rate = "8.4%" } },
  ["Wespe"] = { { name = "Beehive chip", average_rate = "32.8%" }, { name = "Insect wing", average_rate = "8.2%" }, { name = "Pot of honey", average_rate = "15.1%" }, { name = "Nest chest key", average_rate = "3.4%" } },
  ["Witch Hazel"] = { { name = "Lump of loam", average_rate = "47.4%" }, { name = "Nest chest key", average_rate = "7.4%" } },
  ["Worker Crawler"] = { { name = "Spool of silk thread", average_rate = "18.7%" }, { name = "Earth cluster", average_rate = "0.01%" } },
}
