-- Zone: Maze of Shakhrami
return {
  ["Abyss Worm"] = { { name = "Flint stone", average_rate = "32.6%" }, { name = "Chunk of copper ore", average_rate = "14.0%" }, { name = "Shakhrami chest key", average_rate = "2.1%" }, { name = "Chunk of zinc ore", average_rate = "6.9%" }, { name = "Chunk of silver ore", average_rate = "1.9%" } },
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "142.9%" }, { name = "Shakhrami chest key", average_rate = "5.8%" } },
  ["Ancient Bat"] = { { name = "Bat wing", average_rate = "31.7%" }, { name = "Vial of fiend blood", average_rate = "2.0%" }, { name = "Wind cluster", average_rate = "0.02%" } },
  ["Argus"] = { { name = "Vial of mercury", average_rate = "108.0%" }, { name = "Peacock amulet", average_rate = "46.2%" }, { name = "Hecteyes eye", average_rate = "103.4%" } },
  ["Bleeder Leech"] = { { name = "Vial of fiend blood", average_rate = "16.8%" }, { name = "Water cluster", average_rate = "0.01%" } },
  ["Carnivorous Crawler"] = { { name = "Inferior cocoon", average_rate = "18.1%" }, { name = "Spool of silk thread", average_rate = "19.0%" } },
  ["Caterchipillar"] = { { name = "Inferior cocoon", average_rate = "14.9%" }, { name = "Spool of silk thread", average_rate = "13.2%" }, { name = "Shakhrami chest key", average_rate = "5.3%" } },
  ["Chaser Bats"] = { { name = "Bat wing", average_rate = "36.7%" } },
  ["Combat"] = { { name = "Bat wing", average_rate = "33.0%" }, { name = "Vial of fiend blood", average_rate = "2.0%" } },
  ["Crypterpillar"] = { { name = "Spool of silk thread", average_rate = "17.7%" }, { name = "Inferior cocoon", average_rate = "8.3%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "140.9%" }, { name = "Shakhrami chest key", average_rate = "6.4%" } },
  ["Ghoul"] = { { name = "Bone chip", average_rate = "32.3%" }, { name = "Magicked skull", average_rate = "6.4%" }, { name = "Earth cluster", average_rate = "0.03%" } },
  ["Gloombound Lurker"] = { { name = "Penumbral brass ingot", average_rate = "37.1%" } },
  ["Goblin Ambusher"] = { { name = "Block of animal glue", average_rate = "30.3%" }, { name = "Leather gloves", average_rate = "1.9%" }, { name = "Leather bandana", average_rate = "1.9%" }, { name = "Leather trousers", average_rate = "2.2%" }, { name = "Leather highboots", average_rate = "2.0%" } },
  ["Goblin Butcher"] = { { name = "Faceguard", average_rate = "0.98%" }, { name = "Scale greaves", average_rate = "1.0%" }, { name = "Scale cuisses", average_rate = "0.76%" }, { name = "Scale finger gauntlets", average_rate = "1.0%" } },
  ["Goblin Furrier"] = { { name = "Square of sheep leather", average_rate = "10.6%" }, { name = "Shakhrami chest key", average_rate = "8.4%" }, { name = "Square of coeurl leather", average_rate = "0.95%" }, { name = "Square of black tiger leather", average_rate = "1.1%" }, { name = "Studded trousers", average_rate = "0.95%" }, { name = "Square of dhalmel leather", average_rate = "3.2%" }, { name = "Studded bandana", average_rate = "0.63%" }, { name = "Studded boots", average_rate = "0.48%" }, { name = "Studded gloves", average_rate = "0.48%" } },
  ["Goblin Gambler"] = { { name = "Bag of poison flour", average_rate = "8.8%" }, { name = "Poet's circlet", average_rate = "0.85%" }, { name = "Linen slops", average_rate = "1.0%" }, { name = "Linen cuffs", average_rate = "1.4%" }, { name = "Holly clogs", average_rate = "0.34%" } },
  ["Goblin Leecher"] = { { name = "Scroll of Paralyze", average_rate = "10.5%" }, { name = "Scroll of Protectra", average_rate = "9.4%" }, { name = "Scroll of Silence", average_rate = "8.3%" }, { name = "Scroll of Sneak", average_rate = "9.4%" }, { name = "Scroll of Barsleep", average_rate = "6.2%" }, { name = "Scroll of Barpoison", average_rate = "4.8%" }, { name = "Linen slops", average_rate = "2.6%" }, { name = "Scroll of Deodorize", average_rate = "2.2%" }, { name = "Scroll of Invisible", average_rate = "0.80%" }, { name = "Poet's circlet", average_rate = "0.96%" }, { name = "Holly clogs", average_rate = "0.96%" }, { name = "Linen cuffs", average_rate = "0.96%" } },
  ["Goblin Mugger"] = { { name = "Brass subligar", average_rate = "2.6%" }, { name = "Brass cap", average_rate = "2.0%" }, { name = "Brass mittens", average_rate = "2.3%" }, { name = "Brass leggings", average_rate = "2.0%" } },
  ["Goblin Pathfinder"] = { { name = "Shakhrami chest key", average_rate = "8.3%" }, { name = "Brass finger gauntlets", average_rate = "1.2%" }, { name = "Brass mask", average_rate = "1.4%" }, { name = "Brass greaves", average_rate = "1.5%" }, { name = "Brass cuisses", average_rate = "0.55%" } },
  ["Goblin Shaman"] = { { name = "Shakhrami chest key", average_rate = "9.7%" }, { name = "Sack of Mithra fangs", average_rate = "6.7%" }, { name = "Chestnut sabots", average_rate = "0.24%" }, { name = "Wool slops", average_rate = "0.12%" }, { name = "Wool hat", average_rate = "0.24%" }, { name = "Fire cluster", average_rate = "0.12%" } },
  ["Goblin Smithy"] = { { name = "Sack of Mithra fangs", average_rate = "6.3%" }, { name = "Chain mittens", average_rate = "1.6%" }, { name = "Shakhrami chest key", average_rate = "6.5%" }, { name = "Chain hose", average_rate = "0.95%" }, { name = "Iron mask", average_rate = "0.63%" }, { name = "Greaves", average_rate = "0.47%" } },
  ["Goblin Tinkerer"] = { { name = "Scale greaves", average_rate = "0.85%" }, { name = "Scale finger gauntlets", average_rate = "0.99%" }, { name = "Scale cuisses", average_rate = "0.91%" }, { name = "Faceguard", average_rate = "0.63%" } },
  ["Ichorous Ire"] = { { name = "Burnite shell stone", average_rate = "122.7%" }, { name = "Vial of slime oil", average_rate = "52.3%" } },
  ["Jelly"] = { { name = "Vial of slime oil", average_rate = "15.8%" } },
  ["Labyrinth Scorpion"] = { { name = "Scorpion claw", average_rate = "73.6%" }, { name = "Scorpion stinger", average_rate = "54.4%" }, { name = "Scorpion shell", average_rate = "26.9%" }, { name = "Shakhrami chest key", average_rate = "12.3%" } },
  ["Leech King"] = { { name = "Vial of fiend blood", average_rate = "45.7%" }, { name = "Bloodbead earring", average_rate = "30.4%" }, { name = "Carbuncle's ruby", average_rate = "6.8%" } },
  ["Lesath"] = { { name = "Esse earring", average_rate = "34.9%" } },
  ["Maze Maker"] = { { name = "Flint stone", average_rate = "28.1%" }, { name = "Chunk of copper ore", average_rate = "14.4%" }, { name = "Chunk of zinc ore", average_rate = "6.8%" }, { name = "Chunk of silver ore", average_rate = "1.6%" }, { name = "Earth cluster", average_rate = "0.00%" } },
  ["Maze Scorpion"] = { { name = "Scorpion stinger", average_rate = "22.7%" }, { name = "Scorpion claw", average_rate = "49.1%" }, { name = "Scorpion shell", average_rate = "17.6%" } },
  ["Poison Leech"] = { { name = "Vial of fiend blood", average_rate = "18.4%" }, { name = "Carbuncle's ruby", average_rate = "2.1%" } },
  ["Protozoan"] = { { name = "Shakhrami chest key", average_rate = "6.4%" }, { name = "Vial of slime oil", average_rate = "30.9%" } },
  ["Seeker Bats"] = { { name = "Bat wing", average_rate = "32.4%" } },
  ["Stink Bats"] = { { name = "Bat wing", average_rate = "30.6%" }, { name = "Wind cluster", average_rate = "0.02%" } },
  ["Trembler Tabitha"] = { { name = "Grimy bronze sheet", average_rate = "22.3%" } },
  ["Warren Bat"] = { { name = "Bat wing", average_rate = "37.9%" }, { name = "Vial of fiend blood", average_rate = "2.4%" }, { name = "Wind cluster", average_rate = "0.02%" } },
  ["Wendigo"] = { { name = "Bone chip", average_rate = "37.2%" }, { name = "Scroll of Gravity", average_rate = "8.8%" } },
  ["Wight"] = { { name = "Rusty key", average_rate = "19.0%" }, { name = "Scroll of Tractor", average_rate = "4.3%" }, { name = "Bone chip", average_rate = "62.4%" }, { name = "Scroll of Absorb-INT", average_rate = "4.1%" }, { name = "Scroll of Absorb-AGI", average_rate = "2.4%" }, { name = "Shakhrami chest key", average_rate = "12.7%" }, { name = "Scroll of Absorb-VIT", average_rate = "2.4%" } },
}
