-- Zone: Carpenters' Landing
return {
  ["Battrap"] = { { name = "Flytrap leaf", average_rate = "8.3%" } },
  ["Beady Beetle"] = { { name = "Insect wing", average_rate = "33.4%" }, { name = "Beetle jaw", average_rate = "9.5%" } },
  ["Birdtrap"] = { { name = "Flytrap leaf", average_rate = "6.2%" } },
  ["Bulldog Bats"] = { { name = "Bat fang", average_rate = "20.0%" }, { name = "Bat wing", average_rate = "30.0%" } },
  ["Clipper"] = { { name = "Slice of land crab meat", average_rate = "4.0%" }, { name = "Chunk of rock salt", average_rate = "12.0%" } },
  ["Digger Wasp"] = { { name = "Insect wing", average_rate = "18.7%" }, { name = "Giant stinger", average_rate = "3.8%" } },
  ["Diving Beetle"] = { { name = "Insect wing", average_rate = "29.4%" }, { name = "Beetle jaw", average_rate = "8.6%" } },
  ["Fishtrap"] = { { name = "Piece of Garhada teak lumber", average_rate = "21.4%" }, { name = "Flytrap leaf", average_rate = "7.1%" } },
  ["Flytrap"] = { { name = "Flytrap leaf", average_rate = "7.1%" } },
  ["Forest Tiger"] = { { name = "Black tiger hide", average_rate = "17.3%" }, { name = "Black tiger fang", average_rate = "31.4%" } },
  ["Fosse Pugil"] = { { name = "Handful of pugil scales", average_rate = "13.2%" } },
  ["Ghoul"] = { { name = "Revival tree root", average_rate = "16.7%" }, { name = "Bone chip", average_rate = "25.0%" } },
  ["Glide Bomb"] = { { name = "Pinch of bomb ash", average_rate = "26.3%" }, { name = "Bomb arm", average_rate = "5.3%" } },
  ["Land Pugil"] = { { name = "Handful of pugil scales", average_rate = "10.9%" } },
  ["Marsh Funguar"] = { { name = "Sleepshroom", average_rate = "41.1%" }, { name = "Woozyshroom", average_rate = "17.8%" } },
  ["Mycophile"] = { { name = "Mycophile cuffs", average_rate = "40.0%" } },
  ["Orcish Grunt"] = { { name = "Fire cluster", average_rate = "1.2%" } },
  ["Orctrap"] = { { name = "Flytrap leaf", average_rate = "19.6%" }, { name = "Hojutsu belt", average_rate = "6.1%" }, { name = "Nikkariaoe", average_rate = "12.2%" } },
  ["Poison Funguar"] = { { name = "Woozyshroom", average_rate = "14.4%" }, { name = "Sleepshroom", average_rate = "29.3%" } },
  ["Sabertooth Tiger"] = { { name = "Black tiger hide", average_rate = "15.3%" }, { name = "Black tiger fang", average_rate = "30.9%" } },
  ["Shrieker"] = { { name = "Sleepshroom", average_rate = "32.5%" }, { name = "Woozyshroom", average_rate = "15.4%" } },
  ["Snipper"] = { { name = "Chunk of rock salt", average_rate = "37.0%" }, { name = "Slice of land crab meat", average_rate = "6.5%" }, { name = "Crab shell", average_rate = "2.2%" } },
  ["Specter Bat"] = { { name = "Bat fang", average_rate = "33.3%" } },
  ["Spider Wasp"] = { { name = "Insect wing", average_rate = "29.0%" }, { name = "Giant stinger", average_rate = "3.2%" } },
  ["Spinous Pugil"] = { { name = "Handful of pugil scales", average_rate = "16.2%" } },
  ["Spunkie"] = { { name = "Pinch of bomb ash", average_rate = "105.3%" }, { name = "Bomb arm", average_rate = "23.7%" } },
  ["Stag Beetle"] = { { name = "Insect wing", average_rate = "36.5%" }, { name = "Beetle jaw", average_rate = "9.2%" } },
  ["Stagdella"] = { { name = "Water cluster", average_rate = "28.6%" } },
  ["Tempest Tigon"] = { { name = "Elan earring", average_rate = "25.0%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "140.9%" } },
  ["Triangle Crab"] = { { name = "Chunk of rock salt", average_rate = "18.8%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "131.7%" } },
  ["Wendigo"] = { { name = "Bone chip", average_rate = "37.9%" }, { name = "Revival tree root", average_rate = "13.8%" } },
  ["Wight"] = { { name = "Bone chip", average_rate = "28.0%" }, { name = "Revival tree root", average_rate = "12.0%" }, { name = "Scroll of Gravity", average_rate = "8.0%" } },
  ["Will-O'-The-Wisp"] = { { name = "Pinch of bomb ash", average_rate = "105.6%" }, { name = "Bomb arm", average_rate = "55.6%" } },
}
