-- Zone: Promyvion - Mea
return {
  ["Coveter"] = { { name = "Remnant of a coveter", average_rate = "96.9%" }, { name = "Indigo memosphere", average_rate = "130.9%" } },
  ["Craver"] = { { name = "Remnant of a startling memory", average_rate = "2.5%" }, { name = "Indigo memosphere", average_rate = "7.0%" }, { name = "Recollection of fear", average_rate = "19.3%" }, { name = "Remnant of a fleeting memory", average_rate = "2.5%" }, { name = "Recollection of guilt", average_rate = "20.9%" }, { name = "Remnant of a radiant memory", average_rate = "2.6%" }, { name = "Remnant of a malevolent memory", average_rate = "2.4%" }, { name = "Remnant of a burning memory", average_rate = "2.6%" }, { name = "Remnant of a bitter memory", average_rate = "2.2%" }, { name = "Remnant of a somber memory", average_rate = "2.8%" }, { name = "Remnant of a profane memory", average_rate = "2.1%" } },
  ["Idle Wanderer"] = { { name = "Remnant of a burning memory", average_rate = "2.5%" }, { name = "Remnant of a startling memory", average_rate = "1.8%" }, { name = "Remnant of a malevolent memory", average_rate = "1.2%" }, { name = "Remnant of a radiant memory", average_rate = "1.9%" }, { name = "Remnant of a bitter memory", average_rate = "1.8%" }, { name = "Remnant of a profane memory", average_rate = "1.9%" }, { name = "Remnant of a fleeting memory", average_rate = "1.9%" }, { name = "Remnant of a somber memory", average_rate = "2.1%" } },
  ["Livid Seether"] = { { name = "Remnant of a fleeting memory", average_rate = "5.3%" }, { name = "Remnant of a radiant memory", average_rate = "5.6%" }, { name = "Remnant of a malevolent memory", average_rate = "6.2%" }, { name = "Remnant of a burning memory", average_rate = "5.9%" }, { name = "Remnant of a bitter memory", average_rate = "5.0%" }, { name = "Remnant of a startling memory", average_rate = "5.6%" }, { name = "Remnant of a somber memory", average_rate = "3.4%" }, { name = "Remnant of a profane memory", average_rate = "4.2%" } },
  ["Seether"] = { { name = "Remnant of a somber memory", average_rate = "6.2%" }, { name = "Remnant of a malevolent memory", average_rate = "18.3%" }, { name = "Recollection of pain", average_rate = "24.1%" }, { name = "Remnant of a bitter memory", average_rate = "6.6%" }, { name = "Remnant of a fleeting memory", average_rate = "6.6%" }, { name = "Remnant of a radiant memory", average_rate = "18.6%" }, { name = "Remnant of a burning memory", average_rate = "6.7%" }, { name = "Remnant of a profane memory", average_rate = "6.1%" }, { name = "Remnant of a startling memory", average_rate = "6.3%" } },
  ["Wanderer"] = { { name = "Remnant of a malevolent memory", average_rate = "18.4%" }, { name = "Recollection of guilt", average_rate = "23.4%" }, { name = "Remnant of a radiant memory", average_rate = "18.4%" }, { name = "Remnant of a profane memory", average_rate = "6.5%" }, { name = "Remnant of a burning memory", average_rate = "5.9%" }, { name = "Remnant of a bitter memory", average_rate = "6.1%" }, { name = "Remnant of a fleeting memory", average_rate = "6.5%" }, { name = "Remnant of a somber memory", average_rate = "6.3%" }, { name = "Remnant of a startling memory", average_rate = "6.4%" } },
  ["Weeper"] = { { name = "Recollection of fear", average_rate = "23.9%" }, { name = "Remnant of a malevolent memory", average_rate = "18.7%" }, { name = "Remnant of a startling memory", average_rate = "6.3%" }, { name = "Remnant of a fleeting memory", average_rate = "7.1%" }, { name = "Remnant of a radiant memory", average_rate = "18.5%" }, { name = "Remnant of a somber memory", average_rate = "6.6%" }, { name = "Remnant of a burning memory", average_rate = "6.8%" }, { name = "Remnant of a bitter memory", average_rate = "6.4%" }, { name = "Remnant of a profane memory", average_rate = "6.3%" } },
  ["Woeful Weeper"] = { { name = "Remnant of a somber memory", average_rate = "5.7%" }, { name = "Remnant of a malevolent memory", average_rate = "2.7%" }, { name = "Remnant of a startling memory", average_rate = "4.0%" }, { name = "Remnant of a fleeting memory", average_rate = "3.7%" }, { name = "Remnant of a profane memory", average_rate = "2.4%" }, { name = "Remnant of a radiant memory", average_rate = "4.7%" }, { name = "Remnant of a burning memory", average_rate = "5.7%" }, { name = "Remnant of a bitter memory", average_rate = "4.7%" } },
}
