-- Zone: Garlaige Citadel
return {
  ["Acid Grease"] = { { name = "Vial of slime oil", average_rate = "146.1%" }, { name = "Garlaige chest key", average_rate = "10.7%" } },
  ["Bhuta"] = { { name = "Square of cotton cloth", average_rate = "20.7%" }, { name = "Luminicloth", average_rate = "1.2%" }, { name = "Revival tree root", average_rate = "5.4%" } },
  ["Borer Beetle"] = { { name = "Insect wing", average_rate = "99.0%" }, { name = "Beetle shell", average_rate = "61.5%" }, { name = "Beetle jaw", average_rate = "29.9%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Chamber Beetle"] = { { name = "Insect wing", average_rate = "101.1%" }, { name = "Beetle shell", average_rate = "100.4%" }, { name = "Beetle jaw", average_rate = "50.2%" } },
  ["Chandelier"] = { { name = "Lump of chandelier coal", average_rate = "105.8%" } },
  ["Citadel Bats"] = { { name = "Bat wing", average_rate = "32.2%" }, { name = "Bat fang", average_rate = "64.9%" }, { name = "Wind cluster", average_rate = "0.02%" } },
  ["Clockwork Pod"] = { { name = "Vial of mercury", average_rate = "15.2%" }, { name = "Piece of eastern pottery", average_rate = "9.8%" }, { name = "Magic pot shard", average_rate = "26.8%" }, { name = "Chrysoberyl", average_rate = "0.89%" } },
  ["Demonic Weapon"] = { { name = "Wind cluster", average_rate = "0.07%" } },
  ["Donjon Bat"] = { { name = "Bat wing", average_rate = "34.4%" }, { name = "Vial of fiend blood", average_rate = "1.9%" }, { name = "Wind cluster", average_rate = "0.13%" } },
  ["Droma"] = { { name = "Vial of mercury", average_rate = "16.0%" }, { name = "Magic pot shard", average_rate = "35.8%" }, { name = "Garlaige chest key", average_rate = "7.1%" }, { name = "Jadeite", average_rate = "2.5%" }, { name = "Light cluster", average_rate = "0.15%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "159.3%" }, { name = "Garlaige chest key", average_rate = "9.3%" } },
  ["Explosure"] = { { name = "Chunk of bomb coal", average_rate = "38.8%" }, { name = "Garlaige chest key", average_rate = "8.3%" }, { name = "Fire cluster", average_rate = "0.02%" } },
  ["Fallen Evacuee"] = { { name = "Bone chip", average_rate = "33.8%" }, { name = "Scroll of Absorb-AGI", average_rate = "0.86%" }, { name = "Garlaige key", average_rate = "8.0%" }, { name = "Scroll of Absorb-VIT", average_rate = "1.1%" }, { name = "Scroll of Absorb-INT", average_rate = "1.9%" } },
  ["Fallen Mage"] = { { name = "Garlaige coffer key", average_rate = "5.9%" }, { name = "Bone chip", average_rate = "30.7%" }, { name = "Scroll of Blizzard III", average_rate = "5.6%" } },
  ["Fallen Major"] = { { name = "Garlaige coffer key", average_rate = "6.0%" } },
  ["Fallen Officer"] = { { name = "Bone chip", average_rate = "35.6%" }, { name = "Garlaige chest key", average_rate = "8.5%" }, { name = "Scroll of Absorb-AGI", average_rate = "2.3%" }, { name = "Scroll of Absorb-INT", average_rate = "3.2%" }, { name = "Scroll of Absorb-VIT", average_rate = "2.6%" } },
  ["Fallen Soldier"] = { { name = "Scroll of Absorb-INT", average_rate = "3.4%" }, { name = "Bone chip", average_rate = "32.4%" }, { name = "Scroll of Absorb-VIT", average_rate = "1.7%" }, { name = "Scroll of Absorb-AGI", average_rate = "1.7%" }, { name = "Scroll of Stun", average_rate = "1.9%" } },
  ["Fetid Flesh"] = { { name = "Revival tree root", average_rate = "33.6%" }, { name = "Undead skin", average_rate = "27.4%" }, { name = "Garlaige chest key", average_rate = "4.6%" } },
  ["Fortalice Bats"] = { { name = "Bat wing", average_rate = "35.3%" }, { name = "Wind cluster", average_rate = "0.04%" } },
  ["Frogamander"] = { { name = "Selemnus belt", average_rate = "34.7%" } },
  ["Funnel Bats"] = { { name = "Bat fang", average_rate = "98.8%" }, { name = "Bat wing", average_rate = "49.5%" }, { name = "Garlaige chest key", average_rate = "8.1%" } },
  ["Guardian Statue"] = { { name = "Nail puller", average_rate = "105.3%" } },
  ["Hazmat"] = { { name = "Promptitude solea", average_rate = "33.5%" } },
  ["Hellmine"] = { { name = "Garlaige coffer key", average_rate = "6.9%" } },
  ["Hovering Hotpot"] = { { name = "Sleight kukri", average_rate = "20.4%" } },
  ["Kaboom"] = { { name = "Bomb arm", average_rate = "16.6%" }, { name = "Pinch of bomb ash", average_rate = "36.9%" }, { name = "Fire cluster", average_rate = "0.11%" } },
  ["Magic Jug"] = { { name = "Scroll of Shell IV", average_rate = "6.8%" }, { name = "Garlaige coffer key", average_rate = "8.4%" }, { name = "Scroll of Enaero II", average_rate = "12.3%" } },
  ["Mimic"] = { { name = "Garlaige coffer key", average_rate = "100.0%" } },
  ["Oil Spill"] = { { name = "Vial of slime oil", average_rate = "51.3%" } },
  ["Old Two-Wings"] = { { name = "Vial of fiend blood", average_rate = "108.9%" }, { name = "Bat cape", average_rate = "55.2%" } },
  ["Over Weapon"] = { { name = "Garlaige coffer key", average_rate = "7.3%" } },
  ["Puroboros"] = { { name = "Pinch of bomb ash", average_rate = "28.6%" }, { name = "Bomb arm", average_rate = "13.6%" } },
  ["Revenant"] = { { name = "Square of cotton cloth", average_rate = "27.6%" }, { name = "Revival tree root", average_rate = "10.0%" }, { name = "Luminicloth", average_rate = "1.8%" } },
  ["Serket"] = { { name = "Reraiser", average_rate = "45.3%" }, { name = "Vile elixir", average_rate = "42.1%" }, { name = "Serket ring", average_rate = "46.9%" }, { name = "Serket shield", average_rate = "50.2%" }, { name = "Hi-reraiser", average_rate = "30.5%" }, { name = "Vile elixir +1", average_rate = "32.3%" }, { name = "Triple dagger", average_rate = "62.4%" }, { name = "Venomous claw", average_rate = "24.1%" }, { name = "Earth cluster", average_rate = "0.05%" } },
  ["Siege Bat"] = { { name = "Bat fang", average_rate = "60.1%" }, { name = "Bat wing", average_rate = "30.0%" }, { name = "Vial of fiend blood", average_rate = "1.8%" }, { name = "Wind cluster", average_rate = "0.04%" } },
  ["Skewer Sam"] = { { name = "Cockatrice skin", average_rate = "221.8%" }, { name = "Wind spear", average_rate = "58.9%" } },
  ["Tainted Flesh"] = { { name = "Undead skin", average_rate = "28.1%" }, { name = "Garlaige coffer key", average_rate = "8.7%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "144.8%" }, { name = "Garlaige chest key", average_rate = "12.6%" } },
  ["Vault Weapon"] = { { name = "Garlaige coffer key", average_rate = "7.4%" } },
  ["Warden Beetle"] = { { name = "Insect wing", average_rate = "34.0%" }, { name = "Beetle jaw", average_rate = "7.9%" }, { name = "Beetle shell", average_rate = "16.3%" }, { name = "Earth cluster", average_rate = "0.03%" } },
  ["Wingrats"] = { { name = "Bat fang", average_rate = "55.3%" }, { name = "Bat wing", average_rate = "27.7%" } },
  ["Wraith"] = { { name = "Square of cotton cloth", average_rate = "34.8%" }, { name = "Revival tree root", average_rate = "8.4%" }, { name = "Garlaige coffer key", average_rate = "8.1%" }, { name = "Luminicloth", average_rate = "2.3%" }, { name = "Ice cluster", average_rate = "0.01%" } },
}
