-- Zone: Fei'Yin
return {
  ["Altedour I Tavnazia"] = { { name = "Tavnazian mask", average_rate = "105.7%" }, { name = "Revival tree root", average_rate = "6.8%" } },
  ["Balayang"] = { { name = "Seasoning stone", average_rate = "14.6%" }, { name = "Bat wing", average_rate = "29.1%" }, { name = "Vial of fiend blood", average_rate = "1.7%" }, { name = "Wind cluster", average_rate = "0.02%" } },
  ["Camazotz"] = { { name = "Bat fang", average_rate = "99.6%" }, { name = "Bat wing", average_rate = "47.2%" }, { name = "Vial of fiend blood", average_rate = "2.8%" } },
  ["Capricious Cassie"] = { { name = "Reraiser", average_rate = "49.8%" }, { name = "Vile elixir", average_rate = "62.1%" }, { name = "Vile elixir +1", average_rate = "37.5%" }, { name = "Hi-reraiser", average_rate = "23.6%" }, { name = "Amity cape", average_rate = "58.1%" }, { name = "Aiming bracelets", average_rate = "50.7%" }, { name = "Cassie earring", average_rate = "34.0%" }, { name = "Spool of malboro fiber", average_rate = "26.2%" } },
  ["Clockwork Pod"] = { { name = "Vial of mercury", average_rate = "16.4%" }, { name = "Magic pot shard", average_rate = "37.2%" }, { name = "Piece of eastern pottery", average_rate = "5.7%" }, { name = "Zircon", average_rate = "2.7%" } },
  ["Colossus"] = { { name = "Chunk of mythril ore", average_rate = "43.2%" }, { name = "Golem shard", average_rate = "9.7%" } },
  ["Dark Elemental"] = { { name = "Dark cluster", average_rate = "187.6%" } },
  ["Droma"] = { { name = "Magic pot shard", average_rate = "36.7%" }, { name = "Scroll of Enfire II", average_rate = "7.0%" }, { name = "Vial of mercury", average_rate = "8.6%" }, { name = "Painite", average_rate = "2.6%" } },
  ["Drone"] = { { name = "Doll shard", average_rate = "6.8%" }, { name = "Vial of mercury", average_rate = "13.2%" }, { name = "Ice cluster", average_rate = "0.05%" } },
  ["Eastern Shadow"] = { { name = "Revival tree root", average_rate = "105.1%" }, { name = "Vali's bow", average_rate = "36.4%" } },
  ["Goliath"] = { { name = "Slab of granite", average_rate = "105.4%" }, { name = "Chunk of mythril ore", average_rate = "42.6%" }, { name = "Golem shard", average_rate = "34.1%" } },
  ["Hellish Weapon"] = { { name = "Scroll of Reraise II", average_rate = "6.9%" }, { name = "Wind cluster", average_rate = "0.03%" } },
  ["Ice Elemental"] = { { name = "Ice cluster", average_rate = "202.8%" } },
  ["Jenglot"] = { { name = "Aptant of haelan", average_rate = "23.1%" }, { name = "Aptant of secan", average_rate = "20.5%" } },
  ["Mind Hoarder"] = { { name = "Lleu's charm", average_rate = "28.0%" } },
  ["Miser Murphy"] = { { name = "Antique coin", average_rate = "102.3%" } },
  ["Northern Shadow"] = { { name = "Revival tree root", average_rate = "108.5%" }, { name = "Executioner", average_rate = "33.9%" } },
  ["Ore Golem"] = { { name = "Chunk of mythril ore", average_rate = "32.3%" }, { name = "Golem shard", average_rate = "8.8%" }, { name = "Fei'Yin chest key", average_rate = "2.3%" } },
  ["Revenant"] = { { name = "Square of cotton cloth", average_rate = "30.1%" }, { name = "Revival tree root", average_rate = "8.1%" }, { name = "Luminicloth", average_rate = "1.8%" } },
  ["Sentient Carafe"] = { { name = "Seasoning stone", average_rate = "14.7%" }, { name = "Vial of mercury", average_rate = "14.5%" }, { name = "Magic pot shard", average_rate = "29.9%" }, { name = "Light cluster", average_rate = "0.06%" } },
  ["Shadow"] = { { name = "Revival tree root", average_rate = "2.6%" }, { name = "Ingot of royal treasury gold", average_rate = "8.8%" }, { name = "Fei'Yin chest key", average_rate = "5.3%" } },
  ["Sluagh"] = { { name = "Square of ensanguined cloth", average_rate = "42.3%" } },
  ["Southern Shadow"] = { { name = "Revival tree root", average_rate = "103.3%" }, { name = "Master shield", average_rate = "50.0%" } },
  ["Specter"] = { { name = "Scroll of Absorb-AGI", average_rate = "3.2%" }, { name = "Scroll of Absorb-INT", average_rate = "4.3%" }, { name = "Revival tree root", average_rate = "3.0%" }, { name = "Scroll of Absorb-VIT", average_rate = "2.7%" }, { name = "Dark cluster", average_rate = "0.05%" } },
  ["Talos"] = { { name = "Vial of mercury", average_rate = "17.4%" }, { name = "Doll shard", average_rate = "7.1%" } },
  ["Undead Bats"] = { { name = "Bat fang", average_rate = "20.1%" }, { name = "Bat wing", average_rate = "21.3%" } },
  ["Underworld Bats"] = { { name = "Bat wing", average_rate = "51.7%" }, { name = "Bat fang", average_rate = "101.4%" }, { name = "Fei'Yin chest key", average_rate = "2.8%" }, { name = "Wind cluster", average_rate = "0.03%" } },
  ["Utukku"] = { { name = "Wandering bulb", average_rate = "8.7%" }, { name = "Square of cotton cloth", average_rate = "36.0%" }, { name = "Revival tree root", average_rate = "17.9%" }, { name = "Luminicloth", average_rate = "2.7%" } },
  ["Vampire Bat"] = { { name = "Bat wing", average_rate = "26.7%" }, { name = "Bat fang", average_rate = "50.4%" }, { name = "Vial of fiend blood", average_rate = "1.8%" }, { name = "Wind cluster", average_rate = "0.04%" } },
  ["Wekufe"] = { { name = "Seasoning stone", average_rate = "17.7%" }, { name = "Square of cotton cloth", average_rate = "33.2%" }, { name = "Revival tree root", average_rate = "17.5%" }, { name = "Luminicloth", average_rate = "2.5%" } },
  ["Western Shadow"] = { { name = "Revival tree root", average_rate = "105.3%" }, { name = "Retaliators", average_rate = "36.3%" }, { name = "Dark cluster", average_rate = "0.88%" } },
}
