-- Zone: Promyvion - Vahzl
return {
  ["Craver"] = { { name = "Recollection of guilt", average_rate = "14.1%" }, { name = "Recollection of fear", average_rate = "14.7%" }, { name = "Remnant of a bitter memory", average_rate = "2.0%" }, { name = "White memosphere", average_rate = "6.3%" }, { name = "Remnant of a malevolent memory", average_rate = "1.8%" }, { name = "Remnant of a profane memory", average_rate = "1.7%" }, { name = "Remnant of a burning memory", average_rate = "1.3%" }, { name = "Remnant of a startling memory", average_rate = "1.8%" }, { name = "Remnant of a fleeting memory", average_rate = "1.3%" }, { name = "Remnant of a somber memory", average_rate = "2.3%" }, { name = "Remnant of a radiant memory", average_rate = "1.7%" } },
  ["Deviator"] = { { name = "White memosphere", average_rate = "184.1%" }, { name = "Recollection of suffering", average_rate = "38.6%" } },
  ["Gorger"] = { { name = "Remnant of a somber memory", average_rate = "2.6%" }, { name = "Remnant of a bitter memory", average_rate = "1.5%" }, { name = "Recollection of pain", average_rate = "16.6%" }, { name = "Remnant of a fleeting memory", average_rate = "2.7%" }, { name = "Recollection of guilt", average_rate = "15.3%" }, { name = "White memosphere", average_rate = "7.5%" }, { name = "Remnant of a profane memory", average_rate = "2.4%" }, { name = "Remnant of a burning memory", average_rate = "2.4%" }, { name = "Remnant of a radiant memory", average_rate = "2.2%" }, { name = "Remnant of a malevolent memory", average_rate = "1.4%" }, { name = "Remnant of a startling memory", average_rate = "1.8%" } },
  ["Idle Wanderer"] = { { name = "Remnant of a fleeting memory", average_rate = "4.3%" }, { name = "Remnant of a malevolent memory", average_rate = "4.1%" }, { name = "Remnant of a somber memory", average_rate = "3.4%" }, { name = "Remnant of a bitter memory", average_rate = "3.4%" }, { name = "Remnant of a profane memory", average_rate = "3.0%" }, { name = "Remnant of a burning memory", average_rate = "5.0%" }, { name = "Remnant of a radiant memory", average_rate = "4.3%" }, { name = "Remnant of a startling memory", average_rate = "4.9%" } },
  ["Livid Seether"] = { { name = "Remnant of a burning memory", average_rate = "6.0%" }, { name = "Remnant of a bitter memory", average_rate = "2.0%" }, { name = "Remnant of a malevolent memory", average_rate = "2.0%" }, { name = "Remnant of a fleeting memory", average_rate = "4.0%" }, { name = "Remnant of a somber memory", average_rate = "6.5%" }, { name = "Remnant of a radiant memory", average_rate = "6.0%" }, { name = "Remnant of a startling memory", average_rate = "2.5%" }, { name = "Remnant of a profane memory", average_rate = "4.0%" } },
  ["Provoker"] = { { name = "White memosphere", average_rate = "192.1%" }, { name = "Recollection of anxiety", average_rate = "57.7%" } },
  ["Seether"] = { { name = "Remnant of a malevolent memory", average_rate = "11.7%" }, { name = "Remnant of a profane memory", average_rate = "3.7%" }, { name = "Remnant of a startling memory", average_rate = "2.8%" }, { name = "Remnant of a somber memory", average_rate = "3.0%" }, { name = "Recollection of pain", average_rate = "15.7%" }, { name = "Remnant of a burning memory", average_rate = "4.2%" }, { name = "Remnant of a fleeting memory", average_rate = "3.3%" }, { name = "Remnant of a radiant memory", average_rate = "12.1%" }, { name = "Remnant of a bitter memory", average_rate = "3.4%" } },
  ["Stray"] = { { name = "Recollection of pain", average_rate = "0.30%" } },
  ["Thinker"] = { { name = "Remnant of a bitter memory", average_rate = "1.8%" }, { name = "Recollection of pain", average_rate = "13.7%" }, { name = "White memosphere", average_rate = "5.3%" }, { name = "Recollection of fear", average_rate = "15.8%" }, { name = "Remnant of a burning memory", average_rate = "1.7%" }, { name = "Remnant of a startling memory", average_rate = "1.6%" }, { name = "Remnant of a malevolent memory", average_rate = "1.6%" }, { name = "Remnant of a profane memory", average_rate = "2.3%" }, { name = "Remnant of a somber memory", average_rate = "2.1%" }, { name = "Remnant of a radiant memory", average_rate = "1.6%" }, { name = "Remnant of a fleeting memory", average_rate = "1.4%" } },
  ["Wailer"] = { { name = "White memosphere", average_rate = "164.4%" }, { name = "Recollection of animosity", average_rate = "46.7%" } },
  ["Wanderer"] = { { name = "Remnant of a fleeting memory", average_rate = "4.5%" }, { name = "Remnant of a radiant memory", average_rate = "13.3%" }, { name = "Recollection of guilt", average_rate = "17.3%" }, { name = "Remnant of a burning memory", average_rate = "5.4%" }, { name = "Remnant of a profane memory", average_rate = "4.5%" }, { name = "Remnant of a malevolent memory", average_rate = "11.7%" }, { name = "Remnant of a startling memory", average_rate = "4.9%" }, { name = "Remnant of a bitter memory", average_rate = "4.7%" }, { name = "Remnant of a somber memory", average_rate = "4.6%" } },
  ["Weeper"] = { { name = "Remnant of a profane memory", average_rate = "4.5%" }, { name = "Remnant of a bitter memory", average_rate = "5.4%" }, { name = "Remnant of a malevolent memory", average_rate = "13.2%" }, { name = "Remnant of a startling memory", average_rate = "4.7%" }, { name = "Remnant of a somber memory", average_rate = "4.1%" }, { name = "Recollection of fear", average_rate = "18.2%" }, { name = "Remnant of a burning memory", average_rate = "4.8%" }, { name = "Remnant of a radiant memory", average_rate = "13.8%" }, { name = "Remnant of a fleeting memory", average_rate = "3.8%" } },
  ["Woeful Weeper"] = { { name = "Remnant of a startling memory", average_rate = "6.6%" }, { name = "Remnant of a bitter memory", average_rate = "4.1%" }, { name = "Remnant of a somber memory", average_rate = "5.6%" }, { name = "Remnant of a fleeting memory", average_rate = "3.6%" }, { name = "Remnant of a radiant memory", average_rate = "3.0%" }, { name = "Remnant of a malevolent memory", average_rate = "3.0%" }, { name = "Remnant of a burning memory", average_rate = "5.1%" }, { name = "Remnant of a profane memory", average_rate = "1.5%" } },
}
