-- Zone: Lufaise Meadows
return {
  ["Abraxas"] = { { name = "Giant bird feather", average_rate = "64.7%" }, { name = "Giant bird plume", average_rate = "9.9%" }, { name = "Wind cluster", average_rate = "0.02%" } },
  ["Acrophies"] = { { name = "Vial of fiend blood", average_rate = "15.0%" }, { name = "Vial of beastman blood", average_rate = "6.9%" }, { name = "Carbuncle's ruby", average_rate = "1.2%" } },
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "156.8%" } },
  ["Amaltheia"] = { { name = "Amaltheia hide", average_rate = "102.1%" }, { name = "Lanolin cube", average_rate = "102.1%" }, { name = "Ram skin", average_rate = "224.3%" }, { name = "Ram horn", average_rate = "76.0%" } },
  ["Atomic Cluster"] = { { name = "Cluster core", average_rate = "100.8%" }, { name = "Cluster arm", average_rate = "7.5%" }, { name = "Pinch of cluster ash", average_rate = "12.5%" } },
  ["Bugard"] = { { name = "Bugard skin", average_rate = "28.4%" }, { name = "Bugard tusk", average_rate = "1.8%" } },
  ["Clipper"] = { { name = "Slice of land crab meat", average_rate = "27.8%" }, { name = "Chunk of rock salt", average_rate = "8.3%" }, { name = "Crab shell", average_rate = "2.8%" } },
  ["Cluster"] = { { name = "Cluster core", average_rate = "103.0%" }, { name = "Cluster arm", average_rate = "12.1%" }, { name = "Pinch of cluster ash", average_rate = "9.1%" } },
  ["Colorful Leshy"] = { { name = "Harvest earring", average_rate = "48.6%" }, { name = "Mahogany log", average_rate = "26.0%" }, { name = "Ebony log", average_rate = "14.1%" }, { name = "Rosewood log", average_rate = "52.0%" }, { name = "Petrified log", average_rate = "5.1%" } },
  ["Crimson Knight Crab"] = { { name = "Sack of silica", average_rate = "6.9%" }, { name = "Slice of land crab meat", average_rate = "43.1%" }, { name = "Crab shell", average_rate = "27.5%" } },
  ["Dark Elemental"] = { { name = "Dark cluster", average_rate = "153.3%" } },
  ["Death Jacket"] = { { name = "Beehive chip", average_rate = "32.0%" }, { name = "Pot of honey", average_rate = "19.2%" }, { name = "Insect wing", average_rate = "6.9%" }, { name = "Giant stinger", average_rate = "2.1%" } },
  ["Defoliate Leshy"] = { { name = "Mahogany log", average_rate = "31.1%" }, { name = "Rosewood log", average_rate = "44.6%" }, { name = "Heims earring", average_rate = "47.3%" }, { name = "Ebony log", average_rate = "16.2%" }, { name = "Petrified log", average_rate = "8.1%" } },
  ["Flockbock"] = { { name = "Woolly pelage", average_rate = "20.2%" }, { name = "Earth cluster", average_rate = "0.34%" } },
  ["Fomor Bard"] = { { name = "Revival tree root", average_rate = "1.8%" }, { name = "Square of spectral crimson", average_rate = "12.5%" } },
  ["Fomor Beastmaster"] = { { name = "Revival tree root", average_rate = "0.83%" } },
  ["Fomor Black Mage"] = { { name = "Revival tree root", average_rate = "13.8%" } },
  ["Fomor Dark Knight"] = { { name = "Extra-fine file", average_rate = "5.6%" }, { name = "Revival tree root", average_rate = "5.6%" } },
  ["Fomor Monk"] = { { name = "Extra-fine file", average_rate = "11.0%" }, { name = "Revival tree root", average_rate = "3.7%" } },
  ["Fomor Ninja"] = { { name = "Revival tree root", average_rate = "1.6%" } },
  ["Fomor Paladin"] = { { name = "Extra-fine file", average_rate = "6.2%" }, { name = "Square of spectral crimson", average_rate = "6.2%" } },
  ["Fomor Ranger"] = { { name = "Revival tree root", average_rate = "0.63%" } },
  ["Fomor Red Mage"] = { { name = "Square of spectral crimson", average_rate = "9.5%" }, { name = "Revival tree root", average_rate = "2.1%" } },
  ["Fomor Samurai"] = { { name = "Extra-fine file", average_rate = "10.7%" }, { name = "Revival tree root", average_rate = "0.76%" } },
  ["Fomor Summoner"] = { { name = "Revival tree root", average_rate = "1.7%" } },
  ["Fomor Thief"] = { { name = "Revival tree root", average_rate = "0.71%" } },
  ["Fomor Warrior"] = { { name = "Revival tree root", average_rate = "1.7%" }, { name = "Extra-fine file", average_rate = "7.3%" } },
  ["Gigantobugard"] = { { name = "Bugard skin", average_rate = "25.9%" }, { name = "Bugard tusk", average_rate = "1.8%" } },
  ["Gigas Braver"] = { { name = "Chameleon diamond", average_rate = "15.6%" }, { name = "Maple shield", average_rate = "3.4%" }, { name = "Gigas necklace", average_rate = "1.1%" } },
  ["Gigas Catapulter"] = { { name = "Chameleon diamond", average_rate = "13.7%" }, { name = "Maple shield", average_rate = "7.8%" }, { name = "Gigas necklace", average_rate = "0.78%" } },
  ["Gigas Fighter"] = { { name = "Chameleon diamond", average_rate = "14.0%" }, { name = "Maple shield", average_rate = "5.4%" }, { name = "Gigas necklace", average_rate = "2.2%" } },
  ["Gigas Martialist"] = { { name = "Maple shield", average_rate = "5.7%" }, { name = "Chameleon diamond", average_rate = "14.2%" }, { name = "Gigas necklace", average_rate = "0.94%" } },
  ["Gigas Slinger"] = { { name = "Maple shield", average_rate = "6.4%" }, { name = "Chameleon diamond", average_rate = "13.9%" } },
  ["Gigas Warwolf"] = { { name = "Chameleon diamond", average_rate = "11.2%" }, { name = "Maple shield", average_rate = "6.0%" }, { name = "Gigas necklace", average_rate = "0.86%" } },
  ["Gigas Wrestler"] = { { name = "Chameleon diamond", average_rate = "19.0%" }, { name = "Maple shield", average_rate = "6.3%" }, { name = "Gigas necklace", average_rate = "3.5%" } },
  ["Grindylow"] = { { name = "Slice of land crab meat", average_rate = "12.0%" }, { name = "Chunk of rock salt", average_rate = "16.0%" } },
  ["Kurrea"] = { { name = "Galliard trousers", average_rate = "100.0%" } },
  ["Leshachikha"] = { { name = "Bag of fruit seeds", average_rate = "7.7%" }, { name = "Treant bulb", average_rate = "40.7%" }, { name = "Bag of grain seeds", average_rate = "2.1%" } },
  ["Leshy"] = { { name = "Dryad root", average_rate = "42.7%" }, { name = "Sprig of mistletoe", average_rate = "20.5%" }, { name = "Puffball", average_rate = "9.9%" }, { name = "Ebony log", average_rate = "0.86%" }, { name = "Mahogany log", average_rate = "0.73%" }, { name = "Rosewood log", average_rate = "1.8%" }, { name = "Petrified log", average_rate = "0.29%" } },
  ["Maze Lurker"] = { { name = "Beetle shell", average_rate = "50.0%" }, { name = "Beetle jaw", average_rate = "50.0%" } },
  ["Megalobugard"] = { { name = "Caitiff's socks", average_rate = "13.0%" }, { name = "Hercules' ring", average_rate = "11.7%" }, { name = "Bugard skin", average_rate = "12.8%" }, { name = "Megalobugard tusk", average_rate = "6.0%" } },
  ["Miner Bee"] = { { name = "Beehive chip", average_rate = "27.9%" }, { name = "Pot of honey", average_rate = "13.9%" }, { name = "Insect wing", average_rate = "6.7%" }, { name = "Giant stinger", average_rate = "2.1%" } },
  ["Orcish Beastrider"] = { { name = "Tavnazian sheep liver", average_rate = "7.9%" } },
  ["Orcish Bowshooter"] = { { name = "Tavnazian sheep liver", average_rate = "8.5%" } },
  ["Orcish Brawler"] = { { name = "Tavnazian sheep liver", average_rate = "5.0%" } },
  ["Orcish Footsoldier"] = { { name = "Tavnazian sheep liver", average_rate = "8.9%" } },
  ["Orcish Gladiator"] = { { name = "Tavnazian sheep liver", average_rate = "3.9%" } },
  ["Orcish Nightraider"] = { { name = "Tavnazian sheep liver", average_rate = "5.3%" } },
  ["Orcish Trooper"] = { { name = "Tavnazian sheep liver", average_rate = "7.6%" } },
  ["Padfoot"] = { { name = "Assailant's ring", average_rate = "19.8%" }, { name = "Sheepskin", average_rate = "70.1%" }, { name = "Lanolin cube", average_rate = "70.0%" }, { name = "Astral earring", average_rate = "12.3%" } },
  ["Sengann"] = { { name = "Square of lineadach", average_rate = "10.7%" } },
  ["Tavnazian Ram"] = { { name = "Ram skin", average_rate = "27.5%" }, { name = "Ram horn", average_rate = "9.5%" }, { name = "Slice of Tavnazian ram meat", average_rate = "36.1%" }, { name = "Lanolin cube", average_rate = "7.3%" } },
  ["Tavnazian Sheep"] = { { name = "Slice of giant sheep meat", average_rate = "22.0%" }, { name = "Sheepskin", average_rate = "14.3%" }, { name = "Tavnazian sheep liver", average_rate = "2.5%" }, { name = "Sheep tooth", average_rate = "3.4%" }, { name = "Jug of Selbina milk", average_rate = "7.7%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "143.7%" } },
  ["Vampire Bat"] = { { name = "Bat fang", average_rate = "50.0%" }, { name = "Bat wing", average_rate = "37.5%" }, { name = "Vial of fiend blood", average_rate = "12.5%" } },
  ["Wingrats"] = { { name = "Bat wing", average_rate = "28.6%" } },
  ["Yal-Un Eke"] = { { name = "Beacon cuffs", average_rate = "8.2%" } },
}
