-- Zone: Misareaux Coast
return {
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "151.3%" } },
  ["Atomic Cluster"] = { { name = "Cluster core", average_rate = "100.0%" }, { name = "Pinch of cluster ash", average_rate = "36.0%" }, { name = "Cluster arm", average_rate = "8.0%" } },
  ["Bigclaw"] = { { name = "Crab shell", average_rate = "17.9%" }, { name = "Slice of land crab meat", average_rate = "36.1%" }, { name = "Sack of silica", average_rate = "8.4%" }, { name = "High-quality crab shell", average_rate = "2.6%" } },
  ["Bugard"] = { { name = "Bugard skin", average_rate = "34.3%" }, { name = "High-quality bugard skin", average_rate = "7.7%" }, { name = "Bugard tusk", average_rate = "2.0%" } },
  ["Clipper"] = { { name = "Chunk of rock salt", average_rate = "40.0%" }, { name = "Slice of land crab meat", average_rate = "40.0%" } },
  ["Crimson Knight Crab"] = { { name = "Slice of land crab meat", average_rate = "47.6%" }, { name = "Crab shell", average_rate = "17.3%" }, { name = "Sack of silica", average_rate = "9.2%" } },
  ["Dark Elemental"] = { { name = "Dark cluster", average_rate = "157.1%" } },
  ["Death Jacket"] = { { name = "Beehive chip", average_rate = "20.2%" }, { name = "Pot of honey", average_rate = "16.0%" }, { name = "Insect wing", average_rate = "8.4%" }, { name = "Giant stinger", average_rate = "1.0%" } },
  ["Diatryma"] = { { name = "Slice of diatryma meat", average_rate = "30.3%" }, { name = "Giant bird feather", average_rate = "16.2%" }, { name = "Giant bird plume", average_rate = "7.6%" } },
  ["Fomor Bard"] = { { name = "Square of spectral crimson", average_rate = "2.8%" }, { name = "Revival tree root", average_rate = "4.2%" } },
  ["Fomor Dark Knight"] = { { name = "Revival tree root", average_rate = "4.2%" } },
  ["Fomor Dragoon"] = { { name = "Revival tree root", average_rate = "1.6%" } },
  ["Fomor Ninja"] = { { name = "Revival tree root", average_rate = "3.6%" } },
  ["Fomor Paladin"] = { { name = "Square of spectral crimson", average_rate = "5.0%" }, { name = "Revival tree root", average_rate = "1.2%" } },
  ["Fomor Red Mage"] = { { name = "Revival tree root", average_rate = "1.5%" }, { name = "Square of spectral crimson", average_rate = "4.5%" } },
  ["Fomor Summoner"] = { { name = "Revival tree root", average_rate = "4.8%" } },
  ["Fomor Thief"] = { { name = "Revival tree root", average_rate = "1.9%" } },
  ["Fomor Warrior"] = { { name = "Revival tree root", average_rate = "10.3%" } },
  ["Gigantobugard"] = { { name = "Bugard skin", average_rate = "48.4%" }, { name = "High-quality bugard skin", average_rate = "16.7%" }, { name = "Bugard tusk", average_rate = "8.1%" } },
  ["Gigas Braver"] = { { name = "Gigas socks", average_rate = "29.1%" }, { name = "Maple shield", average_rate = "15.4%" }, { name = "Gigas necklace", average_rate = "6.3%" } },
  ["Gigas Catapulter"] = { { name = "Gigas socks", average_rate = "37.8%" }, { name = "Gigas necklace", average_rate = "10.9%" }, { name = "Maple shield", average_rate = "19.7%" }, { name = "Gigas bracelets", average_rate = "4.1%" } },
  ["Gigas Martialist"] = { { name = "Gigas socks", average_rate = "25.5%" }, { name = "Gigas necklace", average_rate = "7.5%" }, { name = "Maple shield", average_rate = "15.7%" } },
  ["Gigas Warwolf"] = { { name = "Maple shield", average_rate = "25.0%" }, { name = "Gigas socks", average_rate = "41.5%" }, { name = "Gigas necklace", average_rate = "9.7%" } },
  ["Goaftrap"] = { { name = "Altdorf's earring", average_rate = "10.1%" } },
  ["Gration"] = { { name = "Tatami shield", average_rate = "57.1%" } },
  ["Grindylow"] = { { name = "Chunk of rock salt", average_rate = "18.2%" }, { name = "Slice of land crab meat", average_rate = "27.3%" } },
  ["Makara"] = { { name = "Sack of silica", average_rate = "43.1%" }, { name = "Handful of pugil scales", average_rate = "21.0%" } },
  ["Mantrap"] = { { name = "Bunch of habanero peppers", average_rate = "18.5%" } },
  ["Miner Bee"] = { { name = "Beehive chip", average_rate = "25.6%" }, { name = "Pot of honey", average_rate = "12.5%" }, { name = "Insect wing", average_rate = "8.5%" }, { name = "Giant stinger", average_rate = "1.9%" } },
  ["Odqan"] = { { name = "Cluster core", average_rate = "105.5%" }, { name = "Pinch of cluster ash", average_rate = "23.6%" }, { name = "Atlaua's ring", average_rate = "30.9%" }, { name = "Bravo's subligar", average_rate = "5.5%" } },
  ["Okyupete"] = { { name = "Shepherd's chain", average_rate = "7.7%" } },
  ["Orcish Bowshooter"] = { { name = "Bulb of Misareaux garlic", average_rate = "13.1%" }, { name = "Tavnazian sheep liver", average_rate = "6.9%" } },
  ["Orcish Gladiator"] = { { name = "Bulb of Misareaux garlic", average_rate = "14.3%" } },
  ["Orcish Stonelauncher"] = { { name = "Long boomerang", average_rate = "1.8%" } },
  ["Orcish Trooper"] = { { name = "Bulb of Misareaux garlic", average_rate = "13.1%" } },
  ["Overgrown Rose"] = { { name = "Malboro vine", average_rate = "45.4%" } },
  ["Seaboard Vulture"] = { { name = "Bird egg", average_rate = "14.5%" }, { name = "Bird feather", average_rate = "26.1%" }, { name = "Fire cluster", average_rate = "0.01%" } },
  ["Tavnazian Sheep"] = { { name = "Slice of giant sheep meat", average_rate = "26.6%" }, { name = "Sheepskin", average_rate = "18.7%" }, { name = "Jug of Selbina milk", average_rate = "8.1%" }, { name = "Sheep tooth", average_rate = "4.9%" }, { name = "Tavnazian sheep liver", average_rate = "1.8%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "143.8%" } },
  ["Upyri"] = { { name = "Vampire cloak", average_rate = "103.2%" }, { name = "Vampire earring", average_rate = "7.1%" }, { name = "Vampire boots", average_rate = "44.7%" }, { name = "Vampire mask", average_rate = "42.6%" } },
  ["Vampire Bat"] = { { name = "Bat fang", average_rate = "21.7%" }, { name = "Vial of fiend blood", average_rate = "17.4%" }, { name = "Bat wing", average_rate = "17.4%" } },
  ["Wingrats"] = { { name = "Bat wing", average_rate = "36.0%" }, { name = "Bat fang", average_rate = "12.0%" }, { name = "Vial of fiend blood", average_rate = "4.0%" } },
  ["Ziphius"] = { { name = "Hospitaler earring", average_rate = "43.1%" } },
}
