-- Zone: Yahse Hunting Grounds
return {
  ["Alluring Orobon"] = { { name = "Orobon lure", average_rate = "39.8%" } },
  ["Beady Panopt"] = { { name = "Bottle of panopt tears", average_rate = "8.9%" }, { name = "Sacred Kindred's crest", average_rate = "2.6%" } },
  ["Bight Uragnite"] = { { name = "Seashell", average_rate = "50.8%" }, { name = "Uragnite shell", average_rate = "10.1%" }, { name = "Sacred Kindred's crest", average_rate = "5.3%" } },
  ["Bothersome Chapuli"] = { { name = "Chapuli wing", average_rate = "13.6%" }, { name = "Chapuli horn", average_rate = "8.1%" } },
  ["Broad Scarlet"] = { { name = "Insect wing", average_rate = "47.1%" }, { name = "Sacred Kindred's crest", average_rate = "1.6%" } },
  ["Burning Mantis"] = { { name = "Mantid carapace", average_rate = "9.3%" }, { name = "Sacred Kindred's crest", average_rate = "1.7%" } },
  ["Calfcleaving Chapuli"] = { { name = "Chapuli wing", average_rate = "3.2%" }, { name = "Chapuli horn", average_rate = "1.5%" }, { name = "Sacred Kindred's crest", average_rate = "0.25%" } },
  ["Canopycrusher Beetle"] = { { name = "Beetle jaw", average_rate = "9.2%" }, { name = "Insect wing", average_rate = "48.2%" }, { name = "Beetle shell", average_rate = "19.8%" }, { name = "Sacred Kindred's crest", average_rate = "1.7%" } },
  ["Crusty Crab"] = { { name = "Slice of land crab meat", average_rate = "38.1%" }, { name = "Crab shell", average_rate = "33.3%" }, { name = "Sacred Kindred's crest", average_rate = "4.8%" } },
  ["Edacious Orobon"] = { { name = "Orobon lure", average_rate = "54.7%" }, { name = "Chunk of orobon meat", average_rate = "10.6%" }, { name = "Sacred Kindred's crest", average_rate = "5.5%" } },
  ["Fiery Wasp"] = { { name = "Giant stinger", average_rate = "2.6%" }, { name = "Insect wing", average_rate = "9.3%" }, { name = "Beehive chip", average_rate = "47.4%" }, { name = "Pot of honey", average_rate = "19.4%" }, { name = "Sacred Kindred's crest", average_rate = "1.7%" } },
  ["Frondescent Leafkin"] = { { name = "Sacred Kindred's crest", average_rate = "1.2%" } },
  ["Hinterland Peiste"] = { { name = "Peiste stinger", average_rate = "21.9%" }, { name = "Peiste skin", average_rate = "10.4%" }, { name = "Sacred Kindred's crest", average_rate = "1.7%" } },
  ["Jungle Baelfyr"] = { { name = "Sacred Kindred's crest", average_rate = "3.1%" } },
  ["Luckybug Hoarder"] = { { name = "Ladybug wing", average_rate = "64.6%" }, { name = "Sacred Kindred's crest", average_rate = "2.6%" } },
  ["Monstrosiraptor"] = { { name = "Raptor skin", average_rate = "20.0%" }, { name = "Sacred Kindred's crest", average_rate = "1.7%" } },
  ["Nettled Wasp"] = { { name = "Beehive chip", average_rate = "50.5%" }, { name = "Insect wing", average_rate = "9.7%" }, { name = "Pot of honey", average_rate = "20.7%" }, { name = "Giant stinger", average_rate = "2.8%" }, { name = "Sacred Kindred's crest", average_rate = "1.8%" } },
  ["Pinetorum"] = { { name = "Two-leaf mandragora bud", average_rate = "4.9%" }, { name = "Clump of Yahse humus", average_rate = "21.0%" }, { name = "Sacred Kindred's crest", average_rate = "2.2%" } },
  ["Shy Heartwing"] = { { name = "Sacred Kindred's crest", average_rate = "1.4%" } },
  ["Twitherym Infestation"] = { { name = "Twitherym wing", average_rate = "1.6%" }, { name = "Sacred Kindred's crest", average_rate = "0.28%" } },
  ["Ulbukan Sheep"] = { { name = "Sheepskin", average_rate = "27.9%" }, { name = "Slice of giant sheep meat", average_rate = "65.1%" }, { name = "Sheep tooth", average_rate = "12.8%" }, { name = "Sacred Kindred's crest", average_rate = "2.2%" } },
  ["Umbril"] = { { name = "Leafkin frond", average_rate = "9.1%" }, { name = "Jar of umbril ooze", average_rate = "9.4%" }, { name = "Sacred Kindred's crest", average_rate = "1.9%" } },
  ["Velkk Marauder"] = { { name = "Velkk necklace", average_rate = "19.1%" }, { name = "Sacred Kindred's crest", average_rate = "1.9%" } },
  ["Verdant Treant"] = { { name = "Dryad root", average_rate = "46.3%" }, { name = "Sprig of mistletoe", average_rate = "20.4%" }, { name = "Puffball", average_rate = "7.0%" }, { name = "Mahogany log", average_rate = "0.67%" }, { name = "Sacred Kindred's crest", average_rate = "4.3%" }, { name = "Ebony log", average_rate = "0.45%" }, { name = "Rosewood log", average_rate = "0.67%" }, { name = "Petrified log", average_rate = "0.22%" } },
  ["Wooded Ungeweder"] = { { name = "Sacred Kindred's crest", average_rate = "2.5%" } },
}
