-- Zone: Phomiuna Aqueducts
return {
  ["Addled Tumor"] = { { name = "Undead skin", average_rate = "23.4%" } },
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "162.9%" } },
  ["Aqueduct Spider"] = { { name = "Water spider's web", average_rate = "24.4%" }, { name = "Earth cluster", average_rate = "0.01%" } },
  ["Big Jaw"] = { { name = "Sack of silica", average_rate = "32.1%" }, { name = "Handful of pugil scales", average_rate = "15.2%" } },
  ["Canal Bats"] = { { name = "Bat wing", average_rate = "36.4%" }, { name = "Vial of fiend blood", average_rate = "10.2%" }, { name = "Bat fang", average_rate = "15.3%" }, { name = "Vial of beastman blood", average_rate = "1.7%" } },
  ["Dark Elemental"] = { { name = "Dark cluster", average_rate = "146.2%" } },
  ["Diremite"] = { { name = "Spool of bloodthread", average_rate = "21.8%" }, { name = "Bottle of avatar blood", average_rate = "3.6%" } },
  ["Duendes' Amoroso"] = { { name = "Revival tree root", average_rate = "2.3%" } },
  ["Eba"] = { { name = "Fomor tunic", average_rate = "57.0%" } },
  ["Fomor Bard"] = { { name = "Bronze key", average_rate = "7.9%" }, { name = "Libra subligar", average_rate = "29.1%" }, { name = "Revival tree root", average_rate = "1.3%" } },
  ["Fomor Beastmaster"] = { { name = "Ophiuchus subligar", average_rate = "31.5%" }, { name = "Bronze key", average_rate = "8.6%" }, { name = "Revival tree root", average_rate = "1.1%" } },
  ["Fomor Black Mage"] = { { name = "Aries subligar", average_rate = "29.6%" }, { name = "Revival tree root", average_rate = "2.6%" } },
  ["Fomor Dark Knight"] = { { name = "Sagittarius subligar", average_rate = "26.5%" }, { name = "Bronze key", average_rate = "6.7%" }, { name = "Revival tree root", average_rate = "1.9%" } },
  ["Fomor Dragoon"] = { { name = "Leo subligar", average_rate = "29.4%" }, { name = "Revival tree root", average_rate = "2.1%" }, { name = "Bronze key", average_rate = "7.6%" }, { name = "Dark cluster", average_rate = "0.07%" } },
  ["Fomor Monk"] = { { name = "Revival tree root", average_rate = "2.0%" }, { name = "Bronze key", average_rate = "15.5%" }, { name = "Aquarius subligar", average_rate = "24.9%" } },
  ["Fomor Ninja"] = { { name = "Taurus subligar", average_rate = "27.4%" }, { name = "Bronze key", average_rate = "6.6%" }, { name = "Shakudo ingot", average_rate = "35.0%" }, { name = "Revival tree root", average_rate = "2.3%" } },
  ["Fomor Paladin"] = { { name = "Pisces subligar", average_rate = "32.2%" }, { name = "Bronze key", average_rate = "7.7%" }, { name = "Revival tree root", average_rate = "2.3%" } },
  ["Fomor Ranger"] = { { name = "Square of balloon cloth", average_rate = "29.8%" }, { name = "Bronze key", average_rate = "6.2%" }, { name = "Virgo subligar", average_rate = "5.5%" }, { name = "Revival tree root", average_rate = "2.5%" } },
  ["Fomor Red Mage"] = { { name = "Scorpius subligar", average_rate = "33.0%" }, { name = "Bronze key", average_rate = "8.6%" }, { name = "Revival tree root", average_rate = "2.3%" } },
  ["Fomor Samurai"] = { { name = "Cancer subligar", average_rate = "29.7%" }, { name = "Shakudo ingot", average_rate = "34.6%" }, { name = "Bronze key", average_rate = "5.8%" }, { name = "Revival tree root", average_rate = "2.9%" } },
  ["Fomor Summoner"] = { { name = "Capricornus subligar", average_rate = "34.1%" }, { name = "Bronze key", average_rate = "4.3%" }, { name = "Revival tree root", average_rate = "2.9%" } },
  ["Fomor Thief"] = { { name = "Square of balloon cloth", average_rate = "40.9%" }, { name = "Bronze key", average_rate = "6.6%" }, { name = "Gemini subligar", average_rate = "29.1%" }, { name = "Revival tree root", average_rate = "3.0%" }, { name = "Dark cluster", average_rate = "0.10%" } },
  ["Fomor Warrior"] = { { name = "Bronze key", average_rate = "7.7%" }, { name = "Revival tree root", average_rate = "2.2%" } },
  ["Foul Meat"] = { { name = "Undead skin", average_rate = "20.9%" } },
  ["Gloop"] = { { name = "Vial of slime oil", average_rate = "22.9%" } },
  ["Hell Bat"] = { { name = "Bat wing", average_rate = "30.2%" }, { name = "Bat fang", average_rate = "15.1%" }, { name = "Vial of fiend blood", average_rate = "7.3%" }, { name = "Vial of beastman blood", average_rate = "3.0%" } },
  ["Mahisha"] = { { name = "Sinister mask", average_rate = "47.5%" } },
  ["Makara"] = { { name = "Sack of silica", average_rate = "38.5%" }, { name = "Handful of pugil scales", average_rate = "13.5%" } },
  ["Maze Lurker"] = { { name = "Water cluster", average_rate = "100.0%" } },
  ["Oil Spill"] = { { name = "Vial of slime oil", average_rate = "22.5%" } },
  ["Stegotaur"] = { { name = "Fomor codex", average_rate = "6.1%" }, { name = "Taurus horn", average_rate = "7.4%" }, { name = "Piece of spruce lumber", average_rate = "12.5%" } },
  ["Taurus"] = { { name = "Taurus horn", average_rate = "6.1%" }, { name = "Piece of spruce lumber", average_rate = "11.9%" }, { name = "Fomor codex", average_rate = "6.7%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "163.6%" } },
  ["Tres Duendes"] = { { name = "Vampiric claws", average_rate = "49.8%" }, { name = "Niokiyotsuna", average_rate = "50.2%" }, { name = "Chiroptera dagger", average_rate = "50.9%" } },
  ["Vampire Bat"] = { { name = "Bat wing", average_rate = "25.0%" }, { name = "Bat fang", average_rate = "13.9%" }, { name = "Vial of fiend blood", average_rate = "10.2%" }, { name = "Vial of beastman blood", average_rate = "1.9%" } },
}
