-- Zone: Outer Ra'Kaznar
return {
  ["Apex Bat"] = { { name = "Sacred Kindred's crest", average_rate = "21.7%" } },
  ["Astringent Acuex"] = { { name = "Jar of acuex poison", average_rate = "19.1%" }, { name = "Sacred Kindred's crest", average_rate = "1.1%" } },
  ["Bristlehair Bat"] = { { name = "Bat wing", average_rate = "70.0%" }, { name = "Bat fang", average_rate = "52.6%" }, { name = "Vial of fiend blood", average_rate = "10.4%" }, { name = "Sacred Kindred's crest", average_rate = "3.2%" } },
  ["Debauched Unseelie"] = { { name = "Sacred Kindred's crest", average_rate = "2.2%" } },
  ["Dreadhound"] = { { name = "Wolf hide", average_rate = "50.6%" }, { name = "Revival tree root", average_rate = "21.4%" }, { name = "Sacred Kindred's crest", average_rate = "2.2%" } },
  ["Dullahan"] = { { name = "Suit of dullahan armor", average_rate = "18.9%" }, { name = "Sacred Kindred's crest", average_rate = "0.95%" } },
  ["Enshrouded Cyhiraeth"] = { { name = "Sacred Kindred's crest", average_rate = "1.9%" } },
  ["Fluturini"] = { { name = "Twitherym wing", average_rate = "21.5%" }, { name = "Sacred Kindred's crest", average_rate = "1.6%" } },
  ["Horrific Bhoot"] = { { name = "Square of mohbwa cloth", average_rate = "53.4%" }, { name = "Luminicloth", average_rate = "13.8%" }, { name = "Revival tree root", average_rate = "19.8%" }, { name = "Sacred Kindred's crest", average_rate = "1.7%" } },
  ["Ironclad"] = { { name = "Sacred Kindred's crest", average_rate = "3.0%" } },
  ["Legionless Draugar"] = { { name = "Bone chip", average_rate = "70.6%" }, { name = "Sacred Kindred's crest", average_rate = "2.0%" } },
  ["Obfuscous Obdella"] = { { name = "Vial of fiend blood", average_rate = "46.5%" }, { name = "Sacred Kindred's crest", average_rate = "1.4%" } },
  ["Phlegmatic Byrgen"] = { { name = "Sacred Kindred's crest", average_rate = "2.3%" } },
  ["Restless Twitherym"] = { { name = "Twitherym wing", average_rate = "21.9%" }, { name = "Sacred Kindred's crest", average_rate = "2.0%" } },
  ["Shunned Deeparrow"] = { { name = "Revival tree root", average_rate = "49.6%" }, { name = "Square of ancestral cloth", average_rate = "21.1%" }, { name = "Sacred Kindred's crest", average_rate = "1.6%" }, { name = "Vial of befouled water", average_rate = "0.40%" } },
  ["Shunned Elementalist"] = { { name = "Revival tree root", average_rate = "53.1%" }, { name = "Square of ancestral cloth", average_rate = "22.0%" }, { name = "Sacred Kindred's crest", average_rate = "2.5%" }, { name = "Vial of befouled water", average_rate = "1.1%" } },
  ["Shunned Engraver"] = { { name = "Sacred Kindred's crest", average_rate = "3.7%" }, { name = "Square of ancestral cloth", average_rate = "26.0%" }, { name = "Revival tree root", average_rate = "51.8%" }, { name = "Vial of befouled water", average_rate = "2.5%" } },
  ["Shunned Fluteslinger"] = { { name = "Revival tree root", average_rate = "47.7%" }, { name = "Square of ancestral cloth", average_rate = "20.3%" }, { name = "Sacred Kindred's crest", average_rate = "2.7%" }, { name = "Vial of befouled water", average_rate = "0.19%" } },
  ["Shunned Harpslinger"] = { { name = "Square of ancestral cloth", average_rate = "20.0%" }, { name = "Revival tree root", average_rate = "57.8%" }, { name = "Sacred Kindred's crest", average_rate = "2.2%" } },
  ["Shunned Hexer"] = { { name = "Revival tree root", average_rate = "49.4%" }, { name = "Square of ancestral cloth", average_rate = "21.4%" }, { name = "Sacred Kindred's crest", average_rate = "2.0%" }, { name = "Vial of befouled water", average_rate = "0.81%" } },
  ["Shunned Nightstalker"] = { { name = "Revival tree root", average_rate = "49.9%" }, { name = "Sacred Kindred's crest", average_rate = "1.8%" }, { name = "Square of ancestral cloth", average_rate = "20.8%" }, { name = "Vial of befouled water", average_rate = "0.62%" } },
  ["Shunned Saboteur"] = { { name = "Revival tree root", average_rate = "48.6%" }, { name = "Square of ancestral cloth", average_rate = "23.3%" }, { name = "Sacred Kindred's crest", average_rate = "2.0%" }, { name = "Vial of befouled water", average_rate = "0.40%" } },
  ["Shunned Valiant"] = { { name = "Square of ancestral cloth", average_rate = "23.7%" }, { name = "Revival tree root", average_rate = "61.8%" }, { name = "Sacred Kindred's crest", average_rate = "3.6%" }, { name = "Vial of befouled water", average_rate = "0.89%" } },
  ["Undulating Umbril"] = { { name = "Jar of umbril ooze", average_rate = "54.1%" }, { name = "Sacred Kindred's crest", average_rate = "3.5%" }, { name = "Leafkin frond", average_rate = "10.5%" } },
}
