-- Zone: Outer Ra'Kaznar [U]
return {
  ["Air Elemental"] = { { name = "Etched memory", average_rate = "23.8%" }, { name = "Codex of etchings", average_rate = "3.3%" } },
  ["Blightslither"] = { { name = "Supay weskit", average_rate = "74.1%" }, { name = "Codex of etchings", average_rate = "123.9%" }, { name = "Umbra strap", average_rate = "78.6%" } },
  ["Breathless Clansman"] = { { name = "Sacred Kindred's crest", average_rate = "2.7%" } },
  ["Brimboil"] = { { name = "Meekculler", average_rate = "23.3%" }, { name = "Codex of etchings", average_rate = "36.2%" }, { name = "Deviant necklace", average_rate = "20.2%" } },
  ["Burnished Mimic"] = { { name = "Sacred Kindred's crest", average_rate = "2.0%" } },
  ["Conniving Gefyrst"] = { { name = "Etched memory", average_rate = "24.9%" }, { name = "Codex of etchings", average_rate = "2.3%" } },
  ["Corrupt Baelfyr"] = { { name = "Etched memory", average_rate = "26.5%" }, { name = "Codex of etchings", average_rate = "3.4%" } },
  ["Dark Elemental"] = { { name = "Codex of etchings", average_rate = "3.1%" }, { name = "Etched memory", average_rate = "29.6%" } },
  ["Disdained One"] = { { name = "Focal orb", average_rate = "13.0%" }, { name = "Limbo trousers", average_rate = "12.9%" }, { name = "Codex of etchings", average_rate = "12.6%" } },
  ["Dismal Djinn"] = { { name = "Sacred Kindred's crest", average_rate = "2.6%" } },
  ["Dreary Obdella"] = { { name = "Etched memory", average_rate = "28.9%" }, { name = "Codex of etchings", average_rate = "4.2%" } },
  ["Earth Elemental"] = { { name = "Etched memory", average_rate = "25.8%" }, { name = "Codex of etchings", average_rate = "4.5%" } },
  ["Effluvial Acuex"] = { { name = "Sacred Kindred's crest", average_rate = "2.2%" } },
  ["Fire Elemental"] = { { name = "Etched memory", average_rate = "23.9%" }, { name = "Codex of etchings", average_rate = "3.4%" } },
  ["Gangrenous Leech"] = { { name = "Etched memory", average_rate = "28.3%" }, { name = "Codex of etchings", average_rate = "4.1%" } },
  ["Ice Elemental"] = { { name = "Codex of etchings", average_rate = "3.8%" }, { name = "Etched memory", average_rate = "25.4%" } },
  ["Insidious Ungeweder"] = { { name = "Etched memory", average_rate = "25.4%" }, { name = "Codex of etchings", average_rate = "2.8%" } },
  ["Insidivo"] = { { name = "Vengeful ring", average_rate = "72.9%" }, { name = "Avatara slops", average_rate = "77.7%" }, { name = "Codex of etchings", average_rate = "126.5%" } },
  ["Jaundiced Slime"] = { { name = "Etched memory", average_rate = "28.1%" }, { name = "Codex of etchings", average_rate = "3.6%" } },
  ["Light Elemental"] = { { name = "Codex of etchings", average_rate = "3.7%" }, { name = "Etched memory", average_rate = "28.9%" } },
  ["Lightreaper"] = { { name = "Famine sash", average_rate = "78.3%" }, { name = "Codex of etchings", average_rate = "127.1%" }, { name = "Feast hose", average_rate = "77.3%" } },
  ["Murkcrawler"] = { { name = "Rabid visor", average_rate = "67.3%" }, { name = "Codex of etchings", average_rate = "125.6%" }, { name = "Brahmastra", average_rate = "84.8%" } },
  ["Palloritus"] = { { name = "Defiant collar", average_rate = "38.2%" }, { name = "Punchinellos", average_rate = "35.4%" }, { name = "Defiant scarf", average_rate = "143.1%" }, { name = "Vial of defiant sweat", average_rate = "270.8%" }, { name = "Rhadamanthus", average_rate = "33.3%" }, { name = "Achiuchikapu", average_rate = "46.5%" } },
  ["Perfidien"] = { { name = "Count's cuffs", average_rate = "38.9%" }, { name = "Tartarian chain", average_rate = "255.0%" }, { name = "Tartarian soul", average_rate = "134.4%" }, { name = "Count's garb", average_rate = "40.6%" }, { name = "Enervating earring", average_rate = "37.2%" }, { name = "Etiolation earring", average_rate = "27.2%" } },
  ["Plouton"] = { { name = "Incarnation sash", average_rate = "43.2%" }, { name = "Hades' claw", average_rate = "140.5%" }, { name = "Chunk of dark matter", average_rate = "269.3%" }, { name = "Befouled crown", average_rate = "37.5%" }, { name = "Odium", average_rate = "60.6%" }, { name = "Tartarus platemail", average_rate = "1.9%" } },
  ["Psychotic Gefyrst"] = { { name = "Etched memory", average_rate = "20.7%" }, { name = "Codex of etchings", average_rate = "3.8%" } },
  ["Putraxia"] = { { name = "Macuil plating", average_rate = "139.9%" }, { name = "Soulcleaver", average_rate = "27.8%" }, { name = "Macuil horn", average_rate = "271.5%" }, { name = "Rumination sash", average_rate = "50.0%" }, { name = "Acclimator", average_rate = "43.7%" }, { name = "Crusher's gauntlets", average_rate = "40.5%" } },
  ["Rancibus"] = { { name = "Chunk of plovid flesh", average_rate = "132.4%" }, { name = "Vial of plovid effluvium", average_rate = "258.3%" }, { name = "Cryptic earring", average_rate = "55.4%" }, { name = "Devivifier", average_rate = "28.8%" }, { name = "Miasmic pants", average_rate = "35.3%" }, { name = "Mindmelter", average_rate = "29.5%" } },
  ["Ravaging Acuex"] = { { name = "Etched memory", average_rate = "29.9%" }, { name = "Codex of etchings", average_rate = "4.0%" } },
  ["Reckless Ungeweder"] = { { name = "Etched memory", average_rate = "24.5%" }, { name = "Codex of etchings", average_rate = "2.9%" } },
  ["Shunned Deeparrow"] = { { name = "Etched memory", average_rate = "22.8%" }, { name = "Codex of etchings", average_rate = "1.8%" } },
  ["Shunned Elementalist"] = { { name = "Etched memory", average_rate = "25.0%" }, { name = "Codex of etchings", average_rate = "3.2%" } },
  ["Shunned Engraver"] = { { name = "Etched memory", average_rate = "22.4%" }, { name = "Codex of etchings", average_rate = "4.7%" } },
  ["Shunned Fluteslinger"] = { { name = "Etched memory", average_rate = "24.1%" }, { name = "Codex of etchings", average_rate = "3.4%" } },
  ["Shunned Hexer"] = { { name = "Etched memory", average_rate = "23.3%" }, { name = "Codex of etchings", average_rate = "3.9%" } },
  ["Shunned Nightstalker"] = { { name = "Etched memory", average_rate = "23.3%" }, { name = "Codex of etchings", average_rate = "2.2%" } },
  ["Shunned Saboteur"] = { { name = "Etched memory", average_rate = "25.2%" }, { name = "Codex of etchings", average_rate = "4.2%" } },
  ["Shunned Valiant"] = { { name = "Etched memory", average_rate = "24.2%" }, { name = "Codex of etchings", average_rate = "2.5%" } },
  ["Spiteful Byrgen"] = { { name = "Etched memory", average_rate = "28.1%" }, { name = "Codex of etchings", average_rate = "2.9%" } },
  ["Splenetic Umbril"] = { { name = "Sacred Kindred's crest", average_rate = "2.2%" } },
  ["Spurned Deeparrow"] = { { name = "Etched memory", average_rate = "16.9%" }, { name = "Codex of etchings", average_rate = "1.8%" } },
  ["Spurned Elementalist"] = { { name = "Etched memory", average_rate = "18.5%" }, { name = "Codex of etchings", average_rate = "3.1%" } },
  ["Spurned Engraver"] = { { name = "Codex of etchings", average_rate = "4.9%" }, { name = "Etched memory", average_rate = "20.9%" } },
  ["Spurned Fluteslinger"] = { { name = "Etched memory", average_rate = "18.9%" }, { name = "Codex of etchings", average_rate = "5.5%" } },
  ["Spurned Hexer"] = { { name = "Etched memory", average_rate = "25.0%" }, { name = "Codex of etchings", average_rate = "3.0%" } },
  ["Spurned Nightstalker"] = { { name = "Codex of etchings", average_rate = "4.4%" }, { name = "Etched memory", average_rate = "33.8%" } },
  ["Spurned Saboteur"] = { { name = "Etched memory", average_rate = "24.2%" }, { name = "Codex of etchings", average_rate = "2.5%" } },
  ["Spurned Valiant"] = { { name = "Etched memory", average_rate = "26.7%" }, { name = "Codex of etchings", average_rate = "3.6%" } },
  ["Thunder Elemental"] = { { name = "Etched memory", average_rate = "27.9%" }, { name = "Codex of etchings", average_rate = "3.0%" } },
  ["Unabated Mush"] = { { name = "Etched memory", average_rate = "29.9%" }, { name = "Codex of etchings", average_rate = "3.8%" } },
  ["Vile Byrgen"] = { { name = "Etched memory", average_rate = "23.8%" }, { name = "Codex of etchings", average_rate = "3.7%" } },
  ["Wailing Corse"] = { { name = "Etched memory", average_rate = "31.6%" }, { name = "Codex of etchings", average_rate = "3.5%" } },
  ["Water Elemental"] = { { name = "Etched memory", average_rate = "21.4%" }, { name = "Codex of etchings", average_rate = "4.0%" } },
  ["Wicked Baelfyr"] = { { name = "Etched memory", average_rate = "26.1%" }, { name = "Codex of etchings", average_rate = "1.9%" } },
}
