-- Zone: Ra'Kaznar Inner Court
return {
  ["Bilespouting Acuex"] = { { name = "Jar of acuex poison", average_rate = "26.7%" }, { name = "Sacred Kindred's crest", average_rate = "7.1%" } },
  ["Boilridden Umbril"] = { { name = "Sacred Kindred's crest", average_rate = "20.2%" }, { name = "Jar of umbril ooze", average_rate = "40.4%" }, { name = "Leafkin frond", average_rate = "6.7%" } },
  ["Deserter Draugar"] = { { name = "Bone chip", average_rate = "78.4%" }, { name = "Sacred Kindred's crest", average_rate = "5.2%" } },
  ["Disheveled Naraka"] = { { name = "Sacred Kindred's crest", average_rate = "25.0%" } },
  ["Dolorous Cyhiraeth"] = { { name = "Sacred Kindred's crest", average_rate = "7.7%" } },
  ["Doorlock Effect"] = { { name = "Twitherym wing", average_rate = "12.5%" } },
  ["Draftdance Fluturini"] = { { name = "Twitherym wing", average_rate = "15.3%" }, { name = "Sacred Kindred's crest", average_rate = "5.1%" } },
  ["Dullahan Axegrinder"] = { { name = "Sacred Kindred's crest", average_rate = "10.2%" }, { name = "Suit of dullahan armor", average_rate = "17.7%" } },
  ["Enigmatic Vampyr"] = { { name = "Sacred Kindred's crest", average_rate = "22.7%" } },
  ["Inimical Corse"] = { { name = "Corse bracelet", average_rate = "100.0%" } },
  ["Ironclad Animus"] = { { name = "Sacred Kindred's crest", average_rate = "14.2%" } },
  ["Ironclad Wrecker"] = { { name = "Sacred Kindred's crest", average_rate = "100.0%" } },
  ["Jgl_build_master_0"] = { { name = "Wolf hide", average_rate = "50.0%" }, { name = "Revival tree root", average_rate = "16.7%" } },
  ["Jgl_build_master_1"] = { { name = "Bone chip", average_rate = "100.0%" } },
  ["Jgl_build_master_2"] = { { name = "Bone chip", average_rate = "50.0%" } },
  ["Jgl_build_master_3"] = { { name = "Bone chip", average_rate = "33.3%" }, { name = "Sacred Kindred's crest", average_rate = "66.7%" } },
  ["Moogle"] = { { name = "Sacred Kindred's crest", average_rate = "10.0%" }, { name = "Revival tree root", average_rate = "30.0%" } },
  ["Poxhound"] = { { name = "Wolf hide", average_rate = "51.8%" }, { name = "Revival tree root", average_rate = "26.3%" }, { name = "Sacred Kindred's crest", average_rate = "9.6%" } },
  ["Scowling Vodoriga"] = { { name = "Gargouille eye", average_rate = "26.8%" }, { name = "Gargouille shank", average_rate = "59.5%" }, { name = "Iridium ingot", average_rate = "12.2%" }, { name = "Sacred Kindred's crest", average_rate = "17.0%" }, { name = "Gargouille horn", average_rate = "3.1%" } },
  ["Slimeskin Obdella"] = { { name = "Vial of fiend blood", average_rate = "45.2%" }, { name = "Sacred Kindred's crest", average_rate = "3.2%" } },
  ["Soul Pyre"] = { { name = "Revival tree root", average_rate = "40.0%" }, { name = "Sacred Kindred's crest", average_rate = "20.0%" } },
  ["Spurned Deeparrow"] = { { name = "Revival tree root", average_rate = "46.0%" }, { name = "Sacred Kindred's crest", average_rate = "10.3%" }, { name = "Vial of befouled water", average_rate = "0.79%" } },
  ["Spurned Elementalist"] = { { name = "Revival tree root", average_rate = "55.2%" }, { name = "Sacred Kindred's crest", average_rate = "12.8%" }, { name = "Vial of befouled water", average_rate = "3.2%" } },
  ["Spurned Engraver"] = { { name = "Revival tree root", average_rate = "43.3%" }, { name = "Sacred Kindred's crest", average_rate = "12.5%" }, { name = "Vial of befouled water", average_rate = "11.7%" } },
  ["Spurned Fluteslinger"] = { { name = "Revival tree root", average_rate = "53.4%" }, { name = "Sacred Kindred's crest", average_rate = "18.1%" }, { name = "Vial of befouled water", average_rate = "6.0%" } },
  ["Spurned Hexer"] = { { name = "Revival tree root", average_rate = "48.4%" }, { name = "Sacred Kindred's crest", average_rate = "8.2%" }, { name = "Vial of befouled water", average_rate = "4.4%" } },
  ["Spurned Nightstalker"] = { { name = "Revival tree root", average_rate = "41.7%" }, { name = "Sacred Kindred's crest", average_rate = "10.2%" }, { name = "Vial of befouled water", average_rate = "2.4%" } },
  ["Spurned Saboteur"] = { { name = "Revival tree root", average_rate = "55.4%" }, { name = "Sacred Kindred's crest", average_rate = "11.9%" } },
  ["Spurned Valiant"] = { { name = "Sacred Kindred's crest", average_rate = "10.7%" }, { name = "Revival tree root", average_rate = "53.6%" }, { name = "Vial of befouled water", average_rate = "2.4%" } },
  ["Unrepentant Byrgen"] = { { name = "Sacred Kindred's crest", average_rate = "19.4%" } },
  ["Wayward Bhoot"] = { { name = "Square of cotton cloth", average_rate = "33.3%" }, { name = "Luminicloth", average_rate = "33.3%" } },
  ["Whitenoise Bats"] = { { name = "Bat wing", average_rate = "65.5%" }, { name = "Vial of fiend blood", average_rate = "20.0%" }, { name = "Bat fang", average_rate = "60.0%" }, { name = "Sacred Kindred's crest", average_rate = "12.7%" } },
}
