-- Zone: Sacrarium
return {
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "193.2%" } },
  ["Aqueduct Spider"] = { { name = "Water spider's web", average_rate = "26.1%" } },
  ["Balor"] = { { name = "Swift belt", average_rate = "45.2%" } },
  ["Blubber Eyes"] = { { name = "Vial of mercury", average_rate = "59.4%" }, { name = "Hecteyes eye", average_rate = "10.9%" } },
  ["Caithleann"] = { { name = "Swift belt", average_rate = "32.6%" } },
  ["Dark Elemental"] = { { name = "Dark cluster", average_rate = "163.2%" } },
  ["Elel"] = { { name = "Corse bracelet", average_rate = "102.2%" }, { name = "Magical mitts", average_rate = "39.0%" }, { name = "Corse robe", average_rate = "25.7%" }, { name = "Frenzy sallet", average_rate = "11.0%" } },
  ["Fomor Bard"] = { { name = "Coral crest key", average_rate = "11.0%" }, { name = "Sacrarium chest key", average_rate = "4.3%" }, { name = "Libra subligar", average_rate = "6.9%" }, { name = "Revival tree root", average_rate = "2.1%" } },
  ["Fomor Beastmaster"] = { { name = "Coral crest key", average_rate = "11.0%" }, { name = "Revival tree root", average_rate = "2.5%" }, { name = "Ophiuchus subligar", average_rate = "9.5%" }, { name = "Sacrarium chest key", average_rate = "3.9%" } },
  ["Fomor Black Mage"] = { { name = "Aries subligar", average_rate = "7.7%" }, { name = "Coral crest key", average_rate = "10.5%" }, { name = "Revival tree root", average_rate = "2.4%" }, { name = "Sacrarium chest key", average_rate = "3.7%" } },
  ["Fomor Dark Knight"] = { { name = "Sagittarius subligar", average_rate = "27.2%" }, { name = "Sacrarium chest key", average_rate = "3.7%" }, { name = "Revival tree root", average_rate = "2.1%" }, { name = "Coral crest key", average_rate = "5.2%" } },
  ["Fomor Dragoon"] = { { name = "Leo subligar", average_rate = "8.2%" }, { name = "Coral crest key", average_rate = "8.4%" }, { name = "Revival tree root", average_rate = "2.3%" }, { name = "Sacrarium chest key", average_rate = "2.9%" }, { name = "Dark cluster", average_rate = "0.17%" } },
  ["Fomor Monk"] = { { name = "Coral crest key", average_rate = "11.9%" }, { name = "Aquarius subligar", average_rate = "7.7%" }, { name = "Sacrarium chest key", average_rate = "3.7%" }, { name = "Revival tree root", average_rate = "2.6%" } },
  ["Fomor Ninja"] = { { name = "Shakudo ingot", average_rate = "71.6%" }, { name = "Sacrarium chest key", average_rate = "6.7%" }, { name = "Taurus subligar", average_rate = "7.2%" }, { name = "Coral crest key", average_rate = "12.3%" } },
  ["Fomor Paladin"] = { { name = "Coral crest key", average_rate = "10.1%" }, { name = "Revival tree root", average_rate = "1.7%" }, { name = "Pisces subligar", average_rate = "8.3%" }, { name = "Sacrarium chest key", average_rate = "3.4%" } },
  ["Fomor Ranger"] = { { name = "Revival tree root", average_rate = "5.0%" }, { name = "Coral crest key", average_rate = "10.6%" }, { name = "Square of balloon cloth", average_rate = "32.2%" }, { name = "Virgo subligar", average_rate = "5.3%" }, { name = "Sacrarium chest key", average_rate = "4.6%" } },
  ["Fomor Red Mage"] = { { name = "Scorpius subligar", average_rate = "8.6%" }, { name = "Coral crest key", average_rate = "11.0%" }, { name = "Sacrarium chest key", average_rate = "5.2%" }, { name = "Revival tree root", average_rate = "2.4%" } },
  ["Fomor Samurai"] = { { name = "Shakudo ingot", average_rate = "66.6%" }, { name = "Cancer subligar", average_rate = "7.8%" }, { name = "Coral crest key", average_rate = "11.7%" }, { name = "Sacrarium chest key", average_rate = "4.6%" } },
  ["Fomor Summoner"] = { { name = "Sacrarium chest key", average_rate = "4.8%" }, { name = "Capricornus subligar", average_rate = "7.2%" }, { name = "Revival tree root", average_rate = "2.9%" }, { name = "Coral crest key", average_rate = "10.3%" } },
  ["Fomor Thief"] = { { name = "Square of balloon cloth", average_rate = "66.1%" }, { name = "Gemini subligar", average_rate = "8.2%" }, { name = "Coral crest key", average_rate = "11.3%" }, { name = "Sacrarium chest key", average_rate = "4.9%" } },
  ["Fomor Warrior"] = { { name = "Coral crest key", average_rate = "6.8%" }, { name = "Revival tree root", average_rate = "3.0%" }, { name = "Sacrarium chest key", average_rate = "2.6%" } },
  ["Fomor's Bats"] = { { name = "Sacrarium chest key", average_rate = "4.8%" } },
  ["Fomor's Elemental"] = { { name = "Sacrarium chest key", average_rate = "11.9%" } },
  ["Fomor's Wyvern"] = { { name = "Sacrarium chest key", average_rate = "7.2%" } },
  ["Gazer"] = { { name = "Vial of mercury", average_rate = "49.2%" }, { name = "Hecteyes eye", average_rate = "6.9%" }, { name = "Sacrarium chest key", average_rate = "3.8%" } },
  ["Greater Gaylas"] = { { name = "Bat fang", average_rate = "14.8%" }, { name = "Bat wing", average_rate = "32.9%" }, { name = "Vial of fiend blood", average_rate = "7.8%" }, { name = "Vial of beastman blood", average_rate = "2.6%" } },
  ["Indich"] = { { name = "Swift belt", average_rate = "57.1%" }, { name = "Dark cluster", average_rate = "14.3%" } },
  ["Keremet"] = { { name = "Sealion crest key", average_rate = "99.0%" } },
  ["Lich"] = { { name = "Sacrarium chest key", average_rate = "7.2%" }, { name = "Bone chip", average_rate = "33.1%" }, { name = "Revival tree root", average_rate = "17.0%" } },
  ["Lobais"] = { { name = "Swift belt", average_rate = "46.2%" } },
  ["Luaith"] = { { name = "Swift belt", average_rate = "47.4%" } },
  ["Mummy"] = { { name = "Sacrarium chest key", average_rate = "5.0%" } },
  ["Stegotaur"] = { { name = "Taurus horn", average_rate = "6.7%" }, { name = "Fomor codex", average_rate = "6.1%" } },
  ["Teratotaur"] = { { name = "Fomor codex", average_rate = "7.4%" }, { name = "Taurus horn", average_rate = "8.1%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "186.1%" } },
  ["Utukku"] = { { name = "Square of cotton cloth", average_rate = "47.8%" }, { name = "Revival tree root", average_rate = "22.4%" }, { name = "Sacrarium chest key", average_rate = "10.4%" } },
}
