-- Zone: Reisenjima Henge
return {
  ["Fu"] = { { name = "Moonbow stone", average_rate = "200.0%" }, { name = "Fu's scale", average_rate = "233.3%" }, { name = "Shulmanu collar", average_rate = "133.3%" }, { name = "Niqmaddu ring", average_rate = "33.3%" } },
  ["Gin"] = { { name = "Gin's scale", average_rate = "163.6%" }, { name = "Dingir ring", average_rate = "27.3%" }, { name = "Square of moonbow leather", average_rate = "136.4%" }, { name = "Yamarang", average_rate = "81.8%" } },
  ["Glassy Craver"] = { { name = "Hope crystal", average_rate = "121.4%" }, { name = "Sherida earring", average_rate = "28.6%" }, { name = "Nusku shield", average_rate = "50.0%" }, { name = "Anu torque", average_rate = "35.7%" } },
  ["Glassy Gorger"] = { { name = "Fulfillment crystal", average_rate = "162.5%" }, { name = "Kishar ring", average_rate = "75.0%" }, { name = "Enki strap", average_rate = "62.5%" }, { name = "Erra pendant", average_rate = "18.8%" } },
  ["Glassy Thinker"] = { { name = "Knobkierrie", average_rate = "25.0%" }, { name = "Thought crystal", average_rate = "141.7%" }, { name = "Adapa shield", average_rate = "50.0%" }, { name = "Adad amulet", average_rate = "66.7%" } },
  ["Kei"] = { { name = "Pot of moonbow urushi", average_rate = "150.0%" }, { name = "Kei's scale", average_rate = "200.0%" }, { name = "Ammurapi shield", average_rate = "75.0%" }, { name = "Lugalbanda earring", average_rate = "25.0%" } },
  ["Kin"] = { { name = "Piece of moonbow steel", average_rate = "130.0%" }, { name = "Kin's scale", average_rate = "230.0%" }, { name = "Utu grip", average_rate = "20.0%" }, { name = "Ilabrat ring", average_rate = "10.0%" } },
  ["Kyou"] = { { name = "Kyou's scale", average_rate = "200.0%" }, { name = "Iskur gorget", average_rate = "133.3%" }, { name = "Bolt of moonbow cloth", average_rate = "166.7%" } },
  ["Ou"] = { { name = "Piece of moonlight coral", average_rate = "216.7%" }, { name = "Regal gem", average_rate = "50.0%" }, { name = "Piece of moonbow steel", average_rate = "33.3%" }, { name = "Regal necklace", average_rate = "50.0%" }, { name = "Regal ring", average_rate = "50.0%" }, { name = "Pot of moonbow urushi", average_rate = "33.3%" }, { name = "Bolt of moonbow cloth", average_rate = "16.7%" } },
  ["Sweetwater Bats"] = { { name = "Sacred Kindred's crest", average_rate = "17.4%" } },
  ["Sweetwater Beetle"] = { { name = "Sacred Kindred's crest", average_rate = "10.3%" } },
  ["Sweetwater Cyhiraeth"] = { { name = "Sacred Kindred's crest", average_rate = "14.3%" } },
  ["Sweetwater Doll"] = { { name = "Sacred Kindred's crest", average_rate = "37.8%" } },
  ["Sweetwater Doomed"] = { { name = "Sacred Kindred's crest", average_rate = "10.0%" } },
  ["Sweetwater Faaz"] = { { name = "Sacred Kindred's crest", average_rate = "12.3%" } },
  ["Sweetwater Fly"] = { { name = "Sacred Kindred's crest", average_rate = "19.6%" } },
  ["Sweetwater Ghost"] = { { name = "Sacred Kindred's crest", average_rate = "10.8%" } },
  ["Sweetwater Goobbue"] = { { name = "Sacred Kindred's crest", average_rate = "13.8%" } },
  ["Sweetwater Hippogryph"] = { { name = "Sacred Kindred's crest", average_rate = "11.9%" } },
  ["Sweetwater Ladybug"] = { { name = "Sacred Kindred's crest", average_rate = "8.4%" } },
  ["Sweetwater Leech"] = { { name = "Sacred Kindred's crest", average_rate = "8.9%" } },
  ["Sweetwater Lizard"] = { { name = "Sacred Kindred's crest", average_rate = "7.4%" } },
  ["Sweetwater Lucani"] = { { name = "Sacred Kindred's crest", average_rate = "6.2%" } },
  ["Sweetwater Mandragora"] = { { name = "Sacred Kindred's crest", average_rate = "16.9%" } },
  ["Sweetwater Mantis"] = { { name = "Sacred Kindred's crest", average_rate = "18.2%" } },
  ["Sweetwater Mosquito"] = { { name = "Sacred Kindred's crest", average_rate = "3.4%" } },
  ["Sweetwater Panopt"] = { { name = "Sacred Kindred's crest", average_rate = "9.9%" } },
  ["Sweetwater Porxie"] = { { name = "Sacred Kindred's crest", average_rate = "5.1%" } },
  ["Sweetwater Pugil"] = { { name = "Sacred Kindred's crest", average_rate = "17.3%" } },
  ["Sweetwater Rabbit"] = { { name = "Sacred Kindred's crest", average_rate = "14.7%" } },
  ["Sweetwater Raptor"] = { { name = "Sacred Kindred's crest", average_rate = "9.1%" } },
  ["Sweetwater Skeleton"] = { { name = "Sacred Kindred's crest", average_rate = "8.7%" } },
  ["Sweetwater Tiger"] = { { name = "Sacred Kindred's crest", average_rate = "13.8%" } },
  ["Sweetwater Toad"] = { { name = "Sacred Kindred's crest", average_rate = "16.0%" } },
  ["Sweetwater Treant"] = { { name = "Sacred Kindred's crest", average_rate = "7.7%" } },
  ["Sweetwater Unseelie"] = { { name = "Sacred Kindred's crest", average_rate = "13.6%" } },
  ["Sweetwater Vulture"] = { { name = "Sacred Kindred's crest", average_rate = "12.1%" } },
  ["Sweetwater Worm"] = { { name = "Sacred Kindred's crest", average_rate = "19.4%" } },
  ["Transcended Bats"] = { { name = "Sacred Kindred's crest", average_rate = "30.0%" } },
  ["Transcended Beetle"] = { { name = "Sacred Kindred's crest", average_rate = "8.9%" } },
  ["Transcended Chapuli"] = { { name = "Sacred Kindred's crest", average_rate = "50.0%" } },
  ["Transcended Faaz"] = { { name = "Sacred Kindred's crest", average_rate = "9.1%" } },
  ["Transcended Fly"] = { { name = "Sacred Kindred's crest", average_rate = "17.9%" } },
  ["Transcended Ghost"] = { { name = "Sacred Kindred's crest", average_rate = "22.2%" } },
  ["Transcended Goobbue"] = { { name = "Sacred Kindred's crest", average_rate = "8.3%" } },
  ["Transcended Ladybug"] = { { name = "Sacred Kindred's crest", average_rate = "26.7%" } },
  ["Transcended Leech"] = { { name = "Sacred Kindred's crest", average_rate = "9.9%" } },
  ["Transcended Lizard"] = { { name = "Sacred Kindred's crest", average_rate = "10.0%" } },
  ["Transcended Mandragora"] = { { name = "Sacred Kindred's crest", average_rate = "14.8%" } },
  ["Transcended Mantis"] = { { name = "Sacred Kindred's crest", average_rate = "100.0%" } },
  ["Transcended Mosquito"] = { { name = "Sacred Kindred's crest", average_rate = "25.0%" } },
  ["Transcended Panopt"] = { { name = "Sacred Kindred's crest", average_rate = "24.0%" } },
  ["Transcended Porxie"] = { { name = "Sacred Kindred's crest", average_rate = "17.2%" } },
  ["Transcended Rabbit"] = { { name = "Sacred Kindred's crest", average_rate = "16.2%" } },
  ["Transcended Tiger"] = { { name = "Sacred Kindred's crest", average_rate = "16.3%" } },
  ["Transcended Unseelie"] = { { name = "Sacred Kindred's crest", average_rate = "7.7%" } },
  ["Transcended Vulture"] = { { name = "Sacred Kindred's crest", average_rate = "12.9%" } },
  ["Transcended Worm"] = { { name = "Sacred Kindred's crest", average_rate = "14.3%" } },
}
