-- Zone: Dynamis - Bastok [D]
return {
  ["Assassin Commander"] = { { name = "Piece of void torsowear: BLU", average_rate = "100.0%" }, { name = "Blackened identification card", average_rate = "500.0%" } },
  ["Brother Leader"] = { { name = "Rusted identification card", average_rate = "800.0%" }, { name = "Torsoshard: PUP", average_rate = "200.0%" } },
  ["Chevalier Commander"] = { { name = "Blackened identification card", average_rate = "400.0%" }, { name = "Piece of void torsowear: DRG", average_rate = "50.0%" }, { name = "Piece of void torsowear: PLD", average_rate = "50.0%" } },
  ["Chevalier Leader"] = { { name = "Rusted identification card", average_rate = "600.0%" }, { name = "Torsoshard: PLD", average_rate = "100.0%" }, { name = "Handshard: PLD", average_rate = "66.7%" } },
  ["Domesticator Commander"] = { { name = "Piece of void torsowear: RNG", average_rate = "50.0%" }, { name = "Blackened identification card", average_rate = "425.0%" }, { name = "Piece of void torsowear: BST", average_rate = "50.0%" } },
  ["Domesticator Leader"] = { { name = "Rusted identification card", average_rate = "800.0%" }, { name = "Torsoshard: RNG", average_rate = "200.0%" } },
  ["Fighter Leader"] = { { name = "Rusted identification card", average_rate = "533.3%" }, { name = "Torsoshard: DRK", average_rate = "33.3%" }, { name = "Torsoshard: WAR", average_rate = "100.0%" } },
  ["Freebooter Commander"] = { { name = "Piece of void torsowear: COR", average_rate = "100.0%" }, { name = "Blackened identification card", average_rate = "400.0%" } },
  ["Freebooter Leader"] = { { name = "Rusted identification card", average_rate = "633.3%" }, { name = "Torsoshard: COR", average_rate = "166.7%" }, { name = "Handshard: COR", average_rate = "66.7%" } },
  ["Healer Commander"] = { { name = "Piece of void torsowear: WHM", average_rate = "100.0%" }, { name = "Blackened identification card", average_rate = "300.0%" } },
  ["Healer Leader"] = { { name = "Rusted identification card", average_rate = "566.7%" }, { name = "Torsoshard: WHM", average_rate = "100.0%" } },
  ["Joculator Commander"] = { { name = "Blackened identification card", average_rate = "1200.0%" }, { name = "Piece of void torsowear: SAM", average_rate = "200.0%" } },
  ["Joculator Leader"] = { { name = "Rusted identification card", average_rate = "580.0%" }, { name = "Torsoshard: BRD", average_rate = "160.0%" }, { name = "Handshard: SAM", average_rate = "40.0%" } },
  ["Magus Commander"] = { { name = "Blackened identification card", average_rate = "583.3%" }, { name = "Piece of void torsowear: GEO", average_rate = "116.7%" }, { name = "Piece of void torsowear: BLM", average_rate = "33.3%" } },
  ["Mu'sha Effigy"] = { { name = "Rusted identification card", average_rate = "312.5%" }, { name = "Beastmen's medal", average_rate = "337.5%" } },
  ["Pickpocket Commander"] = { { name = "Piece of void torsowear: DNC", average_rate = "83.3%" }, { name = "Blackened identification card", average_rate = "650.0%" }, { name = "Kindred's medal", average_rate = "33.3%" }, { name = "Piece of void torsowear: THF", average_rate = "83.3%" }, { name = "Pair of void handwear: DNC", average_rate = "33.3%" } },
  ["Pickpocket Leader"] = { { name = "Rusted identification card", average_rate = "500.0%" }, { name = "Torsoshard: DNC", average_rate = "50.0%" }, { name = "Torsoshard: THF", average_rate = "100.0%" } },
  ["Regiment Balladeer"] = { { name = "Blackened identification card", average_rate = "407.7%" }, { name = "Pair of void handwear: SAM", average_rate = "7.7%" }, { name = "Pair of void handwear: BRD", average_rate = "3.8%" } },
  ["Regiment Cavalier"] = { { name = "Pair of void handwear: PLD", average_rate = "8.3%" }, { name = "Blackened identification card", average_rate = "325.0%" } },
  ["Regiment Combatant"] = { { name = "Blackened identification card", average_rate = "378.8%" }, { name = "Pair of void handwear: MNK", average_rate = "3.0%" }, { name = "Pair of void handwear: PUP", average_rate = "3.0%" } },
  ["Regiment Harnesser"] = { { name = "Blackened identification card", average_rate = "428.6%" } },
  ["Regiment Magician"] = { { name = "Blackened identification card", average_rate = "409.7%" }, { name = "Pair of void handwear: RDM", average_rate = "6.5%" }, { name = "Kindred's medal", average_rate = "6.5%" } },
  ["Regiment Magister"] = { { name = "Blackened identification card", average_rate = "364.9%" }, { name = "Pair of void handwear: BLM", average_rate = "2.7%" }, { name = "Pair of void handwear: GEO", average_rate = "8.1%" } },
  ["Regiment Mender"] = { { name = "Blackened identification card", average_rate = "342.9%" }, { name = "Pair of void handwear: SMN", average_rate = "3.6%" }, { name = "Pair of void handwear: WHM", average_rate = "7.1%" } },
  ["Regiment Scallywag"] = { { name = "Blackened identification card", average_rate = "381.2%" }, { name = "Pair of void handwear: COR", average_rate = "6.2%" } },
  ["Regiment Shadowstalker"] = { { name = "Blackened identification card", average_rate = "423.5%" }, { name = "Pair of void handwear: BLU", average_rate = "11.8%" } },
  ["Regiment Trickster"] = { { name = "Pair of void handwear: THF", average_rate = "8.8%" }, { name = "Blackened identification card", average_rate = "382.4%" }, { name = "Pair of void handwear: DNC", average_rate = "5.9%" } },
  ["Regiment Weaponmaster"] = { { name = "Blackened identification card", average_rate = "391.2%" }, { name = "Pair of void handwear: DRK", average_rate = "5.9%" } },
  ["Shaman Commander"] = { { name = "Blackened identification card", average_rate = "580.0%" }, { name = "Piece of void torsowear: RDM", average_rate = "40.0%" }, { name = "Piece of void torsowear: RUN", average_rate = "120.0%" }, { name = "Pair of void handwear: RDM", average_rate = "40.0%" }, { name = "Volte mittens", average_rate = "60.0%" } },
  ["Shaman Leader"] = { { name = "Torsoshard: RUN", average_rate = "166.7%" }, { name = "Rusted identification card", average_rate = "666.7%" } },
  ["Squadron Balladeer"] = { { name = "Rusted identification card", average_rate = "445.8%" }, { name = "Handshard: BRD", average_rate = "29.2%" } },
  ["Squadron Cavalier"] = { { name = "Rusted identification card", average_rate = "392.0%" }, { name = "Handshard: PLD", average_rate = "8.0%" } },
  ["Squadron Combatant"] = { { name = "Rusted identification card", average_rate = "385.1%" }, { name = "Handshard: MNK", average_rate = "4.3%" } },
  ["Squadron Harnesser"] = { { name = "Rusted identification card", average_rate = "379.2%" }, { name = "Beastmen's medal", average_rate = "4.2%" }, { name = "Handshard: RNG", average_rate = "8.3%" } },
  ["Squadron Magician"] = { { name = "Rusted identification card", average_rate = "368.0%" } },
  ["Squadron Magister"] = { { name = "Rusted identification card", average_rate = "340.0%" }, { name = "Handshard: GEO", average_rate = "4.0%" }, { name = "Beastmen's medal", average_rate = "4.0%" } },
  ["Squadron Mender"] = { { name = "Rusted identification card", average_rate = "391.9%" }, { name = "Handshard: SMN", average_rate = "5.4%" }, { name = "Handshard: WHM", average_rate = "2.7%" } },
  ["Squadron Scallywag"] = { { name = "Rusted identification card", average_rate = "418.4%" }, { name = "Handshard: SCH", average_rate = "2.6%" }, { name = "Handshard: COR", average_rate = "5.3%" } },
  ["Squadron Shadowstalker"] = { { name = "Rusted identification card", average_rate = "365.9%" }, { name = "Handshard: BLU", average_rate = "9.1%" }, { name = "Handshard: NIN", average_rate = "9.1%" } },
  ["Squadron Trickster"] = { { name = "Rusted identification card", average_rate = "380.8%" }, { name = "Beastmen's medal", average_rate = "3.8%" } },
  ["Squadron Weaponmaster"] = { { name = "Rusted identification card", average_rate = "396.4%" }, { name = "Beastmen's medal", average_rate = "1.8%" }, { name = "Handshard: DRK", average_rate = "1.8%" } },
}
