-- Zone: Dynamis - Windurst [D]
return {
  ["Ascetic Leader"] = { { name = "Headshard: MNK", average_rate = "100.0%" }, { name = "Rusted identification card", average_rate = "300.0%" }, { name = "Torsoshard: PUP", average_rate = "100.0%" } },
  ["Champion Commander"] = { { name = "Piece of void torsowear: PLD", average_rate = "50.0%" }, { name = "Blackened identification card", average_rate = "350.0%" }, { name = "Piece of void torsowear: DRG", average_rate = "100.0%" } },
  ["Champion Leader"] = { { name = "Rusted identification card", average_rate = "500.0%" }, { name = "Torsoshard: PLD", average_rate = "100.0%" } },
  ["Empath Leader"] = { { name = "Headshard: BST", average_rate = "50.0%" }, { name = "Rusted identification card", average_rate = "450.0%" }, { name = "Torsoshard: BST", average_rate = "50.0%" }, { name = "Torsoshard: RNG", average_rate = "50.0%" } },
  ["Evincing Idol"] = { { name = "Rusted identification card", average_rate = "250.0%" }, { name = "Beastmen's medal", average_rate = "150.0%" } },
  ["Hoplite Leader"] = { { name = "Rusted identification card", average_rate = "300.0%" }, { name = "Torsoshard: DRK", average_rate = "100.0%" } },
  ["Magian Leader"] = { { name = "Torsoshard: GEO", average_rate = "200.0%" }, { name = "Rusted identification card", average_rate = "600.0%" } },
  ["Minnesinger Commander"] = { { name = "Piece of void torsowear: BRD", average_rate = "100.0%" }, { name = "Blackened identification card", average_rate = "300.0%" } },
  ["Minnesinger Leader"] = { { name = "Rusted identification card", average_rate = "400.0%" }, { name = "Torsoshard: SAM", average_rate = "200.0%" } },
  ["Orisha Leader"] = { { name = "Rusted identification card", average_rate = "600.0%" }, { name = "Torsoshard: WHM", average_rate = "200.0%" } },
  ["Privateer Commander"] = { { name = "Blackened identification card", average_rate = "400.0%" }, { name = "Piece of void torsowear: SCH", average_rate = "100.0%" } },
  ["Privateer Leader"] = { { name = "Rusted identification card", average_rate = "400.0%" }, { name = "Torsoshard: SCH", average_rate = "100.0%" } },
  ["Prognosticator Leader"] = { { name = "Torsoshard: RUN", average_rate = "100.0%" }, { name = "Rusted identification card", average_rate = "300.0%" }, { name = "Headshard: RDM", average_rate = "100.0%" } },
  ["Regiment Ascetic"] = { { name = "Blackened identification card", average_rate = "238.9%" }, { name = "Piece of void headwear: PUP", average_rate = "11.1%" } },
  ["Regiment Champion"] = { { name = "Blackened identification card", average_rate = "270.0%" }, { name = "Piece of void headwear: PLD", average_rate = "10.0%" } },
  ["Regiment Empath"] = { { name = "Piece of void headwear: RNG", average_rate = "14.3%" }, { name = "Blackened identification card", average_rate = "200.0%" }, { name = "Piece of void headwear: BST", average_rate = "42.9%" } },
  ["Regiment Hoplite"] = { { name = "Blackened identification card", average_rate = "228.6%" } },
  ["Regiment Magian"] = { { name = "Blackened identification card", average_rate = "246.2%" }, { name = "Piece of void headwear: BLM", average_rate = "7.7%" }, { name = "Piece of void headwear: GEO", average_rate = "7.7%" } },
  ["Regiment Minnesinger"] = { { name = "Blackened identification card", average_rate = "263.2%" }, { name = "Piece of void headwear: SAM", average_rate = "5.3%" } },
  ["Regiment Orisha"] = { { name = "Piece of void headwear: SMN", average_rate = "7.7%" }, { name = "Blackened identification card", average_rate = "292.3%" }, { name = "Piece of void headwear: WHM", average_rate = "7.7%" } },
  ["Regiment Privateer"] = { { name = "Blackened identification card", average_rate = "270.0%" } },
  ["Regiment Prognosticator"] = { { name = "Blackened identification card", average_rate = "244.4%" } },
  ["Regiment Ruffian"] = { { name = "Blackened identification card", average_rate = "262.5%" } },
  ["Regiment Spy"] = { { name = "Blackened identification card", average_rate = "250.0%" }, { name = "Piece of void headwear: NIN", average_rate = "16.7%" } },
  ["Ruffian Leader"] = { { name = "Torsoshard: THF", average_rate = "100.0%" }, { name = "Rusted identification card", average_rate = "300.0%" } },
  ["Spy Leader"] = { { name = "Rusted identification card", average_rate = "800.0%" }, { name = "Torsoshard: BLU", average_rate = "200.0%" } },
  ["Squadron Ascetic"] = { { name = "Headshard: PUP", average_rate = "9.4%" }, { name = "Rusted identification card", average_rate = "237.5%" } },
  ["Squadron Champion"] = { { name = "Rusted identification card", average_rate = "231.6%" } },
  ["Squadron Empath"] = { { name = "Rusted identification card", average_rate = "250.0%" }, { name = "Headshard: BST", average_rate = "16.7%" }, { name = "Headshard: RNG", average_rate = "11.1%" } },
  ["Squadron Hoplite"] = { { name = "Rusted identification card", average_rate = "237.5%" }, { name = "Headshard: DRK", average_rate = "6.2%" }, { name = "Headshard: WAR", average_rate = "3.1%" } },
  ["Squadron Magian"] = { { name = "Rusted identification card", average_rate = "243.6%" }, { name = "Headshard: BLM", average_rate = "7.7%" }, { name = "Headshard: GEO", average_rate = "2.6%" } },
  ["Squadron Minnesinger"] = { { name = "Rusted identification card", average_rate = "276.0%" }, { name = "Headshard: SAM", average_rate = "4.0%" } },
  ["Squadron Orisha"] = { { name = "Rusted identification card", average_rate = "300.0%" } },
  ["Squadron Privateer"] = { { name = "Rusted identification card", average_rate = "216.7%" }, { name = "Headshard: SCH", average_rate = "4.2%" } },
  ["Squadron Prognosticator"] = { { name = "Rusted identification card", average_rate = "186.7%" } },
  ["Squadron Ruffian"] = { { name = "Rusted identification card", average_rate = "217.9%" }, { name = "Headshard: THF", average_rate = "21.4%" } },
  ["Squadron Spy"] = { { name = "Rusted identification card", average_rate = "224.1%" }, { name = "Headshard: BLU", average_rate = "6.9%" }, { name = "Headshard: NIN", average_rate = "10.3%" } },
}
