-- Zone: Dynamis - Jeuno [D]
return {
  ["Animist Commander"] = { { name = "Piece of void torsowear: BST", average_rate = "100.0%" }, { name = "Blackened identification card", average_rate = "800.0%" }, { name = "Piece of void torsowear: RNG", average_rate = "100.0%" } },
  ["Animist Leader"] = { { name = "Rusted identification card", average_rate = "500.0%" }, { name = "Torsoshard: RNG", average_rate = "75.0%" }, { name = "Beastmen's medal", average_rate = "25.0%" }, { name = "Torsoshard: BST", average_rate = "50.0%" } },
  ["Arcanomancer Commander"] = { { name = "Blackened identification card", average_rate = "575.0%" }, { name = "Piece of void torsowear: BLM", average_rate = "50.0%" }, { name = "Piece of void legwear: GEO", average_rate = "25.0%" }, { name = "Piece of void torsowear: GEO", average_rate = "100.0%" } },
  ["Arcanomancer Leader"] = { { name = "Torsoshard: GEO", average_rate = "66.7%" }, { name = "Rusted identification card", average_rate = "566.7%" }, { name = "Torsoshard: BLM", average_rate = "66.7%" } },
  ["Aurix"] = { { name = "Blackened identification card", average_rate = "350.0%" }, { name = "Kindred's medal", average_rate = "50.0%" }, { name = "Rusted identification card", average_rate = "450.0%" }, { name = "Beastmen's medal", average_rate = "50.0%" } },
  ["Banneret Commander"] = { { name = "Blackened identification card", average_rate = "600.0%" }, { name = "Piece of void torsowear: DRG", average_rate = "200.0%" } },
  ["Banneret Leader"] = { { name = "Torsoshard: DRG", average_rate = "133.3%" }, { name = "Rusted identification card", average_rate = "566.7%" } },
  ["Berserker Commander"] = { { name = "Piece of void torsowear: WAR", average_rate = "75.0%" }, { name = "Blackened identification card", average_rate = "725.0%" }, { name = "Piece of void torsowear: DRK", average_rate = "75.0%" }, { name = "Piece of void legwear: DRK", average_rate = "25.0%" } },
  ["Berserker Leader"] = { { name = "Rusted identification card", average_rate = "377.8%" }, { name = "Torsoshard: WAR", average_rate = "66.7%" }, { name = "Beastmen's medal", average_rate = "44.4%" }, { name = "Legshard: DRK", average_rate = "11.1%" }, { name = "Torsoshard: DRK", average_rate = "66.7%" } },
  ["Buccaneer Commander"] = { { name = "Blackened identification card", average_rate = "400.0%" }, { name = "Piece of void torsowear: SCH", average_rate = "33.3%" }, { name = "Piece of void torsowear: COR", average_rate = "66.7%" }, { name = "Piece of void legwear: COR", average_rate = "33.3%" } },
  ["Buccaneer Leader"] = { { name = "Rusted identification card", average_rate = "625.0%" }, { name = "Torsoshard: COR", average_rate = "175.0%" }, { name = "Legshard: SCH", average_rate = "50.0%" }, { name = "Legshard: COR", average_rate = "50.0%" } },
  ["Defiler Commander"] = { { name = "Blackened identification card", average_rate = "500.0%" }, { name = "Kindred's medal", average_rate = "25.0%" }, { name = "Piece of void torsowear: RDM", average_rate = "50.0%" }, { name = "Piece of void torsowear: RUN", average_rate = "50.0%" } },
  ["Defiler Leader"] = { { name = "Torsoshard: RDM", average_rate = "66.7%" }, { name = "Rusted identification card", average_rate = "433.3%" }, { name = "Legshard: RDM", average_rate = "16.7%" }, { name = "Torsoshard: RUN", average_rate = "50.0%" } },
  ["Fistfighter Commander"] = { { name = "Piece of void torsowear: MNK", average_rate = "66.7%" }, { name = "Blackened identification card", average_rate = "633.3%" }, { name = "Piece of void legwear: MNK", average_rate = "66.7%" }, { name = "Piece of void torsowear: PUP", average_rate = "100.0%" } },
  ["Fistfighter Leader"] = { { name = "Rusted identification card", average_rate = "300.0%" }, { name = "Torsoshard: PUP", average_rate = "50.0%" }, { name = "Beastmen's medal", average_rate = "25.0%" }, { name = "Torsoshard: MNK", average_rate = "25.0%" } },
  ["Flautist Commander"] = { { name = "Piece of void torsowear: BRD", average_rate = "200.0%" }, { name = "Blackened identification card", average_rate = "900.0%" }, { name = "Piece of void legwear: SAM", average_rate = "100.0%" }, { name = "Piece of void legwear: BRD", average_rate = "100.0%" } },
  ["Flautist Leader"] = { { name = "Rusted identification card", average_rate = "425.0%" }, { name = "Torsoshard: BRD", average_rate = "100.0%" }, { name = "Legshard: BRD", average_rate = "25.0%" }, { name = "Legshard: SAM", average_rate = "25.0%" } },
  ["Impish Golem"] = { { name = "Rusted identification card", average_rate = "266.7%" }, { name = "Beastmen's medal", average_rate = "311.1%" } },
  ["Operative Commander"] = { { name = "Piece of void torsowear: BLU", average_rate = "200.0%" }, { name = "Blackened identification card", average_rate = "800.0%" }, { name = "Piece of void legwear: NIN", average_rate = "200.0%" } },
  ["Operative Leader"] = { { name = "Rusted identification card", average_rate = "550.0%" }, { name = "Torsoshard: BLU", average_rate = "75.0%" }, { name = "Torsoshard: NIN", average_rate = "75.0%" } },
  ["Regiment Animist"] = { { name = "Blackened identification card", average_rate = "353.8%" } },
  ["Regiment Arcanomancer"] = { { name = "Blackened identification card", average_rate = "312.8%" }, { name = "Piece of void legwear: BLM", average_rate = "2.1%" }, { name = "Piece of void legwear: GEO", average_rate = "2.1%" } },
  ["Regiment Banneret"] = { { name = "Blackened identification card", average_rate = "289.5%" }, { name = "Piece of void legwear: PLD", average_rate = "5.3%" } },
  ["Regiment Berserker"] = { { name = "Blackened identification card", average_rate = "376.4%" }, { name = "Piece of void legwear: DRK", average_rate = "1.8%" } },
  ["Regiment Buccaneer"] = { { name = "Blackened identification card", average_rate = "337.5%" } },
  ["Regiment Defiler"] = { { name = "Blackened identification card", average_rate = "363.9%" }, { name = "Piece of void legwear: RUN", average_rate = "2.8%" } },
  ["Regiment Fistfighter"] = { { name = "Blackened identification card", average_rate = "351.1%" }, { name = "Kindred's medal", average_rate = "4.3%" }, { name = "Piece of void legwear: MNK", average_rate = "4.3%" } },
  ["Regiment Flautist"] = { { name = "Blackened identification card", average_rate = "332.4%" }, { name = "Piece of void legwear: BRD", average_rate = "8.1%" } },
  ["Regiment Operative"] = { { name = "Blackened identification card", average_rate = "318.2%" }, { name = "Piece of void legwear: NIN", average_rate = "3.0%" } },
  ["Regiment Vandal"] = { { name = "Blackened identification card", average_rate = "336.6%" }, { name = "Piece of void legwear: THF", average_rate = "2.4%" } },
  ["Regiment Vivifier"] = { { name = "Blackened identification card", average_rate = "268.2%" }, { name = "Piece of void legwear: WHM", average_rate = "4.5%" }, { name = "Piece of void legwear: SMN", average_rate = "4.5%" } },
  ["Squadron Animist"] = { { name = "Rusted identification card", average_rate = "339.6%" }, { name = "Legshard: BST", average_rate = "10.4%" }, { name = "Legshard: RNG", average_rate = "4.2%" } },
  ["Squadron Arcanomancer"] = { { name = "Rusted identification card", average_rate = "323.5%" }, { name = "Legshard: BLM", average_rate = "4.9%" }, { name = "Beastmen's medal", average_rate = "2.5%" } },
  ["Squadron Banneret"] = { { name = "Rusted identification card", average_rate = "306.5%" }, { name = "Legshard: DRG", average_rate = "2.2%" } },
  ["Squadron Berserker"] = { { name = "Rusted identification card", average_rate = "346.4%" }, { name = "Legshard: WAR", average_rate = "3.6%" }, { name = "Legshard: DRK", average_rate = "3.6%" } },
  ["Squadron Buccaneer"] = { { name = "Rusted identification card", average_rate = "353.7%" }, { name = "Beastmen's medal", average_rate = "3.0%" }, { name = "Legshard: COR", average_rate = "9.0%" }, { name = "Legshard: SCH", average_rate = "3.0%" } },
  ["Squadron Defiler"] = { { name = "Rusted identification card", average_rate = "311.2%" } },
  ["Squadron Fistfighter"] = { { name = "Rusted identification card", average_rate = "332.4%" }, { name = "Legshard: MNK", average_rate = "5.9%" }, { name = "Legshard: PUP", average_rate = "5.9%" } },
  ["Squadron Flautist"] = { { name = "Rusted identification card", average_rate = "346.6%" }, { name = "Legshard: BRD", average_rate = "1.7%" }, { name = "Legshard: SAM", average_rate = "3.4%" } },
  ["Squadron Operative"] = { { name = "Rusted identification card", average_rate = "351.3%" }, { name = "Legshard: BLU", average_rate = "10.3%" }, { name = "Legshard: NIN", average_rate = "2.6%" } },
  ["Squadron Vandal"] = { { name = "Rusted identification card", average_rate = "359.7%" }, { name = "Legshard: DNC", average_rate = "4.8%" }, { name = "Legshard: THF", average_rate = "4.8%" } },
  ["Squadron Vivifier"] = { { name = "Rusted identification card", average_rate = "320.9%" }, { name = "Legshard: WHM", average_rate = "4.7%" }, { name = "Legshard: SMN", average_rate = "4.7%" } },
  ["Vandal Commander"] = { { name = "Piece of void torsowear: DNC", average_rate = "100.0%" }, { name = "Blackened identification card", average_rate = "800.0%" } },
  ["Vandal Leader"] = { { name = "Rusted identification card", average_rate = "600.0%" }, { name = "Torsoshard: DNC", average_rate = "33.3%" }, { name = "Torsoshard: THF", average_rate = "100.0%" }, { name = "Legshard: THF", average_rate = "66.7%" } },
  ["Vivifier Commander"] = { { name = "Piece of void torsowear: SMN", average_rate = "150.0%" }, { name = "Blackened identification card", average_rate = "675.0%" } },
  ["Vivifier Leader"] = { { name = "Rusted identification card", average_rate = "450.0%" }, { name = "Torsoshard: WHM", average_rate = "50.0%" }, { name = "Torsoshard: SMN", average_rate = "50.0%" } },
}
