-- Zone: Al'Taieu
return {
  ["Absolute Virtue"] = { { name = "Sin of invidiousness", average_rate = "101.4%" }, { name = "Sin of insolence", average_rate = "101.4%" }, { name = "Sin of infatuation", average_rate = "101.3%" }, { name = "Sin of intemperance", average_rate = "58.8%" }, { name = "Sin of indolence", average_rate = "61.4%" }, { name = "Sin of indignation", average_rate = "56.8%" }, { name = "Sin of indulgence", average_rate = "11.6%" } },
  ["Jailer Of Hope"] = { { name = "Fifth virtue", average_rate = "102.3%" }, { name = "Hope staff", average_rate = "99.8%" }, { name = "Hope torque", average_rate = "25.1%" } },
  ["Jailer Of Justice"] = { { name = "Fourth virtue", average_rate = "102.6%" }, { name = "Justice sword", average_rate = "99.3%" }, { name = "Justice torque", average_rate = "24.3%" } },
  ["Jailer Of Love"] = { { name = "Love halberd", average_rate = "102.3%" }, { name = "Aura of voracity", average_rate = "55.4%" }, { name = "Love torque", average_rate = "54.3%" }, { name = "Aura of adulation", average_rate = "54.7%" } },
  ["Jailer Of Prudence"] = { { name = "Sixth virtue", average_rate = "50.5%" }, { name = "Prudence rod", average_rate = "48.4%" }, { name = "Prudence torque", average_rate = "11.2%" } },
  ["Om'aern"] = { { name = "Aern organ", average_rate = "5.7%" }, { name = "Lightning cluster", average_rate = "0.33%" }, { name = "Water cluster", average_rate = "0.30%" }, { name = "Sample of Luminian tissue", average_rate = "2.5%" }, { name = "Light cluster", average_rate = "0.28%" }, { name = "Fire cluster", average_rate = "0.45%" }, { name = "Earth cluster", average_rate = "0.27%" }, { name = "Dark cluster", average_rate = "0.27%" }, { name = "Ice cluster", average_rate = "0.30%" }, { name = "Wind cluster", average_rate = "0.33%" } },
  ["Om'hpemde"] = { { name = "Wind cluster", average_rate = "2.8%" }, { name = "Hpemde organ", average_rate = "8.3%" }, { name = "High-quality hpemde organ", average_rate = "8.4%" }, { name = "Earth cluster", average_rate = "0.94%" }, { name = "Sample of Luminian tissue", average_rate = "1.5%" }, { name = "Fire cluster", average_rate = "1.3%" }, { name = "Ice cluster", average_rate = "1.0%" }, { name = "Water cluster", average_rate = "0.95%" }, { name = "Dark cluster", average_rate = "0.89%" }, { name = "Lightning cluster", average_rate = "1.2%" }, { name = "Light cluster", average_rate = "0.94%" } },
  ["Om'phuabo"] = { { name = "Phuabo organ", average_rate = "61.7%" }, { name = "High-quality phuabo organ", average_rate = "3.2%" }, { name = "Sample of Luminian tissue", average_rate = "9.5%" } },
  ["Om'xzomit"] = { { name = "Xzomit organ", average_rate = "31.4%" }, { name = "High-quality xzomit organ", average_rate = "14.3%" }, { name = "Sample of Luminian tissue", average_rate = "6.3%" }, { name = "Light cluster", average_rate = "0.31%" }, { name = "Fire cluster", average_rate = "0.32%" }, { name = "Dark cluster", average_rate = "0.21%" }, { name = "Lightning cluster", average_rate = "0.30%" }, { name = "Ice cluster", average_rate = "0.21%" }, { name = "Water cluster", average_rate = "0.24%" }, { name = "Wind cluster", average_rate = "0.22%" }, { name = "Earth cluster", average_rate = "0.17%" } },
  ["Om'yovra"] = { { name = "Yovra organ", average_rate = "103.2%" }, { name = "Water cluster", average_rate = "2.3%" }, { name = "Earth cluster", average_rate = "2.9%" }, { name = "Dark cluster", average_rate = "2.4%" }, { name = "Fire cluster", average_rate = "3.7%" }, { name = "Light cluster", average_rate = "2.1%" }, { name = "Sample of Luminian tissue", average_rate = "9.3%" }, { name = "Ice cluster", average_rate = "2.5%" }, { name = "Wind cluster", average_rate = "2.3%" }, { name = "Lightning cluster", average_rate = "3.1%" } },
  ["Ul'aern"] = { { name = "Aern organ", average_rate = "14.9%" }, { name = "Water cluster", average_rate = "0.81%" }, { name = "Sample of Luminian tissue", average_rate = "7.3%" }, { name = "Dark cluster", average_rate = "0.82%" }, { name = "Earth cluster", average_rate = "0.97%" }, { name = "Wind cluster", average_rate = "0.89%" }, { name = "Light cluster", average_rate = "0.71%" }, { name = "Ice cluster", average_rate = "0.88%" }, { name = "Fire cluster", average_rate = "1.2%" }, { name = "Lightning cluster", average_rate = "1.0%" } },
  ["Ul'hpemde"] = { { name = "Sample of Luminian tissue", average_rate = "3.6%" }, { name = "Light cluster", average_rate = "1.1%" }, { name = "High-quality hpemde organ", average_rate = "9.9%" }, { name = "Hpemde organ", average_rate = "10.1%" }, { name = "Dark cluster", average_rate = "1.1%" }, { name = "Water cluster", average_rate = "1.1%" }, { name = "Fire cluster", average_rate = "1.7%" }, { name = "Lightning cluster", average_rate = "1.4%" }, { name = "Wind cluster", average_rate = "1.3%" }, { name = "Earth cluster", average_rate = "1.3%" }, { name = "Ice cluster", average_rate = "1.3%" } },
  ["Ul'phuabo"] = { { name = "Phuabo organ", average_rate = "29.7%" }, { name = "High-quality phuabo organ", average_rate = "9.6%" }, { name = "Sample of Luminian tissue", average_rate = "3.3%" } },
  ["Ul'xzomit"] = { { name = "Xzomit organ", average_rate = "37.3%" }, { name = "Sample of Luminian tissue", average_rate = "9.4%" }, { name = "High-quality xzomit organ", average_rate = "17.0%" }, { name = "Wind cluster", average_rate = "0.73%" }, { name = "Earth cluster", average_rate = "0.72%" }, { name = "Fire cluster", average_rate = "1.1%" }, { name = "Light cluster", average_rate = "0.62%" }, { name = "Ice cluster", average_rate = "0.78%" }, { name = "Lightning cluster", average_rate = "0.71%" }, { name = "Water cluster", average_rate = "0.63%" }, { name = "Dark cluster", average_rate = "0.55%" } },
  ["Ul'yovra"] = { { name = "Yovra organ", average_rate = "57.2%" }, { name = "Ice cluster", average_rate = "3.3%" }, { name = "Sample of Luminian tissue", average_rate = "10.3%" }, { name = "Lightning cluster", average_rate = "3.7%" }, { name = "Water cluster", average_rate = "2.0%" }, { name = "Fire cluster", average_rate = "3.7%" }, { name = "Earth cluster", average_rate = "2.5%" }, { name = "Light cluster", average_rate = "1.7%" }, { name = "Wind cluster", average_rate = "2.5%" }, { name = "Dark cluster", average_rate = "2.1%" } },
}
