-- Zone: Grand Palace of Hu'Xzoi
return {
  ["Eo'aern"] = { { name = "Aern organ", average_rate = "14.2%" }, { name = "High-quality aern organ", average_rate = "6.4%" }, { name = "Sample of Luminian tissue", average_rate = "6.7%" }, { name = "Dark cluster", average_rate = "0.30%" }, { name = "Fire cluster", average_rate = "0.43%" }, { name = "Ice cluster", average_rate = "0.35%" }, { name = "Water cluster", average_rate = "0.28%" }, { name = "Earth cluster", average_rate = "0.32%" }, { name = "Wind cluster", average_rate = "0.31%" }, { name = "Light cluster", average_rate = "0.28%" }, { name = "Lightning cluster", average_rate = "0.38%" } },
  ["Eo'euvhi"] = { { name = "Sample of Luminian tissue", average_rate = "8.1%" }, { name = "Euvhi organ", average_rate = "2.7%" }, { name = "Wind cluster", average_rate = "1.1%" }, { name = "Water cluster", average_rate = "0.98%" }, { name = "Light cluster", average_rate = "1.00%" }, { name = "Earth cluster", average_rate = "1.0%" }, { name = "Fire cluster", average_rate = "1.3%" }, { name = "Ice cluster", average_rate = "0.94%" }, { name = "Lightning cluster", average_rate = "1.3%" }, { name = "Dark cluster", average_rate = "0.88%" } },
  ["Eo'ghrah"] = { { name = "Luminion chip", average_rate = "23.5%" }, { name = "Fire cluster", average_rate = "0.78%" }, { name = "Ghrah M chip", average_rate = "10.4%" }, { name = "Ice cluster", average_rate = "0.96%" }, { name = "Water cluster", average_rate = "0.46%" }, { name = "Wind cluster", average_rate = "0.46%" }, { name = "Light cluster", average_rate = "0.71%" }, { name = "Earth cluster", average_rate = "0.31%" }, { name = "Lightning cluster", average_rate = "0.65%" }, { name = "Dark cluster", average_rate = "0.42%" } },
  ["Eo'zdei"] = { { name = "Luminion chip", average_rate = "18.2%" } },
  ["Ix'aern"] = { { name = "Deed of placidity", average_rate = "61.8%" }, { name = "Vice of antipathy", average_rate = "14.3%" } },
  ["Jailer Of Temperance"] = { { name = "First virtue", average_rate = "101.3%" }, { name = "Temperance axe", average_rate = "96.0%" }, { name = "Temperance torque", average_rate = "17.6%" } },
}
