-- Zone: The Garden of Ru'Hmet
return {
  ["Aw'aern"] = { { name = "Aern organ", average_rate = "11.7%" }, { name = "Earth cluster", average_rate = "0.66%" }, { name = "Fire cluster", average_rate = "0.90%" }, { name = "Dark cluster", average_rate = "0.57%" }, { name = "Sample of Luminian tissue", average_rate = "5.3%" }, { name = "Ice cluster", average_rate = "0.72%" }, { name = "Water cluster", average_rate = "0.63%" }, { name = "Lightning cluster", average_rate = "0.76%" }, { name = "Light cluster", average_rate = "0.58%" }, { name = "Wind cluster", average_rate = "0.65%" } },
  ["Aw'euvhi"] = { { name = "High-quality euvhi organ", average_rate = "9.3%" }, { name = "Euvhi organ", average_rate = "9.8%" }, { name = "Sample of Luminian tissue", average_rate = "9.2%" }, { name = "Wind cluster", average_rate = "1.1%" }, { name = "Ice cluster", average_rate = "1.3%" }, { name = "Light cluster", average_rate = "1.0%" }, { name = "Fire cluster", average_rate = "1.7%" }, { name = "Earth cluster", average_rate = "1.2%" }, { name = "Lightning cluster", average_rate = "1.3%" }, { name = "Dark cluster", average_rate = "1.0%" }, { name = "Water cluster", average_rate = "1.1%" } },
  ["Aw'ghrah"] = { { name = "Wind cluster", average_rate = "0.63%" }, { name = "Luminion chip", average_rate = "22.9%" }, { name = "Earth cluster", average_rate = "0.68%" }, { name = "Ghrah M chip", average_rate = "2.9%" }, { name = "Ice cluster", average_rate = "1.1%" }, { name = "Fire cluster", average_rate = "0.84%" }, { name = "Water cluster", average_rate = "0.60%" }, { name = "Lightning cluster", average_rate = "0.61%" }, { name = "Light cluster", average_rate = "0.15%" }, { name = "Dark cluster", average_rate = "0.20%" } },
  ["Aw'zdei"] = { { name = "Luminion chip", average_rate = "18.4%" } },
  ["Ix'aern"] = { { name = "Deed of moderation", average_rate = "19.5%" }, { name = "Deed of sensibility", average_rate = "25.0%" }, { name = "Vice of avarice", average_rate = "4.0%" }, { name = "Vice of aspersion", average_rate = "5.4%" } },
  ["Jailer Of Faith"] = { { name = "Third virtue", average_rate = "101.4%" }, { name = "Faith baghnakhs", average_rate = "97.8%" }, { name = "Faith torque", average_rate = "26.4%" } },
  ["Jailer Of Fortitude"] = { { name = "Second virtue", average_rate = "101.0%" }, { name = "Fortitude axe", average_rate = "100.3%" }, { name = "Fortitude torque", average_rate = "28.3%" } },
  ["Maze Lurker"] = { { name = "Water cluster", average_rate = "50.0%" } },
}
