-- Zone: Temenos
return {
  ["Abyssdweller Jhabdebb"] = { { name = "Ancient beastcoin", average_rate = "701.4%" } },
  ["Air Elemental"] = { { name = "Ancient beastcoin", average_rate = "56.7%" } },
  ["Airi"] = { { name = "Ancient beastcoin", average_rate = "604.8%" } },
  ["Beli"] = { { name = "Ancient beastcoin", average_rate = "45.9%" } },
  ["Cryptonberry Abductor"] = { { name = "Ancient beastcoin", average_rate = "48.6%" } },
  ["Cryptonberry Charmer"] = { { name = "Ancient beastcoin", average_rate = "47.8%" } },
  ["Cryptonberry Designator"] = { { name = "Ancient beastcoin", average_rate = "46.4%" } },
  ["Cryptonberry Skulker"] = { { name = "Ancient beastcoin", average_rate = "46.4%" } },
  ["Dark Elemental"] = { { name = "Ancient beastcoin", average_rate = "87.9%" } },
  ["Earth Elemental"] = { { name = "Ancient beastcoin", average_rate = "55.2%" } },
  ["Enhanced Ahriman"] = { { name = "Ancient beastcoin", average_rate = "601.0%" } },
  ["Enhanced Akbaba"] = { { name = "Ancient beastcoin", average_rate = "321.2%" } },
  ["Enhanced Beetle"] = { { name = "Ancient beastcoin", average_rate = "48.1%" } },
  ["Enhanced Dragon"] = { { name = "Ancient beastcoin", average_rate = "588.1%" } },
  ["Enhanced Jelly"] = { { name = "Ancient beastcoin", average_rate = "325.9%" } },
  ["Enhanced Kettenkaefer"] = { { name = "Ancient beastcoin", average_rate = "315.2%" } },
  ["Enhanced Koenigstiger"] = { { name = "Ancient beastcoin", average_rate = "322.2%" } },
  ["Enhanced Lizard"] = { { name = "Ancient beastcoin", average_rate = "48.6%" } },
  ["Enhanced Makara"] = { { name = "Ancient beastcoin", average_rate = "316.3%" } },
  ["Enhanced Mandragora"] = { { name = "Ancient beastcoin", average_rate = "49.7%" } },
  ["Enhanced Pugil"] = { { name = "Ancient beastcoin", average_rate = "48.6%" } },
  ["Enhanced Pygmaioi"] = { { name = "Ancient beastcoin", average_rate = "312.9%" } },
  ["Enhanced Salamander"] = { { name = "Ancient beastcoin", average_rate = "320.7%" } },
  ["Enhanced Slime"] = { { name = "Ancient beastcoin", average_rate = "50.1%" } },
  ["Enhanced Tiger"] = { { name = "Ancient beastcoin", average_rate = "48.7%" } },
  ["Enhanced Vulture"] = { { name = "Ancient beastcoin", average_rate = "49.0%" } },
  ["Fire Elemental"] = { { name = "Ancient beastcoin", average_rate = "55.2%" } },
  ["Fossil Quadav"] = { { name = "Ancient beastcoin", average_rate = "79.3%" } },
  ["Goblin Fencer"] = { { name = "Ancient beastcoin", average_rate = "150.2%" } },
  ["Goblin Slaughterman"] = { { name = "Ancient beastcoin", average_rate = "46.5%" } },
  ["Goblin Theurgist"] = { { name = "Ancient beastcoin", average_rate = "149.2%" } },
  ["Goblin Warlord"] = { { name = "Ancient beastcoin", average_rate = "148.9%" } },
  ["Grognard Footsoldier"] = { { name = "Ancient beastcoin", average_rate = "81.1%" } },
  ["Grognard Grappler"] = { { name = "Ancient beastcoin", average_rate = "78.2%" } },
  ["Grognard Impaler"] = { { name = "Ancient beastcoin", average_rate = "82.7%" } },
  ["Grognard Mesmerizer"] = { { name = "Ancient beastcoin", average_rate = "81.1%" } },
  ["Grognard Neckchopper"] = { { name = "Ancient beastcoin", average_rate = "82.9%" } },
  ["Grognard Predator"] = { { name = "Ancient beastcoin", average_rate = "77.3%" } },
  ["Ice Elemental"] = { { name = "Ancient beastcoin", average_rate = "50.2%" } },
  ["Iruci"] = { { name = "Ancient beastcoin", average_rate = "592.5%" } },
  ["Ji'gho Ageless"] = { { name = "Ancient beastcoin", average_rate = "329.9%" } },
  ["Kari"] = { { name = "Ancient beastcoin", average_rate = "46.8%" } },
  ["Kindred Black Mage"] = { { name = "Ancient beastcoin", average_rate = "46.2%" } },
  ["Kindred Dark Knight"] = { { name = "Ancient beastcoin", average_rate = "46.9%" } },
  ["Kindred Summoner"] = { { name = "Ancient beastcoin", average_rate = "46.1%" } },
  ["Kindred Warrior"] = { { name = "Ancient beastcoin", average_rate = "45.9%" } },
  ["Kingslayer Doggvdegg"] = { { name = "Ancient beastcoin", average_rate = "312.6%" } },
  ["Koo Buzu The Theomanic"] = { { name = "Ancient beastcoin", average_rate = "331.2%" } },
  ["Light Elemental"] = { { name = "Ancient beastcoin", average_rate = "701.1%" } },
  ["Lightsteel Quadav"] = { { name = "Ancient beastcoin", average_rate = "80.6%" } },
  ["Moblin Dustman"] = { { name = "Ancient beastcoin", average_rate = "46.5%" } },
  ["Mystic Avatar"] = { { name = "Ancient beastcoin", average_rate = "167.7%" } },
  ["Orichalcum Quadav"] = { { name = "Ancient beastcoin", average_rate = "698.6%" } },
  ["Pee Qoho The Python"] = { { name = "Ancient beastcoin", average_rate = "700.0%" } },
  ["Praetorian Guard Cccxi"] = { { name = "Ancient beastcoin", average_rate = "45.4%" } },
  ["Praetorian Guard Ccxx"] = { { name = "Ancient beastcoin", average_rate = "46.6%" } },
  ["Praetorian Guard Cxlviii"] = { { name = "Ancient beastcoin", average_rate = "45.4%" } },
  ["Praetorian Guard Lxxiii"] = { { name = "Ancient beastcoin", average_rate = "46.1%" } },
  ["Pyrrha"] = { { name = "Ancient beastcoin", average_rate = "655.9%" } },
  ["Skadi"] = { { name = "Ancient beastcoin", average_rate = "44.3%" } },
  ["Star Ruby Quadav"] = { { name = "Ancient beastcoin", average_rate = "86.9%" } },
  ["Star Sapphire Quadav"] = { { name = "Ancient beastcoin", average_rate = "79.3%" } },
  ["Telchines Bard"] = { { name = "Ancient beastcoin", average_rate = "45.3%" } },
  ["Telchines Dragoon"] = { { name = "Ancient beastcoin", average_rate = "45.3%" } },
  ["Telchines Monk"] = { { name = "Ancient beastcoin", average_rate = "45.9%" } },
  ["Telchines White Mage"] = { { name = "Ancient beastcoin", average_rate = "47.3%" } },
  ["Temenos Aern"] = { { name = "Ancient beastcoin", average_rate = "118.2%" } },
  ["Temenos Cleaner"] = { { name = "Ancient beastcoin", average_rate = "593.9%" } },
  ["Temenos Euvhi"] = { { name = "Ancient beastcoin", average_rate = "220.9%" } },
  ["Temenos Ghrah"] = { { name = "Ancient beastcoin", average_rate = "376.5%" } },
  ["Temenos Weapon"] = { { name = "Ancient beastcoin", average_rate = "599.0%" } },
  ["Thalesek"] = { { name = "Ancient beastcoin", average_rate = "456.2%" } },
  ["Thrym"] = { { name = "Ancient beastcoin", average_rate = "45.8%" } },
  ["Thunder Elemental"] = { { name = "Ancient beastcoin", average_rate = "59.5%" } },
  ["Water Elemental"] = { { name = "Ancient beastcoin", average_rate = "53.8%" } },
  ["Whitegold Quadav"] = { { name = "Ancient beastcoin", average_rate = "85.7%" } },
  ["Wootz Quadav"] = { { name = "Ancient beastcoin", average_rate = "72.8%" } },
  ["Yagudo Archpriest"] = { { name = "Ancient beastcoin", average_rate = "78.0%" } },
  ["Yagudo Disciplinant"] = { { name = "Ancient beastcoin", average_rate = "83.6%" } },
  ["Yagudo Eradicator"] = { { name = "Ancient beastcoin", average_rate = "81.3%" } },
  ["Yagudo Kapellmeister"] = { { name = "Ancient beastcoin", average_rate = "83.4%" } },
  ["Yagudo Knight Templar"] = { { name = "Ancient beastcoin", average_rate = "79.3%" } },
  ["Yagudo Prelatess"] = { { name = "Ancient beastcoin", average_rate = "74.0%" } },
}
