-- Zone: Apollyon
return {
  ["Adamantshell"] = { { name = "Ancient beastcoin", average_rate = "44.7%" } },
  ["Aeshma"] = { { name = "Ancient beastcoin", average_rate = "391.4%" } },
  ["Air Elemental"] = { { name = "Ancient beastcoin", average_rate = "45.7%" } },
  ["Apollyon Ahriman"] = { { name = "Ancient beastcoin", average_rate = "141.4%" } },
  ["Apollyon Cleaner"] = { { name = "Ancient beastcoin", average_rate = "45.9%" } },
  ["Apollyon Demon"] = { { name = "Ancient beastcoin", average_rate = "142.0%" } },
  ["Apollyon Sapling"] = { { name = "Ancient beastcoin", average_rate = "102.1%" } },
  ["Apollyon Scavenger"] = { { name = "Ancient beastcoin", average_rate = "47.0%" } },
  ["Apollyon Taurus"] = { { name = "Ancient beastcoin", average_rate = "142.0%" } },
  ["Arboricole Beetle"] = { { name = "Ancient beastcoin", average_rate = "102.1%" } },
  ["Arboricole Crawler"] = { { name = "Ancient beastcoin", average_rate = "102.6%" } },
  ["Arboricole Hornet"] = { { name = "Ancient beastcoin", average_rate = "102.9%" } },
  ["Arboricole Opo-Opo"] = { { name = "Ancient beastcoin", average_rate = "102.7%" } },
  ["Arboricole Raven"] = { { name = "Ancient beastcoin", average_rate = "44.9%" } },
  ["Arboricole Spider"] = { { name = "Ancient beastcoin", average_rate = "102.2%" } },
  ["Armoury Crate"] = { { name = "Ancient beastcoin", average_rate = "45.2%" } },
  ["Bardha"] = { { name = "Ancient beastcoin", average_rate = "48.3%" } },
  ["Barometz"] = { { name = "Ancient beastcoin", average_rate = "27.2%" } },
  ["Bata"] = { { name = "Ancient beastcoin", average_rate = "393.3%" } },
  ["Borametz"] = { { name = "Ancient beastcoin", average_rate = "26.9%" } },
  ["Carnagechief Jackbodokk"] = { { name = "Ancient beastcoin", average_rate = "302.2%" } },
  ["Cornu"] = { { name = "Ancient beastcoin", average_rate = "46.8%" } },
  ["Criosphinx"] = { { name = "Ancient beastcoin", average_rate = "204.9%" } },
  ["Dark Elemental"] = { { name = "Ancient beastcoin", average_rate = "46.6%" } },
  ["Dee Wapa The Desolator"] = { { name = "Ancient beastcoin", average_rate = "298.1%" } },
  ["Earth Elemental"] = { { name = "Ancient beastcoin", average_rate = "48.6%" } },
  ["Fir Bholg"] = { { name = "Ancient beastcoin", average_rate = "45.3%" } },
  ["Fire Elemental"] = { { name = "Ancient beastcoin", average_rate = "47.7%" } },
  ["Flying Spear"] = { { name = "Ancient beastcoin", average_rate = "203.8%" } },
  ["Fossil Quadav"] = { { name = "Ancient beastcoin", average_rate = "440.7%" } },
  ["Gorynich"] = { { name = "Ancient beastcoin", average_rate = "205.4%" } },
  ["Grognard Footsoldier"] = { { name = "Ancient beastcoin", average_rate = "406.0%" } },
  ["Grognard Grappler"] = { { name = "Ancient beastcoin", average_rate = "419.4%" } },
  ["Grognard Impaler"] = { { name = "Ancient beastcoin", average_rate = "410.6%" } },
  ["Grognard Mesmerizer"] = { { name = "Ancient beastcoin", average_rate = "409.9%" } },
  ["Grognard Neckchopper"] = { { name = "Ancient beastcoin", average_rate = "404.8%" } },
  ["Grognard Predator"] = { { name = "Ancient beastcoin", average_rate = "411.0%" } },
  ["Gunpod"] = { { name = "Ancient beastcoin", average_rate = "112.8%" }, { name = "Charcoal chip", average_rate = "4.2%" }, { name = "Smalt chip", average_rate = "6.2%" }, { name = "Pot of ebony lacquer", average_rate = "1.3%" }, { name = "Smoky chip", average_rate = "5.7%" }, { name = "Electrum stud", average_rate = "1.1%" }, { name = "Black rivet", average_rate = "1.8%" }, { name = "Square of brown doeskin", average_rate = "1.4%" }, { name = "Ancient brass ingot", average_rate = "1.3%" }, { name = "Square of flameshun cloth", average_rate = "1.6%" }, { name = "Darksteel sheet", average_rate = "2.4%" }, { name = "Square of canvas toile", average_rate = "1.4%" }, { name = "Square of corduroy cloth", average_rate = "1.5%" }, { name = "Magenta chip", average_rate = "4.6%" }, { name = "Spool of light filament", average_rate = "1.6%" }, { name = "Chunk of adaman ore", average_rate = "2.6%" }, { name = "Light steel ingot", average_rate = "3.3%" }, { name = "Handful of clot plasma", average_rate = "2.1%" }, { name = "Argyro rivet", average_rate = "1.6%" }, { name = "Ponze of shell powder", average_rate = "2.1%" }, { name = "Spool of diabolic yarn", average_rate = "0.94%" }, { name = "Chunk of darksteel ore", average_rate = "2.7%" }, { name = "Spool of rainbow thread", average_rate = "2.8%" }, { name = "Sheet of kurogane", average_rate = "1.8%" }, { name = "Fetid lanolin cube", average_rate = "1.1%" }, { name = "Square of charcoal cotton", average_rate = "0.95%" }, { name = "Gold stud", average_rate = "0.65%" }, { name = "Piece of oxblood", average_rate = "2.3%" }, { name = "Square of cardinal cloth", average_rate = "0.82%" }, { name = "White rivet", average_rate = "0.65%" }, { name = "Square of astral leather", average_rate = "1.1%" }, { name = "Spool of benedict yarn", average_rate = "0.89%" }, { name = "Blue rivet", average_rate = "1.3%" } },
  ["Hieracosphinx"] = { { name = "Ancient beastcoin", average_rate = "205.5%" } },
  ["Ice Elemental"] = { { name = "Ancient beastcoin", average_rate = "47.5%" } },
  ["Inhumer"] = { { name = "Ancient beastcoin", average_rate = "41.4%" } },
  ["Kerkopes"] = { { name = "Ancient beastcoin", average_rate = "102.2%" } },
  ["Kronprinz Behemoth"] = { { name = "Ancient beastcoin", average_rate = "560.3%" } },
  ["Light Elemental"] = { { name = "Ancient beastcoin", average_rate = "50.2%" } },
  ["Lightsteel Quadav"] = { { name = "Ancient beastcoin", average_rate = "434.8%" } },
  ["Metalloid Amoeba"] = { { name = "Ancient beastcoin", average_rate = "43.2%" } },
  ["Mountain Buffalo"] = { { name = "Ancient beastcoin", average_rate = "48.2%" } },
  ["Na'qba Chirurgeon"] = { { name = "Ancient beastcoin", average_rate = "307.7%" } },
  ["Nergal"] = { { name = "Ancient beastcoin", average_rate = "391.0%" } },
  ["Sirin"] = { { name = "Ancient beastcoin", average_rate = "102.2%" } },
  ["Star Ruby Quadav"] = { { name = "Ancient beastcoin", average_rate = "418.2%" } },
  ["Star Sapphire Quadav"] = { { name = "Ancient beastcoin", average_rate = "425.9%" } },
  ["Thunder Elemental"] = { { name = "Ancient beastcoin", average_rate = "51.0%" } },
  ["Troglodyte Dhalmel"] = { { name = "Ancient beastcoin", average_rate = "203.8%" } },
  ["Water Elemental"] = { { name = "Ancient beastcoin", average_rate = "47.8%" } },
  ["Whitegold Quadav"] = { { name = "Ancient beastcoin", average_rate = "424.2%" } },
  ["Wootz Quadav"] = { { name = "Ancient beastcoin", average_rate = "426.4%" } },
  ["Yagudo Archpriest"] = { { name = "Ancient beastcoin", average_rate = "428.1%" } },
  ["Yagudo Disciplinant"] = { { name = "Ancient beastcoin", average_rate = "431.0%" } },
  ["Yagudo Eradicator"] = { { name = "Ancient beastcoin", average_rate = "419.6%" } },
  ["Yagudo Kapellmeister"] = { { name = "Ancient beastcoin", average_rate = "424.8%" } },
  ["Yagudo Knight Templar"] = { { name = "Ancient beastcoin", average_rate = "428.5%" } },
  ["Yagudo Prelatess"] = { { name = "Ancient beastcoin", average_rate = "425.2%" } },
}
