-- Zone: Bibiki Bay
return {
  ["Alraune"] = { { name = "Two-leaf mandragora bud", average_rate = "24.0%" }, { name = "Four-leaf mandragora bud", average_rate = "5.7%" } },
  ["Bight Rarab"] = { { name = "Slice of hare meat", average_rate = "25.3%" }, { name = "Rabbit hide", average_rate = "13.9%" } },
  ["Camelopard"] = { { name = "Slice of dhalmel meat", average_rate = "47.0%" }, { name = "Catoblepas hide", average_rate = "21.1%" }, { name = "Giant femur", average_rate = "10.0%" }, { name = "Earth cluster", average_rate = "0.03%" } },
  ["Catoblepas"] = { { name = "Slice of dhalmel meat", average_rate = "48.8%" }, { name = "Catoblepas hide", average_rate = "20.6%" }, { name = "Giant femur", average_rate = "10.1%" }, { name = "Earth cluster", average_rate = "0.03%" } },
  ["Coastal Opo-Opo"] = { { name = "Pebble", average_rate = "23.8%" }, { name = "Bunch of pamamas", average_rate = "12.7%" }, { name = "Elshimo coconut", average_rate = "6.7%" }, { name = "Thundermelon", average_rate = "1.8%" } },
  ["Coralline Uragnite"] = { { name = "Uragnite shell", average_rate = "7.4%" }, { name = "Seashell", average_rate = "26.5%" }, { name = "Sack of white sand", average_rate = "14.9%" } },
  ["Eft"] = { { name = "Eft skin", average_rate = "6.6%" }, { name = "High-quality eft skin", average_rate = "1.5%" }, { name = "Lizard egg", average_rate = "13.4%" } },
  ["Ghost Crab"] = { { name = "Chunk of rock salt", average_rate = "103.3%" }, { name = "Slice of land crab meat", average_rate = "34.4%" }, { name = "Crab shell", average_rate = "34.4%" } },
  ["Goblin Pathfinder"] = { { name = "Handful of counterfeit gil", average_rate = "6.0%" }, { name = "Goblin armor", average_rate = "2.6%" }, { name = "Goblin mask", average_rate = "2.6%" }, { name = "Mythril beastcoin", average_rate = "1.7%" } },
  ["Goblin Shaman"] = { { name = "Mythril beastcoin", average_rate = "1.4%" }, { name = "Goblin mask", average_rate = "4.5%" }, { name = "Goblin armor", average_rate = "1.5%" } },
  ["Grindylow"] = { { name = "Chunk of rock salt", average_rate = "96.3%" }, { name = "Slice of land crab meat", average_rate = "40.7%" }, { name = "Crab shell", average_rate = "33.3%" } },
  ["Hobgoblin Alastor"] = { { name = "Goblin helm", average_rate = "5.3%" }, { name = "Goblin mail", average_rate = "4.5%" }, { name = "Scroll of Absorb-VIT", average_rate = "0.75%" }, { name = "Scroll of Absorb-INT", average_rate = "1.5%" }, { name = "Scroll of Absorb-AGI", average_rate = "0.75%" } },
  ["Hobgoblin Angler"] = { { name = "Goblin helm", average_rate = "9.1%" }, { name = "Goblin mail", average_rate = "2.8%" }, { name = "Carbon fishing rod", average_rate = "8.5%" } },
  ["Hobgoblin Animalier"] = { { name = "Goblin mask", average_rate = "5.0%" }, { name = "Goblin armor", average_rate = "2.9%" } },
  ["Hobgoblin Blagger"] = { { name = "Goblin mask", average_rate = "10.4%" }, { name = "Air tank", average_rate = "9.3%" }, { name = "Goblin armor", average_rate = "3.0%" } },
  ["Hobgoblin Fascinator"] = { { name = "Goblin armor", average_rate = "3.4%" }, { name = "Goblin mask", average_rate = "7.3%" }, { name = "Fire cluster", average_rate = "0.12%" } },
  ["Hobgoblin Martialist"] = { { name = "Goblin mail", average_rate = "3.3%" }, { name = "Goblin helm", average_rate = "4.3%" } },
  ["Hobgoblin Physician"] = { { name = "Goblin mask", average_rate = "8.1%" }, { name = "Goblin armor", average_rate = "5.9%" }, { name = "Scroll of Cure V", average_rate = "2.3%" }, { name = "Scroll of Shellra IV", average_rate = "4.1%" }, { name = "Scroll of Regen III", average_rate = "1.4%" }, { name = "Scroll of Curaga IV", average_rate = "1.4%" } },
  ["Hobgoblin Toreador"] = { { name = "Goblin armor", average_rate = "2.9%" }, { name = "Goblin mask", average_rate = "5.2%" } },
  ["Hobgoblin Venerer"] = { { name = "Goblin mask", average_rate = "4.9%" }, { name = "Goblin armor", average_rate = "1.6%" } },
  ["Hypnos Eft"] = { { name = "High-quality eft skin", average_rate = "35.9%" }, { name = "Lizard egg", average_rate = "17.0%" }, { name = "Eft skin", average_rate = "9.6%" }, { name = "Fire cluster", average_rate = "0.08%" } },
  ["Ignis Fatuus"] = { { name = "Pinch of bomb ash", average_rate = "102.1%" }, { name = "Bomb arm", average_rate = "14.9%" } },
  ["Intulo"] = { { name = "Eft skin", average_rate = "13.4%" }, { name = "Curaga earring", average_rate = "20.8%" }, { name = "Magic slacks", average_rate = "7.5%" } },
  ["Island Rarab"] = { { name = "Rabbit hide", average_rate = "14.3%" }, { name = "Slice of hare meat", average_rate = "25.7%" }, { name = "Earth cluster", average_rate = "0.04%" } },
  ["Jagil"] = { { name = "Handful of pugil scales", average_rate = "16.8%" }, { name = "Shall shell", average_rate = "8.1%" } },
  ["Kraken"] = { { name = "Seashell", average_rate = "25.5%" }, { name = "Shall shell", average_rate = "2.2%" } },
  ["Lancet Jagil"] = { { name = "Cleanly snapped rod", average_rate = "94.1%" } },
  ["Marine Dhalmel"] = { { name = "Dhalmel hide", average_rate = "3.5%" }, { name = "Giant femur", average_rate = "4.8%" }, { name = "Slice of dhalmel meat", average_rate = "26.6%" }, { name = "Sprig of papaka grass", average_rate = "1.4%" } },
  ["Raven"] = { { name = "Bird feather", average_rate = "28.8%" }, { name = "Bird egg", average_rate = "6.3%" } },
  ["Serra"] = { { name = "Volans greaves", average_rate = "18.8%" }, { name = "Shall shell", average_rate = "2.4%" }, { name = "Handful of pugil scales", average_rate = "8.6%" } },
  ["Shankha"] = { { name = "Adoubeur's pavise", average_rate = "14.9%" } },
  ["Shen"] = { { name = "Reverend mail", average_rate = "86.0%" } },
  ["Tartarus Eft"] = { { name = "Eft skin", average_rate = "8.3%" }, { name = "High-quality eft skin", average_rate = "31.7%" }, { name = "Lizard egg", average_rate = "16.8%" } },
  ["Teine Sith"] = { { name = "Pinch of bomb ash", average_rate = "110.0%" }, { name = "Bomb arm", average_rate = "40.0%" } },
  ["Toucan"] = { { name = "Bird feather", average_rate = "23.8%" }, { name = "Bird egg", average_rate = "6.4%" } },
  ["Tragopan"] = { { name = "Bird egg", average_rate = "7.0%" }, { name = "Bird feather", average_rate = "25.3%" }, { name = "Fire cluster", average_rate = "0.08%" } },
  ["Tropical Rarab"] = { { name = "Rabbit hide", average_rate = "14.1%" }, { name = "Slice of hare meat", average_rate = "24.6%" }, { name = "Earth cluster", average_rate = "0.06%" } },
  ["Viscous Clot"] = { { name = "Handful of clot plasma", average_rate = "8.7%" } },
}
