-- Zone: Uleguerand Range
return {
  ["Agloolik"] = { { name = "Snoll arm", average_rate = "32.7%" } },
  ["Akselloak"] = { { name = "Snoll arm", average_rate = "39.0%" } },
  ["Black Coney"] = { { name = "Slice of hare meat", average_rate = "46.2%" }, { name = "Selene's bow", average_rate = "11.5%" } },
  ["Bonnacon"] = { { name = "Buffalo hide", average_rate = "47.4%" }, { name = "Cure clogs", average_rate = "28.0%" }, { name = "Slice of buffalo meat", average_rate = "63.2%" }, { name = "Tredecim scythe", average_rate = "13.3%" } },
  ["Brontotaur"] = { { name = "Taurus horn", average_rate = "3.4%" }, { name = "Taurus wing", average_rate = "1.4%" } },
  ["Buffalo"] = { { name = "Slice of buffalo meat", average_rate = "21.8%" }, { name = "Jug of Uleguerand milk", average_rate = "46.7%" }, { name = "Buffalo hide", average_rate = "3.7%" } },
  ["Cwn Annwn"] = { { name = "Snow lily", average_rate = "16.4%" }, { name = "Wolf hide", average_rate = "7.8%" }, { name = "Revival tree root", average_rate = "2.3%" } },
  ["Doom Mage"] = { { name = "Bone chip", average_rate = "36.0%" }, { name = "Revival tree root", average_rate = "15.6%" }, { name = "Scroll of Blizzard III", average_rate = "5.8%" } },
  ["Doom Soldier"] = { { name = "Bone chip", average_rate = "26.5%" }, { name = "Scroll of Absorb-AGI", average_rate = "1.8%" }, { name = "Scroll of Absorb-INT", average_rate = "1.6%" }, { name = "Scroll of Absorb-VIT", average_rate = "0.82%" } },
  ["Dread Demon"] = { { name = "Demon skull", average_rate = "11.1%" }, { name = "Demon horn", average_rate = "13.5%" }, { name = "Scroll of Firaga II", average_rate = "5.2%" } },
  ["Esbat"] = { { name = "Bat wing", average_rate = "30.3%" }, { name = "Bat fang", average_rate = "15.3%" }, { name = "Vial of fiend blood", average_rate = "7.1%" }, { name = "Vial of beastman blood", average_rate = "2.0%" } },
  ["Fachan"] = { { name = "Bottle of Ahriman tears", average_rate = "37.8%" }, { name = "Ahriman lens", average_rate = "18.5%" }, { name = "Ahriman wing", average_rate = "8.7%" } },
  ["Father Frost"] = { { name = "Purgatory collar", average_rate = "51.0%" }, { name = "Snoll arm", average_rate = "58.8%" } },
  ["Frost Flambeau"] = { { name = "Aptant of geoc", average_rate = "17.3%" }, { name = "Aptant of fyrst", average_rate = "22.2%" } },
  ["Geush Urvan"] = { { name = "Toreador's cape", average_rate = "100.0%" } },
  ["Giant Buffalo"] = { { name = "Jug of Uleguerand milk", average_rate = "46.5%" }, { name = "Slice of buffalo meat", average_rate = "3.6%" }, { name = "Buffalo hide", average_rate = "1.4%" }, { name = "Buffalo horn", average_rate = "0.84%" }, { name = "Ice cluster", average_rate = "0.02%" } },
  ["Glacier Eater"] = { { name = "Chunk of zinc ore", average_rate = "20.8%" }, { name = "Chunk of zincite", average_rate = "27.7%" }, { name = "Chunk of iron ore", average_rate = "1.9%" } },
  ["Gore Demon"] = { { name = "Demon horn", average_rate = "10.2%" }, { name = "Demon skull", average_rate = "6.8%" } },
  ["Ice Elemental"] = { { name = "Ice cluster", average_rate = "153.8%" } },
  ["Jormungand"] = { { name = "Chunk of molybdenum ore", average_rate = "400.0%" }, { name = "Adaman ingot", average_rate = "50.0%" }, { name = "Dragon talon", average_rate = "50.0%" } },
  ["Judicator Demon"] = { { name = "Demon skull", average_rate = "13.7%" }, { name = "Demon horn", average_rate = "18.6%" }, { name = "Scroll of Absorb-DEX", average_rate = "12.3%" } },
  ["Kindred Black Mage"] = { { name = "Scroll of Firaga II", average_rate = "12.1%" }, { name = "Demon skull", average_rate = "5.7%" }, { name = "Demon horn", average_rate = "5.9%" } },
  ["Kindred Dark Knight"] = { { name = "Demon horn", average_rate = "13.6%" }, { name = "Demon skull", average_rate = "11.1%" } },
  ["Kindred Summoner"] = { { name = "Demon skull", average_rate = "12.9%" }, { name = "Demon horn", average_rate = "16.5%" }, { name = "Dark Spirit pact", average_rate = "4.2%" } },
  ["Kindred Warrior"] = { { name = "Demon horn", average_rate = "13.3%" }, { name = "Demon skull", average_rate = "10.3%" } },
  ["King Buffalo"] = { { name = "Slice of buffalo meat", average_rate = "22.2%" }, { name = "Jug of Uleguerand milk", average_rate = "47.8%" }, { name = "Buffalo hide", average_rate = "10.4%" }, { name = "Buffalo horn", average_rate = "4.1%" }, { name = "Ice cluster", average_rate = "0.01%" } },
  ["Magnotaur"] = { { name = "Pygme sainti", average_rate = "14.3%" } },
  ["Maze Lurker"] = { { name = "Shall shell", average_rate = "33.3%" }, { name = "Handful of pugil scales", average_rate = "33.3%" } },
  ["Mindgazer"] = { { name = "Vial of mercury", average_rate = "50.1%" }, { name = "Hecteyes eye", average_rate = "8.4%" } },
  ["Molech"] = { { name = "Taurus horn", average_rate = "20.1%" }, { name = "Taurus wing", average_rate = "9.0%" } },
  ["Morozko"] = { { name = "Snoll arm", average_rate = "29.2%" } },
  ["Mountain Worm"] = { { name = "Chunk of zincite", average_rate = "36.5%" }, { name = "Chunk of zinc ore", average_rate = "24.0%" }, { name = "Chunk of iron ore", average_rate = "2.7%" }, { name = "Heavy gauntlets", average_rate = "0.70%" }, { name = "Chunk of silver ore", average_rate = "0.09%" } },
  ["Nightmare Bats"] = { { name = "Bat wing", average_rate = "33.3%" }, { name = "Bat fang", average_rate = "17.6%" }, { name = "Vial of fiend blood", average_rate = "6.9%" }, { name = "Vial of beastman blood", average_rate = "2.0%" } },
  ["Nival Raptor"] = { { name = "Raptor skin", average_rate = "1.4%" } },
  ["Phasma"] = { { name = "Square of cotton cloth", average_rate = "35.4%" }, { name = "Scroll of Blizzaga II", average_rate = "21.5%" } },
  ["Polar Hare"] = { { name = "Slice of hare meat", average_rate = "27.4%" }, { name = "Rabbit hide", average_rate = "15.7%" }, { name = "Frost turnip", average_rate = "6.8%" } },
  ["Scowlenkos"] = { { name = "Bottle of Ahriman tears", average_rate = "55.8%" }, { name = "Ahriman wing", average_rate = "12.3%" }, { name = "Ahriman lens", average_rate = "26.5%" } },
  ["Skvader"] = { { name = "Aptant of haelan", average_rate = "14.7%" }, { name = "Aptant of geoc", average_rate = "17.6%" } },
  ["Smolenkos"] = { { name = "Bottle of Ahriman tears", average_rate = "43.0%" }, { name = "Ahriman lens", average_rate = "20.2%" }, { name = "Ahriman wing", average_rate = "10.2%" } },
  ["Snoll"] = { { name = "Snoll arm", average_rate = "28.3%" }, { name = "Ice cluster", average_rate = "0.01%" } },
  ["Snow Maiden"] = { { name = "Snoll arm", average_rate = "59.1%" }, { name = "Purgatory collar", average_rate = "9.1%" } },
  ["Srei Ap"] = { { name = "Scroll of Blizzaga II", average_rate = "17.3%" }, { name = "Square of cotton cloth", average_rate = "30.8%" } },
  ["Stygian Demon"] = { { name = "Ice Spirit pact", average_rate = "9.3%" }, { name = "Demon skull", average_rate = "8.0%" }, { name = "Demon horn", average_rate = "11.0%" } },
  ["Succubus Bats"] = { { name = "Bat wing", average_rate = "24.8%" }, { name = "Vial of fiend blood", average_rate = "8.0%" }, { name = "Bat fang", average_rate = "14.8%" }, { name = "Vial of beastman blood", average_rate = "1.1%" } },
  ["Tyrannotaur"] = { { name = "Taurus horn", average_rate = "19.6%" }, { name = "Taurus wing", average_rate = "8.5%" } },
  ["Uleguerand Tiger"] = { { name = "Black tiger fang", average_rate = "27.9%" }, { name = "Snow lily", average_rate = "7.3%" }, { name = "Black tiger hide", average_rate = "15.0%" } },
  ["Variable Hare"] = { { name = "Slice of hare meat", average_rate = "30.2%" }, { name = "Frost turnip", average_rate = "7.6%" }, { name = "Rabbit hide", average_rate = "15.7%" }, { name = "Earth cluster", average_rate = "0.00%" } },
  ["White Coney"] = { { name = "Slice of hare meat", average_rate = "52.9%" }, { name = "Selene's bow", average_rate = "20.6%" }, { name = "Frost turnip", average_rate = "11.8%" } },
}
