-- Zone: Wajaom Woodlands
return {
  ["Aht Urhgan Attercop"] = { { name = "Spider web", average_rate = "40.5%" }, { name = "Frayed arrow", average_rate = "6.3%" } },
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "147.1%" } },
  ["Ameretat"] = { { name = "Vial of Jody's acid", average_rate = "28.3%" }, { name = "Ameretat vine", average_rate = "24.3%" }, { name = "Lacquer tree log", average_rate = "2.8%" } },
  ["Berried Chigoe"] = { { name = "Vial of beast blood", average_rate = "133.3%" } },
  ["Carmine Eruca"] = { { name = "Crawler egg", average_rate = "27.8%" }, { name = "Spool of silk thread", average_rate = "9.9%" }, { name = "Piece of crawler cocoon", average_rate = "18.4%" } },
  ["Chelicerata"] = { { name = "Aptant of arkhe", average_rate = "15.3%" }, { name = "Aptant of tachus", average_rate = "16.0%" } },
  ["Chigoe"] = { { name = "Vial of chimera blood", average_rate = "37.2%" }, { name = "Vial of demon blood", average_rate = "2.2%" } },
  ["Dark Bugler"] = { { name = "Imp horn", average_rate = "40.0%" } },
  ["Defoliate Treant"] = { { name = "Sprig of mistletoe", average_rate = "29.2%" }, { name = "Dryad root", average_rate = "42.3%" }, { name = "Puffball", average_rate = "16.4%" }, { name = "Mahogany log", average_rate = "2.2%" }, { name = "Petrified log", average_rate = "0.68%" }, { name = "Rosewood log", average_rate = "3.5%" }, { name = "Ebony log", average_rate = "1.4%" } },
  ["Gharial"] = { { name = "Tartaglia", average_rate = "16.2%" } },
  ["Gotoh Zha The Redolent"] = { { name = "Gotoh Zha's necklace", average_rate = "104.9%" }, { name = "Aurum cuisses", average_rate = "46.2%" }, { name = "Light grip", average_rate = "41.8%" }, { name = "Enkidu's mittens", average_rate = "35.7%" }, { name = "Water grip", average_rate = "41.1%" }, { name = "Naglering", average_rate = "37.3%" } },
  ["Grand Marid"] = { { name = "Marid tusk", average_rate = "137.5%" }, { name = "Marid hide", average_rate = "43.4%" }, { name = "Lock of marid hair", average_rate = "10.5%" } },
  ["Great Ameretat"] = { { name = "Vial of Jody's acid", average_rate = "19.6%" }, { name = "Ameretat vine", average_rate = "25.3%" }, { name = "Lacquer tree log", average_rate = "2.7%" } },
  ["Haunt"] = { { name = "Square of cotton cloth", average_rate = "42.0%" }, { name = "Revival tree root", average_rate = "13.8%" } },
  ["Hydra"] = { { name = "Hydra scale", average_rate = "149.0%" }, { name = "Chunk of hydra meat", average_rate = "207.9%" }, { name = "Hydra fang", average_rate = "156.5%" }, { name = "Sirius axe", average_rate = "48.2%" }, { name = "Berserker's torque", average_rate = "50.6%" } },
  ["Iriz Ima"] = { { name = "Ferrara", average_rate = "12.6%" }, { name = "Iriz Ima's hide", average_rate = "105.8%" }, { name = "Marid tusk", average_rate = "4.8%" }, { name = "Avocat pigaches", average_rate = "12.3%" } },
  ["Jaded Jody"] = { { name = "Scogan's knuckles", average_rate = "43.0%" }, { name = "Jet seraweels", average_rate = "26.7%" } },
  ["Lesser Colibri"] = { { name = "Colibri feather", average_rate = "38.1%" }, { name = "Colibri beak", average_rate = "25.8%" } },
  ["Mamool Ja Bounder"] = { { name = "Mamook tanscale key", average_rate = "12.2%" }, { name = "Blue mage's testimony", average_rate = "14.7%" }, { name = "Mamool Ja helmet", average_rate = "2.2%" } },
  ["Mamool Ja Mimicker"] = { { name = "Mamook tanscale key", average_rate = "19.4%" }, { name = "Blue mage's testimony", average_rate = "17.9%" }, { name = "Mamool Ja helmet", average_rate = "1.6%" } },
  ["Mamool Ja Savant"] = { { name = "Mamook tanscale key", average_rate = "15.3%" }, { name = "Blue mage's testimony", average_rate = "15.5%" }, { name = "Mamool Ja collar", average_rate = "2.8%" } },
  ["Mamool Ja Sophist"] = { { name = "Blue mage's testimony", average_rate = "14.5%" }, { name = "Mamook tanscale key", average_rate = "11.0%" }, { name = "Mamool Ja collar", average_rate = "0.69%" } },
  ["Mamool Ja Zenist"] = { { name = "Mamook tanscale key", average_rate = "14.6%" }, { name = "Blue mage's testimony", average_rate = "17.1%" }, { name = "Mamool Ja helmet", average_rate = "1.6%" } },
  ["Marid"] = { { name = "Marid tusk", average_rate = "152.9%" }, { name = "Marid hide", average_rate = "43.4%" }, { name = "Lock of marid hair", average_rate = "9.7%" } },
  ["Puk"] = { { name = "Puk wing", average_rate = "45.4%" }, { name = "Puk egg", average_rate = "16.6%" }, { name = "Vial of chimera blood", average_rate = "8.0%" } },
  ["Red Kisser"] = { { name = "Vial of beastman blood", average_rate = "7.9%" }, { name = "Carbuncle's ruby", average_rate = "1.3%" }, { name = "Vial of fiend blood", average_rate = "14.7%" } },
  ["Soldier Pephredo"] = { { name = "Pephredo hive chip", average_rate = "33.0%" }, { name = "Serving of royal jelly", average_rate = "2.4%" }, { name = "Pot of white honey", average_rate = "17.2%" }, { name = "Giant stinger", average_rate = "8.1%" } },
  ["Tinnin"] = { { name = "Hydra scale", average_rate = "136.5%" }, { name = "Chunk of hydra meat", average_rate = "105.2%" }, { name = "Hydra fang", average_rate = "105.2%" }, { name = "Tinnin's fang", average_rate = "104.9%" }, { name = "Enkidu's harness", average_rate = "35.2%" }, { name = "Oracle's cap", average_rate = "32.9%" }, { name = "Enkidu's cap", average_rate = "43.0%" }, { name = "Hachiryu sune-ate", average_rate = "8.7%" }, { name = "Shusui", average_rate = "11.9%" }, { name = "Alkalurops", average_rate = "8.0%" } },
  ["Treant Sapling"] = { { name = "Treant bulb", average_rate = "29.2%" }, { name = "Bag of grain seeds", average_rate = "2.0%" }, { name = "Bag of fruit seeds", average_rate = "7.2%" } },
  ["Vulpangue"] = { { name = "Vulpangue's wing", average_rate = "106.0%" }, { name = "Karura hachigane", average_rate = "26.8%" }, { name = "Sylphid epee", average_rate = "26.8%" } },
  ["Wajaom Tiger"] = { { name = "Rusty medal", average_rate = "9.0%" }, { name = "Black tiger fang", average_rate = "28.6%" } },
  ["Woodland Runner"] = { { name = "Raptor skin", average_rate = "16.2%" } },
  ["Woodtroll Dark Knight"] = { { name = "Puppetmaster's testimony", average_rate = "13.2%" }, { name = "Halvung brass key", average_rate = "6.4%" }, { name = "Slab of plumbago", average_rate = "14.5%" }, { name = "Troll vambrace", average_rate = "2.9%" } },
  ["Woodtroll Monk"] = { { name = "Puppetmaster's testimony", average_rate = "13.1%" }, { name = "Halvung brass key", average_rate = "5.0%" }, { name = "Troll pauldron", average_rate = "1.7%" } },
  ["Woodtroll Ranger"] = { { name = "Puppetmaster's testimony", average_rate = "14.8%" }, { name = "Troll pauldron", average_rate = "2.1%" }, { name = "Halvung brass key", average_rate = "3.7%" } },
  ["Woodtroll Warrior"] = { { name = "Puppetmaster's testimony", average_rate = "16.0%" }, { name = "Slab of plumbago", average_rate = "14.2%" }, { name = "Troll vambrace", average_rate = "3.0%" }, { name = "Halvung brass key", average_rate = "4.8%" } },
  ["Worker Pephredo"] = { { name = "Pephredo hive chip", average_rate = "33.3%" }, { name = "Pot of white honey", average_rate = "16.9%" }, { name = "Giant stinger", average_rate = "8.1%" }, { name = "Serving of royal jelly", average_rate = "2.4%" } },
  ["Zoraal Ja's Pkuucha"] = { { name = "Fowling earring", average_rate = "33.3%" } },
}
