-- Zone: Bhaflau Thickets
return {
  ["Aht Urhgan Attercop"] = { { name = "Frayed arrow", average_rate = "8.3%" }, { name = "Spider web", average_rate = "33.3%" } },
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "158.4%" } },
  ["Ameretat"] = { { name = "Ameretat vine", average_rate = "23.8%" }, { name = "Vial of Jody's acid", average_rate = "26.1%" }, { name = "Lacquer tree log", average_rate = "2.0%" } },
  ["Berried Chigoe"] = { { name = "Vial of beast blood", average_rate = "80.0%" }, { name = "Philosopher's stone", average_rate = "40.0%" } },
  ["Chigoe"] = { { name = "Vial of chimera blood", average_rate = "31.3%" }, { name = "Vial of demon blood", average_rate = "2.0%" } },
  ["Colibri"] = { { name = "Colibri feather", average_rate = "45.8%" }, { name = "Colibri beak", average_rate = "16.0%" } },
  ["Dark Bugler"] = { { name = "Imp horn", average_rate = "25.0%" } },
  ["Date Eruca"] = { { name = "Crawler egg", average_rate = "34.4%" }, { name = "Piece of crawler cocoon", average_rate = "20.0%" }, { name = "Spool of silk thread", average_rate = "8.0%" } },
  ["Dea"] = { { name = "Dea's horn", average_rate = "106.2%" }, { name = "Cletine", average_rate = "38.2%" }, { name = "Oracle's pigaches", average_rate = "46.3%" }, { name = "Fire grip", average_rate = "42.8%" }, { name = "Dark grip", average_rate = "40.4%" }, { name = "Enkidu's subligar", average_rate = "36.0%" } },
  ["Emergent Elm"] = { { name = "Gloom claymore", average_rate = "41.3%" }, { name = "Arborist nails", average_rate = "20.6%" } },
  ["Grand Marid"] = { { name = "Marid tusk", average_rate = "124.9%" }, { name = "Marid hide", average_rate = "33.6%" }, { name = "Lock of marid hair", average_rate = "7.9%" } },
  ["Greater Colibri"] = { { name = "Colibri feather", average_rate = "37.7%" }, { name = "Colibri beak", average_rate = "25.0%" } },
  ["Harvestman"] = { { name = "Aptant of primus", average_rate = "19.7%" }, { name = "Aptant of bellum", average_rate = "14.6%" } },
  ["Haunt"] = { { name = "Square of cotton cloth", average_rate = "41.6%" }, { name = "Revival tree root", average_rate = "15.5%" } },
  ["Incubus Bats"] = { { name = "Bat wing", average_rate = "34.8%" }, { name = "Bat fang", average_rate = "15.9%" }, { name = "Vial of fiend blood", average_rate = "4.4%" }, { name = "Vial of beastman blood", average_rate = "1.3%" } },
  ["Lesser Colibri"] = { { name = "Colibri beak", average_rate = "20.9%" }, { name = "Colibri feather", average_rate = "32.6%" } },
  ["Lividroot Amooshah"] = { { name = "Amooshah's tendril", average_rate = "104.7%" }, { name = "Nobushi kyahan", average_rate = "29.1%" }, { name = "Reikyo hairpin", average_rate = "27.0%" } },
  ["Mahishasura"] = { { name = "Veuglaire", average_rate = "23.5%" } },
  ["Mamool Ja Blusterer"] = { { name = "Mamook blackscale key", average_rate = "16.2%" }, { name = "Mamool Ja collar", average_rate = "2.5%" } },
  ["Mamool Ja Infiltrator"] = { { name = "Mamook blackscale key", average_rate = "11.0%" }, { name = "Mamool Ja helmet", average_rate = "1.6%" } },
  ["Mamool Ja Lurker"] = { { name = "Tariqah -1", average_rate = "15.4%" }, { name = "Macuahuitl -1", average_rate = "37.0%" }, { name = "Mamool Ja helmet", average_rate = "1.4%" } },
  ["Mamool Ja Mimer"] = { { name = "Macuahuitl -1", average_rate = "41.9%" }, { name = "Tariqah -1", average_rate = "14.8%" }, { name = "Mamool Ja helmet", average_rate = "1.2%" } },
  ["Mamool Ja Philosopher"] = { { name = "Mamook blackscale key", average_rate = "13.2%" }, { name = "Mamool Ja collar", average_rate = "1.9%" } },
  ["Mamool Ja Pikeman"] = { { name = "Mamook blackscale key", average_rate = "11.3%" }, { name = "Mamool Ja helmet", average_rate = "1.6%" } },
  ["Mamool Ja Stabler"] = { { name = "Mamook blackscale key", average_rate = "19.7%" }, { name = "Tariqah -1", average_rate = "15.1%" }, { name = "Mamool Ja helmet", average_rate = "1.5%" } },
  ["Marid"] = { { name = "Marid tusk", average_rate = "139.7%" }, { name = "Marid hide", average_rate = "36.7%" }, { name = "Lock of marid hair", average_rate = "9.2%" } },
  ["Nis Puk"] = { { name = "Tempest belt", average_rate = "18.6%" } },
  ["Olden Treant"] = { { name = "Dryad root", average_rate = "50.9%" }, { name = "Sprig of mistletoe", average_rate = "36.5%" }, { name = "Ebony log", average_rate = "1.8%" }, { name = "Puffball", average_rate = "18.4%" }, { name = "Petrified log", average_rate = "0.89%" }, { name = "Mahogany log", average_rate = "2.7%" }, { name = "Rosewood log", average_rate = "3.5%" } },
  ["Red Kisser"] = { { name = "Vial of fiend blood", average_rate = "26.9%" }, { name = "Vial of beastman blood", average_rate = "11.2%" }, { name = "Carbuncle's ruby", average_rate = "1.2%" } },
  ["Sea Puk"] = { { name = "Puk wing", average_rate = "44.7%" }, { name = "Puk egg", average_rate = "31.3%" }, { name = "Vial of chimera blood", average_rate = "17.5%" } },
  ["Skoffin"] = { { name = "Wyvern skin", average_rate = "15.4%" }, { name = "Wyvern wing", average_rate = "8.3%" } },
  ["Treant Sapling"] = { { name = "Bag of fruit seeds", average_rate = "6.9%" }, { name = "Treant bulb", average_rate = "27.0%" }, { name = "Bag of grain seeds", average_rate = "1.9%" } },
  ["Troll Sabreur"] = { { name = "Halvung brass key", average_rate = "8.1%" }, { name = "Puppetmaster's testimony", average_rate = "23.9%" }, { name = "Troll pauldron", average_rate = "1.5%" }, { name = "Vial of Moblin oil", average_rate = "3.1%" } },
  ["Troll Shieldbearer"] = { { name = "Puppetmaster's testimony", average_rate = "17.0%" }, { name = "Halvung brass key", average_rate = "8.8%" }, { name = "Troll vambrace", average_rate = "2.0%" }, { name = "Vial of Moblin oil", average_rate = "2.7%" } },
  ["Troll Surveillant"] = { { name = "Puppetmaster's testimony", average_rate = "19.4%" }, { name = "Troll pauldron", average_rate = "3.0%" }, { name = "Halvung brass key", average_rate = "5.2%" }, { name = "Vial of Moblin oil", average_rate = "4.3%" } },
  ["Wajaom Tiger"] = { { name = "Rusty medal", average_rate = "11.8%" }, { name = "Black tiger fang", average_rate = "31.2%" } },
  ["Wivre"] = { { name = "Wivre maul", average_rate = "25.8%" }, { name = "Wivre horn", average_rate = "6.6%" }, { name = "Wivre hide", average_rate = "1.6%" } },
}
