-- Zone: Arrapago Reef
return {
  ["Archaic Mirror"] = { { name = "Archaic mirror", average_rate = "93.1%" } },
  ["Arrapago Apkallu"] = { { name = "Apkallu feather", average_rate = "38.1%" }, { name = "Apkallu egg", average_rate = "14.4%" } },
  ["Arrapago Leech"] = { { name = "Vial of fiend blood", average_rate = "42.9%" }, { name = "Vial of beastman blood", average_rate = "14.3%" } },
  ["Ashakku"] = { { name = "Vial of fiend blood", average_rate = "14.5%" }, { name = "Vial of beastman blood", average_rate = "6.1%" }, { name = "Carbuncle's ruby", average_rate = "2.3%" } },
  ["Bhoot"] = { { name = "Square of mohbwa cloth", average_rate = "28.2%" }, { name = "Revival tree root", average_rate = "17.1%" } },
  ["Bloody Bones"] = { { name = "Blackjack", average_rate = "66.7%" }, { name = "Ace's locket", average_rate = "33.3%" } },
  ["Chimera Clot"] = { { name = "Handful of clot plasma", average_rate = "66.7%" } },
  ["Dark Elemental"] = { { name = "Dark cluster", average_rate = "150.0%" } },
  ["Draugar Servant"] = { { name = "Bone chip", average_rate = "29.8%" }, { name = "Lamian fang key", average_rate = "12.2%" } },
  ["Dweomershell"] = { { name = "Slice of land crab meat", average_rate = "32.2%" }, { name = "Crab shell", average_rate = "15.8%" }, { name = "Sack of white sand", average_rate = "8.6%" }, { name = "High-quality crab shell", average_rate = "1.4%" } },
  ["Emperor Apkallu"] = { { name = "Apkallu feather", average_rate = "43.8%" }, { name = "Apkallu egg", average_rate = "12.5%" } },
  ["Ephramadian Shade"] = { { name = "Timeworn talisman", average_rate = "26.5%" } },
  ["Euryale"] = { { name = "Lyft jambiya", average_rate = "7.3%" } },
  ["Heraldic Imp"] = { { name = "Imp horn", average_rate = "10.2%" }, { name = "Imp wing", average_rate = "41.6%" } },
  ["Ice Elemental"] = { { name = "Ice cluster", average_rate = "127.3%" } },
  ["Jnun"] = { { name = "Revival tree root", average_rate = "29.0%" }, { name = "Undead skin", average_rate = "18.5%" } },
  ["Lahama"] = { { name = "Seashell", average_rate = "107.5%" }, { name = "Shall shell", average_rate = "6.0%" } },
  ["Lamia Bellydancer"] = { { name = "Lamia skin", average_rate = "27.6%" }, { name = "Lamian armlet", average_rate = "6.0%" }, { name = "Vial of chimera blood", average_rate = "15.5%" } },
  ["Lamia Dancer"] = { { name = "Lamian armlet", average_rate = "1.8%" }, { name = "Corsair's testimony", average_rate = "20.8%" }, { name = "Vial of chimera blood", average_rate = "7.5%" }, { name = "Lamia skin", average_rate = "14.0%" } },
  ["Lamia Dartist"] = { { name = "Lamia skin", average_rate = "14.7%" }, { name = "Corsair's testimony", average_rate = "21.2%" }, { name = "Vial of chimera blood", average_rate = "6.9%" }, { name = "Lamian armlet", average_rate = "1.7%" } },
  ["Lamia Deathdancer"] = { { name = "Lamia skin", average_rate = "22.6%" }, { name = "Vial of chimera blood", average_rate = "11.3%" }, { name = "Lamian armlet", average_rate = "1.9%" } },
  ["Lamia Fatedealer"] = { { name = "Corsair's testimony", average_rate = "25.5%" }, { name = "Vial of chimera blood", average_rate = "6.4%" }, { name = "Lamian armlet", average_rate = "1.4%" } },
  ["Lamia Graverobber"] = { { name = "Corsair's testimony", average_rate = "21.7%" }, { name = "Lamian armlet", average_rate = "1.7%" }, { name = "Lamia skin", average_rate = "13.6%" }, { name = "Vial of chimera blood", average_rate = "8.0%" } },
  ["Lamia Idolater"] = { { name = "Qutrub bandage", average_rate = "39.0%" }, { name = "Lamian claw key", average_rate = "9.0%" }, { name = "Lamian bone key", average_rate = "11.4%" }, { name = "Qutrub gorget", average_rate = "2.8%" } },
  ["Lamia Necromancer"] = { { name = "Vial of chimera blood", average_rate = "14.7%" }, { name = "Lamia skin", average_rate = "34.3%" }, { name = "Lamian armlet", average_rate = "1.2%" } },
  ["Lamia No.19"] = { { name = "Templar mace", average_rate = "62.5%" }, { name = "Exorcist hose", average_rate = "62.5%" } },
  ["Lamia Toxophilite"] = { { name = "Lamia skin", average_rate = "34.8%" }, { name = "Lamian kaman -1", average_rate = "18.3%" }, { name = "Lamian armlet", average_rate = "3.7%" } },
  ["Lamie Bellydancer"] = { { name = "Lamia skin", average_rate = "33.3%" }, { name = "Vial of chimera blood", average_rate = "15.4%" }, { name = "Lamian armlet", average_rate = "5.1%" }, { name = "Lamian armlet", average_rate = "2.6%" } },
  ["Lamie Deathdancer"] = { { name = "Lamia skin", average_rate = "28.0%" }, { name = "Vial of chimera blood", average_rate = "12.0%" } },
  ["Lamie Necromancer"] = { { name = "Lamia skin", average_rate = "20.0%" }, { name = "Vial of chimera blood", average_rate = "10.0%" } },
  ["Lamie No.7"] = { { name = "Corsair's scimitar", average_rate = "40.3%" }, { name = "Lamia skin", average_rate = "9.3%" }, { name = "Vial of chimera blood", average_rate = "10.1%" }, { name = "Lamian armlet", average_rate = "2.3%" } },
  ["Lamie No.8"] = { { name = "Mercenary's turban", average_rate = "31.0%" }, { name = "Vial of chimera blood", average_rate = "8.0%" }, { name = "Lamian armlet", average_rate = "1.8%" }, { name = "Lamia skin", average_rate = "15.0%" } },
  ["Lamie No.9"] = { { name = "Evoker's gages", average_rate = "36.7%" }, { name = "Lamia skin", average_rate = "14.2%" }, { name = "Lamian armlet", average_rate = "0.83%" } },
  ["Lamie Toxophilite"] = { { name = "Lamian armlet", average_rate = "8.0%" }, { name = "Lamian kaman -1", average_rate = "24.0%" }, { name = "Lamia skin", average_rate = "12.0%" } },
  ["Lil' Apkallu"] = { { name = "Lil' Apkallu's egg", average_rate = "104.4%" }, { name = "Hakke habaki", average_rate = "29.2%" }, { name = "Numerist pumps", average_rate = "28.1%" } },
  ["Llamhigyn Y Dwr"] = { { name = "Undead skin", average_rate = "66.7%" } },
  ["Medusa"] = { { name = "Medusa's armlet", average_rate = "51.3%" }, { name = "Mercenary's dastanas", average_rate = "38.4%" } },
  ["Merrow Bladedancer"] = { { name = "Lamian fang key", average_rate = "15.7%" }, { name = "Merrow scale", average_rate = "32.1%" }, { name = "Vial of chimera blood", average_rate = "8.9%" } },
  ["Merrow Chantress"] = { { name = "Corsair's testimony", average_rate = "26.4%" }, { name = "Lamian fang key", average_rate = "13.6%" }, { name = "Merrow scale", average_rate = "7.4%" }, { name = "Vial of chimera blood", average_rate = "2.2%" } },
  ["Merrow Icedancer"] = { { name = "Corsair's testimony", average_rate = "22.8%" }, { name = "Lamian fang key", average_rate = "12.0%" }, { name = "Vial of chimera blood", average_rate = "2.2%" }, { name = "Merrow scale", average_rate = "6.8%" } },
  ["Merrow Kabukidancer"] = { { name = "Merrow scale", average_rate = "8.3%" }, { name = "Corsair's testimony", average_rate = "20.8%" }, { name = "Lamian fang key", average_rate = "11.6%" }, { name = "Vial of chimera blood", average_rate = "1.4%" } },
  ["Merrow No.5"] = { { name = "Volunteer's nails", average_rate = "34.2%" }, { name = "Merrow scale", average_rate = "15.8%" }, { name = "Vial of chimera blood", average_rate = "8.8%" } },
  ["Merrow Shadowdancer"] = { { name = "Corsair's testimony", average_rate = "23.3%" }, { name = "Merrow scale", average_rate = "15.8%" }, { name = "Lamian fang key", average_rate = "25.8%" }, { name = "Vial of chimera blood", average_rate = "8.6%" } },
  ["Merrow Songstress"] = { { name = "Merrow scale", average_rate = "33.3%" }, { name = "Lamian fang key", average_rate = "13.8%" }, { name = "Vial of chimera blood", average_rate = "5.6%" } },
  ["Merrow Typhoondancer"] = { { name = "Merrow scale", average_rate = "34.6%" }, { name = "Lamian fang key", average_rate = "15.0%" }, { name = "Vial of chimera blood", average_rate = "8.5%" } },
  ["Merrow Wavedancer"] = { { name = "Lamian fang key", average_rate = "13.4%" }, { name = "Merrow scale", average_rate = "32.1%" }, { name = "Vial of chimera blood", average_rate = "6.8%" } },
  ["Naraka Bat"] = { { name = "Bat fang", average_rate = "11.8%" }, { name = "Bat wing", average_rate = "27.6%" }, { name = "Vial of fiend blood", average_rate = "7.9%" }, { name = "Vial of beastman blood", average_rate = "1.3%" } },
  ["Nergal"] = { { name = "Vial of fiend blood", average_rate = "12.8%" }, { name = "Vial of beastman blood", average_rate = "4.6%" }, { name = "Carbuncle's ruby", average_rate = "0.92%" } },
  ["Nipper"] = { { name = "Crab shell", average_rate = "12.9%" }, { name = "Sack of white sand", average_rate = "4.1%" }, { name = "Slice of land crab meat", average_rate = "18.6%" }, { name = "High-quality crab shell", average_rate = "1.5%" } },
  ["Nirgali"] = { { name = "Vial of fiend blood", average_rate = "16.7%" }, { name = "Vial of beastman blood", average_rate = "8.3%" } },
  ["Nix Bladedancer"] = { { name = "Merrow scale", average_rate = "29.8%" }, { name = "Lamian fang key", average_rate = "10.6%" }, { name = "Vial of chimera blood", average_rate = "4.3%" } },
  ["Nix Songstress"] = { { name = "Merrow scale", average_rate = "35.3%" }, { name = "Lamian fang key", average_rate = "14.5%" }, { name = "Vial of chimera blood", average_rate = "7.6%" } },
  ["Nix Typhoondancer"] = { { name = "Vial of chimera blood", average_rate = "10.5%" }, { name = "Merrow scale", average_rate = "39.5%" }, { name = "Lamian fang key", average_rate = "5.3%" } },
  ["Nix Wavedancer"] = { { name = "Vial of chimera blood", average_rate = "9.1%" }, { name = "Merrow scale", average_rate = "27.3%" }, { name = "Lamian fang key", average_rate = "9.1%" } },
  ["Nostokulshedra"] = { { name = "Seashell", average_rate = "103.7%" }, { name = "Shall shell", average_rate = "8.1%" } },
  ["Nuhn"] = { { name = "Nuhn's esca", average_rate = "105.8%" }, { name = "Oninohocho", average_rate = "37.1%" }, { name = "Oracle's pigaches", average_rate = "48.4%" }, { name = "Light grip", average_rate = "42.0%" }, { name = "Enkidu's mittens", average_rate = "35.8%" }, { name = "Wind grip", average_rate = "42.8%" } },
  ["Phasma"] = { { name = "Square of cotton cloth", average_rate = "34.1%" }, { name = "Revival tree root", average_rate = "17.4%" } },
  ["Purgatory Bat"] = { { name = "Bat wing", average_rate = "37.5%" }, { name = "Bat fang", average_rate = "12.5%" } },
  ["Qiqirn Trailer"] = { { name = "Pebble", average_rate = "18.2%" }, { name = "Handful of almonds", average_rate = "36.4%" }, { name = "Qiqirn cape", average_rate = "9.1%" }, { name = "Bowl of Nashmau stew", average_rate = "9.1%" } },
  ["Qiqirn Treasure Hunter"] = { { name = "Handful of almonds", average_rate = "75.0%" } },
  ["Qutrub"] = { { name = "Qutrub bandage", average_rate = "30.2%" }, { name = "Lamian bone key", average_rate = "12.2%" }, { name = "Qutrub gorget", average_rate = "2.2%" } },
  ["Reserve Draugar"] = { { name = "Lamian fang key", average_rate = "16.0%" }, { name = "Bone chip", average_rate = "28.7%" }, { name = "Revival tree root", average_rate = "16.0%" } },
  ["Seneschal Imp"] = { { name = "Imp horn", average_rate = "9.1%" }, { name = "Imp wing", average_rate = "42.0%" } },
  ["Soulflayer"] = { { name = "Soulflayer tentacle", average_rate = "29.1%" }, { name = "Soulflayer staff", average_rate = "15.3%" }, { name = "Soulflayer robe", average_rate = "9.2%" } },
  ["Velionis"] = { { name = "Velionis's bone", average_rate = "107.9%" }, { name = "White joker", average_rate = "27.1%" }, { name = "Corsair's belt", average_rate = "27.7%" } },
  ["Wootzshell"] = { { name = "Slice of land crab meat", average_rate = "8.3%" }, { name = "Crab shell", average_rate = "8.3%" } },
  ["Zareehkl The Jubilant"] = { { name = "Zareekhl's neckpiece", average_rate = "107.0%" }, { name = "Zareehkl jambiya", average_rate = "27.0%" }, { name = "Zareehkl scythe", average_rate = "26.1%" } },
}
