-- Zone: Talacca Cove
return {
  ["Arrapago Leech"] = { { name = "Vial of fiend blood", average_rate = "27.9%" }, { name = "Vial of beastman blood", average_rate = "14.8%" } },
  ["Gessho"] = { { name = "Scroll of Mage's Ballad III", average_rate = "13.3%" }, { name = "Copy of Rem's Tale, chapter 6", average_rate = "26.7%" }, { name = "Copy of Rem's Tale, chapter 10", average_rate = "46.7%" }, { name = "Square of damascene cloth", average_rate = "6.7%" }, { name = "Pluton", average_rate = "53.3%" }, { name = "Max-potion +3", average_rate = "40.0%" }, { name = "Chunk of hepatizon ore", average_rate = "60.0%" }, { name = "Piece of habu skin", average_rate = "20.0%" }, { name = "Scroll of Valor Minuet V", average_rate = "6.7%" }, { name = "Chunk of beryllium ore", average_rate = "13.3%" }, { name = "Chunk of beitetsu", average_rate = "33.3%" }, { name = "Scroll of Water Carol II", average_rate = "6.7%" }, { name = "Copy of Rem's Tale, chapter 8", average_rate = "26.7%" }, { name = "Copy of Rem's Tale, chapter 7", average_rate = "33.3%" }, { name = "Copy of Rem's Tale, chapter 9", average_rate = "80.0%" }, { name = "Scroll of Stoneja", average_rate = "13.3%" }, { name = "Seraphicaller", average_rate = "26.7%" }, { name = "Scroll of Boost-CHR", average_rate = "6.7%" }, { name = "Pro-ether +3", average_rate = "40.0%" }, { name = "Intelligence potion", average_rate = "6.7%" }, { name = "Plate of Indi-Malaise", average_rate = "6.7%" }, { name = "Pot of urushi", average_rate = "13.3%" }, { name = "Kandza crackows", average_rate = "13.3%" }, { name = "Beitetsu parcel", average_rate = "6.7%" }, { name = "Scroll of Thundara II", average_rate = "6.7%" }, { name = "Tengu-no-obi", average_rate = "6.7%" }, { name = "Pluton case", average_rate = "26.7%" }, { name = "Scroll of Boost-VIT", average_rate = "6.7%" }, { name = "Scarletite ingot", average_rate = "20.0%" }, { name = "Scroll of Blizzara II", average_rate = "6.7%" }, { name = "Scroll of Fira II", average_rate = "6.7%" }, { name = "Riftborn boulder", average_rate = "13.3%" }, { name = "Tengu-no-hane", average_rate = "20.0%" }, { name = "Scroll of Gain-VIT", average_rate = "6.7%" }, { name = "Spool of malboro fiber", average_rate = "6.7%" }, { name = "Ptica headgear", average_rate = "6.7%" } },
  ["Giant Orobon"] = { { name = "Orobon lure", average_rate = "100.0%" }, { name = "Chunk of orobon meat", average_rate = "100.0%" } },
  ["Lahama"] = { { name = "Seashell", average_rate = "114.7%" }, { name = "Shall shell", average_rate = "20.6%" }, { name = "Blue rock", average_rate = "11.8%" } },
  ["Llamhigyn Y Dwr"] = { { name = "Revival tree root", average_rate = "17.6%" }, { name = "Undead skin", average_rate = "11.8%" } },
  ["Maze Lurker"] = { { name = "Lizard skin", average_rate = "100.0%" }, { name = "Lizard tail", average_rate = "100.0%" } },
  ["Talacca Clot"] = { { name = "Handful of clot plasma", average_rate = "18.8%" } },
  ["Wootzshell"] = { { name = "Slice of land crab meat", average_rate = "37.2%" }, { name = "Crab shell", average_rate = "23.1%" }, { name = "Sack of white sand", average_rate = "7.7%" }, { name = "High-quality crab shell", average_rate = "1.3%" } },
}
