-- Zone: Mount Zhayolm
return {
  ["Anantaboga"] = { { name = "Anantaboga's heart", average_rate = "106.3%" }, { name = "Trilling dagger", average_rate = "26.8%" }, { name = "Hacchonenbutsu dangozashi", average_rate = "26.9%" } },
  ["Assassin Fly"] = { { name = "Insect wing", average_rate = "28.2%" } },
  ["Brass Borer"] = { { name = "Brass Borer's cocoon", average_rate = "106.7%" }, { name = "Ritterhentzes", average_rate = "26.8%" }, { name = "Lion tamer", average_rate = "26.2%" } },
  ["Cerberus"] = { { name = "Cerberus claw", average_rate = "205.5%" }, { name = "Cerberus hide", average_rate = "102.9%" }, { name = "Slice of Cerberus meat", average_rate = "102.9%" }, { name = "Algol", average_rate = "47.8%" } },
  ["Chary Apkallu"] = { { name = "Aptant of arkhe", average_rate = "16.3%" }, { name = "Aptant of ishis", average_rate = "26.5%" } },
  ["Claret"] = { { name = "Globule of Claret", average_rate = "107.6%" }, { name = "Kerykeion", average_rate = "24.7%" }, { name = "Almah torque", average_rate = "28.2%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "153.4%" } },
  ["Ebony Pudding"] = { { name = "Chunk of flan meat", average_rate = "41.2%" } },
  ["Energetic Eruca"] = { { name = "Astral staff", average_rate = "38.1%" }, { name = "Hanzo tekko", average_rate = "9.5%" } },
  ["Fahrafahr The Bloodied"] = { { name = "Lyft ferule", average_rate = "23.4%" } },
  ["Fire Elemental"] = { { name = "Fire cluster", average_rate = "176.7%" } },
  ["Garharlor The Unruly"] = { { name = "Genie gages", average_rate = "71.0%" }, { name = "Trance belt", average_rate = "51.6%" } },
  ["Giant Orobon"] = { { name = "Orobon lure", average_rate = "72.2%" } },
  ["Hilltroll Dark Knight"] = { { name = "Slab of plumbago", average_rate = "36.5%" }, { name = "Troll vambrace", average_rate = "3.0%" } },
  ["Hilltroll Monk"] = { { name = "Khroma nugget", average_rate = "7.3%" }, { name = "Troll pauldron", average_rate = "2.0%" } },
  ["Hilltroll Paladin"] = { { name = "Januwiyah -1", average_rate = "18.5%" }, { name = "Jadagna -1", average_rate = "33.9%" }, { name = "Troll vambrace", average_rate = "2.8%" } },
  ["Hilltroll Puppetmaster"] = { { name = "Auto-repair kit II", average_rate = "2.2%" }, { name = "Stabilizer II", average_rate = "3.3%" }, { name = "Troll pauldron", average_rate = "3.5%" }, { name = "Mana jammer II", average_rate = "2.8%" }, { name = "Tension spring II", average_rate = "3.9%" }, { name = "Loudspeaker II", average_rate = "2.5%" }, { name = "Heat seeker", average_rate = "1.5%" }, { name = "Analyzer", average_rate = "1.1%" }, { name = "Heatsink", average_rate = "1.3%" }, { name = "Flashbulb", average_rate = "1.7%" }, { name = "Accelerator II", average_rate = "3.0%" }, { name = "Strobe", average_rate = "1.9%" }, { name = "Mana tank II", average_rate = "2.1%" }, { name = "Pattern reader", average_rate = "1.7%" }, { name = "Armor plate II", average_rate = "2.3%" }, { name = "Scanner", average_rate = "2.0%" }, { name = "Mana converter", average_rate = "0.93%" } },
  ["Hilltroll Ranger"] = { { name = "Khroma nugget", average_rate = "8.0%" }, { name = "Troll pauldron", average_rate = "2.9%" } },
  ["Hilltroll Red Mage"] = { { name = "Hydrangea", average_rate = "14.0%" }, { name = "Troll pauldron", average_rate = "2.5%" } },
  ["Hilltroll Warrior"] = { { name = "Troll vambrace", average_rate = "2.9%" }, { name = "Slab of plumbago", average_rate = "35.2%" }, { name = "Hydrangea", average_rate = "15.0%" } },
  ["Ignamoth"] = { { name = "Octant", average_rate = "22.9%" } },
  ["Khromasoul Bhurborlor"] = { { name = "Bhurborlor's vambrace", average_rate = "106.2%" }, { name = "Oracle's gloves", average_rate = "46.9%" }, { name = "Ice grip", average_rate = "40.5%" }, { name = "Simba buckler", average_rate = "37.0%" }, { name = "Dark grip", average_rate = "40.6%" }, { name = "Enkidu's subligar", average_rate = "34.9%" } },
  ["King Apkallu"] = { { name = "Apkallu egg", average_rate = "42.2%" }, { name = "Apkallu feather", average_rate = "57.7%" } },
  ["Magmatic Eruca"] = { { name = "Crawler egg", average_rate = "27.9%" }, { name = "Piece of crawler cocoon", average_rate = "15.2%" }, { name = "Spool of silk thread", average_rate = "7.4%" } },
  ["Orichalcumshell"] = { { name = "Slice of land crab meat", average_rate = "35.1%" }, { name = "Crab shell", average_rate = "19.3%" }, { name = "High-quality crab shell", average_rate = "2.5%" }, { name = "Sack of silica", average_rate = "8.8%" } },
  ["Phasma"] = { { name = "Revival tree root", average_rate = "14.5%" }, { name = "Square of cotton cloth", average_rate = "37.7%" } },
  ["Sarameya"] = { { name = "Slice of Cerberus meat", average_rate = "105.4%" }, { name = "Cerberus claw", average_rate = "105.3%" }, { name = "Cerberus hide", average_rate = "105.4%" }, { name = "Sarameya's hide", average_rate = "104.8%" }, { name = "Oracle's cap", average_rate = "43.5%" }, { name = "Foolkiller", average_rate = "8.0%" }, { name = "Aurum armet", average_rate = "33.0%" }, { name = "Pachipachio", average_rate = "10.9%" }, { name = "Oracle's robe", average_rate = "34.0%" }, { name = "Hachiryu haidate", average_rate = "7.3%" } },
  ["Scoriaceous Eruca"] = { { name = "Piece of crawler cocoon", average_rate = "16.5%" }, { name = "Crawler egg", average_rate = "29.5%" }, { name = "Spool of silk thread", average_rate = "8.0%" } },
  ["Sicklemoon Crab"] = { { name = "Slice of land crab meat", average_rate = "21.1%" }, { name = "Crab shell", average_rate = "26.3%" }, { name = "Sack of white sand", average_rate = "5.3%" } },
  ["Sicklemoon Jagil"] = { { name = "Handful of pugil scales", average_rate = "13.3%" } },
  ["Sulphuric Jagil"] = { { name = "Handful of pugil scales", average_rate = "14.9%" } },
  ["Sweeping Cluster"] = { { name = "Pinch of cluster ash", average_rate = "15.0%" }, { name = "Cluster arm", average_rate = "7.7%" } },
  ["Volcanic Leech"] = { { name = "Vial of fiend blood", average_rate = "13.0%" }, { name = "Vial of beastman blood", average_rate = "7.1%" }, { name = "Carbuncle's ruby", average_rate = "1.4%" } },
  ["Wamoura"] = { { name = "Wamoura scale", average_rate = "45.9%" }, { name = "Clump of wamoura hair", average_rate = "32.4%" } },
  ["Wamoura Prince"] = { { name = "Wamoura cocoon", average_rate = "16.9%" } },
  ["Wootzshell"] = { { name = "Slice of land crab meat", average_rate = "24.5%" }, { name = "High-quality crab shell", average_rate = "1.4%" }, { name = "Sack of white sand", average_rate = "6.9%" }, { name = "Crab shell", average_rate = "14.6%" } },
  ["Zazalda Clot"] = { { name = "Handful of clot plasma", average_rate = "50.0%" } },
  ["Zazalda Jagil"] = { { name = "Handful of pugil scales", average_rate = "100.0%" } },
  ["Zhayolm Apkallu"] = { { name = "Apkallu feather", average_rate = "45.8%" }, { name = "Apkallu egg", average_rate = "16.8%" } },
}
