-- Zone: Halvung
return {
  ["Achamoth"] = { { name = "Achamoth's antenna", average_rate = "105.9%" }, { name = "Oracle's braconi", average_rate = "46.2%" }, { name = "Ice grip", average_rate = "39.9%" }, { name = "Thunder grip", average_rate = "41.3%" }, { name = "Organics", average_rate = "36.2%" }, { name = "Aurum sabatons", average_rate = "35.7%" } },
  ["Antares"] = { { name = "Scorpion shell", average_rate = "28.6%" }, { name = "High-quality scorpion shell", average_rate = "7.0%" }, { name = "Scorpion claw", average_rate = "42.2%" } },
  ["Archaic Mirror"] = { { name = "Archaic mirror", average_rate = "92.6%" } },
  ["Big Bomb"] = { { name = "Horrent mace", average_rate = "69.6%" }, { name = "Fire bomblet", average_rate = "27.0%" } },
  ["Black Pudding"] = { { name = "Chunk of flan meat", average_rate = "44.9%" } },
  ["Copper Borer"] = { { name = "Wayang kulit mantle", average_rate = "13.3%" } },
  ["Dextrose"] = { { name = "Blob of Dextrose's blubber", average_rate = "104.2%" }, { name = "Achilles' spear", average_rate = "28.3%" }, { name = "Ruby seraweels", average_rate = "27.7%" } },
  ["Dorgerwor The Astute"] = { { name = "Mercenary's mantle", average_rate = "38.9%" }, { name = "Troll pauldron", average_rate = "8.7%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "148.0%" } },
  ["Ebony Pudding"] = { { name = "Chunk of flan meat", average_rate = "43.0%" } },
  ["Farlarder The Shrewd"] = { { name = "Mercenary's subligar", average_rate = "36.9%" }, { name = "Troll pauldron", average_rate = "8.2%" } },
  ["Fire Elemental"] = { { name = "Fire cluster", average_rate = "215.8%" } },
  ["Flammeri"] = { { name = "Musanto", average_rate = "20.0%" } },
  ["Friar's Lantern"] = { { name = "Pinch of bomb ash", average_rate = "52.9%" }, { name = "Smoke-filled flask", average_rate = "5.6%" }, { name = "Bomb arm", average_rate = "7.5%" } },
  ["Gurfurlur The Menacing"] = { { name = "Gurfurlur's helmet", average_rate = "56.6%" }, { name = "Mercenary's ring", average_rate = "39.7%" } },
  ["Kirlirger The Abhorrent"] = { { name = "Mercenary's boots", average_rate = "40.0%" }, { name = "Troll vambrace", average_rate = "5.8%" } },
  ["Magmatic Eruca"] = { { name = "Crawler egg", average_rate = "29.0%" }, { name = "Spool of silk thread", average_rate = "7.2%" }, { name = "Piece of crawler cocoon", average_rate = "15.4%" } },
  ["Maze Lurker"] = { { name = "Lizard skin", average_rate = "100.0%" }, { name = "Lizard tail", average_rate = "100.0%" } },
  ["Moblin Billionaire"] = { { name = "Halvung shakudo key", average_rate = "80.9%" }, { name = "Moblin armor", average_rate = "19.5%" }, { name = "Moblin mask", average_rate = "33.9%" } },
  ["Moblin Millionaire"] = { { name = "Halvung shakudo key", average_rate = "95.6%" }, { name = "Moblin mask", average_rate = "34.7%" }, { name = "Moblin sheepskin", average_rate = "17.3%" }, { name = "Moblin armor", average_rate = "9.9%" } },
  ["Mythril Mouth Monamaq"] = { { name = "Volunteer's earring", average_rate = "38.1%" }, { name = "Moblin armor", average_rate = "22.2%" }, { name = "Moblin mask", average_rate = "13.5%" } },
  ["Purgatory Bat"] = { { name = "Bat fang", average_rate = "16.2%" }, { name = "Bat wing", average_rate = "30.0%" }, { name = "Vial of beastman blood", average_rate = "1.0%" }, { name = "Vial of fiend blood", average_rate = "5.7%" } },
  ["Qiqirn Diamantaire"] = { { name = "Handful of almonds", average_rate = "28.6%" }, { name = "Bowl of Nashmau stew", average_rate = "14.3%" }, { name = "Qiqirn cape", average_rate = "14.3%" } },
  ["Qiqirn Mercenary"] = { { name = "Qiqirn cape", average_rate = "8.3%" }, { name = "Handful of almonds", average_rate = "45.8%" }, { name = "Bowl of Nashmau stew", average_rate = "4.2%" }, { name = "Qiqirn sandbag", average_rate = "4.2%" }, { name = "Pebble", average_rate = "4.2%" }, { name = "Sack of silica", average_rate = "2.1%" } },
  ["Reacton"] = { { name = "Pile of Reacton's ashes", average_rate = "105.2%" }, { name = "Magic strap", average_rate = "27.0%" }, { name = "Reacton arm", average_rate = "26.0%" } },
  ["Troll Artilleryman"] = { { name = "Khroma nugget", average_rate = "8.1%" }, { name = "Halvung bronze key", average_rate = "15.6%" }, { name = "Troll pauldron", average_rate = "3.1%" } },
  ["Troll Cameist"] = { { name = "Puppetmaster's testimony", average_rate = "21.3%" }, { name = "Halvung brass key", average_rate = "7.4%" }, { name = "Troll pauldron", average_rate = "2.8%" }, { name = "Vial of Moblin oil", average_rate = "7.3%" } },
  ["Troll Combatant"] = { { name = "Halvung bronze key", average_rate = "13.7%" }, { name = "Khroma nugget", average_rate = "7.6%" }, { name = "Troll pauldron", average_rate = "2.3%" } },
  ["Troll Cuirasser"] = { { name = "Slab of plumbago", average_rate = "34.1%" }, { name = "Halvung bronze key", average_rate = "14.4%" }, { name = "Troll vambrace", average_rate = "2.2%" } },
  ["Troll Engraver"] = { { name = "Puppetmaster's testimony", average_rate = "20.0%" }, { name = "Halvung brass key", average_rate = "6.4%" }, { name = "Troll pauldron", average_rate = "2.2%" }, { name = "Vial of Moblin oil", average_rate = "8.2%" } },
  ["Troll Gemologist"] = { { name = "Puppetmaster's testimony", average_rate = "21.9%" }, { name = "Troll vambrace", average_rate = "2.4%" }, { name = "Halvung brass key", average_rate = "5.0%" }, { name = "Vial of Moblin oil", average_rate = "7.4%" } },
  ["Troll Grenadier"] = { { name = "Halvung brass key", average_rate = "13.9%" }, { name = "Troll pauldron", average_rate = "2.3%" } },
  ["Troll Ironworker"] = { { name = "Puppetmaster's testimony", average_rate = "20.0%" }, { name = "Halvung brass key", average_rate = "7.8%" }, { name = "Slab of plumbago", average_rate = "16.5%" }, { name = "Troll vambrace", average_rate = "2.9%" } },
  ["Troll Lapidarist"] = { { name = "Slab of plumbago", average_rate = "17.0%" }, { name = "Troll vambrace", average_rate = "2.8%" }, { name = "Puppetmaster's testimony", average_rate = "21.3%" }, { name = "Halvung brass key", average_rate = "5.8%" } },
  ["Troll Machinist"] = { { name = "Halvung bronze key", average_rate = "15.4%" }, { name = "Strobe", average_rate = "1.4%" }, { name = "Troll pauldron", average_rate = "2.6%" }, { name = "Scanner", average_rate = "1.1%" }, { name = "Pattern reader", average_rate = "1.0%" }, { name = "Heatsink", average_rate = "1.2%" }, { name = "Mana converter", average_rate = "0.58%" }, { name = "Flashbulb", average_rate = "1.1%" }, { name = "Heat seeker", average_rate = "1.2%" }, { name = "Analyzer", average_rate = "0.81%" } },
  ["Troll Scrimer"] = { { name = "Slab of plumbago", average_rate = "33.0%" }, { name = "Halvung brass key", average_rate = "14.9%" }, { name = "Troll vambrace", average_rate = "2.4%" } },
  ["Troll Smelter"] = { { name = "Puppetmaster's testimony", average_rate = "20.0%" }, { name = "Halvung brass key", average_rate = "5.8%" }, { name = "Troll pauldron", average_rate = "2.4%" } },
  ["Troll Stoneworker"] = { { name = "Puppetmaster's testimony", average_rate = "19.9%" }, { name = "Halvung brass key", average_rate = "5.6%" }, { name = "Troll pauldron", average_rate = "2.4%" } },
  ["Troll Targeteer"] = { { name = "Jadagna -1", average_rate = "32.9%" }, { name = "Januwiyah -1", average_rate = "16.7%" }, { name = "Troll vambrace", average_rate = "2.0%" } },
  ["Volcanic Bats"] = { { name = "Bat wing", average_rate = "29.5%" }, { name = "Vial of fiend blood", average_rate = "8.5%" }, { name = "Bat fang", average_rate = "19.0%" }, { name = "Vial of beastman blood", average_rate = "2.1%" } },
  ["Wamoura"] = { { name = "Wamoura scale", average_rate = "40.0%" }, { name = "Clump of wamoura hair", average_rate = "28.3%" } },
  ["Wamouracampa"] = { { name = "Wamoura cocoon", average_rate = "8.0%" } },
}
