-- Zone: Mamook
return {
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "130.3%" } },
  ["Archaic Mirror"] = { { name = "Archaic mirror", average_rate = "88.8%" } },
  ["Battle Bugard"] = { { name = "Bugard skin", average_rate = "32.6%" }, { name = "Bugard tusk", average_rate = "2.4%" }, { name = "High-quality bugard skin", average_rate = "7.9%" } },
  ["Brei"] = { { name = "Vial of slime oil", average_rate = "43.5%" } },
  ["Carriage Lizard"] = { { name = "Lizard tail", average_rate = "29.8%" }, { name = "Lizard egg", average_rate = "16.1%" }, { name = "Lizard skin", average_rate = "7.2%" } },
  ["Chamrosh"] = { { name = "Chamrosh's beak", average_rate = "106.7%" }, { name = "Dragoon's earring", average_rate = "29.4%" }, { name = "Erato's cape", average_rate = "26.9%" } },
  ["Colibri"] = { { name = "Colibri feather", average_rate = "35.3%" }, { name = "Colibri beak", average_rate = "14.0%" } },
  ["Darting Kachaal Ja"] = { { name = "Volunteer's belt", average_rate = "39.7%" }, { name = "Mamool Ja collar", average_rate = "6.9%" } },
  ["Devout Radol Ja"] = { { name = "Volunteer's khud", average_rate = "39.0%" }, { name = "Mamool Ja collar", average_rate = "10.4%" } },
  ["Dragonscaled Bugaal Ja"] = { { name = "Beast bazubands", average_rate = "40.4%" }, { name = "Mamool Ja helmet", average_rate = "10.5%" } },
  ["Firedance Magmaal Ja"] = { { name = "Lyft hexagun", average_rate = "24.0%" } },
  ["Gulool Ja Ja"] = { { name = "Ja Ja's chestplate", average_rate = "51.4%" }, { name = "Volunteer's ring", average_rate = "39.8%" } },
  ["Hundredfaced Hapool Ja"] = { { name = "Ryumon", average_rate = "18.5%" }, { name = "Mamool Ja helmet", average_rate = "3.3%" } },
  ["Hunting Raptor"] = { { name = "Raptor skin", average_rate = "13.4%" } },
  ["Iriri Samariri"] = { { name = "Iriri Samariri's hat", average_rate = "104.2%" }, { name = "Paddock trousers", average_rate = "27.0%" }, { name = "Toad mittens", average_rate = "23.3%" } },
  ["Mamool Ja Bloodsucker"] = { { name = "Vial of fiend blood", average_rate = "100.0%" } },
  ["Mamool Ja Blusterer"] = { { name = "Mamook blackscale key", average_rate = "17.3%" }, { name = "Mamool Ja collar", average_rate = "2.1%" } },
  ["Mamool Ja Bounder"] = { { name = "Mamook tanscale key", average_rate = "19.2%" }, { name = "Blue mage's testimony", average_rate = "18.9%" }, { name = "Mamool Ja helmet", average_rate = "2.0%" } },
  ["Mamool Ja Diver"] = { { name = "Mamook silverscale key", average_rate = "71.4%" }, { name = "Seashell", average_rate = "34.5%" }, { name = "Shall shell", average_rate = "17.7%" }, { name = "Coral fragment", average_rate = "9.2%" } },
  ["Mamool Ja Frogman"] = { { name = "Mamook silverscale key", average_rate = "71.5%" }, { name = "Seashell", average_rate = "31.8%" }, { name = "Shall shell", average_rate = "18.1%" }, { name = "Coral fragment", average_rate = "9.7%" } },
  ["Mamool Ja Infiltrator"] = { { name = "Mamook blackscale key", average_rate = "15.7%" }, { name = "Mamool Ja helmet", average_rate = "2.1%" } },
  ["Mamool Ja Lurker"] = { { name = "Macuahuitl -1", average_rate = "45.7%" }, { name = "Tariqah -1", average_rate = "16.1%" }, { name = "Mamool Ja helmet", average_rate = "2.2%" } },
  ["Mamool Ja Mimer"] = { { name = "Macuahuitl -1", average_rate = "46.8%" }, { name = "Tariqah -1", average_rate = "16.5%" }, { name = "Mamool Ja helmet", average_rate = "2.0%" } },
  ["Mamool Ja Mimicker"] = { { name = "Mamook tanscale key", average_rate = "20.1%" }, { name = "Blue mage's testimony", average_rate = "19.5%" }, { name = "Mamool Ja helmet", average_rate = "2.0%" } },
  ["Mamool Ja Philosopher"] = { { name = "Mamook blackscale key", average_rate = "19.4%" }, { name = "Mamool Ja collar", average_rate = "1.7%" } },
  ["Mamool Ja Pikeman"] = { { name = "Mamook blackscale key", average_rate = "15.4%" }, { name = "Mamool Ja helmet", average_rate = "1.7%" } },
  ["Mamool Ja Savant"] = { { name = "Mamook tanscale key", average_rate = "18.7%" }, { name = "Blue mage's testimony", average_rate = "18.1%" }, { name = "Mamool Ja collar", average_rate = "1.7%" } },
  ["Mamool Ja Sophist"] = { { name = "Blue mage's testimony", average_rate = "18.6%" }, { name = "Mamook tanscale key", average_rate = "18.3%" }, { name = "Mamool Ja collar", average_rate = "1.8%" } },
  ["Mamool Ja Spearman"] = { { name = "Mamook tanscale key", average_rate = "21.0%" }, { name = "Blue mage's testimony", average_rate = "24.1%" }, { name = "Mamool Ja helmet", average_rate = "2.6%" } },
  ["Mamool Ja Stabler"] = { { name = "Mamook blackscale key", average_rate = "24.7%" }, { name = "Tariqah -1", average_rate = "14.6%" }, { name = "Mamool Ja helmet", average_rate = "1.4%" } },
  ["Mamool Ja Strapper"] = { { name = "Blue mage's testimony", average_rate = "21.6%" }, { name = "Mamook tanscale key", average_rate = "21.2%" }, { name = "Mamool Ja helmet", average_rate = "2.3%" } },
  ["Mamool Ja Zenist"] = { { name = "Blue mage's testimony", average_rate = "19.4%" }, { name = "Mamook tanscale key", average_rate = "18.3%" }, { name = "Mamool Ja helmet", average_rate = "2.0%" } },
  ["Nipper"] = { { name = "Crab shell", average_rate = "19.6%" }, { name = "Sack of silica", average_rate = "8.8%" }, { name = "Slice of land crab meat", average_rate = "35.1%" }, { name = "High-quality crab shell", average_rate = "0.90%" } },
  ["Poroggo"] = { { name = "Poroggo hat", average_rate = "33.9%" } },
  ["Puk"] = { { name = "Puk wing", average_rate = "44.0%" }, { name = "Vial of chimera blood", average_rate = "6.8%" }, { name = "Puk egg", average_rate = "16.8%" } },
  ["Qiqirn Goldsmith"] = { { name = "Handful of almonds", average_rate = "76.9%" }, { name = "Jar of firesand", average_rate = "7.7%" }, { name = "Bowl of Nashmau stew", average_rate = "7.7%" }, { name = "Pebble", average_rate = "7.7%" } },
  ["Qiqirn Poulterer"] = { { name = "Qiqirn cape", average_rate = "10.0%" }, { name = "Handful of almonds", average_rate = "70.0%" }, { name = "Jar of firesand", average_rate = "10.0%" }, { name = "Pebble", average_rate = "10.0%" }, { name = "Qiqirn sandbag", average_rate = "10.0%" } },
  ["Sea Puk"] = { { name = "Puk wing", average_rate = "44.3%" }, { name = "Vial of chimera blood", average_rate = "18.0%" }, { name = "Puk egg", average_rate = "30.1%" } },
  ["Spinner"] = { { name = "Spider web", average_rate = "33.0%" } },
  ["Suhur Mas"] = { { name = "Sack of silica", average_rate = "29.8%" }, { name = "Handful of pugil scales", average_rate = "14.6%" } },
  ["Venomfang"] = { { name = "Aptant of pera", average_rate = "15.9%" }, { name = "Aptant of tachus", average_rate = "12.7%" } },
  ["Watch Wyvern"] = { { name = "Wyvern skin", average_rate = "16.8%" }, { name = "Wyvern wing", average_rate = "8.7%" } },
  ["Ziz"] = { { name = "Giant bird feather", average_rate = "16.4%" }, { name = "Slice of ziz meat", average_rate = "32.2%" } },
  ["Zizzy Zillah"] = { { name = "Fencing bracers", average_rate = "59.3%" }, { name = "Namikirimaru", average_rate = "25.9%" } },
}
