-- Zone: Aydeewa Subterrane
return {
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "152.9%" } },
  ["Anautogenous Slug"] = { { name = "Vial of beastman blood", average_rate = "25.0%" } },
  ["Aydeewa Crab"] = { { name = "Slice of land crab meat", average_rate = "50.0%" } },
  ["Aydeewa Diremite"] = { { name = "Tuft of colorful hair", average_rate = "21.3%" }, { name = "Spool of bloodthread", average_rate = "15.2%" }, { name = "Bottle of avatar blood", average_rate = "6.7%" } },
  ["Bluestreak Gyugyuroon"] = { { name = "Peacemaker", average_rate = "80.0%" }, { name = "Qiqirn collar", average_rate = "20.0%" } },
  ["Cave Mold"] = { { name = "Vial of slime oil", average_rate = "64.7%" } },
  ["Cave Pugil"] = { { name = "Sack of silica", average_rate = "60.0%" }, { name = "Handful of pugil scales", average_rate = "40.0%" } },
  ["Cave Tiger"] = { { name = "Black tiger fang", average_rate = "28.2%" }, { name = "Black tiger hide", average_rate = "17.1%" } },
  ["Chigre"] = { { name = "Chigre", average_rate = "105.0%" }, { name = "Insect ring", average_rate = "27.2%" }, { name = "Blood ring", average_rate = "27.9%" } },
  ["Defoliator"] = { { name = "Crawler egg", average_rate = "32.1%" }, { name = "Piece of crawler cocoon", average_rate = "15.9%" }, { name = "Spool of silk thread", average_rate = "6.5%" } },
  ["Deforester"] = { { name = "Crawler egg", average_rate = "26.6%" }, { name = "Piece of crawler cocoon", average_rate = "16.0%" }, { name = "Spool of silk thread", average_rate = "7.7%" } },
  ["Fossorial Flea"] = { { name = "Vial of chimera blood", average_rate = "25.5%" }, { name = "Vial of demon blood", average_rate = "1.7%" } },
  ["Great Ameretat"] = { { name = "Vial of Jody's acid", average_rate = "37.2%" }, { name = "Ameretat vine", average_rate = "22.1%" }, { name = "Lacquer tree log", average_rate = "1.6%" } },
  ["Lizardtrap"] = { { name = "Fenrir's crown", average_rate = "3.8%" } },
  ["Mold Eater"] = { { name = "Chunk of copper ore", average_rate = "14.6%" }, { name = "Flint stone", average_rate = "21.7%" }, { name = "Chunk of zinc ore", average_rate = "7.6%" }, { name = "Chunk of silver ore", average_rate = "0.99%" } },
  ["Mycohopper"] = { { name = "Woozyshroom", average_rate = "27.8%" }, { name = "Danceshroom", average_rate = "15.7%" }, { name = "King truffle", average_rate = "7.4%" } },
  ["Mycoskulker"] = { { name = "Danceshroom", average_rate = "21.2%" }, { name = "Woozyshroom", average_rate = "35.7%" }, { name = "King truffle", average_rate = "3.7%" } },
  ["Nosferatu"] = { { name = "Nosferatu's claw", average_rate = "106.2%" }, { name = "Labrys", average_rate = "37.1%" }, { name = "Wind grip", average_rate = "41.1%" }, { name = "Earth grip", average_rate = "40.9%" }, { name = "Enkidu's leggings", average_rate = "35.3%" }, { name = "Aurum gauntlets", average_rate = "47.4%" } },
  ["Pandemonium Warden"] = { { name = "Hachiryu haramaki", average_rate = "59.3%" }, { name = "Dorje", average_rate = "59.0%" }, { name = "Shenlong's baghnakhs", average_rate = "61.2%" }, { name = "Hydra fang", average_rate = "79.7%" }, { name = "Cerberus hide", average_rate = "105.3%" }, { name = "Khimaira mane", average_rate = "105.4%" }, { name = "Chunk of Mulcibar's scoria", average_rate = "110.1%" }, { name = "Hydra scale", average_rate = "105.1%" }, { name = "Nanatsusayanotachi", average_rate = "59.4%" }, { name = "Khimaira horn", average_rate = "61.6%" }, { name = "Cerberus claw", average_rate = "64.7%" } },
  ["Phlebotomic Slug"] = { { name = "Vial of fiend blood", average_rate = "14.2%" }, { name = "Vial of beastman blood", average_rate = "7.1%" }, { name = "Carbuncle's ruby", average_rate = "2.0%" } },
  ["Puktrap"] = { { name = "Flytrap leaf", average_rate = "6.5%" } },
  ["Qiqirn Archaeologist"] = { { name = "Bowl of Nashmau stew", average_rate = "7.9%" }, { name = "Handful of almonds", average_rate = "51.2%" }, { name = "Qiqirn sandbag", average_rate = "2.6%" }, { name = "Qiqirn cape", average_rate = "4.3%" }, { name = "Jar of firesand", average_rate = "1.3%" }, { name = "Sack of silica", average_rate = "1.7%" }, { name = "Pebble", average_rate = "1.7%" }, { name = "Handful of iron sand", average_rate = "1.3%" } },
  ["Qiqirn Enterpriser"] = { { name = "Handful of almonds", average_rate = "36.1%" }, { name = "Pebble", average_rate = "1.8%" }, { name = "Jar of firesand", average_rate = "0.95%" }, { name = "Qiqirn cape", average_rate = "1.7%" }, { name = "Bowl of Nashmau stew", average_rate = "0.99%" }, { name = "Qiqirn sandbag", average_rate = "2.0%" }, { name = "Sack of silica", average_rate = "0.23%" }, { name = "Handful of iron sand", average_rate = "0.36%" } },
  ["Qiqirn Lieuter"] = { { name = "Handful of almonds", average_rate = "36.1%" }, { name = "Jar of firesand", average_rate = "0.95%" }, { name = "Qiqirn sandbag", average_rate = "2.3%" }, { name = "Pebble", average_rate = "3.1%" }, { name = "Handful of iron sand", average_rate = "0.52%" }, { name = "Qiqirn cape", average_rate = "1.9%" }, { name = "Bowl of Nashmau stew", average_rate = "0.90%" }, { name = "Sack of silica", average_rate = "0.22%" } },
  ["Qiqirn Mosstrooper"] = { { name = "Qiqirn cape", average_rate = "5.6%" }, { name = "Handful of almonds", average_rate = "46.1%" }, { name = "Handful of iron sand", average_rate = "2.2%" }, { name = "Pebble", average_rate = "1.1%" }, { name = "Bowl of Nashmau stew", average_rate = "10.1%" }, { name = "Jar of firesand", average_rate = "1.1%" } },
  ["Slime Eater"] = { { name = "Chunk of copper ore", average_rate = "14.8%" }, { name = "Flint stone", average_rate = "23.8%" }, { name = "Chunk of silver ore", average_rate = "1.4%" }, { name = "Chunk of zinc ore", average_rate = "7.7%" } },
  ["Slime Mold"] = { { name = "Vial of slime oil", average_rate = "28.3%" } },
  ["Treant Sapling"] = { { name = "Treant bulb", average_rate = "23.7%" }, { name = "Bag of fruit seeds", average_rate = "8.2%" }, { name = "Bag of grain seeds", average_rate = "1.6%" } },
}
