-- Zone: Attohwa Chasm
return {
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "153.4%" } },
  ["Alastor Antlion"] = { { name = "Rostrum pumps", average_rate = "100.0%" } },
  ["Ambusher Antlion"] = { { name = "Archer's jupon", average_rate = "100.0%" } },
  ["Arch Corse"] = { { name = "Iolite", average_rate = "36.9%" }, { name = "Corse robe", average_rate = "8.3%" }, { name = "Corse bracelet", average_rate = "16.9%" } },
  ["Attohwa Coeurl"] = { { name = "Coeurl whisker", average_rate = "31.3%" }, { name = "Coeurl hide", average_rate = "9.0%" }, { name = "Slice of coeurl meat", average_rate = "15.9%" } },
  ["Bane Lizard"] = { { name = "Lizard tail", average_rate = "39.3%" }, { name = "Lizard egg", average_rate = "7.1%" }, { name = "Lizard skin", average_rate = "7.1%" } },
  ["Bifrons"] = { { name = "Pinch of bomb ash", average_rate = "103.8%" }, { name = "Bomb arm", average_rate = "35.5%" } },
  ["Burrow Antlion"] = { { name = "Antlion jaw", average_rate = "11.8%" }, { name = "Scarlet stone", average_rate = "23.5%" } },
  ["Cave Antlion"] = { { name = "High-quality antlion jaw", average_rate = "36.1%" }, { name = "Antlion jaw", average_rate = "17.3%" }, { name = "Scarlet stone", average_rate = "35.0%" } },
  ["Chasm Lizard"] = { { name = "Lizard tail", average_rate = "30.0%" }, { name = "Lizard egg", average_rate = "7.0%" }, { name = "Lizard skin", average_rate = "4.0%" } },
  ["Citipati"] = { { name = "Corse bracelet", average_rate = "44.4%" }, { name = "Druid's slops", average_rate = "44.4%" }, { name = "Harpe", average_rate = "3.7%" } },
  ["Corse"] = { { name = "Bone chip", average_rate = "33.9%" }, { name = "Iolite", average_rate = "20.9%" }, { name = "Corse bracelet", average_rate = "8.8%" }, { name = "Corse robe", average_rate = "1.9%" }, { name = "Dark cluster", average_rate = "0.39%" } },
  ["Cutlass Scorpion"] = { { name = "Scorpion claw", average_rate = "30.8%" }, { name = "Scorpion shell", average_rate = "16.3%" }, { name = "High-quality scorpion shell", average_rate = "8.4%" }, { name = "Earth cluster", average_rate = "0.04%" } },
  ["Doom Scorpion"] = { { name = "Scorpion claw", average_rate = "25.2%" }, { name = "Scorpion shell", average_rate = "14.0%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "157.9%" } },
  ["Flesh Eater"] = { { name = "Flint stone", average_rate = "25.9%" }, { name = "Chunk of copper ore", average_rate = "16.8%" }, { name = "Igneous rock", average_rate = "7.2%" } },
  ["Gallinipper"] = { { name = "Insect wing", average_rate = "11.9%" }, { name = "Piece of Attohwa ginseng", average_rate = "7.3%" }, { name = "Wind cluster", average_rate = "0.10%" } },
  ["Goblin Furrier"] = { { name = "Goblin mask", average_rate = "4.5%" }, { name = "Square of sheep leather", average_rate = "6.8%" }, { name = "Square of dhalmel leather", average_rate = "1.1%" }, { name = "Mythril beastcoin", average_rate = "2.3%" } },
  ["Goblin Pathfinder"] = { { name = "Goblin mask", average_rate = "11.9%" }, { name = "Goblin armor", average_rate = "2.4%" }, { name = "Mythril beastcoin", average_rate = "2.4%" } },
  ["Goblin Reaper"] = { { name = "Scroll of Absorb-INT", average_rate = "5.9%" }, { name = "Goblin helm", average_rate = "5.9%" }, { name = "Goblin mail", average_rate = "11.8%" }, { name = "Scroll of Absorb-AGI", average_rate = "5.9%" } },
  ["Goblin Robber"] = { { name = "Goblin armor", average_rate = "14.3%" }, { name = "Mythril beastcoin", average_rate = "7.1%" } },
  ["Goblin Shaman"] = { { name = "Goblin mask", average_rate = "3.2%" }, { name = "Mythril beastcoin", average_rate = "1.1%" }, { name = "Goblin armor", average_rate = "1.6%" } },
  ["Goblin Smithy"] = { { name = "Goblin helm", average_rate = "4.0%" }, { name = "Goblin mail", average_rate = "1.3%" } },
  ["Goblin Trader"] = { { name = "Goblin mask", average_rate = "5.9%" } },
  ["Hecteyes"] = { { name = "Vial of mercury", average_rate = "57.9%" }, { name = "Hecteyes eye", average_rate = "10.0%" } },
  ["Hunter Antlion"] = { { name = "Antlion jaw", average_rate = "4.7%" } },
  ["Lich"] = { { name = "Bone chip", average_rate = "25.9%" }, { name = "Revival tree root", average_rate = "7.4%" } },
  ["Master Coeurl"] = { { name = "Coeurl whisker", average_rate = "26.9%" }, { name = "Slice of coeurl meat", average_rate = "17.3%" }, { name = "Coeurl hide", average_rate = "3.8%" } },
  ["Maze Lurker"] = { { name = "Shall shell", average_rate = "33.3%" }, { name = "Handful of pugil scales", average_rate = "33.3%" } },
  ["Monarch Ogrefly"] = { { name = "Insect wing", average_rate = "13.1%" }, { name = "Piece of Attohwa ginseng", average_rate = "10.4%" }, { name = "Wind cluster", average_rate = "0.01%" } },
  ["Mummy"] = { { name = "Revival tree root", average_rate = "17.6%" }, { name = "Bone chip", average_rate = "23.5%" } },
  ["Ogrefly"] = { { name = "Insect wing", average_rate = "5.9%" }, { name = "Piece of Attohwa ginseng", average_rate = "5.9%" } },
  ["Pit Antlion"] = { { name = "Scarlet stone", average_rate = "66.7%" }, { name = "Antlion jaw", average_rate = "33.3%" } },
  ["Sand Lizard"] = { { name = "Lizard tail", average_rate = "24.6%" }, { name = "Lizard egg", average_rate = "11.4%" }, { name = "Lizard skin", average_rate = "6.3%" } },
  ["Sargas"] = { { name = "Aptant of aecus", average_rate = "8.2%" }, { name = "Aptant of primus", average_rate = "5.9%" } },
  ["Sekhmet"] = { { name = "Layqa seraweels", average_rate = "13.7%" } },
  ["Tiamat"] = { { name = "Wyrm horn", average_rate = "75.0%" }, { name = "Crier's gaiters", average_rate = "75.0%" }, { name = "Dragon talon", average_rate = "25.0%" }, { name = "Piece of oxblood", average_rate = "25.0%" }, { name = "Vial of black beetle blood", average_rate = "25.0%" } },
  ["Tomb Mage"] = { { name = "Scroll of Blizzard III", average_rate = "11.5%" }, { name = "Bone chip", average_rate = "35.4%" }, { name = "Revival tree root", average_rate = "17.7%" } },
  ["Tomb Warrior"] = { { name = "Bone chip", average_rate = "35.2%" }, { name = "Revival tree root", average_rate = "16.8%" }, { name = "Earth cluster", average_rate = "0.40%" } },
  ["Tracer Antlion"] = { { name = "Antlion jaw", average_rate = "1.4%" } },
  ["Tracker Antlion"] = { { name = "Antlion jaw", average_rate = "7.1%" }, { name = "Scarlet stone", average_rate = "1.7%" } },
  ["Trench Antlion"] = { { name = "Scarlet stone", average_rate = "30.3%" }, { name = "High-quality antlion jaw", average_rate = "29.1%" }, { name = "Antlion jaw", average_rate = "13.0%" } },
  ["Tulwar Scorpion"] = { { name = "Scorpion claw", average_rate = "25.1%" }, { name = "Scorpion shell", average_rate = "14.7%" } },
  ["Will-O'-The-Wykes"] = { { name = "Pinch of bomb ash", average_rate = "100.0%" }, { name = "Bomb arm", average_rate = "23.1%" } },
  ["Xolotl"] = { { name = "Zoolater hat", average_rate = "62.6%" }, { name = "Bandomusha kote", average_rate = "21.8%" }, { name = "Perseus's harpe", average_rate = "3.4%" } },
}
