-- Zone: Alzadaal Undersea Ruins
return {
  ["Armed Gears"] = { { name = "Armed Gears' fragment", average_rate = "105.6%" }, { name = "Tomoe", average_rate = "36.6%" }, { name = "Oracle's gloves", average_rate = "47.1%" }, { name = "Thunder grip", average_rate = "41.9%" }, { name = "Earth grip", average_rate = "40.1%" }, { name = "Aurum sabatons", average_rate = "36.4%" } },
  ["Boompadu"] = { { name = "Surge subligar", average_rate = "19.7%" } },
  ["Cheese Hoarder Gigiroon"] = { { name = "Gigiroon's Cape", average_rate = "104.7%" }, { name = "Beast slayer", average_rate = "27.0%" }, { name = "Armadillo cuisses", average_rate = "26.3%" } },
  ["Cookieduster Lipiroon"] = { { name = "Lyft crossbow", average_rate = "19.3%" } },
  ["Ob"] = { { name = "Ob's arm", average_rate = "100.2%" }, { name = "Guignol earring", average_rate = "28.1%" }, { name = "Tactical processor", average_rate = "4.0%" }, { name = "Target marker", average_rate = "3.9%" }, { name = "Barrier module II", average_rate = "9.9%" }, { name = "Equalizer", average_rate = "3.8%" }, { name = "Mana channeler", average_rate = "3.8%" }, { name = "Steam jacket", average_rate = "16.3%" }, { name = "Percolator", average_rate = "7.9%" }, { name = "Coiler", average_rate = "18.5%" }, { name = "Drum magazine", average_rate = "5.9%" }, { name = "Disruptor", average_rate = "8.5%" }, { name = "Smoke screen", average_rate = "4.1%" }, { name = "Vivi-valve", average_rate = "7.7%" }, { name = "Attuner", average_rate = "4.7%" }, { name = "Eraser", average_rate = "4.2%" } },
  ["Oupire"] = { { name = "Vial of ebur pigment", average_rate = "105.8%" }, { name = "Chunk of adaman ore", average_rate = "56.6%" }, { name = "Chunk of orichalcum ore", average_rate = "63.0%" }, { name = "Narigitsune", average_rate = "22.7%" }, { name = "Square of cambric", average_rate = "122.6%" } },
  ["Qiqirn Goldsmith"] = { { name = "Handful of almonds", average_rate = "45.0%" }, { name = "Qiqirn sandbag", average_rate = "1.9%" }, { name = "Jar of firesand", average_rate = "1.1%" }, { name = "Bowl of Nashmau stew", average_rate = "0.32%" }, { name = "Pebble", average_rate = "3.3%" }, { name = "Qiqirn cape", average_rate = "1.6%" }, { name = "Handful of iron sand", average_rate = "0.20%" }, { name = "Sack of silica", average_rate = "0.15%" } },
  ["Qiqirn Poulterer"] = { { name = "Jar of firesand", average_rate = "0.96%" }, { name = "Handful of almonds", average_rate = "43.7%" }, { name = "Qiqirn sandbag", average_rate = "2.1%" }, { name = "Pebble", average_rate = "2.9%" }, { name = "Handful of iron sand", average_rate = "0.39%" }, { name = "Qiqirn cape", average_rate = "1.2%" }, { name = "Bowl of Nashmau stew", average_rate = "0.23%" }, { name = "Sack of silica", average_rate = "0.08%" } },
  ["Wulgaru"] = { { name = "Wulgaru's head", average_rate = "105.3%" }, { name = "Riot shield", average_rate = "29.9%" }, { name = "Hissho hachimaki", average_rate = "31.5%" } },
}
