-- Zone: Hazhalm Testing Grounds
return {
  ["Angantyr"] = { { name = "Page from Balrahn's Reflections", average_rate = "14.6%" } },
  ["Audhumbla"] = { { name = "Page from Balrahn's Reflections", average_rate = "16.3%" } },
  ["Barri"] = { { name = "Page from Balrahn's Reflections", average_rate = "14.1%" } },
  ["Battlemite"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.0%" } },
  ["Berserkr"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.6%" } },
  ["Brami"] = { { name = "Page from Balrahn's Reflections", average_rate = "14.7%" } },
  ["Bugard-X"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.0%" } },
  ["Bui"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.8%" } },
  ["Chigoe"] = { { name = "Page from Balrahn's Reflections", average_rate = "13.9%" } },
  ["Corrupt Einherjar"] = { { name = "Page from Balrahn's Reflections", average_rate = "16.1%" } },
  ["Craven Einherjar"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.8%" } },
  ["Dark Elemental"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.7%" } },
  ["Djigga"] = { { name = "Page from Balrahn's Reflections", average_rate = "11.4%" } },
  ["Einherjar Brei"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.9%" } },
  ["Einherjar Eater"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.2%" } },
  ["Experimental Poroggo"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.9%" } },
  ["Flames Of Muspelheim"] = { { name = "Page from Balrahn's Reflections", average_rate = "16.6%" } },
  ["Gardsvor"] = { { name = "Page from Balrahn's Reflections", average_rate = "14.0%" } },
  ["Hadding The Elder"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.6%" } },
  ["Hadding The Younger"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.6%" } },
  ["Hafgygr"] = { { name = "Page from Balrahn's Reflections", average_rate = "16.2%" } },
  ["Hazhalm Bat"] = { { name = "Page from Balrahn's Reflections", average_rate = "14.5%" } },
  ["Hazhalm Bats"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.3%" } },
  ["Hazhalm Leech"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.6%" } },
  ["Hervarth"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.3%" } },
  ["Hjorvarth"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.4%" } },
  ["Hrani"] = { { name = "Page from Balrahn's Reflections", average_rate = "16.1%" } },
  ["Hyndla"] = { { name = "Page from Balrahn's Reflections", average_rate = "16.3%" } },
  ["Idun"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.4%" } },
  ["Infected Wamoura"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.8%" } },
  ["Liquified Einherjar"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.8%" } },
  ["Logi"] = { { name = "Page from Balrahn's Reflections", average_rate = "6.2%" } },
  ["Manticore-X"] = { { name = "Page from Balrahn's Reflections", average_rate = "16.4%" } },
  ["Margygr"] = { { name = "Page from Balrahn's Reflections", average_rate = "16.3%" } },
  ["Marid-X"] = { { name = "Page from Balrahn's Reflections", average_rate = "16.9%" } },
  ["Nickur"] = { { name = "Page from Balrahn's Reflections", average_rate = "16.8%" } },
  ["Odin"] = { { name = "Aquarian abjuration: body", average_rate = "28.0%" }, { name = "Martial abjuration: feet", average_rate = "10.5%" }, { name = "Hadean abjuration: hands", average_rate = "12.0%" }, { name = "Earthen abjuration: body", average_rate = "35.4%" }, { name = "Valhalla helm", average_rate = "14.0%" }, { name = "Aquarian abjuration: hands", average_rate = "9.2%" }, { name = "Martial abjuration: body", average_rate = "23.7%" }, { name = "Phantasmal abjuration: hands", average_rate = "12.5%" }, { name = "Phantasmal abjuration: body", average_rate = "24.5%" }, { name = "Hadean abjuration: head", average_rate = "16.4%" }, { name = "Valhalla breastplate", average_rate = "10.6%" }, { name = "Hadean abjuration: legs", average_rate = "14.9%" }, { name = "Hofud", average_rate = "10.4%" }, { name = "Dryadic abjuration: feet", average_rate = "12.1%" }, { name = "Phantasmal abjuration: feet", average_rate = "10.3%" }, { name = "Hadean abjuration: body", average_rate = "27.2%" }, { name = "Earthen abjuration: legs", average_rate = "8.3%" }, { name = "Wyrmal abjuration: body", average_rate = "30.5%" }, { name = "Neptunal abjuration: head", average_rate = "11.0%" }, { name = "Earthen abjuration: hands", average_rate = "8.4%" }, { name = "Wyrmal abjuration: head", average_rate = "10.3%" }, { name = "Neptunal abjuration: legs", average_rate = "9.7%" }, { name = "Valkyrie's fork", average_rate = "9.3%" }, { name = "Phantasmal abjuration: head", average_rate = "12.6%" }, { name = "Aquarian abjuration: feet", average_rate = "10.1%" }, { name = "Hadean abjuration: feet", average_rate = "10.6%" }, { name = "Phantasmal abjuration: legs", average_rate = "10.9%" }, { name = "Martial abjuration: legs", average_rate = "10.7%" }, { name = "Dagaz ring", average_rate = "13.1%" }, { name = "Laeradr breastplate", average_rate = "8.2%" }, { name = "Othila sash", average_rate = "11.3%" }, { name = "Laeradr helm", average_rate = "10.6%" }, { name = "Eihwaz ring", average_rate = "11.3%" }, { name = "Heimdall's doom", average_rate = "8.0%" }, { name = "Herja's fork", average_rate = "8.2%" } },
  ["Odin's Fool"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.7%" } },
  ["Odin's Jester"] = { { name = "Page from Balrahn's Reflections", average_rate = "16.1%" } },
  ["Ormr"] = { { name = "Page from Balrahn's Reflections", average_rate = "16.7%" } },
  ["Reifnir"] = { { name = "Page from Balrahn's Reflections", average_rate = "14.0%" } },
  ["Rotting Huskarl"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.3%" } },
  ["Sjokrakjen"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.5%" } },
  ["Soulflayer"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.6%" } },
  ["Tind"] = { { name = "Page from Balrahn's Reflections", average_rate = "16.4%" } },
  ["Tyrfing"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.0%" } },
  ["Utgarth Bat"] = { { name = "Page from Balrahn's Reflections", average_rate = "16.7%" } },
  ["Utgarth Bats"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.9%" } },
  ["Utgarth Leech"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.8%" } },
  ["Vampyr Dog"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.8%" } },
  ["Vanquished Einherjar"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.3%" } },
  ["Waldgeist"] = { { name = "Page from Balrahn's Reflections", average_rate = "14.3%" } },
  ["Winebibber"] = { { name = "Page from Balrahn's Reflections", average_rate = "15.8%" } },
  ["Wivre-X"] = { { name = "Page from Balrahn's Reflections", average_rate = "17.0%" } },
}
