-- Zone: Caedarva Mire
return {
  ["Aynu-Kaysey"] = { { name = "Cinquedea", average_rate = "17.3%" } },
  ["Caedarva Leech"] = { { name = "Vial of beastman blood", average_rate = "6.1%" }, { name = "Vial of fiend blood", average_rate = "12.9%" }, { name = "Carbuncle's ruby", average_rate = "0.63%" } },
  ["Caedarva Marshscum"] = { { name = "Vial of slime oil", average_rate = "41.7%" } },
  ["Caedarva Pondscum"] = { { name = "Vial of slime oil", average_rate = "100.0%" } },
  ["Chigoe"] = { { name = "Vial of chimera blood", average_rate = "24.2%" }, { name = "Vial of demon blood", average_rate = "1.5%" } },
  ["Dark Elemental"] = { { name = "Dark cluster", average_rate = "146.6%" } },
  ["Draugar Servant"] = { { name = "Bone chip", average_rate = "31.4%" }, { name = "Lamian fang key", average_rate = "9.4%" } },
  ["Ephramadian Shade"] = { { name = "Timeworn talisman", average_rate = "17.4%" } },
  ["Experimental Lamia"] = { { name = "Experimental Lamia's armband", average_rate = "104.5%" }, { name = "Enkidu's leggings", average_rate = "38.8%" }, { name = "Aurum cuisses", average_rate = "48.0%" }, { name = "Water grip", average_rate = "48.3%" }, { name = "Mekki shakki", average_rate = "32.0%" }, { name = "Earth grip", average_rate = "48.8%" } },
  ["Guard Bhoot"] = { { name = "Square of mohbwa cloth", average_rate = "22.9%" }, { name = "Revival tree root", average_rate = "15.7%" } },
  ["Guard Skeleton"] = { { name = "Revival tree root", average_rate = "15.5%" }, { name = "Bone chip", average_rate = "24.6%" } },
  ["Heraldic Imp"] = { { name = "Imp wing", average_rate = "42.2%" }, { name = "Imp horn", average_rate = "7.8%" } },
  ["Jnun"] = { { name = "Revival tree root", average_rate = "27.6%" }, { name = "Undead skin", average_rate = "15.9%" } },
  ["Khimaira"] = { { name = "Khimaira horn", average_rate = "103.3%" }, { name = "Khimaira mane", average_rate = "206.3%" }, { name = "Khimaira tail", average_rate = "103.3%" }, { name = "Seveneyes", average_rate = "19.9%" }, { name = "Hauteclaire", average_rate = "11.7%" } },
  ["Lamia Chaukidar"] = { { name = "Lamia skin", average_rate = "32.3%" }, { name = "Vial of chimera blood", average_rate = "16.2%" }, { name = "Lamian armlet", average_rate = "1.5%" } },
  ["Lamia Fatedealer"] = { { name = "Corsair's testimony", average_rate = "20.5%" }, { name = "Lamian armlet", average_rate = "1.8%" }, { name = "Vial of chimera blood", average_rate = "6.6%" } },
  ["Lamia Idolater"] = { { name = "Qutrub bandage", average_rate = "30.4%" }, { name = "Qutrub gorget", average_rate = "1.9%" } },
  ["Lamia Necromancer"] = { { name = "Lamia skin", average_rate = "30.4%" }, { name = "Vial of chimera blood", average_rate = "14.5%" }, { name = "Lamian armlet", average_rate = "1.9%" } },
  ["Lamia Toxophilite"] = { { name = "Lamia skin", average_rate = "32.8%" }, { name = "Lamian kaman -1", average_rate = "17.6%" }, { name = "Lamian armlet", average_rate = "1.8%" } },
  ["Mahjlaef The Paintorn"] = { { name = "Mahjlaef's staff", average_rate = "104.4%" }, { name = "Aurum gauntlets", average_rate = "47.2%" }, { name = "Oracle's braconi", average_rate = "36.3%" }, { name = "Fire grip", average_rate = "50.6%" }, { name = "Thunder grip", average_rate = "49.1%" }, { name = "Legion scutum", average_rate = "33.1%" } },
  ["Marsh Murre"] = { { name = "Bird feather", average_rate = "25.6%" }, { name = "Handful of almonds", average_rate = "37.0%" }, { name = "Bird egg", average_rate = "6.9%" } },
  ["Mature Treant"] = { { name = "Dryad root", average_rate = "42.5%" }, { name = "Sprig of mistletoe", average_rate = "30.2%" }, { name = "Puffball", average_rate = "17.1%" }, { name = "Ebony log", average_rate = "1.7%" }, { name = "Rosewood log", average_rate = "3.2%" }, { name = "Mahogany log", average_rate = "2.7%" }, { name = "Petrified log", average_rate = "0.83%" } },
  ["Mosshorn"] = { { name = "Ram skin", average_rate = "242.1%" }, { name = "Lanolin cube", average_rate = "100.5%" }, { name = "Ram horn", average_rate = "82.3%" } },
  ["Oil Slick"] = { { name = "Vial of slime oil", average_rate = "28.0%" } },
  ["Orderly Imp"] = { { name = "Imp wing", average_rate = "35.0%" }, { name = "Imp horn", average_rate = "7.8%" } },
  ["Peallaidh"] = { { name = "Nightmare gloves", average_rate = "60.1%" } },
  ["Puktrap"] = { { name = "Flytrap leaf", average_rate = "6.6%" } },
  ["Qiqirn Mireguide"] = { { name = "Handful of almonds", average_rate = "42.4%" }, { name = "Qiqirn sandbag", average_rate = "1.8%" } },
  ["Qiqirn Rock Hound"] = { { name = "Handful of almonds", average_rate = "37.2%" }, { name = "Qiqirn sandbag", average_rate = "1.2%" } },
  ["Reserve Draugar"] = { { name = "Bone chip", average_rate = "23.2%" }, { name = "Lamian fang key", average_rate = "15.9%" }, { name = "Revival tree root", average_rate = "13.8%" } },
  ["Slough Skua"] = { { name = "Bird feather", average_rate = "25.0%" }, { name = "Bird egg", average_rate = "6.8%" }, { name = "Handful of almonds", average_rate = "37.2%" } },
  ["Soulflayer"] = { { name = "Soulflayer tentacle", average_rate = "36.2%" }, { name = "Soulflayer staff", average_rate = "19.2%" }, { name = "Soulflayer robe", average_rate = "9.0%" } },
  ["Spongilla Fly"] = { { name = "Insect wing", average_rate = "10.3%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "149.4%" } },
  ["Treant Sapling"] = { { name = "Bag of wildgrass seeds", average_rate = "13.2%" }, { name = "Bag of fruit seeds", average_rate = "6.8%" }, { name = "Treant bulb", average_rate = "22.4%" }, { name = "Bag of grain seeds", average_rate = "1.6%" } },
  ["Tyger"] = { { name = "Khimaira tail", average_rate = "105.5%" }, { name = "Khimaira horn", average_rate = "105.5%" }, { name = "Khimaira mane", average_rate = "105.6%" }, { name = "Tyger's tail", average_rate = "105.4%" }, { name = "Aurum armet", average_rate = "45.0%" }, { name = "Antares", average_rate = "11.5%" }, { name = "Aurum cuirass", average_rate = "33.4%" }, { name = "Enforcer", average_rate = "8.3%" }, { name = "Enkidu's cap", average_rate = "32.9%" }, { name = "Hachiryu kote", average_rate = "7.9%" } },
  ["Vauxia Fly"] = { { name = "Insect wing", average_rate = "29.6%" } },
  ["Verdelet"] = { { name = "Verdelet's wing", average_rate = "104.8%" }, { name = "Solitaire cape", average_rate = "28.9%" }, { name = "Muse tariqah", average_rate = "26.9%" } },
  ["Vidhuwa The Wrathborn"] = { { name = "Lyft scythe", average_rate = "25.0%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "144.1%" } },
  ["Wild Karakul"] = { { name = "Karakul skin", average_rate = "47.0%" }, { name = "Slice of karakul meat", average_rate = "21.9%" } },
  ["Zikko"] = { { name = "Imp horn", average_rate = "17.1%" }, { name = "Templar hammer", average_rate = "44.9%" }, { name = "Immortal's sash", average_rate = "25.7%" } },
}
