-- Zone: Jugner Forest [S]
return {
  ["Biddybug"] = { { name = "Ladybug wing", average_rate = "35.3%" } },
  ["Boll Weevil"] = { { name = "Nasatya's ring", average_rate = "15.9%" } },
  ["Brutal Sheep"] = { { name = "Slice of giant sheep meat", average_rate = "19.5%" }, { name = "Sheep tooth", average_rate = "7.8%" }, { name = "Sheepskin", average_rate = "11.7%" } },
  ["Capricornus"] = { { name = "Fierce belt", average_rate = "14.7%" } },
  ["Dark Ixion"] = { { name = "Azoth", average_rate = "49.0%" }, { name = "Ixion cape", average_rate = "43.7%" }, { name = "Dark Ixion horn", average_rate = "101.6%" }, { name = "Dark Ixion tail", average_rate = "101.6%" }, { name = "Ixion cloak", average_rate = "44.9%" } },
  ["Decrepit Gnole"] = { { name = "Gnole claw", average_rate = "6.8%" } },
  ["Drumskull Zogdregg"] = { { name = "Aptant of secan", average_rate = "23.1%" }, { name = "Aptant of geoc", average_rate = "7.7%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "0.39%" } },
  ["Forest Leech"] = { { name = "Vial of beastman blood", average_rate = "5.3%" }, { name = "Vial of fiend blood", average_rate = "17.9%" } },
  ["Ghoul"] = { { name = "Bone chip", average_rate = "19.0%" }, { name = "Scroll of Absorb-VIT", average_rate = "1.7%" }, { name = "Scroll of Absorb-AGI", average_rate = "1.7%" } },
  ["Gnoletrap"] = { { name = "Flytrap leaf", average_rate = "12.8%" } },
  ["Goblin Bombardier"] = { { name = "Goblin mask", average_rate = "6.0%" }, { name = "Goblin armor", average_rate = "2.0%" } },
  ["Goblin Field Doctor"] = { { name = "Goblin mask", average_rate = "6.7%" }, { name = "Goblin armor", average_rate = "6.1%" }, { name = "Bottled pixie", average_rate = "21.3%" } },
  ["Goblin Paratrooper"] = { { name = "Gold beastcoin", average_rate = "2.8%" }, { name = "Goblin helm", average_rate = "5.6%" }, { name = "Goblin mail", average_rate = "3.6%" } },
  ["Goblin Picket"] = { { name = "Goblin mess tin", average_rate = "13.1%" }, { name = "Goblin weel", average_rate = "14.6%" } },
  ["Hawkertrap"] = { { name = "Flytrap leaf", average_rate = "17.9%" } },
  ["Ignis Djinn"] = { { name = "Pinch of djinn ash", average_rate = "38.9%" }, { name = "Djinn arm", average_rate = "24.3%" } },
  ["Jugner Funguar"] = { { name = "Sleepshroom", average_rate = "40.3%" } },
  ["Krabkatoa"] = { { name = "Krabkatoa shell", average_rate = "124.8%" }, { name = "Gold ingot", average_rate = "7.4%" }, { name = "Ebony log", average_rate = "9.1%" }, { name = "Acubens helm", average_rate = "27.3%" }, { name = "Platinum ingot", average_rate = "8.3%" }, { name = "Vile elixir", average_rate = "3.7%" }, { name = "Igneous barnacle", average_rate = "46.3%" }, { name = "Darksteel ingot", average_rate = "6.6%" }, { name = "Ram horn", average_rate = "10.7%" }, { name = "Mahogany log", average_rate = "18.6%" }, { name = "Spool of gold thread", average_rate = "5.0%" }, { name = "Chunk of lightning ore", average_rate = "2.5%" }, { name = "Chunk of fire ore", average_rate = "2.5%" }, { name = "Coral fragment", average_rate = "6.6%" }, { name = "Demon horn", average_rate = "6.6%" }, { name = "Chunk of gold ore", average_rate = "10.7%" }, { name = "Petrified log", average_rate = "14.9%" }, { name = "Reraiser", average_rate = "4.1%" }, { name = "Chunk of platinum ore", average_rate = "8.3%" }, { name = "Handful of wyvern scales", average_rate = "9.1%" }, { name = "Chunk of mythril ore", average_rate = "5.8%" }, { name = "Vile elixir +1", average_rate = "2.5%" }, { name = "Karka ring", average_rate = "12.4%" }, { name = "Chunk of ice ore", average_rate = "1.7%" }, { name = "Slab of granite", average_rate = "1.2%" }, { name = "Ram skin", average_rate = "4.1%" }, { name = "Phoenix feather", average_rate = "2.1%" }, { name = "Hi-reraiser", average_rate = "2.5%" }, { name = "Chunk of water ore", average_rate = "2.5%" }, { name = "Mythril ingot", average_rate = "5.8%" }, { name = "Wyvern skin", average_rate = "0.83%" }, { name = "Chunk of wind ore", average_rate = "1.7%" }, { name = "Chunk of darksteel ore", average_rate = "3.3%" }, { name = "Chunk of dark ore", average_rate = "1.7%" }, { name = "Chunk of light ore", average_rate = "2.1%" }, { name = "Philosopher's stone", average_rate = "3.3%" }, { name = "Square of rainbow cloth", average_rate = "0.83%" }, { name = "Chunk of earth ore", average_rate = "0.83%" }, { name = "Square of raxa", average_rate = "1.2%" } },
  ["Land Pugil"] = { { name = "Sack of silica", average_rate = "26.0%" }, { name = "Handful of pugil scales", average_rate = "14.3%" } },
  ["Lobison"] = { { name = "Gnole claw", average_rate = "14.6%" } },
  ["Orcish Dragonbrander"] = { { name = "Bottled pixie", average_rate = "12.8%" } },
  ["Orcish Protector"] = { { name = "Orc helmet", average_rate = "14.5%" } },
  ["Orcish Veteran"] = { { name = "Orc helmet", average_rate = "15.1%" } },
  ["Screamer"] = { { name = "Bird feather", average_rate = "22.0%" }, { name = "Bird egg", average_rate = "9.9%" } },
  ["Snipper"] = { { name = "Slice of land crab meat", average_rate = "25.0%" }, { name = "Crab shell", average_rate = "13.6%" } },
  ["Sprite"] = { { name = "Pinch of Stygian ash", average_rate = "15.6%" } },
  ["Stag Beetle"] = { { name = "Insect wing", average_rate = "25.3%" }, { name = "Beetle jaw", average_rate = "5.6%" } },
  ["Stag Crab"] = { { name = "Chunk of rock salt", average_rate = "100.0%" } },
  ["Thread Leech"] = { { name = "Vial of beastman blood", average_rate = "20.0%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "143.6%" } },
  ["Voirloup"] = { { name = "Lyft sainti", average_rate = "9.1%" } },
  ["Vulkodlac"] = { { name = "Gnole claw", average_rate = "55.0%" }, { name = "Sothic rope", average_rate = "30.0%" } },
  ["Walking Tree"] = { { name = "Dryad root", average_rate = "24.5%" }, { name = "Sprig of mistletoe", average_rate = "13.1%" }, { name = "Rosewood log", average_rate = "0.31%" }, { name = "Puffball", average_rate = "6.9%" }, { name = "Petrified log", average_rate = "0.26%" }, { name = "Mahogany log", average_rate = "0.36%" }, { name = "Ebony log", average_rate = "0.31%" } },
  ["Wandering Sapling"] = { { name = "Cernunnos bulb", average_rate = "27.5%" }, { name = "Treant bulb", average_rate = "15.2%" }, { name = "Bag of herb seeds", average_rate = "7.6%" } },
  ["War Smilodon"] = { { name = "Smilodon hide", average_rate = "11.5%" }, { name = "Smilodon liver", average_rate = "5.2%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "140.9%" } },
  ["Yacumama"] = { { name = "Backlash torque", average_rate = "13.9%" } },
  ["Yilbegan"] = { { name = "Chunk of platinum ore", average_rate = "9.1%" }, { name = "Demon horn", average_rate = "9.1%" }, { name = "Zilant ring", average_rate = "9.1%" }, { name = "Galdr ring", average_rate = "9.1%" }, { name = "Mahogany log", average_rate = "18.2%" }, { name = "Square of scarlet kadife", average_rate = "54.5%" }, { name = "Adaman ingot", average_rate = "9.1%" }, { name = "Petrified log", average_rate = "9.1%" }, { name = "Chunk of mythril ore", average_rate = "27.3%" }, { name = "Darksteel ingot", average_rate = "18.2%" }, { name = "Reraiser", average_rate = "9.1%" }, { name = "Chunk of darksteel ore", average_rate = "9.1%" }, { name = "Vile elixir", average_rate = "9.1%" }, { name = "Ebony log", average_rate = "9.1%" }, { name = "Chunk of gold ore", average_rate = "9.1%" }, { name = "Agrona's leggings", average_rate = "18.2%" }, { name = "Lucky coin", average_rate = "9.1%" }, { name = "Handful of wyvern scales", average_rate = "9.1%" }, { name = "Mythril ingot", average_rate = "9.1%" } },
}
