-- Zone: Vunkerl Inlet [S]
return {
  ["Abyssal Pugil"] = { { name = "Handful of pugil scales", average_rate = "14.5%" } },
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "205.2%" } },
  ["Bloodsucker"] = { { name = "Vial of fiend blood", average_rate = "13.3%" }, { name = "Vial of beastman blood", average_rate = "5.8%" } },
  ["Bugard"] = { { name = "Bugard tusk", average_rate = "2.6%" }, { name = "Bugard skin", average_rate = "25.7%" } },
  ["Carrion Marabou"] = { { name = "Bird feather", average_rate = "26.7%" }, { name = "Bird egg", average_rate = "13.7%" } },
  ["Chigoe"] = { { name = "Vial of demon blood", average_rate = "0.79%" }, { name = "Vial of chimera blood", average_rate = "21.1%" } },
  ["Demonic Rose"] = { { name = "Malboro vine", average_rate = "46.2%" } },
  ["Dire Bat"] = { { name = "Bat wing", average_rate = "25.7%" }, { name = "Vial of fiend blood", average_rate = "6.7%" }, { name = "Bat fang", average_rate = "14.5%" }, { name = "Vial of beastman blood", average_rate = "1.7%" } },
  ["Doom Mage"] = { { name = "Revival tree root", average_rate = "12.2%" }, { name = "Bone chip", average_rate = "20.5%" } },
  ["Doom Soldier"] = { { name = "Bone chip", average_rate = "20.0%" } },
  ["Dragonfly"] = { { name = "Insect wing", average_rate = "6.3%" } },
  ["Duriumshell"] = { { name = "Slice of land crab meat", average_rate = "56.5%" }, { name = "Crab shell", average_rate = "26.3%" }, { name = "High-quality crab shell", average_rate = "4.5%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "0.48%" } },
  ["Fierce Smilodon"] = { { name = "Smilodon hide", average_rate = "14.8%" }, { name = "Smilodon liver", average_rate = "7.5%" } },
  ["Gigas Deckhand"] = { { name = "Gigas helm", average_rate = "32.2%" }, { name = "Gigas gauntlets", average_rate = "9.6%" } },
  ["Gigas Helmsman"] = { { name = "Gigas helm", average_rate = "42.4%" }, { name = "Gigas gauntlets", average_rate = "10.5%" } },
  ["Gigas Jack"] = { { name = "Gigas helm", average_rate = "33.0%" }, { name = "Gigas gauntlets", average_rate = "5.7%" } },
  ["Gigas Marine"] = { { name = "Gigas helm", average_rate = "31.8%" }, { name = "Gigas gauntlets", average_rate = "9.4%" } },
  ["Gnole"] = { { name = "Gnole claw", average_rate = "1.6%" } },
  ["Goblin Flagman"] = { { name = "Goblin mask", average_rate = "3.1%" }, { name = "Goblin armor", average_rate = "1.7%" } },
  ["Goblin Grenadier"] = { { name = "Bottled pixie", average_rate = "6.5%" }, { name = "Goblin helm", average_rate = "2.6%" }, { name = "Goblin mail", average_rate = "1.5%" } },
  ["Goblin Guerrilla"] = { { name = "Jug of singing herbal broth", average_rate = "1.9%" }, { name = "Goblin armor", average_rate = "1.5%" }, { name = "Goblin mask", average_rate = "2.0%" } },
  ["Goblin Toxophilite"] = { { name = "Goblin weel", average_rate = "6.5%" }, { name = "Goblin mess tin", average_rate = "6.3%" } },
  ["Goliath Beetle"] = { { name = "Insect wing", average_rate = "23.5%" }, { name = "Beetle jaw", average_rate = "6.0%" } },
  ["Haunt"] = { { name = "Square of cotton cloth", average_rate = "24.0%" }, { name = "Revival tree root", average_rate = "5.2%" }, { name = "Luminicloth", average_rate = "0.73%" } },
  ["Ignis Djinn"] = { { name = "Pinch of djinn ash", average_rate = "41.4%" }, { name = "Djinn arm", average_rate = "27.7%" } },
  ["Judgmental Julika"] = { { name = "Creve-coeur", average_rate = "19.8%" } },
  ["Orcish Footsoldier"] = { { name = "Orc helmet", average_rate = "14.4%" } },
  ["Orcish Gladiator"] = { { name = "Bottled pixie", average_rate = "9.7%" } },
  ["Orcish Hexspinner"] = { { name = "Bottled pixie", average_rate = "16.1%" } },
  ["Orcish Zerker"] = { { name = "Orc helmet", average_rate = "7.7%" } },
  ["Pallas"] = { { name = "Pallas's shield", average_rate = "45.3%" }, { name = "Pallas's bracelets", average_rate = "4.0%" } },
  ["Robber Crab"] = { { name = "Slice of land crab meat", average_rate = "22.7%" }, { name = "Crab shell", average_rate = "13.8%" } },
  ["Royal Leech"] = { { name = "Vial of fiend blood", average_rate = "13.1%" }, { name = "Vial of beastman blood", average_rate = "6.6%" } },
  ["Sprite"] = { { name = "Pinch of Stygian ash", average_rate = "13.5%" } },
  ["Stygian Pugil"] = { { name = "Sack of silica", average_rate = "21.2%" }, { name = "Handful of pugil scales", average_rate = "13.4%" } },
  ["Submarine Nipper"] = { { name = "Chunk of rock salt", average_rate = "22.4%" }, { name = "Slice of land crab meat", average_rate = "2.4%" } },
  ["Thalassic Pugil"] = { { name = "Handful of pugil scales", average_rate = "12.8%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "140.9%" } },
  ["Treant"] = { { name = "Sprig of mistletoe", average_rate = "16.9%" }, { name = "Dryad root", average_rate = "32.7%" }, { name = "Puffball", average_rate = "8.2%" }, { name = "Rosewood log", average_rate = "1.9%" }, { name = "Mahogany log", average_rate = "0.79%" }, { name = "Ebony log", average_rate = "0.40%" }, { name = "Petrified log", average_rate = "0.10%" } },
  ["Wandering Sapling"] = { { name = "Bag of vegetable seeds", average_rate = "16.0%" }, { name = "Treant bulb", average_rate = "28.0%" }, { name = "Bag of herb seeds", average_rate = "7.5%" } },
  ["Warabouc"] = { { name = "Aptant of geoc", average_rate = "17.9%" }, { name = "Aptant of aecus", average_rate = "13.0%" } },
}
