-- Zone: Batallia Downs [S]
return {
  ["Ba"] = { { name = "Bird egg", average_rate = "10.8%" }, { name = "Bird feather", average_rate = "22.0%" } },
  ["Burlibix Brawnback"] = { { name = "Sortie ring", average_rate = "46.2%" } },
  ["Chaneque"] = { { name = "Birdbanes", average_rate = "15.4%" } },
  ["Clipper"] = { { name = "Crab shell", average_rate = "14.7%" }, { name = "Slice of land crab meat", average_rate = "24.9%" } },
  ["Cutter"] = { { name = "Chunk of rock salt", average_rate = "12.5%" } },
  ["Dark Ixion"] = { { name = "Azoth", average_rate = "46.0%" }, { name = "Dark Ixion horn", average_rate = "105.4%" }, { name = "Dark Ixion tail", average_rate = "105.4%" }, { name = "Ixion cloak", average_rate = "46.0%" }, { name = "Ixion cape", average_rate = "45.2%" } },
  ["Djinn"] = { { name = "Pinch of djinn ash", average_rate = "30.8%" }, { name = "Djinn arm", average_rate = "15.7%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "146.3%" } },
  ["Evil Spirit"] = { { name = "Square of cotton cloth", average_rate = "42.9%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "0.22%" } },
  ["Forester Beetle"] = { { name = "Beetle shell", average_rate = "5.4%" }, { name = "Beetle jaw", average_rate = "10.8%" } },
  ["Gnole"] = { { name = "Gnole claw", average_rate = "1.7%" } },
  ["Goblin Blastmaster"] = { { name = "Goblin mask", average_rate = "4.0%" }, { name = "Goblin armor", average_rate = "2.3%" } },
  ["Goblin Corpsman"] = { { name = "Goblin mask", average_rate = "5.3%" }, { name = "Goblin armor", average_rate = "2.3%" } },
  ["Goblin Freesword"] = { { name = "Goblin helm", average_rate = "5.7%" }, { name = "Goblin mail", average_rate = "2.4%" } },
  ["Goblin Pioneer"] = { { name = "Goblin weel", average_rate = "9.7%" }, { name = "Goblin mess tin", average_rate = "7.9%" } },
  ["Greater Pugil"] = { { name = "Handful of pugil scales", average_rate = "18.2%" } },
  ["Habergoass"] = { { name = "Kyoshu kyahan", average_rate = "33.3%" } },
  ["Kraken"] = { { name = "Seashell", average_rate = "100.0%" } },
  ["La Velue"] = { { name = "Amakura", average_rate = "26.9%" } },
  ["Land Pugil"] = { { name = "Handful of pugil scales", average_rate = "9.1%" } },
  ["Lycopodium"] = { { name = "Lycopodium flower", average_rate = "7.9%" } },
  ["Orcish Brawler"] = { { name = "Bottled pixie", average_rate = "4.7%" }, { name = "Scholar's testimony", average_rate = "12.4%" } },
  ["Orcish Chasseur"] = { { name = "Scholar's testimony", average_rate = "12.4%" } },
  ["Orcish Impaler"] = { { name = "Scholar's testimony", average_rate = "19.3%" } },
  ["Orcish Trooper"] = { { name = "Orc helmet", average_rate = "8.2%" }, { name = "Scholar's testimony", average_rate = "8.2%" } },
  ["Pixie"] = { { name = "Pinch of Stygian ash", average_rate = "22.6%" } },
  ["Sadfly"] = { { name = "Insect wing", average_rate = "7.5%" } },
  ["Skuld"] = { { name = "Veela cape", average_rate = "18.9%" } },
  ["Smilodon"] = { { name = "Smilodon hide", average_rate = "16.5%" }, { name = "Smilodon liver", average_rate = "8.2%" } },
  ["Snipper"] = { { name = "Chunk of rock salt", average_rate = "36.4%" } },
  ["Stalking Sapling"] = { { name = "Treant bulb", average_rate = "29.2%" }, { name = "Bag of vegetable seeds", average_rate = "12.1%" }, { name = "Bag of herb seeds", average_rate = "7.0%" } },
  ["Tsetse Fly"] = { { name = "Insect wing", average_rate = "33.3%" } },
  ["Urd"] = { { name = "Choreia earring", average_rate = "15.0%" } },
  ["Verthandi"] = { { name = "Eye of Verthandi", average_rate = "135.4%" }, { name = "Handful of wyvern scales", average_rate = "10.2%" }, { name = "Ebony log", average_rate = "15.7%" }, { name = "Petrified log", average_rate = "18.1%" }, { name = "Ethereal squama", average_rate = "45.7%" }, { name = "Reraiser", average_rate = "1.6%" }, { name = "Chunk of darksteel ore", average_rate = "7.1%" }, { name = "Mahogany log", average_rate = "15.7%" }, { name = "Chunk of wind ore", average_rate = "3.1%" }, { name = "Verthandi's gem", average_rate = "26.8%" }, { name = "Demon horn", average_rate = "6.3%" }, { name = "Coral fragment", average_rate = "14.2%" }, { name = "Ram horn", average_rate = "10.2%" }, { name = "Platinum ingot", average_rate = "10.2%" }, { name = "Square of rainbow cloth", average_rate = "0.79%" }, { name = "Darksteel ingot", average_rate = "6.3%" }, { name = "Mythril ingot", average_rate = "5.5%" }, { name = "Gold ingot", average_rate = "11.0%" }, { name = "Philosopher's stone", average_rate = "3.1%" }, { name = "Vile elixir", average_rate = "3.1%" }, { name = "Veela ring", average_rate = "14.2%" }, { name = "Slab of granite", average_rate = "2.4%" }, { name = "Chunk of mythril ore", average_rate = "4.7%" }, { name = "Chunk of dark ore", average_rate = "3.1%" }, { name = "Chunk of gold ore", average_rate = "4.7%" }, { name = "Spool of gold thread", average_rate = "3.9%" }, { name = "Ram skin", average_rate = "2.4%" }, { name = "Square of raxa", average_rate = "1.6%" }, { name = "Wyvern skin", average_rate = "0.79%" }, { name = "Chunk of platinum ore", average_rate = "7.9%" }, { name = "Manticore hide", average_rate = "1.6%" }, { name = "Hi-reraiser", average_rate = "2.4%" }, { name = "Phoenix feather", average_rate = "0.79%" }, { name = "Chunk of light ore", average_rate = "1.6%" }, { name = "Vile elixir +1", average_rate = "0.79%" }, { name = "Chunk of water ore", average_rate = "1.6%" }, { name = "Chunk of fire ore", average_rate = "3.1%" }, { name = "Chunk of ice ore", average_rate = "1.6%" } },
  ["Wight"] = { { name = "Bone chip", average_rate = "22.9%" }, { name = "Revival tree root", average_rate = "11.9%" }, { name = "Scroll of Absorb-INT", average_rate = "0.31%" } },
  ["Yilbegan"] = { { name = "Mahogany log", average_rate = "21.1%" }, { name = "Hi-reraiser", average_rate = "10.5%" }, { name = "Agrona's leggings", average_rate = "26.3%" }, { name = "Coral fragment", average_rate = "10.5%" }, { name = "Lucky coin", average_rate = "31.6%" }, { name = "Darksteel ingot", average_rate = "5.3%" }, { name = "Galdr ring", average_rate = "21.1%" }, { name = "Demon horn", average_rate = "5.3%" }, { name = "Petrified log", average_rate = "36.8%" }, { name = "Square of scarlet kadife", average_rate = "36.8%" }, { name = "Zilant ring", average_rate = "10.5%" }, { name = "Square of raxa", average_rate = "5.3%" }, { name = "Chunk of earth ore", average_rate = "5.3%" }, { name = "Adaman ingot", average_rate = "5.3%" }, { name = "Ram horn", average_rate = "15.8%" }, { name = "Chunk of mythril ore", average_rate = "5.3%" }, { name = "Chunk of mythril ore", average_rate = "5.3%" }, { name = "Wyvern skin", average_rate = "15.8%" }, { name = "Spool of gold thread", average_rate = "5.3%" }, { name = "Platinum ingot", average_rate = "5.3%" }, { name = "Chunk of gold ore", average_rate = "5.3%" }, { name = "Ebony log", average_rate = "5.3%" }, { name = "Handful of wyvern scales", average_rate = "10.5%" }, { name = "Chunk of platinum ore", average_rate = "5.3%" }, { name = "Orichalcum ingot", average_rate = "5.3%" } },
}
