-- Zone: La Vaule [S]
return {
  ["Agrios"] = { { name = "Oak strongbox", average_rate = "103.8%" }, { name = "Iwatsubute", average_rate = "14.6%" }, { name = "Sparth", average_rate = "19.1%" } },
  ["All-Seeing Onyx Eye"] = { { name = "Evergreen strongbox", average_rate = "105.7%" }, { name = "Mirror tiara", average_rate = "11.9%" }, { name = "Namioyogi", average_rate = "14.5%" } },
  ["Ashmaker Gotblut"] = { { name = "Marabout sandals", average_rate = "35.3%" } },
  ["Cogtooth Skagnogg"] = { { name = "Holly strongbox", average_rate = "102.2%" }, { name = "Murderer", average_rate = "16.3%" }, { name = "Llwyd's clogs", average_rate = "11.2%" } },
  ["Coinbiter Cjaknokk"] = { { name = "Maple strongbox", average_rate = "103.9%" }, { name = "Merveilleuse", average_rate = "17.2%" }, { name = "Bandolero scarf", average_rate = "15.5%" } },
  ["Draketrader Zlodgodd"] = { { name = "Magnolia strongbox", average_rate = "103.5%" }, { name = "Skystrider", average_rate = "18.7%" }, { name = "Orca strap", average_rate = "15.2%" } },
  ["Falsespinner Bhudbrodd"] = { { name = "Elm strongbox", average_rate = "101.8%" }, { name = "Rainmaker", average_rate = "12.0%" }, { name = "Acantha shavers", average_rate = "19.6%" } },
  ["Feeblescheme Bhogbigg"] = { { name = "Beech strongbox", average_rate = "103.9%" }, { name = "Viator cape", average_rate = "16.7%" }, { name = "Catalyst", average_rate = "16.7%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "1.8%" } },
  ["Fighting Smilodon"] = { { name = "Smilodon hide", average_rate = "14.7%" }, { name = "Smilodon liver", average_rate = "6.6%" } },
  ["Hawkeyed Dnatbat"] = { { name = "Grand crossbow", average_rate = "27.3%" } },
  ["La Vaule Pugil"] = { { name = "Handful of pugil scales", average_rate = "11.6%" } },
  ["Lobison"] = { { name = "Gnole claw", average_rate = "15.7%" } },
  ["Mariehene"] = { { name = "Ladybug wing", average_rate = "38.8%" } },
  ["Morbol"] = { { name = "Malboro vine", average_rate = "43.6%" } },
  ["Orcish Cupholder"] = { { name = "Jar of Gnole pellets", average_rate = "7.3%" }, { name = "Orc pauldron", average_rate = "2.4%" } },
  ["Orcish Dragonbrander"] = { { name = "Bottled pixie", average_rate = "12.1%" } },
  ["Orcish Dreadnought"] = { { name = "Orc helmet", average_rate = "16.8%" }, { name = "Orc pauldron", average_rate = "2.5%" } },
  ["Orcish Farkiller"] = { { name = "Orc pauldron", average_rate = "1.9%" } },
  ["Orcish Imperial Guard"] = { { name = "Orc pauldron", average_rate = "2.2%" }, { name = "Orc helmet", average_rate = "13.8%" } },
  ["Orcish Prophetess"] = { { name = "Jar of Gnole pellets", average_rate = "8.4%" } },
  ["Orcish Protector"] = { { name = "Orc helmet", average_rate = "17.0%" } },
  ["Orcish Strategist"] = { { name = "Bottled pixie", average_rate = "12.1%" }, { name = "Orc pauldron", average_rate = "2.3%" } },
  ["Orcish Veteran"] = { { name = "Orc helmet", average_rate = "14.3%" } },
  ["Orcish Warlord"] = { { name = "Bottled pixie", average_rate = "11.0%" } },
  ["Orcish Wyrmbrander"] = { { name = "Bottled pixie", average_rate = "11.0%" } },
  ["Rugaroo"] = { { name = "Willow strongbox", average_rate = "105.6%" }, { name = "Danzo tekko", average_rate = "10.7%" }, { name = "Vendetta", average_rate = "14.7%" } },
  ["Seneschal Imp"] = { { name = "Imp horn", average_rate = "6.2%" }, { name = "Imp wing", average_rate = "26.7%" } },
  ["Shatterskull Mippdapp"] = { { name = "Kensei sitabaki", average_rate = "50.9%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "120.0%" } },
  ["War Lizard"] = { { name = "Lizard tail", average_rate = "33.8%" }, { name = "Lizard skin", average_rate = "8.8%" }, { name = "Lizard egg", average_rate = "16.9%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "142.9%" } },
  ["Wolf Bat"] = { { name = "Bat wing", average_rate = "26.7%" }, { name = "Bat fang", average_rate = "6.7%" }, { name = "Vial of beastman blood", average_rate = "6.7%" } },
  ["Wood Bats"] = { { name = "Bat wing", average_rate = "80.0%" }, { name = "Vial of fiend blood", average_rate = "60.0%" } },
}
