-- Zone: Grauberg [S]
return {
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "138.3%" } },
  ["Ajattara"] = { { name = "Wyvern skin", average_rate = "18.6%" }, { name = "Wyvern wing", average_rate = "8.5%" } },
  ["Amethyst Quadav"] = { { name = "Dancer's testimony", average_rate = "19.4%" }, { name = "Quadav backplate", average_rate = "12.2%" }, { name = "Scroll of Protectra", average_rate = "2.0%" }, { name = "Scroll of Paralyze", average_rate = "1.7%" }, { name = "Scroll of Sneak", average_rate = "0.87%" }, { name = "Scroll of Barsleep", average_rate = "1.4%" } },
  ["Black Wolf"] = { { name = "Wolf hide", average_rate = "33.3%" } },
  ["Brass Quadav"] = { { name = "Heavy Quadav backplate", average_rate = "11.9%" }, { name = "Heavy Quadav chestplate", average_rate = "9.5%" } },
  ["Brasscap"] = { { name = "Agaricus mushroom", average_rate = "1.9%" } },
  ["Bronze Quadav"] = { { name = "Heavy Quadav backplate", average_rate = "3.8%" }, { name = "Heavy Quadav chestplate", average_rate = "11.3%" } },
  ["Chigoe"] = { { name = "Vial of chimera blood", average_rate = "23.1%" }, { name = "Vial of demon blood", average_rate = "0.82%" } },
  ["Copper Quadav"] = { { name = "Red oven mitt", average_rate = "5.6%" }, { name = "Shard of obsidian", average_rate = "10.9%" } },
  ["Dark Ixion"] = { { name = "Azoth", average_rate = "44.8%" }, { name = "Ixion cloak", average_rate = "45.3%" }, { name = "Dark Ixion horn", average_rate = "102.2%" }, { name = "Dark Ixion tail", average_rate = "102.2%" }, { name = "Ixion cape", average_rate = "39.0%" } },
  ["Doom Mage"] = { { name = "Bone chip", average_rate = "24.3%" }, { name = "Revival tree root", average_rate = "14.2%" } },
  ["Doom Soldier"] = { { name = "Bone chip", average_rate = "23.5%" } },
  ["Feyweald Sapling"] = { { name = "Treant bulb", average_rate = "38.5%" }, { name = "Bag of vegetable seeds", average_rate = "8.8%" }, { name = "Bag of grain seeds", average_rate = "18.3%" } },
  ["Goblin Blastmaster"] = { { name = "Goblin mask", average_rate = "4.1%" }, { name = "Goblin armor", average_rate = "1.2%" } },
  ["Goblin Corpsman"] = { { name = "Goblin mask", average_rate = "5.9%" }, { name = "Goblin armor", average_rate = "2.7%" } },
  ["Goblin Freesword"] = { { name = "Goblin helm", average_rate = "9.2%" }, { name = "Goblin mail", average_rate = "2.0%" } },
  ["Goblin Pioneer"] = { { name = "Goblin mess tin", average_rate = "6.5%" }, { name = "Goblin weel", average_rate = "8.8%" } },
  ["Grauberg Hippogryph"] = { { name = "Hippogryph tailfeather", average_rate = "27.5%" }, { name = "Hippogryph feather", average_rate = "8.3%" } },
  ["Greater Quadav"] = { { name = "Dancer's testimony", average_rate = "7.6%" }, { name = "Heavy Quadav chestplate", average_rate = "5.0%" }, { name = "Heavy Quadav backplate", average_rate = "6.3%" } },
  ["Heliodor Quadav"] = { { name = "Scroll of Bind", average_rate = "3.9%" }, { name = "Scroll of Blind", average_rate = "5.8%" } },
  ["Knotty Treant"] = { { name = "Dryad root", average_rate = "23.1%" }, { name = "Sprig of mistletoe", average_rate = "14.0%" }, { name = "Puffball", average_rate = "6.5%" }, { name = "Rosewood log", average_rate = "0.81%" }, { name = "Mahogany log", average_rate = "0.43%" }, { name = "Petrified log", average_rate = "0.12%" }, { name = "Ebony log", average_rate = "0.28%" } },
  ["Kotan-Kor Kamuy"] = { { name = "Cradle horn", average_rate = "12.8%" } },
  ["Old Quadav"] = { { name = "Heavy Quadav chestplate", average_rate = "5.6%" }, { name = "Heavy Quadav backplate", average_rate = "1.1%" }, { name = "Dancer's testimony", average_rate = "1.1%" } },
  ["Onyx Quadav"] = { { name = "Red oven mitt", average_rate = "7.0%" }, { name = "Scroll of Enblizzard II", average_rate = "18.9%" }, { name = "Shard of obsidian", average_rate = "13.4%" } },
  ["Peiste"] = { { name = "Peiste stinger", average_rate = "5.9%" }, { name = "Peiste skin", average_rate = "1.3%" } },
  ["Pixie"] = { { name = "Pinch of Stygian ash", average_rate = "12.7%" } },
  ["River Crab"] = { { name = "Chunk of rock salt", average_rate = "100.0%" } },
  ["Rock Eater"] = { { name = "Chunk of copper ore", average_rate = "13.4%" }, { name = "Flint stone", average_rate = "20.6%" }, { name = "Chunk of silver ore", average_rate = "1.2%" }, { name = "Chunk of zinc ore", average_rate = "6.1%" } },
  ["Sapphirine Quadav"] = { { name = "Quadav backplate", average_rate = "20.8%" }, { name = "Scroll of Paralyze", average_rate = "1.9%" }, { name = "Scroll of Sneak", average_rate = "1.3%" }, { name = "Scroll of Barsleep", average_rate = "1.3%" }, { name = "Scroll of Protectra", average_rate = "1.9%" } },
  ["Sarcopsylla"] = { { name = "Morana's pigaches", average_rate = "7.0%" } },
  ["Scitalis"] = { { name = "Saurian helm", average_rate = "28.3%" }, { name = "Wyvern skin", average_rate = "5.7%" }, { name = "Wyvern wing", average_rate = "3.8%" } },
  ["Sidhe"] = { { name = "Pinch of Stygian ash", average_rate = "4.7%" } },
  ["Silver Quadav"] = { { name = "Shard of obsidian", average_rate = "12.6%" }, { name = "Bottled pixie", average_rate = "2.8%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "142.0%" } },
  ["Vampire Bat"] = { { name = "Bat wing", average_rate = "33.1%" }, { name = "Vial of beastman blood", average_rate = "0.81%" } },
  ["Vasiliceratops"] = { { name = "Lyft voulge", average_rate = "20.0%" } },
  ["Veteran Quadav"] = { { name = "Heavy Quadav chestplate", average_rate = "7.4%" }, { name = "Dancer's testimony", average_rate = "30.9%" }, { name = "Heavy Quadav backplate", average_rate = "5.3%" } },
  ["Wandering Sapling"] = { { name = "Head of Grauberg lettuce", average_rate = "33.7%" }, { name = "Treant bulb", average_rate = "23.5%" }, { name = "Bag of vegetable seeds", average_rate = "23.0%" } },
  ["War Lizard"] = { { name = "Lizard egg", average_rate = "6.7%" }, { name = "Lizard skin", average_rate = "5.0%" }, { name = "Lizard tail", average_rate = "19.9%" } },
  ["Wingrats"] = { { name = "Vial of beastman blood", average_rate = "10.0%" } },
  ["Wivre"] = { { name = "Wivre maul", average_rate = "26.3%" }, { name = "Wivre horn", average_rate = "6.6%" } },
  ["Young Quadav"] = { { name = "Dancer's testimony", average_rate = "24.9%" }, { name = "Heavy Quadav backplate", average_rate = "6.1%" }, { name = "Heavy Quadav chestplate", average_rate = "5.1%" } },
}
