-- Zone: Pso'Xja
return {
  ["Archaic Chest"] = { { name = "Cyan chip", average_rate = "39.8%" } },
  ["Avalanche"] = { { name = "Snoll arm", average_rate = "41.4%" } },
  ["Blubber Eyes"] = { { name = "Hecteyes eye", average_rate = "8.0%" }, { name = "Vial of mercury", average_rate = "42.7%" }, { name = "Pso'Xja chest key", average_rate = "8.0%" } },
  ["Camazotz"] = { { name = "Bat wing", average_rate = "35.1%" }, { name = "Bat fang", average_rate = "14.5%" }, { name = "Florid stone", average_rate = "5.7%" }, { name = "Pso'Xja chest key", average_rate = "5.3%" }, { name = "Vial of beastman blood", average_rate = "1.1%" } },
  ["Cryptonberry Cutter"] = { { name = "Tonberry coat", average_rate = "31.2%" }, { name = "Flask of vitriol", average_rate = "17.3%" }, { name = "Scroll of Tonko: Ni", average_rate = "2.0%" }, { name = "Manji shuriken", average_rate = "4.0%" }, { name = "Scroll of Kurayami: Ni", average_rate = "0.99%" }, { name = "Pso'Xja chest key", average_rate = "5.4%" } },
  ["Cryptonberry Harrier"] = { { name = "Tonberry coat", average_rate = "34.6%" }, { name = "Flask of vitriol", average_rate = "15.4%" }, { name = "Pso'Xja chest key", average_rate = "7.1%" }, { name = "Water Spirit pact", average_rate = "2.6%" } },
  ["Cryptonberry Plaguer"] = { { name = "Tonberry coat", average_rate = "44.6%" }, { name = "Flask of vitriol", average_rate = "18.1%" }, { name = "Chunk of ordrynite", average_rate = "6.4%" }, { name = "Pso'Xja chest key", average_rate = "3.6%" } },
  ["Cryptonberry Stalker"] = { { name = "Chunk of ordrynite", average_rate = "14.8%" }, { name = "Tonberry coat", average_rate = "31.1%" }, { name = "Pso'Xja chest key", average_rate = "4.1%" }, { name = "Piece of magnolia lumber", average_rate = "10.4%" }, { name = "Flask of vitriol", average_rate = "2.2%" } },
  ["Dark Elemental"] = { { name = "Dark cluster", average_rate = "161.1%" }, { name = "Pso'Xja chest key", average_rate = "1.4%" } },
  ["Demonic Millstone"] = { { name = "Magic pot shard", average_rate = "66.7%" } },
  ["Dire Bat"] = { { name = "Bat fang", average_rate = "17.6%" }, { name = "Bat wing", average_rate = "32.9%" }, { name = "Florid stone", average_rate = "4.3%" }, { name = "Vial of beastman blood", average_rate = "2.3%" } },
  ["Diremite"] = { { name = "Vial of lizard blood", average_rate = "99.3%" }, { name = "Florid stone", average_rate = "25.0%" }, { name = "Gray chip", average_rate = "18.5%" }, { name = "Bottle of avatar blood", average_rate = "8.6%" } },
  ["Diremite Assaulter"] = { { name = "Gray chip", average_rate = "34.9%" }, { name = "Florid stone", average_rate = "49.3%" }, { name = "Bottle of avatar blood", average_rate = "17.3%" } },
  ["Diremite Dominator"] = { { name = "Florid stone", average_rate = "26.6%" }, { name = "Gray chip", average_rate = "42.9%" }, { name = "Bottle of avatar blood", average_rate = "21.1%" } },
  ["Diremite Stalker"] = { { name = "Florid stone", average_rate = "24.9%" }, { name = "Spool of bloodthread", average_rate = "52.5%" }, { name = "Gray chip", average_rate = "24.6%" }, { name = "Bottle of avatar blood", average_rate = "11.5%" } },
  ["Frost Lizard"] = { { name = "Carmine chip", average_rate = "25.5%" }, { name = "Lizard egg", average_rate = "13.3%" }, { name = "Lizard skin", average_rate = "6.5%" } },
  ["Gargoyle"] = { { name = "Vial of mercury", average_rate = "0.77%" }, { name = "Doll shard", average_rate = "0.40%" }, { name = "Pso'Xja chest key", average_rate = "0.02%" } },
  ["Gazer"] = { { name = "Vial of mercury", average_rate = "48.5%" }, { name = "Hecteyes eye", average_rate = "12.0%" } },
  ["Goblin Alchemist"] = { { name = "Scroll of Sacrifice", average_rate = "14.7%" }, { name = "Scroll of Reraise III", average_rate = "5.8%" }, { name = "Scroll of Curaga IV", average_rate = "2.1%" }, { name = "Scroll of Shellra IV", average_rate = "8.9%" }, { name = "White mage's testimony", average_rate = "11.5%" }, { name = "Scroll of Regen III", average_rate = "1.6%" }, { name = "Scroll of Cure V", average_rate = "3.1%" } },
  ["Goblin Bandit"] = { { name = "Goblin mask", average_rate = "17.9%" }, { name = "Goblin armor", average_rate = "8.9%" }, { name = "Gold beastcoin", average_rate = "8.9%" } },
  ["Goblin Enchanter"] = { { name = "Brass ingot", average_rate = "3.1%" } },
  ["Goblin Hunter"] = { { name = "Goblin mask", average_rate = "6.1%" } },
  ["Goblin Jeweler"] = { { name = "Strip of sheep jerky", average_rate = "3.0%" }, { name = "Goblin mask", average_rate = "9.1%" }, { name = "Flask of distilled water", average_rate = "3.0%" }, { name = "Pickaxe", average_rate = "3.0%" } },
  ["Goblin Mercenary"] = { { name = "Warrior's testimony", average_rate = "4.0%" }, { name = "Goblin helm", average_rate = "17.2%" }, { name = "Goblin mail", average_rate = "4.0%" } },
  ["Goblin Veterinarian"] = { { name = "Ash staff", average_rate = "42.1%" }, { name = "Beastmaster's testimony", average_rate = "16.3%" }, { name = "Ram skin", average_rate = "27.9%" }, { name = "Jug of singing herbal broth", average_rate = "5.3%" } },
  ["Golden-Tongued Culberry"] = { { name = "Uggalepih pendant", average_rate = "100.0%" } },
  ["Gyre-Carlin"] = { { name = "Florid stone", average_rate = "45.0%" }, { name = "Concealing cuffs", average_rate = "5.0%" }, { name = "Rikonodo", average_rate = "25.0%" }, { name = "Bottle of avatar blood", average_rate = "20.0%" } },
  ["Ice Elemental"] = { { name = "Ice cluster", average_rate = "156.7%" }, { name = "Pso'Xja chest key", average_rate = "2.3%" } },
  ["Labyrinth Lizard"] = { { name = "Lizard tail", average_rate = "32.8%" }, { name = "Lizard egg", average_rate = "16.7%" }, { name = "Lizard skin", average_rate = "9.3%" }, { name = "Pso'Xja chest key", average_rate = "3.2%" } },
  ["Magic Millstone"] = { { name = "Magic pot shard", average_rate = "34.9%" }, { name = "Vial of mercury", average_rate = "16.8%" }, { name = "Pso'Xja chest key", average_rate = "1.4%" } },
  ["Maledict Millstone"] = { { name = "Magic pot shard", average_rate = "46.3%" }, { name = "Vial of mercury", average_rate = "8.2%" } },
  ["Maze Lizard"] = { { name = "Lizard egg", average_rate = "16.7%" }, { name = "Lizard skin", average_rate = "9.6%" }, { name = "Lizard tail", average_rate = "30.3%" } },
  ["Million Eyes"] = { { name = "Vial of mercury", average_rate = "57.4%" }, { name = "Hecteyes eye", average_rate = "11.2%" }, { name = "Dark cluster", average_rate = "0.45%" } },
  ["Morozko"] = { { name = "Snoll arm", average_rate = "31.9%" } },
  ["Purgatory Bat"] = { { name = "Bat wing", average_rate = "31.1%" }, { name = "Bat fang", average_rate = "14.5%" }, { name = "Florid stone", average_rate = "3.5%" }, { name = "Vial of beastman blood", average_rate = "1.3%" } },
  ["Snoll"] = { { name = "Snoll arm", average_rate = "10.7%" } },
  ["Snow Lizard"] = { { name = "Carmine chip", average_rate = "25.7%" }, { name = "Lizard egg", average_rate = "11.5%" }, { name = "Lizard skin", average_rate = "6.0%" } },
  ["Snowball"] = { { name = "Snoll arm", average_rate = "30.5%" }, { name = "Pso'Xja chest key", average_rate = "0.54%" } },
  ["Thousand Eyes"] = { { name = "Vial of mercury", average_rate = "50.1%" }, { name = "Hecteyes eye", average_rate = "9.0%" } },
  ["Treasure Chest"] = { { name = "Cyan chip", average_rate = "40.3%" }, { name = "Pso'Xja chest key", average_rate = "8.6%" } },
  ["Vampire Bat"] = { { name = "Florid stone", average_rate = "6.8%" }, { name = "Bat wing", average_rate = "33.0%" }, { name = "Bat fang", average_rate = "18.6%" }, { name = "Pso'Xja chest key", average_rate = "0.90%" }, { name = "Vial of beastman blood", average_rate = "1.4%" } },
}
