-- Zone: Pashhow Marshlands [S]
return {
  ["Ancient Quadav"] = { { name = "Punch bug", average_rate = "13.3%" }, { name = "Heavy Quadav chestplate", average_rate = "13.2%" }, { name = "Heavy Quadav backplate", average_rate = "15.7%" } },
  ["Blobdingnag"] = { { name = "Baby Blobdingnag", average_rate = "130.7%" }, { name = "Demon horn", average_rate = "7.8%" }, { name = "Muculent ingot", average_rate = "50.5%" }, { name = "Darksteel ingot", average_rate = "6.7%" }, { name = "Platinum ingot", average_rate = "9.2%" }, { name = "Chunk of mythril ore", average_rate = "6.0%" }, { name = "Ebony log", average_rate = "7.8%" }, { name = "Mahogany log", average_rate = "13.1%" }, { name = "Beguiling collar", average_rate = "30.0%" }, { name = "Petrified log", average_rate = "23.0%" }, { name = "Square of raxa", average_rate = "2.5%" }, { name = "Blobnag ring", average_rate = "15.5%" }, { name = "Ram horn", average_rate = "10.2%" }, { name = "Chunk of platinum ore", average_rate = "8.8%" }, { name = "Coral fragment", average_rate = "10.2%" }, { name = "Chunk of gold ore", average_rate = "12.0%" }, { name = "Mythril ingot", average_rate = "9.9%" }, { name = "Handful of wyvern scales", average_rate = "10.6%" }, { name = "Ram skin", average_rate = "2.5%" }, { name = "Chunk of lightning ore", average_rate = "2.5%" }, { name = "Vile elixir", average_rate = "4.6%" }, { name = "Gold ingot", average_rate = "5.3%" }, { name = "Square of rainbow cloth", average_rate = "2.5%" }, { name = "Hi-reraiser", average_rate = "2.5%" }, { name = "Reraiser", average_rate = "3.2%" }, { name = "Chunk of dark ore", average_rate = "1.8%" }, { name = "Vile elixir +1", average_rate = "1.1%" }, { name = "Philosopher's stone", average_rate = "0.71%" }, { name = "Chunk of ice ore", average_rate = "1.8%" }, { name = "Chunk of darksteel ore", average_rate = "2.1%" }, { name = "Chunk of light ore", average_rate = "2.1%" }, { name = "Chunk of wind ore", average_rate = "2.1%" }, { name = "Spool of gold thread", average_rate = "0.35%" }, { name = "Manticore hide", average_rate = "0.35%" }, { name = "Chunk of earth ore", average_rate = "0.71%" }, { name = "Chunk of fire ore", average_rate = "1.4%" }, { name = "Phoenix feather", average_rate = "0.71%" }, { name = "Wyvern skin", average_rate = "0.35%" }, { name = "Slab of granite", average_rate = "0.35%" } },
  ["Bog Bunny"] = { { name = "Slice of hare meat", average_rate = "24.1%" }, { name = "Rabbit hide", average_rate = "13.4%" } },
  ["Bogy"] = { { name = "Luminicloth", average_rate = "7.1%" }, { name = "Revival tree root", average_rate = "17.9%" }, { name = "Square of cotton cloth", average_rate = "32.1%" } },
  ["Croque-Mitaine"] = { { name = "Aptant of haelan", average_rate = "15.3%" }, { name = "Aptant of tachus", average_rate = "11.9%" } },
  ["Elder Quadav"] = { { name = "Heavy Quadav backplate", average_rate = "15.6%" }, { name = "Heavy Quadav chestplate", average_rate = "16.7%" } },
  ["Electrumcap"] = { { name = "Agaricus mushroom", average_rate = "2.4%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "0.34%" } },
  ["Gadfly"] = { { name = "Insect wing", average_rate = "7.3%" } },
  ["Garnet Quadav"] = { { name = "Shard of obsidian", average_rate = "13.6%" } },
  ["Ghoul"] = { { name = "Bone chip", average_rate = "21.9%" } },
  ["Goblin Flagman"] = { { name = "Goblin mask", average_rate = "4.1%" }, { name = "Goblin armor", average_rate = "3.1%" } },
  ["Goblin Grenadier"] = { { name = "Bottled pixie", average_rate = "7.3%" }, { name = "Goblin mail", average_rate = "2.3%" }, { name = "Goblin helm", average_rate = "2.4%" } },
  ["Goblin Guerrilla"] = { { name = "Jug of singing herbal broth", average_rate = "1.8%" }, { name = "Goblin armor", average_rate = "2.7%" }, { name = "Goblin mask", average_rate = "2.7%" } },
  ["Goblin Toxophilite"] = { { name = "Goblin mess tin", average_rate = "8.2%" }, { name = "Goblin weel", average_rate = "6.0%" } },
  ["Gold Quadav"] = { { name = "Punch bug", average_rate = "26.9%" }, { name = "Shard of obsidian", average_rate = "15.8%" } },
  ["Goobbue"] = { { name = "Dahlia", average_rate = "6.0%" }, { name = "Bag of tree cuttings", average_rate = "1.9%" } },
  ["Kinepikwa"] = { { name = "Poison taster's cape", average_rate = "8.2%" }, { name = "Peiste stinger", average_rate = "49.2%" }, { name = "Peiste skin", average_rate = "3.3%" } },
  ["Lamprey Lord"] = { { name = "Hirudinea earring", average_rate = "11.7%" } },
  ["Lou Carcolh"] = { { name = "Punch bug", average_rate = "13.9%" }, { name = "Slug eye", average_rate = "1.9%" } },
  ["Malboro"] = { { name = "Malboro vine", average_rate = "49.4%" } },
  ["Moor Hound"] = { { name = "Wolf hide", average_rate = "17.2%" } },
  ["Mousse"] = { { name = "Vial of slime oil", average_rate = "41.6%" } },
  ["Mythril Quadav"] = { { name = "Heavy Quadav backplate", average_rate = "14.5%" }, { name = "Heavy Quadav chestplate", average_rate = "12.6%" } },
  ["Nickel Quadav"] = { { name = "Heavy Quadav backplate", average_rate = "15.6%" }, { name = "Heavy Quadav chestplate", average_rate = "14.2%" } },
  ["Night Bats"] = { { name = "Bat wing", average_rate = "38.5%" }, { name = "Vial of beastman blood", average_rate = "15.4%" } },
  ["Nommo"] = { { name = "Lyft lance", average_rate = "14.3%" } },
  ["Peiste"] = { { name = "Peiste stinger", average_rate = "14.9%" }, { name = "Peiste skin", average_rate = "7.2%" } },
  ["Ruby Quadav"] = { { name = "Bottled pixie", average_rate = "8.1%" }, { name = "Shard of obsidian", average_rate = "14.5%" } },
  ["Shoggoth"] = { { name = "Jinx ampulla", average_rate = "14.5%" } },
  ["Silver Quadav"] = { { name = "Shard of obsidian", average_rate = "15.2%" }, { name = "Bottled pixie", average_rate = "6.7%" } },
  ["Snipper"] = { { name = "Slice of land crab meat", average_rate = "20.7%" }, { name = "Crab shell", average_rate = "13.9%" } },
  ["Sprite"] = { { name = "Pinch of Stygian ash", average_rate = "28.0%" } },
  ["Stag Crab"] = { { name = "Chunk of rock salt", average_rate = "75.0%" }, { name = "Slice of land crab meat", average_rate = "25.0%" } },
  ["Sugaar"] = { { name = "Aoide's pumps", average_rate = "15.4%" } },
  ["Thread Leech"] = { { name = "Vial of fiend blood", average_rate = "14.5%" }, { name = "Vial of beastman blood", average_rate = "4.9%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "128.1%" } },
  ["Vajra Quadav"] = { { name = "Shard of obsidian", average_rate = "15.8%" }, { name = "Punch bug", average_rate = "25.2%" } },
  ["Virulent Peiste"] = { { name = "Peiste skin", average_rate = "8.8%" }, { name = "Peiste stinger", average_rate = "15.3%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "142.6%" } },
  ["Yilbegan"] = { { name = "Reraiser", average_rate = "16.7%" }, { name = "Zilant ring", average_rate = "8.3%" }, { name = "Mahogany log", average_rate = "16.7%" }, { name = "Spool of gold thread", average_rate = "8.3%" }, { name = "Square of scarlet kadife", average_rate = "50.0%" }, { name = "Orichalcum ingot", average_rate = "8.3%" }, { name = "Platinum ingot", average_rate = "8.3%" }, { name = "Chunk of platinum ore", average_rate = "8.3%" }, { name = "Agrona's leggings", average_rate = "8.3%" }, { name = "Ebony log", average_rate = "25.0%" }, { name = "Chunk of gold ore", average_rate = "8.3%" }, { name = "Petrified log", average_rate = "25.0%" }, { name = "Demon horn", average_rate = "8.3%" }, { name = "Handful of wyvern scales", average_rate = "16.7%" }, { name = "Ram skin", average_rate = "8.3%" }, { name = "Philosopher's stone", average_rate = "8.3%" }, { name = "Lucky coin", average_rate = "16.7%" }, { name = "Gold ingot", average_rate = "16.7%" }, { name = "Coral fragment", average_rate = "16.7%" } },
  ["Zircon Quadav"] = { { name = "Scroll of Bind", average_rate = "2.4%" }, { name = "Bottled pixie", average_rate = "14.0%" }, { name = "Scroll of Blind", average_rate = "3.7%" } },
  ["Zombie"] = { { name = "Bone chip", average_rate = "23.5%" }, { name = "Revival tree root", average_rate = "11.8%" } },
}
