-- Zone: Rolanberry Fields [S]
return {
  ["Berry Grub"] = { { name = "Spool of silk thread", average_rate = "18.1%" } },
  ["Brass Quadav"] = { { name = "Heavy Quadav backplate", average_rate = "5.8%" }, { name = "Heavy Quadav chestplate", average_rate = "7.8%" } },
  ["Bronze Quadav"] = { { name = "Heavy Quadav chestplate", average_rate = "7.8%" }, { name = "Heavy Quadav backplate", average_rate = "4.9%" } },
  ["Champion Crawler"] = { { name = "Spool of silk thread", average_rate = "25.2%" }, { name = "Spool of wyrdstrand", average_rate = "11.5%" } },
  ["Chigoe"] = { { name = "Vial of chimera blood", average_rate = "33.3%" }, { name = "Vial of demon blood", average_rate = "3.6%" } },
  ["Clipper"] = { { name = "Slice of land crab meat", average_rate = "21.7%" }, { name = "Crab shell", average_rate = "21.7%" } },
  ["Coppercap"] = { { name = "Agaricus mushroom", average_rate = "4.3%" } },
  ["Dark Ixion"] = { { name = "Azoth", average_rate = "46.6%" }, { name = "Dark Ixion horn", average_rate = "105.5%" }, { name = "Dark Ixion tail", average_rate = "105.9%" }, { name = "Ixion cape", average_rate = "51.0%" }, { name = "Ixion cloak", average_rate = "46.6%" } },
  ["Death Jacket"] = { { name = "Beehive chip", average_rate = "49.4%" }, { name = "Giant stinger", average_rate = "3.6%" }, { name = "Pot of honey", average_rate = "22.2%" }, { name = "Insect wing", average_rate = "10.0%" } },
  ["Death Wasp"] = { { name = "Pot of honey", average_rate = "10.3%" }, { name = "Insect wing", average_rate = "5.6%" }, { name = "Beehive chip", average_rate = "16.8%" }, { name = "Giant stinger", average_rate = "1.1%" } },
  ["Dragonfly"] = { { name = "Insect wing", average_rate = "6.7%" } },
  ["Dyinyinga"] = { { name = "Mahant sandals", average_rate = "27.3%" }, { name = "Slug eye", average_rate = "2.3%" } },
  ["Emerald Quadav"] = { { name = "Shard of obsidian", average_rate = "27.4%" }, { name = "Scroll of Enwater II", average_rate = "39.7%" } },
  ["Erle"] = { { name = "Courser's pugio", average_rate = "14.5%" } },
  ["Evil Spirit"] = { { name = "Square of cotton cloth", average_rate = "20.0%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "0.19%" } },
  ["Fire Elemental"] = { { name = "Fire cluster", average_rate = "100.0%" } },
  ["Goblin Draftee"] = { { name = "Goblin mask", average_rate = "6.0%" }, { name = "Goblin armor", average_rate = "3.0%" }, { name = "Gold ingot", average_rate = "1.5%" }, { name = "Brass ingot", average_rate = "1.5%" } },
  ["Goblin Franctireur"] = { { name = "Goblin mail", average_rate = "4.3%" }, { name = "Goblin helm", average_rate = "8.7%" }, { name = "Scroll of Absorb-VIT", average_rate = "4.3%" }, { name = "Scroll of Absorb-AGI", average_rate = "2.2%" } },
  ["Goblin Patrolman"] = { { name = "Goblin mask", average_rate = "5.6%" } },
  ["Goblin Skirmisher"] = { { name = "Goblin weel", average_rate = "10.0%" }, { name = "Goblin mess tin", average_rate = "9.7%" } },
  ["Goobbue Farmer"] = { { name = "Dahlia", average_rate = "5.9%" }, { name = "Bag of tree cuttings", average_rate = "1.9%" } },
  ["Hawker"] = { { name = "Insect wing", average_rate = "1.1%" } },
  ["Heliodor Quadav"] = { { name = "Scroll of Bind", average_rate = "2.9%" }, { name = "Scroll of Blind", average_rate = "1.4%" } },
  ["Lamina"] = { { name = "Kusha's ring", average_rate = "7.7%" } },
  ["Lycopodium"] = { { name = "Lycopodium flower", average_rate = "7.8%" } },
  ["Moon Bat"] = { { name = "Bat wing", average_rate = "44.4%" } },
  ["Ochu"] = { { name = "Malboro vine", average_rate = "59.0%" } },
  ["Old Quadav"] = { { name = "Heavy Quadav backplate", average_rate = "8.8%" }, { name = "Heavy Quadav chestplate", average_rate = "10.5%" }, { name = "Dancer's testimony", average_rate = "1.8%" } },
  ["Poison Leech"] = { { name = "Vial of fiend blood", average_rate = "9.9%" }, { name = "Vial of beastman blood", average_rate = "7.0%" } },
  ["Sapphirine Quadav"] = { { name = "Scroll of Sneak", average_rate = "5.4%" }, { name = "Quadav backplate", average_rate = "14.3%" }, { name = "Scroll of Barsleep", average_rate = "1.8%" }, { name = "Dancer's testimony", average_rate = "1.8%" }, { name = "Scroll of Protectra", average_rate = "1.8%" } },
  ["Scabrous Slug"] = { { name = "Slug eye", average_rate = "1.7%" } },
  ["Silver Quadav"] = { { name = "Shard of obsidian", average_rate = "27.0%" }, { name = "Bottled pixie", average_rate = "5.4%" } },
  ["Skuld"] = { { name = "Veela cape", average_rate = "19.2%" } },
  ["Sprite"] = { { name = "Pinch of Stygian ash", average_rate = "14.8%" } },
  ["Urd"] = { { name = "Choreia earring", average_rate = "14.2%" } },
  ["Verthandi"] = { { name = "Eye of Verthandi", average_rate = "139.8%" }, { name = "Mahogany log", average_rate = "17.5%" }, { name = "Chunk of gold ore", average_rate = "9.7%" }, { name = "Ethereal squama", average_rate = "45.6%" }, { name = "Gold ingot", average_rate = "10.7%" }, { name = "Handful of wyvern scales", average_rate = "9.7%" }, { name = "Coral fragment", average_rate = "17.5%" }, { name = "Philosopher's stone", average_rate = "2.9%" }, { name = "Veela ring", average_rate = "12.6%" }, { name = "Ebony log", average_rate = "12.6%" }, { name = "Verthandi's gem", average_rate = "20.4%" }, { name = "Platinum ingot", average_rate = "8.7%" }, { name = "Chunk of dark ore", average_rate = "1.9%" }, { name = "Ram horn", average_rate = "3.9%" }, { name = "Vile elixir", average_rate = "5.8%" }, { name = "Chunk of water ore", average_rate = "1.9%" }, { name = "Chunk of light ore", average_rate = "1.9%" }, { name = "Darksteel ingot", average_rate = "6.8%" }, { name = "Phoenix feather", average_rate = "1.9%" }, { name = "Demon horn", average_rate = "11.7%" }, { name = "Chunk of platinum ore", average_rate = "5.8%" }, { name = "Petrified log", average_rate = "28.2%" }, { name = "Vile elixir +1", average_rate = "0.97%" }, { name = "Chunk of mythril ore", average_rate = "4.9%" }, { name = "Chunk of earth ore", average_rate = "0.97%" }, { name = "Mythril ingot", average_rate = "6.8%" }, { name = "Hi-reraiser", average_rate = "3.9%" }, { name = "Spool of gold thread", average_rate = "3.9%" }, { name = "Square of raxa", average_rate = "1.9%" }, { name = "Ram skin", average_rate = "0.97%" }, { name = "Chunk of wind ore", average_rate = "1.9%" }, { name = "Reraiser", average_rate = "0.97%" }, { name = "Chunk of darksteel ore", average_rate = "2.9%" }, { name = "Manticore hide", average_rate = "2.9%" }, { name = "Chunk of fire ore", average_rate = "1.9%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "166.7%" } },
  ["Wight"] = { { name = "Revival tree root", average_rate = "20.0%" } },
  ["Worker Crawler"] = { { name = "Spool of silk thread", average_rate = "15.4%" } },
  ["Yilbegan"] = { { name = "Petrified log", average_rate = "44.4%" }, { name = "Mahogany log", average_rate = "27.8%" }, { name = "Square of scarlet kadife", average_rate = "50.0%" }, { name = "Chunk of gold ore", average_rate = "22.2%" }, { name = "Darksteel ingot", average_rate = "11.1%" }, { name = "Lucky coin", average_rate = "16.7%" }, { name = "Platinum ingot", average_rate = "5.6%" }, { name = "Demon horn", average_rate = "22.2%" }, { name = "Gold ingot", average_rate = "5.6%" }, { name = "Chunk of mythril ore", average_rate = "5.6%" }, { name = "Mythril ingot", average_rate = "11.1%" }, { name = "Agrona's leggings", average_rate = "5.6%" }, { name = "Chunk of platinum ore", average_rate = "5.6%" }, { name = "Reraiser", average_rate = "5.6%" }, { name = "Ram horn", average_rate = "5.6%" }, { name = "Ebony log", average_rate = "5.6%" } },
}
