-- Zone: Beadeaux [S]
return {
  ["Adaman Quadav"] = { { name = "Heavy Quadav backplate", average_rate = "14.9%" }, { name = "Heavy Quadav chestplate", average_rate = "14.4%" } },
  ["Ancient Quadav"] = { { name = "Heavy Quadav backplate", average_rate = "14.4%" }, { name = "Heavy Quadav chestplate", average_rate = "14.6%" }, { name = "Punch bug", average_rate = "8.7%" } },
  ["Ba'tho Mercifulheart"] = { { name = "Heavy Quadav chestplate", average_rate = "37.5%" }, { name = "Moliones's sickle", average_rate = "37.5%" }, { name = "Heavy Quadav backplate", average_rate = "12.5%" } },
  ["Baetyl Quadav"] = { { name = "Bottled pixie", average_rate = "12.9%" }, { name = "Scroll of Water III", average_rate = "4.2%" }, { name = "Scroll of Waterga III", average_rate = "0.81%" }, { name = "Scroll of Waterga II", average_rate = "3.1%" }, { name = "Scroll of Water IV", average_rate = "0.48%" }, { name = "Scroll of Flood", average_rate = "0.32%" } },
  ["Blifnix Oilycheeks"] = { { name = "Iron letterbox", average_rate = "103.0%" }, { name = "Amanokakoyumi", average_rate = "15.8%" }, { name = "Goblin cracker", average_rate = "16.8%" } },
  ["Bres"] = { { name = "Brass letterbox", average_rate = "106.7%" }, { name = "Emissary boots", average_rate = "17.0%" }, { name = "Useshi", average_rate = "16.0%" } },
  ["Chatoyant Quadav"] = { { name = "Jar of Peiste pellets", average_rate = "2.4%" }, { name = "Shard of obsidian", average_rate = "20.8%" } },
  ["Da'dha Hundredmask"] = { { name = "Patrician's cuffs", average_rate = "41.7%" } },
  ["Di'zho Spongeshell"] = { { name = "Shakudo letterbox", average_rate = "106.8%" }, { name = "Patriot's ring", average_rate = "20.1%" }, { name = "Balisarde", average_rate = "14.5%" } },
  ["Doyen Quadav"] = { { name = "Heavy Quadav backplate", average_rate = "10.1%" }, { name = "Heavy Quadav chestplate", average_rate = "17.5%" } },
  ["Ea'tho Cruelheart"] = { { name = "Heavy Quadav backplate", average_rate = "9.1%" }, { name = "Moliones's ring", average_rate = "21.2%" }, { name = "Heavy Quadav chestplate", average_rate = "12.1%" } },
  ["Edible Slug"] = { { name = "Slug eye", average_rate = "7.0%" } },
  ["Electrumcap"] = { { name = "Agaricus mushroom", average_rate = "5.4%" } },
  ["Ferroalloy Quadav"] = { { name = "Heavy Quadav chestplate", average_rate = "19.1%" }, { name = "Heavy Quadav backplate", average_rate = "10.8%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "7.3%" } },
  ["Ga'lhu Nevermolt"] = { { name = "Bronze letterbox", average_rate = "104.4%" }, { name = "Terror shield", average_rate = "18.6%" }, { name = "Sinfender", average_rate = "14.7%" } },
  ["Gold Quadav"] = { { name = "Shard of obsidian", average_rate = "11.7%" }, { name = "Punch bug", average_rate = "19.4%" } },
  ["Iron Quadav"] = { { name = "Heavy Quadav chestplate", average_rate = "15.4%" }, { name = "Heavy Quadav backplate", average_rate = "13.7%" } },
  ["Magnes Quadav"] = { { name = "Bottled pixie", average_rate = "10.2%" }, { name = "Scroll of Bind", average_rate = "4.8%" }, { name = "Scroll of Blind", average_rate = "3.8%" } },
  ["Meteor Quadav"] = { { name = "Shard of obsidian", average_rate = "16.1%" }, { name = "Jar of Peiste pellets", average_rate = "2.3%" } },
  ["Mu'nhi Thimbletail"] = { { name = "Pig iron letterbox", average_rate = "106.7%" }, { name = "Demagogue's sash", average_rate = "17.5%" }, { name = "Farseer", average_rate = "18.6%" } },
  ["Observant Zekka"] = { { name = "Paktong letterbox", average_rate = "93.4%" }, { name = "Kebbie", average_rate = "17.6%" }, { name = "Piper's torque", average_rate = "18.2%" } },
  ["Pitchy Pudding"] = { { name = "Chunk of flan meat", average_rate = "33.2%" } },
  ["Platinum Quadav"] = { { name = "Shard of obsidian", average_rate = "17.1%" } },
  ["Ra'dha Scarscute"] = { { name = "Wrought iron letterbox", average_rate = "109.0%" }, { name = "Louhi's mask", average_rate = "12.9%" }, { name = "Fleetwing", average_rate = "16.7%" } },
  ["Seneschal Imp"] = { { name = "Imp horn", average_rate = "6.9%" }, { name = "Imp wing", average_rate = "31.3%" } },
  ["Star Ruby Quadav"] = { { name = "Shard of obsidian", average_rate = "14.0%" } },
  ["Steel Quadav"] = { { name = "Heavy Quadav chestplate", average_rate = "18.0%" }, { name = "Heavy Quadav backplate", average_rate = "8.8%" } },
  ["Thunder Elemental"] = { { name = "Lightning cluster", average_rate = "120.0%" } },
  ["Va'gho Bloodbasked"] = { { name = "Cast iron letterbox", average_rate = "104.6%" }, { name = "Osoraku", average_rate = "14.7%" }, { name = "Malagigi's trousers", average_rate = "17.0%" } },
  ["Vajra Quadav"] = { { name = "Punch bug", average_rate = "17.8%" }, { name = "Shard of obsidian", average_rate = "14.0%" } },
  ["Virulent Peiste"] = { { name = "Peiste stinger", average_rate = "14.8%" }, { name = "Peiste skin", average_rate = "7.8%" } },
  ["Water Elemental"] = { { name = "Water cluster", average_rate = "113.6%" } },
}
