-- Zone: West Sarutabaruta [S]
return {
  ["Belladonna"] = { { name = "Virtuoso belt", average_rate = "11.6%" } },
  ["Bumblebee"] = { { name = "Insect wing", average_rate = "16.4%" }, { name = "Pot of honey", average_rate = "4.9%" } },
  ["Carrion Crow"] = { { name = "Bird feather", average_rate = "22.9%" }, { name = "Bird egg", average_rate = "6.4%" } },
  ["Crawler"] = { { name = "Spool of silk thread", average_rate = "16.1%" } },
  ["Dark Ixion"] = { { name = "Ixion cape", average_rate = "45.4%" }, { name = "Dark Ixion horn", average_rate = "105.5%" }, { name = "Dark Ixion tail", average_rate = "105.5%" }, { name = "Ixion cloak", average_rate = "40.3%" }, { name = "Azoth", average_rate = "45.1%" } },
  ["Farruca Fly"] = { { name = "Alert ring", average_rate = "13.8%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "2.0%" } },
  ["Fighting Pugil"] = { { name = "Handful of pugil scales", average_rate = "16.7%" } },
  ["Goblin Draftee"] = { { name = "Goblin armor", average_rate = "1.2%" }, { name = "Goblin mask", average_rate = "2.4%" } },
  ["Goblin Franctireur"] = { { name = "Scroll of Absorb-VIT", average_rate = "2.1%" }, { name = "Goblin mail", average_rate = "4.8%" }, { name = "Goblin helm", average_rate = "2.7%" }, { name = "Bottled pixie", average_rate = "1.4%" }, { name = "Scroll of Absorb-INT", average_rate = "2.7%" }, { name = "Scroll of Absorb-AGI", average_rate = "1.4%" } },
  ["Goblin Patrolman"] = { { name = "Goblin mask", average_rate = "3.9%" }, { name = "Goblin armor", average_rate = "0.78%" } },
  ["Goblin Skirmisher"] = { { name = "Goblin mess tin", average_rate = "7.7%" }, { name = "Goblin weel", average_rate = "7.7%" } },
  ["Hispid Rarab"] = { { name = "Slice of hare meat", average_rate = "26.0%" }, { name = "Rabbit hide", average_rate = "14.8%" } },
  ["Jeduah"] = { { name = "Anthos xiphos", average_rate = "42.9%" }, { name = "Lycopodium flower", average_rate = "23.8%" } },
  ["Jyeshtha"] = { { name = "Fatality belt", average_rate = "13.6%" } },
  ["Mad Fox"] = { { name = "Revival tree root", average_rate = "16.7%" } },
  ["Mud Pugil"] = { { name = "Handful of pugil scales", average_rate = "20.0%" } },
  ["Mugger Crab"] = { { name = "Chunk of rock salt", average_rate = "6.2%" } },
  ["Orcus"] = { { name = "Orcus mandible", average_rate = "99.2%" }, { name = "Demon horn", average_rate = "4.7%" }, { name = "Square of raxa", average_rate = "2.3%" }, { name = "Kidney stone", average_rate = "32.8%" }, { name = "Ebony log", average_rate = "10.2%" }, { name = "Coral fragment", average_rate = "7.8%" }, { name = "Ram horn", average_rate = "7.0%" }, { name = "Chunk of gold ore", average_rate = "7.0%" }, { name = "Handful of wyvern scales", average_rate = "7.0%" }, { name = "Mythril ingot", average_rate = "11.7%" }, { name = "Mahogany log", average_rate = "11.7%" }, { name = "Corneus ring", average_rate = "10.9%" }, { name = "Chunk of water ore", average_rate = "1.6%" }, { name = "Bobcat belt", average_rate = "18.0%" }, { name = "Chunk of platinum ore", average_rate = "5.5%" }, { name = "Chunk of mythril ore", average_rate = "11.7%" }, { name = "Vile elixir", average_rate = "3.1%" }, { name = "Reraiser", average_rate = "7.8%" }, { name = "Petrified log", average_rate = "11.7%" }, { name = "Chunk of darksteel ore", average_rate = "7.0%" }, { name = "Darksteel ingot", average_rate = "3.9%" }, { name = "Hi-reraiser", average_rate = "2.3%" }, { name = "Chunk of ice ore", average_rate = "1.6%" }, { name = "Gold ingot", average_rate = "5.5%" }, { name = "Platinum ingot", average_rate = "13.3%" }, { name = "Spool of gold thread", average_rate = "3.1%" }, { name = "Chunk of earth ore", average_rate = "1.6%" }, { name = "Chunk of fire ore", average_rate = "2.3%" }, { name = "Phoenix feather", average_rate = "0.78%" }, { name = "Square of rainbow cloth", average_rate = "2.3%" }, { name = "Philosopher's stone", average_rate = "0.78%" }, { name = "Wyvern skin", average_rate = "1.6%" }, { name = "Chunk of wind ore", average_rate = "0.78%" }, { name = "Vile elixir +1", average_rate = "0.78%" }, { name = "Ram skin", average_rate = "1.6%" } },
  ["Pixie"] = { { name = "Pinch of Stygian ash", average_rate = "21.0%" } },
  ["Pug Pugil"] = { { name = "Handful of pugil scales", average_rate = "16.7%" } },
  ["Rafflesia"] = { { name = "Rafflesia vine", average_rate = "6.6%" }, { name = "Rafflesia petal", average_rate = "0.81%" } },
  ["Ramponneau"] = { { name = "Summoning belt", average_rate = "11.9%" } },
  ["River Crab"] = { { name = "Chunk of rock salt", average_rate = "23.0%" }, { name = "Slice of land crab meat", average_rate = "1.1%" } },
  ["Savanna Crab"] = { { name = "Chunk of rock salt", average_rate = "32.1%" } },
  ["Savanna Dhalmel"] = { { name = "Slice of dhalmel meat", average_rate = "66.7%" }, { name = "Giant femur", average_rate = "13.0%" }, { name = "Tuft of dhalmel hair", average_rate = "23.7%" }, { name = "Dhalmel hide", average_rate = "4.2%" }, { name = "Sprig of papaka grass", average_rate = "1.6%" } },
  ["Savanna Rarab"] = { { name = "Slice of hare meat", average_rate = "44.9%" }, { name = "Wild rabbit tail", average_rate = "3.0%" } },
  ["Tiffenotte"] = { { name = "Vial of ebon pigment", average_rate = "18.5%" }, { name = "Vial of furia pigment", average_rate = "10.8%" } },
  ["Tiny Lycopodium"] = { { name = "Lycopodium flower", average_rate = "6.0%" } },
  ["Yagudo Acolyte"] = { { name = "Yagudo bead necklace", average_rate = "16.5%" }, { name = "Scroll of Paralyze", average_rate = "2.0%" }, { name = "Yagudo feather", average_rate = "26.4%" }, { name = "Scroll of Sneak", average_rate = "2.7%" }, { name = "Scroll of Protectra", average_rate = "1.6%" }, { name = "Scroll of Barsleep", average_rate = "1.9%" } },
  ["Yagudo Condottiere"] = { { name = "Yagudo feather", average_rate = "73.3%" }, { name = "Bottled pixie", average_rate = "4.3%" } },
  ["Yagudo Initiate"] = { { name = "King locust", average_rate = "27.5%" }, { name = "Skull locust", average_rate = "24.2%" }, { name = "Yagudo kote", average_rate = "1.7%" } },
  ["Yagudo Mendicant"] = { { name = "Yagudo feather", average_rate = "33.1%" }, { name = "Air Spirit pact", average_rate = "1.9%" } },
  ["Yagudo Persecutor"] = { { name = "Yagudo feather", average_rate = "46.6%" } },
  ["Yagudo Piper"] = { { name = "Block of Yagudo glue", average_rate = "14.7%" }, { name = "Scroll of Blade Madrigal", average_rate = "5.9%" }, { name = "Scroll of Dragonfoe Mambo", average_rate = "2.1%" } },
  ["Yagudo Scribe"] = { { name = "Yagudo feather", average_rate = "33.3%" }, { name = "Bottled pixie", average_rate = "2.0%" } },
  ["Yilbegan"] = { { name = "Darksteel ingot", average_rate = "50.0%" }, { name = "Square of scarlet kadife", average_rate = "33.3%" }, { name = "Petrified log", average_rate = "16.7%" }, { name = "Ram horn", average_rate = "8.3%" }, { name = "Vile elixir", average_rate = "8.3%" }, { name = "Platinum ingot", average_rate = "8.3%" }, { name = "Mahogany log", average_rate = "8.3%" }, { name = "Ebony log", average_rate = "16.7%" }, { name = "Lucky coin", average_rate = "8.3%" }, { name = "Coral fragment", average_rate = "8.3%" }, { name = "Agrona's leggings", average_rate = "16.7%" }, { name = "Chunk of mythril ore", average_rate = "16.7%" }, { name = "Gold ingot", average_rate = "8.3%" } },
}
