-- Zone: Fort Karugo-Narugo [S]
return {
  ["Air Elemental"] = { { name = "Wind cluster", average_rate = "146.0%" } },
  ["Carrion Crow"] = { { name = "Bird feather", average_rate = "40.0%" } },
  ["Dark Ixion"] = { { name = "Azoth", average_rate = "45.4%" }, { name = "Ixion cape", average_rate = "37.1%" }, { name = "Ixion cloak", average_rate = "45.8%" }, { name = "Dark Ixion horn", average_rate = "105.4%" }, { name = "Dark Ixion tail", average_rate = "105.8%" } },
  ["Death Jacket"] = { { name = "Beehive chip", average_rate = "29.9%" }, { name = "Pot of honey", average_rate = "16.9%" }, { name = "Insect wing", average_rate = "7.7%" } },
  ["Dragonfly"] = { { name = "Insect wing", average_rate = "6.4%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "100.0%" }, { name = "Earth cluster", average_rate = "50.0%" } },
  ["Emela-Ntouka"] = { { name = "Avis", average_rate = "19.7%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "1.0%" } },
  ["Goblin Pioneer"] = { { name = "Goblin weel", average_rate = "7.9%" }, { name = "Goblin mess tin", average_rate = "7.0%" } },
  ["Jumbo Rafflesia"] = { { name = "Rafflesia vine", average_rate = "16.2%" }, { name = "Rafflesia petal", average_rate = "7.9%" } },
  ["Kirtimukha"] = { { name = "Rafflesia petal", average_rate = "4.8%" }, { name = "Rafflesia vine", average_rate = "14.5%" }, { name = "Kogitsunemaru", average_rate = "22.6%" } },
  ["Lycopodium"] = { { name = "Lycopodium flower", average_rate = "4.4%" } },
  ["Pixie"] = { { name = "Pinch of Stygian ash", average_rate = "13.1%" } },
  ["Rafflesia"] = { { name = "Rafflesia vine", average_rate = "6.8%" }, { name = "Rafflesia petal", average_rate = "1.3%" } },
  ["Ratatoskr"] = { { name = "Ratatoskr pelt", average_rate = "11.4%" } },
  ["Vorpal Bunny"] = { { name = "Slice of hare meat", average_rate = "19.6%" }, { name = "Wild rabbit tail", average_rate = "5.2%" } },
  ["Wandering Sapling"] = { { name = "Bag of grain seeds", average_rate = "12.9%" }, { name = "Treant bulb", average_rate = "19.9%" }, { name = "Bag of herb seeds", average_rate = "8.2%" } },
  ["War Lizard"] = { { name = "Lizard egg", average_rate = "23.5%" }, { name = "Lizard tail", average_rate = "29.4%" }, { name = "Lizard skin", average_rate = "3.9%" } },
  ["Yagudo Drummer"] = { { name = "Scroll of Blade Madrigal", average_rate = "7.1%" }, { name = "Block of Yagudo glue", average_rate = "14.3%" }, { name = "Scroll of Dragonfoe Mambo", average_rate = "2.0%" } },
  ["Yagudo Herald"] = { { name = "Yagudo feather", average_rate = "53.7%" } },
  ["Yagudo Interrogator"] = { { name = "Yagudo feather", average_rate = "26.7%" } },
  ["Yagudo Priest"] = { { name = "Yagudo bead necklace", average_rate = "26.2%" }, { name = "Bottled pixie", average_rate = "7.1%" }, { name = "Scroll of Protectra", average_rate = "4.8%" }, { name = "Scroll of Paralyze", average_rate = "7.1%" } },
  ["Yagudo Theologist"] = { { name = "Yagudo feather", average_rate = "40.9%" }, { name = "Bottled pixie", average_rate = "2.3%" } },
  ["Yagudo Votary"] = { { name = "Yagudo kote", average_rate = "10.6%" } },
}
