-- Zone: Meriphataud Mountains [S]
return {
  ["Axe Beak"] = { { name = "Slice of cockatrice meat", average_rate = "28.7%" }, { name = "Giant bird feather", average_rate = "15.8%" }, { name = "Cockatrice skin", average_rate = "2.1%" } },
  ["Black Bat"] = { { name = "Bat wing", average_rate = "50.0%" } },
  ["Bloodlapper"] = { { name = "Vicious mufflers", average_rate = "51.9%" }, { name = "Gnat wing", average_rate = "40.7%" } },
  ["Centipedal Centruroides"] = { { name = "Lyft tabar", average_rate = "100.0%" } },
  ["Condor"] = { { name = "Bird feather", average_rate = "20.2%" }, { name = "Bird egg", average_rate = "13.1%" } },
  ["Dragonfly"] = { { name = "Insect wing", average_rate = "8.2%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "160.0%" } },
  ["Farruca Fly"] = { { name = "Alert ring", average_rate = "13.4%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "0.55%" } },
  ["Fire Elemental"] = { { name = "Fire cluster", average_rate = "130.8%" } },
  ["Gnat"] = { { name = "Gnat wing", average_rate = "26.2%" } },
  ["Goblin Bombardier"] = { { name = "Goblin mask", average_rate = "3.2%" }, { name = "Goblin armor", average_rate = "3.2%" } },
  ["Goblin Field Doctor"] = { { name = "Bottled pixie", average_rate = "33.0%" }, { name = "Goblin mask", average_rate = "13.7%" }, { name = "Goblin armor", average_rate = "2.3%" } },
  ["Goblin Paratrooper"] = { { name = "Goblin helm", average_rate = "7.6%" }, { name = "Goblin mail", average_rate = "1.9%" }, { name = "Gold beastcoin", average_rate = "1.9%" } },
  ["Goblin Picket"] = { { name = "Goblin mess tin", average_rate = "20.0%" }, { name = "Goblin weel", average_rate = "17.3%" } },
  ["Hemodrosophila"] = { { name = "Atesh pole", average_rate = "16.7%" } },
  ["Hill Lizard"] = { { name = "Lizard tail", average_rate = "18.0%" }, { name = "Lizard egg", average_rate = "11.7%" }, { name = "Lizard skin", average_rate = "8.8%" } },
  ["Jubjub"] = { { name = "Bird feather", average_rate = "22.7%" }, { name = "Bird egg", average_rate = "22.7%" } },
  ["Jumbo Rafflesia"] = { { name = "Rafflesia petal", average_rate = "8.7%" }, { name = "Rafflesia vine", average_rate = "13.9%" } },
  ["Jyeshtha"] = { { name = "Fatality belt", average_rate = "13.5%" } },
  ["Lycopodium"] = { { name = "Lycopodium flower", average_rate = "9.1%" } },
  ["Lynx"] = { { name = "Lynx hide", average_rate = "17.4%" }, { name = "Slice of lynx meat", average_rate = "9.0%" } },
  ["Mountain Jubjub"] = { { name = "Bird feather", average_rate = "27.3%" }, { name = "Bird egg", average_rate = "7.3%" } },
  ["Mountain Scolopendrid"] = { { name = "Scorpion claw", average_rate = "52.6%" }, { name = "Scorpion shell", average_rate = "10.0%" } },
  ["Muq Shabeel"] = { { name = "Aptant of fyrst", average_rate = "31.2%" }, { name = "Aptant of haelan", average_rate = "24.1%" } },
  ["Night Bats"] = { { name = "Bat fang", average_rate = "33.3%" } },
  ["Orcus"] = { { name = "Orcus mandible", average_rate = "106.7%" }, { name = "Mahogany log", average_rate = "10.0%" }, { name = "Handful of wyvern scales", average_rate = "18.3%" }, { name = "Kidney stone", average_rate = "38.3%" }, { name = "Demon horn", average_rate = "11.7%" }, { name = "Corneus ring", average_rate = "13.3%" }, { name = "Vile elixir +1", average_rate = "3.3%" }, { name = "Chunk of fire ore", average_rate = "5.0%" }, { name = "Coral fragment", average_rate = "11.7%" }, { name = "Ebony log", average_rate = "6.7%" }, { name = "Chunk of earth ore", average_rate = "5.0%" }, { name = "Ram horn", average_rate = "10.0%" }, { name = "Gold ingot", average_rate = "8.3%" }, { name = "Phoenix feather", average_rate = "1.7%" }, { name = "Chunk of dark ore", average_rate = "1.7%" }, { name = "Bobcat belt", average_rate = "18.3%" }, { name = "Mythril ingot", average_rate = "6.7%" }, { name = "Platinum ingot", average_rate = "10.0%" }, { name = "Darksteel ingot", average_rate = "6.7%" }, { name = "Manticore hide", average_rate = "1.7%" }, { name = "Petrified log", average_rate = "6.7%" }, { name = "Chunk of mythril ore", average_rate = "1.7%" }, { name = "Square of raxa", average_rate = "5.0%" }, { name = "Chunk of platinum ore", average_rate = "3.3%" }, { name = "Square of rainbow cloth", average_rate = "3.3%" }, { name = "Wyvern skin", average_rate = "1.7%" }, { name = "Chunk of gold ore", average_rate = "1.7%" } },
  ["Raptor"] = { { name = "Raptor skin", average_rate = "15.5%" } },
  ["Scavenging Hound"] = { { name = "Wolf hide", average_rate = "14.3%" }, { name = "Revival tree root", average_rate = "2.9%" } },
  ["Scolopendrid"] = { { name = "Scorpion claw", average_rate = "41.2%" }, { name = "Scorpion shell", average_rate = "5.8%" } },
  ["Sprite"] = { { name = "Pinch of Stygian ash", average_rate = "25.0%" } },
  ["Stag Beetle"] = { { name = "Insect wing", average_rate = "22.0%" }, { name = "Beetle jaw", average_rate = "11.4%" } },
  ["Treant Sapling"] = { { name = "Bag of grain seeds", average_rate = "12.2%" }, { name = "Treant bulb", average_rate = "19.9%" }, { name = "Bag of herb seeds", average_rate = "6.3%" } },
  ["Wandering Sapling"] = { { name = "Bag of herb seeds", average_rate = "10.1%" }, { name = "Treant bulb", average_rate = "17.8%" }, { name = "Bag of grain seeds", average_rate = "8.2%" } },
  ["War Lynx"] = { { name = "Slice of lynx meat", average_rate = "23.1%" }, { name = "Lynx hide", average_rate = "49.8%" } },
  ["Yagudo Chanter"] = { { name = "Block of Yagudo glue", average_rate = "28.8%" }, { name = "Scroll of Warding Round", average_rate = "15.6%" }, { name = "Scroll of Goddess's Hymnus", average_rate = "6.9%" } },
  ["Yagudo Eradicator"] = { { name = "Yagudo kote", average_rate = "15.1%" }, { name = "Dorter key", average_rate = "24.9%" } },
  ["Yagudo High Priest"] = { { name = "Yagudo feather", average_rate = "111.8%" }, { name = "Bottled pixie", average_rate = "99.1%" } },
  ["Yagudo Knight Templar"] = { { name = "Yagudo kote", average_rate = "16.1%" }, { name = "Dorter key", average_rate = "30.7%" } },
  ["Yagudo Prelate"] = { { name = "Dorter key", average_rate = "34.8%" }, { name = "Scroll of Tornado", average_rate = "0.77%" }, { name = "Scroll of Aeroga III", average_rate = "2.1%" }, { name = "Scroll of Aeroga II", average_rate = "2.1%" }, { name = "Scroll of Aero III", average_rate = "2.6%" }, { name = "Scroll of Aero IV", average_rate = "0.52%" } },
  ["Yagudo Prioress"] = { { name = "Dorter key", average_rate = "28.8%" }, { name = "Air Spirit pact", average_rate = "9.7%" } },
  ["Yagudo Sentinel"] = { { name = "Yagudo feather", average_rate = "43.2%" }, { name = "Bottled pixie", average_rate = "14.2%" } },
  ["Yilbegan"] = { { name = "Reraiser", average_rate = "20.0%" }, { name = "Lucky coin", average_rate = "20.0%" }, { name = "Gold ingot", average_rate = "20.0%" }, { name = "Vile elixir", average_rate = "20.0%" }, { name = "Mythril ingot", average_rate = "40.0%" }, { name = "Demon horn", average_rate = "20.0%" } },
}
