-- Zone: Sauromugue Champaign [S]
return {
  ["Coquecigrue"] = { { name = "Coquecigrue skin", average_rate = "16.5%" } },
  ["Diving Beetle"] = { { name = "Insect wing", average_rate = "21.5%" }, { name = "Beetle jaw", average_rate = "7.2%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "126.1%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "0.28%" } },
  ["Gnat"] = { { name = "Gnat wing", average_rate = "40.3%" } },
  ["Goblin Flagman"] = { { name = "Goblin mask", average_rate = "3.0%" }, { name = "Goblin armor", average_rate = "2.2%" } },
  ["Goblin Grenadier"] = { { name = "Bottled pixie", average_rate = "6.3%" }, { name = "Goblin helm", average_rate = "3.8%" }, { name = "Goblin mail", average_rate = "0.35%" } },
  ["Goblin Guerrilla"] = { { name = "Goblin mask", average_rate = "3.3%" }, { name = "Goblin armor", average_rate = "2.7%" }, { name = "Jug of singing herbal broth", average_rate = "0.60%" } },
  ["Goblin Toxophilite"] = { { name = "Goblin weel", average_rate = "6.0%" }, { name = "Goblin mess tin", average_rate = "11.1%" } },
  ["Gouger Beetle"] = { { name = "Insect wing", average_rate = "21.0%" }, { name = "Beetle shell", average_rate = "13.0%" }, { name = "Beetle jaw", average_rate = "6.5%" } },
  ["Herensugue"] = { { name = "Herensugue skin", average_rate = "22.9%" } },
  ["Hill Lizard"] = { { name = "Lizard tail", average_rate = "23.3%" }, { name = "Lizard skin", average_rate = "6.2%" }, { name = "Lizard egg", average_rate = "12.2%" } },
  ["Hyakinthos"] = { { name = "Lava's ring", average_rate = "5.9%" } },
  ["Lycopodium"] = { { name = "Lycopodium flower", average_rate = "5.8%" } },
  ["Lynx"] = { { name = "Slice of lynx meat", average_rate = "9.9%" }, { name = "Lynx hide", average_rate = "20.9%" } },
  ["Midnight Wings"] = { { name = "Bat fang", average_rate = "8.0%" }, { name = "Bat wing", average_rate = "8.0%" } },
  ["Moon Bat"] = { { name = "Vial of fiend blood", average_rate = "14.7%" }, { name = "Vial of beastman blood", average_rate = "2.9%" }, { name = "Bat wing", average_rate = "29.4%" }, { name = "Bat fang", average_rate = "20.6%" } },
  ["Sauromugue Skink"] = { { name = "Raptor skin", average_rate = "20.2%" } },
  ["Scavenging Hound"] = { { name = "Wolf hide", average_rate = "26.7%" }, { name = "Revival tree root", average_rate = "6.7%" } },
  ["Skuld"] = { { name = "Veela cape", average_rate = "13.1%" } },
  ["Sprite"] = { { name = "Pinch of Stygian ash", average_rate = "9.1%" } },
  ["Tabar Beak"] = { { name = "Slice of cockatrice meat", average_rate = "22.9%" }, { name = "Giant bird feather", average_rate = "13.7%" }, { name = "Cockatrice skin", average_rate = "0.76%" } },
  ["Urd"] = { { name = "Choreia earring", average_rate = "12.9%" } },
  ["Verthandi"] = { { name = "Eye of Verthandi", average_rate = "152.2%" }, { name = "Ebony log", average_rate = "10.4%" }, { name = "Vile elixir", average_rate = "11.9%" }, { name = "Darksteel ingot", average_rate = "4.5%" }, { name = "Demon horn", average_rate = "19.4%" }, { name = "Chunk of darksteel ore", average_rate = "20.9%" }, { name = "Verthandi's gem", average_rate = "22.4%" }, { name = "Gold ingot", average_rate = "4.5%" }, { name = "Ethereal squama", average_rate = "56.7%" }, { name = "Veela ring", average_rate = "9.0%" }, { name = "Vile elixir +1", average_rate = "1.5%" }, { name = "Ram horn", average_rate = "11.9%" }, { name = "Chunk of earth ore", average_rate = "1.5%" }, { name = "Coral fragment", average_rate = "13.4%" }, { name = "Mahogany log", average_rate = "10.4%" }, { name = "Square of raxa", average_rate = "3.0%" }, { name = "Platinum ingot", average_rate = "4.5%" }, { name = "Reraiser", average_rate = "3.0%" }, { name = "Chunk of mythril ore", average_rate = "7.5%" }, { name = "Mythril ingot", average_rate = "10.4%" }, { name = "Petrified log", average_rate = "11.9%" }, { name = "Chunk of wind ore", average_rate = "4.5%" }, { name = "Spool of gold thread", average_rate = "6.0%" }, { name = "Handful of wyvern scales", average_rate = "11.9%" }, { name = "Chunk of platinum ore", average_rate = "4.5%" }, { name = "Chunk of gold ore", average_rate = "10.4%" }, { name = "Square of rainbow cloth", average_rate = "1.5%" }, { name = "Hi-reraiser", average_rate = "1.5%" }, { name = "Ram skin", average_rate = "4.5%" }, { name = "Chunk of ice ore", average_rate = "1.5%" }, { name = "Chunk of lightning ore", average_rate = "1.5%" }, { name = "Slab of granite", average_rate = "1.5%" } },
  ["Yagudo Abbot"] = { { name = "One hundred eight-knot quipu", average_rate = "19.6%" }, { name = "Yagudo feather", average_rate = "22.1%" } },
  ["Yagudo Inquisitor"] = { { name = "Yagudo kote", average_rate = "8.9%" }, { name = "One hundred eight-knot quipu", average_rate = "21.1%" } },
  ["Yagudo Lutenist"] = { { name = "Block of Yagudo glue", average_rate = "33.9%" }, { name = "One hundred eight-knot quipu", average_rate = "22.0%" }, { name = "Scroll of Goddess's Hymnus", average_rate = "8.3%" }, { name = "Scroll of Warding Round", average_rate = "15.2%" } },
  ["Yagudo Missionary"] = { { name = "One hundred eight-knot quipu", average_rate = "17.3%" }, { name = "Yagudo kote", average_rate = "9.7%" } },
  ["Yagudo Prior"] = { { name = "Scroll of Aero IV", average_rate = "1.5%" }, { name = "One hundred eight-knot quipu", average_rate = "20.9%" }, { name = "Scroll of Aero III", average_rate = "3.6%" }, { name = "Scroll of Aeroga II", average_rate = "1.8%" }, { name = "Scroll of Aeroga III", average_rate = "1.3%" }, { name = "Scroll of Tornado", average_rate = "1.0%" } },
  ["Yagudo Pythoness"] = { { name = "One hundred eight-knot quipu", average_rate = "23.8%" }, { name = "Air Spirit pact", average_rate = "8.9%" } },
  ["Yagudo Zealot"] = { { name = "One hundred eight-knot quipu", average_rate = "23.1%" }, { name = "Bottled pixie", average_rate = "8.3%" }, { name = "Yagudo feather", average_rate = "22.2%" } },
  ["Yilbegan"] = { { name = "Chunk of gold ore", average_rate = "12.5%" }, { name = "Demon horn", average_rate = "62.5%" }, { name = "Lucky coin", average_rate = "12.5%" }, { name = "Wyvern skin", average_rate = "12.5%" }, { name = "Agrona's leggings", average_rate = "37.5%" }, { name = "Ram horn", average_rate = "12.5%" }, { name = "Square of scarlet kadife", average_rate = "12.5%" }, { name = "Square of scarlet kadife", average_rate = "12.5%" }, { name = "Handful of wyvern scales", average_rate = "12.5%" }, { name = "Mahogany log", average_rate = "12.5%" }, { name = "Orichalcum ingot", average_rate = "12.5%" }, { name = "Zilant ring", average_rate = "12.5%" } },
}
