-- Zone: Castle Oztroja [S]
return {
  ["Aa Xalmo The Savage"] = { { name = "Deae Gratia", average_rate = "34.1%" } },
  ["Antlion Fly"] = { { name = "Insect wing", average_rate = "8.9%" } },
  ["Asterion"] = { { name = "Bamboo tea basket", average_rate = "103.8%" }, { name = "Bedivere's hose", average_rate = "18.9%" }, { name = "Alastor", average_rate = "17.1%" } },
  ["Bastion Bats"] = { { name = "Bat wing", average_rate = "28.5%" }, { name = "Bat fang", average_rate = "13.3%" }, { name = "Vial of fiend blood", average_rate = "9.5%" }, { name = "Vial of beastman blood", average_rate = "2.5%" } },
  ["Blooming Rafflesia"] = { { name = "Rafflesia vine", average_rate = "32.1%" }, { name = "Rafflesia petal", average_rate = "18.3%" } },
  ["Bulwark Bat"] = { { name = "Bat fang", average_rate = "16.7%" }, { name = "Bat wing", average_rate = "27.8%" }, { name = "Vial of fiend blood", average_rate = "22.2%" } },
  ["Dee Zelko The Esoteric"] = { { name = "Bamboo grass basket", average_rate = "105.1%" }, { name = "Grandeur", average_rate = "15.4%" }, { name = "Grenadier belt", average_rate = "16.1%" } },
  ["Duu Masa The Onecut"] = { { name = "Naraenten bead necklace", average_rate = "42.9%" }, { name = "Yagudo kote", average_rate = "23.8%" } },
  ["Earth Elemental"] = { { name = "Earth cluster", average_rate = "110.0%" } },
  ["Fiendish Leechkeeper"] = { { name = "Imp horn", average_rate = "3.9%" } },
  ["Fire Elemental"] = { { name = "Fire cluster", average_rate = "100.0%" } },
  ["Fleshgnasher"] = { { name = "Bamboo flower basket", average_rate = "107.7%" }, { name = "Caloyer cape", average_rate = "20.4%" }, { name = "Basilisk", average_rate = "14.8%" } },
  ["Gnat"] = { { name = "Gnat wing", average_rate = "23.6%" } },
  ["Immolatory Pugil"] = { { name = "Handful of pugil scales", average_rate = "24.0%" }, { name = "Shall shell", average_rate = "12.0%" } },
  ["Loo Kutto The Pensive"] = { { name = "Bamboo bugcage", average_rate = "104.1%" }, { name = "Skirmisher's ring", average_rate = "17.0%" }, { name = "Mukademaru", average_rate = "18.8%" } },
  ["Maa Illmu The Bestower"] = { { name = "Bamboo charcoal basket", average_rate = "104.3%" }, { name = "Clearpath", average_rate = "20.3%" }, { name = "Cruadin", average_rate = "15.8%" } },
  ["Marquis Forneus"] = { { name = "Bamboo medicine basket", average_rate = "106.0%" }, { name = "Faucheuse", average_rate = "19.2%" }, { name = "Shark strap", average_rate = "21.9%" } },
  ["Seneschal Imp"] = { { name = "Imp wing", average_rate = "31.0%" }, { name = "Imp horn", average_rate = "7.9%" } },
  ["Suu Xicu The Cantabile"] = { { name = "Bamboo snakecage", average_rate = "104.9%" }, { name = "Failnaught", average_rate = "16.2%" }, { name = "Silktone", average_rate = "15.3%" } },
  ["Vee Ladu The Titterer"] = { { name = "Bamboo birdcage", average_rate = "100.0%" } },
  ["War Lynx"] = { { name = "Slice of lynx meat", average_rate = "18.6%" }, { name = "Lynx hide", average_rate = "34.7%" } },
  ["Yagudo Abbot"] = { { name = "Yagudo feather", average_rate = "41.4%" } },
  ["Yagudo Chanter"] = { { name = "Block of Yagudo glue", average_rate = "22.9%" }, { name = "Scroll of Warding Round", average_rate = "15.1%" }, { name = "Scroll of Goddess's Hymnus", average_rate = "6.6%" } },
  ["Yagudo Conductor"] = { { name = "Block of Yagudo glue", average_rate = "23.5%" }, { name = "Scroll of Goddess's Hymnus", average_rate = "7.9%" }, { name = "Scroll of Warding Round", average_rate = "16.9%" } },
  ["Yagudo Eradicator"] = { { name = "Dorter key", average_rate = "29.2%" }, { name = "Yagudo kote", average_rate = "15.9%" } },
  ["Yagudo Flagellant"] = { { name = "Yagudo feather", average_rate = "44.1%" }, { name = "Yagudo kote", average_rate = "16.9%" }, { name = "Yagudo osode", average_rate = "2.0%" } },
  ["Yagudo Hierogrammat"] = { { name = "Scroll of Tornado", average_rate = "0.67%" }, { name = "Scroll of Aeroga III", average_rate = "1.5%" }, { name = "Scroll of Aero III", average_rate = "2.7%" }, { name = "Scroll of Aeroga II", average_rate = "2.2%" }, { name = "Scroll of Aero IV", average_rate = "0.94%" } },
  ["Yagudo High Priest"] = { { name = "Yagudo feather", average_rate = "116.9%" }, { name = "Bottled pixie", average_rate = "66.3%" } },
  ["Yagudo Knight Templar"] = { { name = "Dorter key", average_rate = "28.7%" }, { name = "Yagudo kote", average_rate = "14.9%" } },
  ["Yagudo Nokizaru"] = { { name = "Yagudo kote", average_rate = "16.5%" }, { name = "Jar of Gnat pellets", average_rate = "22.0%" }, { name = "Yagudo osode", average_rate = "2.4%" } },
  ["Yagudo Parasite"] = { { name = "Vial of beastman blood", average_rate = "4.9%" }, { name = "Vial of fiend blood", average_rate = "17.6%" } },
  ["Yagudo Prelate"] = { { name = "Dorter key", average_rate = "29.8%" }, { name = "Scroll of Aero III", average_rate = "2.9%" }, { name = "Scroll of Aeroga II", average_rate = "1.7%" }, { name = "Scroll of Aeroga III", average_rate = "1.2%" }, { name = "Scroll of Tornado", average_rate = "0.81%" }, { name = "Scroll of Aero IV", average_rate = "0.72%" } },
  ["Yagudo Prioress"] = { { name = "Dorter key", average_rate = "29.8%" }, { name = "Air Spirit pact", average_rate = "7.3%" } },
  ["Yagudo Sentinel"] = { { name = "Yagudo feather", average_rate = "44.2%" }, { name = "Bottled pixie", average_rate = "9.4%" } },
  ["Yagudo Superior"] = { { name = "Jar of Gnat pellets", average_rate = "21.0%" }, { name = "Air Spirit pact", average_rate = "2.4%" } },
  ["Yagudo Yojimbo"] = { { name = "Jar of Gnat pellets", average_rate = "21.3%" }, { name = "Yagudo kote", average_rate = "16.3%" }, { name = "Yagudo osode", average_rate = "1.7%" } },
  ["Zhuu Buxu The Silent"] = { { name = "Yagudo kote", average_rate = "9.1%" }, { name = "Sangoma lappas", average_rate = "18.2%" } },
}
