--Zone: Yughott Grotto
--Zone ID: 142
return {
    Names = {
        ['Ashmaker Gotblut'] = { Name='Ashmaker Gotblut', Notorious=true, Aggro=true, Link=true, TrueSight=false, Job=0, MinLevel=17, MaxLevel=18, Immunities=0, Respawn=0, Sight=true, Sound=false, Blood=false, Magic=false, JA=false, Scent=true, Drops={}, Spells={144,149,154,189,220,230,238,239,245,249,254,258}, Modifiers={Slashing=1, Piercing=1, H2H=1, Impact=1, Fire=1, Ice=1, Wind=1, Earth=1, Lightning=1, Water=1.25, Light=1, Dark=1} },
        ['Grotto Bats'] = { Name='Grotto Bats', Notorious=false, Aggro=true, Link=true, TrueSight=false, Job=0, MinLevel=8, MaxLevel=11, Immunities=0, Respawn=330, Sight=false, Sound=true, Blood=false, Magic=false, JA=false, Scent=false, Drops={}, Spells={}, Modifiers={Slashing=1, Piercing=1.25, H2H=1, Impact=1, Fire=1, Ice=1.125, Wind=1.25, Earth=1, Lightning=1.125, Water=1, Light=1.25, Dark=0.5} },
        ['Orcish Cursemaker'] = { Name='Orcish Cursemaker', Notorious=false, Aggro=true, Link=true, TrueSight=false, Job=4, MinLevel=21, MaxLevel=23, Immunities=0, Respawn=330, Sight=true, Sound=false, Blood=false, Magic=false, JA=false, Scent=true, Drops={}, Spells={144,149,164,184,189,199,230,236,237,238,239,245,249,253,254,258}, Modifiers={Slashing=1, Piercing=1, H2H=1, Impact=1, Fire=1, Ice=1, Wind=1, Earth=1, Lightning=1, Water=1.25, Light=1, Dark=1} },
        ['Orcish Fighter'] = { Name='Orcish Fighter', Notorious=false, Aggro=true, Link=true, TrueSight=false, Job=1, MinLevel=21, MaxLevel=23, Immunities=0, Respawn=330, Sight=true, Sound=false, Blood=false, Magic=false, JA=false, Scent=true, Drops={}, Spells={}, Modifiers={Slashing=1, Piercing=1, H2H=1, Impact=1, Fire=1, Ice=1, Wind=1, Earth=1, Lightning=1, Water=1.25, Light=1, Dark=1} },
        ['Orcish Grunt'] = { Name='Orcish Grunt', Notorious=false, Aggro=true, Link=true, TrueSight=false, Job=14, MinLevel=14, MaxLevel=18, Immunities=0, Respawn=330, Sight=true, Sound=false, Blood=false, Magic=false, JA=false, Scent=true, Drops={}, Spells={}, Modifiers={Slashing=1, Piercing=1, H2H=1, Impact=1, Fire=1, Ice=1, Wind=1, Earth=1, Lightning=1, Water=1.25, Light=1, Dark=1} },
        ['Orcish Neckchopper'] = { Name='Orcish Neckchopper', Notorious=false, Aggro=true, Link=true, TrueSight=false, Job=8, MinLevel=14, MaxLevel=18, Immunities=0, Respawn=330, Sight=true, Sound=false, Blood=false, Magic=false, JA=false, Scent=true, Drops={}, Spells={154,159,169,220,230,245}, Modifiers={Slashing=1, Piercing=1, H2H=1, Impact=1, Fire=1, Ice=1, Wind=1, Earth=1, Lightning=1, Water=1.25, Light=1, Dark=1} },
        ['Orcish Serjeant'] = { Name='Orcish Serjeant', Notorious=false, Aggro=true, Link=true, TrueSight=false, Job=7, MinLevel=21, MaxLevel=23, Immunities=0, Respawn=330, Sight=true, Sound=false, Blood=false, Magic=false, JA=false, Scent=true, Drops={}, Spells={2,28,43,48}, Modifiers={Slashing=1, Piercing=1, H2H=1, Impact=1, Fire=1, Ice=1, Wind=1, Earth=1, Lightning=1, Water=1.25, Light=1, Dark=1} },
        ['Orcish Stonechucker'] = { Name='Orcish Stonechucker', Notorious=false, Aggro=true, Link=true, TrueSight=false, Job=11, MinLevel=14, MaxLevel=18, Immunities=0, Respawn=330, Sight=true, Sound=false, Blood=false, Magic=false, JA=false, Scent=true, Drops={}, Spells={}, Modifiers={Slashing=1, Piercing=1, H2H=1, Impact=1, Fire=1, Ice=1, Wind=1, Earth=1, Lightning=1, Water=1.25, Light=1, Dark=1} },
        ['Riding Lizard'] = { Name='Riding Lizard', Notorious=false, Aggro=false, Link=true, TrueSight=false, Job=0, MinLevel=12, MaxLevel=15, Immunities=0, Respawn=330, Sight=false, Sound=true, Blood=false, Magic=false, JA=false, Scent=false, Drops={}, Spells={}, Modifiers={Slashing=1, Piercing=1, H2H=1, Impact=1, Fire=1, Ice=1.25, Wind=1.25, Earth=1, Lightning=1, Water=1, Light=1, Dark=1} },
        ['Stealth Bat'] = { Name='Stealth Bat', Notorious=false, Aggro=true, Link=true, TrueSight=false, Job=0, MinLevel=15, MaxLevel=18, Immunities=0, Respawn=330, Sight=false, Sound=true, Blood=false, Magic=false, JA=false, Scent=false, Drops={}, Spells={}, Modifiers={Slashing=1, Piercing=1.25, H2H=1, Impact=1, Fire=1, Ice=1.125, Wind=1.25, Earth=1, Lightning=1.125, Water=1, Light=1.25, Dark=0.5} },
    },
    Indices = {
    },
};